"""React track."""
from content_js_sql import M

META = [
    M("react-introduction", "react", "Introduction and Setup", 12, "Beginner", "What React is, how to create a project with Vite and how a first component works.", ["Explain components and the virtual DOM", "Create a Vite project", "Render a component"]),
    M("react-jsx-components", "react", "JSX and Components", 15, "Beginner", "Write JSX, compose components and pass data down with props.", ["Write valid JSX", "Pass and destructure props", "Use children"]),
    M("react-state", "react", "State with useState", 16, "Beginner", "Give components memory and update it without mutating.", ["Use useState", "Update objects and arrays immutably", "Lift state up"]),
    M("react-events-forms", "react", "Events, Lists and Forms", 17, "Beginner", "Handle events, render lists with keys and build controlled forms.", ["Handle events", "Render lists with keys", "Build a controlled form"]),
    M("react-effects", "react", "Effects with useEffect", 16, "Intermediate", "Synchronize with the outside world: fetching, timers and subscriptions.", ["Write effects with correct dependencies", "Clean up effects", "Know when not to use an effect"]),
    M("react-hooks-context", "react", "Custom Hooks, Refs and Context", 17, "Intermediate", "Reuse logic with custom hooks and share data with context.", ["Extract a custom hook", "Use useRef", "Share data with context"]),
    M("react-data-fetching", "react", "Data Fetching and Routing", 18, "Intermediate", "Load data with loading and error states, then add pages with React Router.", ["Model loading/error/success", "Cancel stale requests", "Add client-side routes"]),
]

CONTENT = {}

CONTENT["react-introduction"] = [
    ("p", "<strong>React</strong> is a JavaScript library for building user interfaces. Instead of writing step-by-step instructions to change the page (find this element, set its text), you <em>describe what the screen should look like for the current data</em>, and React updates the real DOM to match. That declarative style makes big interfaces far easier to reason about."),
    ("h2", "Core ideas"),
    ("ul", [
        "<strong>Components</strong>: small, reusable functions that return a piece of UI. You build screens by composing them, like Lego bricks.",
        "<strong>Props and state</strong>: props are inputs passed <em>into</em> a component; state is memory <em>owned by</em> a component. When either changes, React re-renders.",
        "<strong>The virtual DOM</strong>: React compares the new output with the previous one and applies only the minimal real DOM changes.",
    ]),
    ("h2", "Create a project"),
    ("p", "Vite is the standard fast tool for starting a React app. You need Node.js 18 or newer."),
    ("code", "bash", "npm create vite@latest my-app -- --template react\ncd my-app\nnpm install\nnpm run dev"),
    ("p", "Open the local address it prints (usually <code>http://localhost:5173</code>). Edit a file and the browser updates instantly."),
    ("h2", "The project layout"),
    ("ul", [
        "<code>index.html</code>: has one empty <code>&lt;div id=\"root\"&gt;</code>.",
        "<code>src/main.jsx</code>: mounts your app into that div.",
        "<code>src/App.jsx</code>: your first component.",
    ]),
    ("code", "javascript", '// src/main.jsx\nimport { StrictMode } from "react";\nimport { createRoot } from "react-dom/client";\nimport App from "./App.jsx";\n\ncreateRoot(document.getElementById("root")).render(\n  <StrictMode>\n    <App />\n  </StrictMode>\n);'),
    ("h2", "Your first component"),
    ("code", "javascript", '// src/App.jsx\nfunction App() {\n  return (\n    <main>\n      <h1>Hello, React</h1>\n      <p>This UI is a function.</p>\n    </main>\n  );\n}\n\nexport default App;'),
    ("p", "Component names must start with a capital letter; that is how React tells <code>&lt;App /&gt;</code> from a plain HTML tag like <code>&lt;div&gt;</code>. <code>StrictMode</code> runs extra checks in development, including rendering twice to reveal impure code."),
    ("note", "Prerequisite", "React is JavaScript. Be comfortable with functions, arrays, <code>map</code>/<code>filter</code>, destructuring and spread from the JavaScript course first."),
    ("exercise", "Edit <code>App.jsx</code> to show your name in an <code>h1</code> and a short list of three hobbies in a <code>ul</code>."),
    ("solution", "javascript", 'function App() {\n  return (\n    <main>\n      <h1>Amar</h1>\n      <ul>\n        <li>Coding</li>\n        <li>Cycling</li>\n        <li>Chess</li>\n      </ul>\n    </main>\n  );\n}\nexport default App;'),
]

CONTENT["react-jsx-components"] = [
    ("p", "<strong>JSX</strong> is a syntax that lets you write HTML-like markup inside JavaScript. A build tool converts it to ordinary function calls. It is not a template language: it is JavaScript, so you have the full language available inside curly braces."),
    ("h2", "JSX rules"),
    ("ul", [
        "A component returns <strong>one root element</strong>. Wrap siblings in a <code>&lt;div&gt;</code> or a fragment <code>&lt;&gt;...&lt;/&gt;</code>.",
        "Close every tag, including <code>&lt;img /&gt;</code> and <code>&lt;br /&gt;</code>.",
        "Use <code>className</code> instead of <code>class</code>, and <code>htmlFor</code> instead of <code>for</code>.",
        "Attributes are camelCase: <code>onClick</code>, <code>tabIndex</code>.",
        "Put JavaScript expressions in <code>{ }</code>. Style takes an object: <code>style={{ color: \"red\" }}</code>.",
    ]),
    ("code", "javascript", 'function Profile() {\n  const user = { name: "Ada", age: 36 };\n  const year = new Date().getFullYear();\n  return (\n    <>\n      <h2 className="title">{user.name}</h2>\n      <p>Born around {year - user.age}</p>\n    </>\n  );\n}'),
    ("h2", "Props"),
    ("p", "Props are how a parent passes data to a child, exactly like function arguments. They arrive as one object, so destructure them in the parameter list. Props are <strong>read-only</strong>: a component must never change its own props."),
    ("code", "javascript", 'function Greeting({ name, excited = false }) {\n  return <h1>Hello, {name}{excited ? "!" : "."}</h1>;\n}\n\nfunction App() {\n  return (\n    <>\n      <Greeting name="Ada" excited />\n      <Greeting name="Linus" />\n    </>\n  );\n}'),
    ("p", "Strings can be written in quotes; everything else (numbers, booleans, arrays, objects, functions) goes in braces: <code>&lt;Card count={3} tags={[\"a\", \"b\"]} /&gt;</code>."),
    ("h2", "Children and composition"),
    ("p", "Anything placed between a component's tags arrives as the special <code>children</code> prop, letting you build wrapper components."),
    ("code", "javascript", 'function Card({ title, children }) {\n  return (\n    <section className="card">\n      <h3>{title}</h3>\n      {children}\n    </section>\n  );\n}\n\n<Card title="Tip">\n  <p>Small components are easier to reuse.</p>\n</Card>;'),
    ("h2", "Conditional rendering"),
    ("code", "javascript", 'function Status({ online, unread }) {\n  if (!online) return <p>Offline</p>;\n  return (\n    <p>\n      Online {unread > 0 && <strong>({unread} new)</strong>}\n    </p>\n  );\n}'),
    ("note", "Common bug", "<code>{count && &lt;X /&gt;}</code> renders the number <code>0</code> when count is 0. Write <code>{count &gt; 0 &amp;&amp; ...}</code> instead."),
    ("exercise", "Create a <code>Button</code> component that takes <code>label</code> and an optional <code>variant</code> prop (\"primary\" by default) and renders a button whose className includes the variant."),
    ("solution", "javascript", 'function Button({ label, variant = "primary" }) {\n  return <button className={`btn btn-${variant}`}>{label}</button>;\n}\n\n<Button label="Save" />;\n<Button label="Delete" variant="danger" />;'),
]

CONTENT["react-state"] = [
    ("p", "A regular variable inside a component is reset every time the component runs and, crucially, changing it does not tell React to redraw. <strong>State</strong> solves both problems: it is memory that React preserves between renders, and updating it triggers a new render."),
    ("h2", "useState"),
    ("code", "javascript", 'import { useState } from "react";\n\nfunction Counter() {\n  const [count, setCount] = useState(0);\n  return (\n    <button onClick={() => setCount(count + 1)}>\n      Clicked {count} times\n    </button>\n  );\n}'),
    ("p", "<code>useState(0)</code> returns the current value and a setter. The argument is only the initial value. Calling <code>setCount</code> schedules a re-render with the new value. Hooks must be called at the top level of a component, never inside loops, conditions or nested functions."),
    ("h2", "State updates are snapshots"),
    ("p", "Within one render, <code>count</code> is a fixed number. Calling <code>setCount(count + 1)</code> three times adds only one, because each call sees the same <code>count</code>. When the next value depends on the previous one, pass an <strong>updater function</strong>."),
    ("code", "javascript", 'function addThree() {\n  setCount((c) => c + 1);\n  setCount((c) => c + 1);\n  setCount((c) => c + 1);   // total +3\n}'),
    ("h2", "Never mutate state"),
    ("p", "Treat state as immutable. Create a <em>new</em> object or array instead of editing the existing one; otherwise React cannot detect the change."),
    ("code", "javascript", 'const [user, setUser] = useState({ name: "Ada", age: 36 });\nconst [todos, setTodos] = useState(["write", "test"]);\n\n// objects: copy then override\nsetUser({ ...user, age: 37 });\n\n// arrays\nsetTodos([...todos, "deploy"]);                    // add\nsetTodos(todos.filter((t) => t !== "test"));       // remove\nsetTodos(todos.map((t) => (t === "write" ? "edit" : t)));   // change'),
    ("h2", "Lifting state up"),
    ("p", "When two components need the same data, move the state to their closest common parent and pass it down as props, along with functions to change it. This keeps one source of truth."),
    ("code", "javascript", 'function Parent() {\n  const [query, setQuery] = useState("");\n  return (\n    <>\n      <SearchBox value={query} onChange={setQuery} />\n      <Results query={query} />\n    </>\n  );\n}'),
    ("h2", "Deriving values"),
    ("p", "Do not store something in state if you can compute it from existing state or props. Storing <code>fullName</code> alongside <code>first</code> and <code>last</code> creates a chance for them to disagree; compute it during render instead."),
    ("note", "Rule of thumb", "State is for things that <em>change over time and affect what is shown</em>. Everything else should be a constant, a prop, or a value computed while rendering."),
    ("exercise", "Build a <code>Toggle</code> component with a button that switches between \"ON\" and \"OFF\", and a <code>Counter</code> with plus, minus and reset buttons where the count never goes below zero."),
    ("solution", "javascript", 'function Toggle() {\n  const [on, setOn] = useState(false);\n  return <button onClick={() => setOn(!on)}>{on ? "ON" : "OFF"}</button>;\n}\n\nfunction Counter() {\n  const [n, setN] = useState(0);\n  return (\n    <>\n      <button onClick={() => setN((c) => Math.max(0, c - 1))}>-</button>\n      <span>{n}</span>\n      <button onClick={() => setN((c) => c + 1)}>+</button>\n      <button onClick={() => setN(0)}>Reset</button>\n    </>\n  );\n}'),
]

CONTENT["react-events-forms"] = [
    ("p", "Interfaces are interactive: users click, type and submit. In React you attach handlers with camelCase props such as <code>onClick</code>, <code>onChange</code> and <code>onSubmit</code>, and pass them a <em>function</em>, not the result of calling one."),
    ("h2", "Handling events"),
    ("code", "javascript", 'function Save() {\n  function handleClick(event) {\n    console.log("saved", event.type);\n  }\n  return <button onClick={handleClick}>Save</button>;\n  // Wrong: onClick={handleClick()}  runs immediately on every render\n}'),
    ("h2", "Rendering lists"),
    ("p", "Use <code>map</code> to turn an array into elements. Each item needs a stable, unique <code>key</code> prop so React can tell which item is which when the list changes. Use an id from your data, not the array index, if the list can be reordered or filtered."),
    ("code", "javascript", 'const todos = [\n  { id: 1, text: "Learn React", done: true },\n  { id: 2, text: "Build an app", done: false },\n];\n\nfunction TodoList() {\n  return (\n    <ul>\n      {todos.map((t) => (\n        <li key={t.id} style={{ textDecoration: t.done ? "line-through" : "none" }}>\n          {t.text}\n        </li>\n      ))}\n    </ul>\n  );\n}'),
    ("h2", "Controlled inputs"),
    ("p", "In a <strong>controlled</strong> input, React state is the single source of truth: the input shows <code>value</code> from state and updates it in <code>onChange</code>. That makes validation, formatting and clearing trivial."),
    ("code", "javascript", 'function NameForm() {\n  const [name, setName] = useState("");\n  return (\n    <label>\n      Name\n      <input value={name} onChange={(e) => setName(e.target.value)} />\n      <p>Hello, {name || "stranger"}</p>\n    </label>\n  );\n}'),
    ("h2", "A complete form"),
    ("code", "javascript", 'function AddTodo({ onAdd }) {\n  const [text, setText] = useState("");\n\n  function handleSubmit(e) {\n    e.preventDefault();               // stop the page reload\n    if (!text.trim()) return;\n    onAdd(text.trim());\n    setText("");\n  }\n\n  return (\n    <form onSubmit={handleSubmit}>\n      <input value={text} onChange={(e) => setText(e.target.value)} placeholder="New task" />\n      <button type="submit">Add</button>\n    </form>\n  );\n}\n\nfunction App() {\n  const [todos, setTodos] = useState([]);\n  return (\n    <>\n      <AddTodo onAdd={(t) => setTodos([...todos, { id: crypto.randomUUID(), text: t }])} />\n      <ul>{todos.map((t) => <li key={t.id}>{t.text}</li>)}</ul>\n    </>\n  );\n}'),
    ("p", "Checkboxes use <code>checked</code> and <code>e.target.checked</code>; selects use <code>value</code> like text inputs. For forms with many fields, store them in one object: <code>setForm({ ...form, [e.target.name]: e.target.value })</code>."),
    ("note", "Common bugs", "Forgetting <code>preventDefault()</code> reloads the page. Missing keys cause a console warning and odd behavior. An input with <code>value</code> but no <code>onChange</code> is read-only."),
    ("exercise", "Extend the todo app: add a checkbox to mark tasks done, and a delete button per task. Update state without mutating it."),
    ("solution", "javascript", 'const toggle = (id) =>\n  setTodos(todos.map((t) => (t.id === id ? { ...t, done: !t.done } : t)));\nconst remove = (id) => setTodos(todos.filter((t) => t.id !== id));\n\n<li key={t.id}>\n  <input type="checkbox" checked={!!t.done} onChange={() => toggle(t.id)} />\n  {t.text}\n  <button onClick={() => remove(t.id)}>Delete</button>\n</li>'),
]

CONTENT["react-effects"] = [
    ("p", "Rendering should be a pure calculation: same props and state in, same JSX out. But apps also need to talk to things <em>outside</em> React: servers, timers, the browser title, event listeners. <strong>Effects</strong> are the escape hatch. <code>useEffect</code> runs your code after React has updated the screen."),
    ("h2", "Anatomy"),
    ("code", "javascript", 'import { useState, useEffect } from "react";\n\nfunction Title({ name }) {\n  useEffect(() => {\n    document.title = `Hello ${name}`;   // runs after render\n  }, [name]);                            // ...only when name changes\n  return <h1>{name}</h1>;\n}'),
    ("p", "The second argument is the <strong>dependency array</strong>:"),
    ("ul", [
        "<code>[a, b]</code>: run after the first render and whenever <code>a</code> or <code>b</code> changed.",
        "<code>[]</code>: run once after the first render.",
        "omitted: run after every render (rarely what you want).",
    ]),
    ("p", "List every reactive value the effect reads (props, state, values derived from them). The lint rule <code>react-hooks/exhaustive-deps</code> checks this for you; treat its warnings seriously, because stale values are a top source of bugs."),
    ("h2", "Cleanup"),
    ("p", "An effect may return a function that React calls before the effect re-runs and when the component unmounts. Use it to stop timers, remove listeners and cancel subscriptions."),
    ("code", "javascript", 'function Clock() {\n  const [now, setNow] = useState(new Date());\n  useEffect(() => {\n    const id = setInterval(() => setNow(new Date()), 1000);\n    return () => clearInterval(id);     // cleanup\n  }, []);\n  return <p>{now.toLocaleTimeString()}</p>;\n}'),
    ("p", "In development, StrictMode runs effects twice (mount, unmount, mount) on purpose. If your effect breaks when run twice, it is missing a cleanup."),
    ("h2", "Fetching data"),
    ("code", "javascript", 'function User({ id }) {\n  const [user, setUser] = useState(null);\n\n  useEffect(() => {\n    let ignore = false;                 // avoid setting state from a stale request\n    fetch(`/api/users/${id}`)\n      .then((r) => r.json())\n      .then((data) => { if (!ignore) setUser(data); });\n    return () => { ignore = true; };\n  }, [id]);\n\n  return user ? <p>{user.name}</p> : <p>Loading...</p>;\n}'),
    ("h2", "You might not need an effect"),
    ("ul", [
        "Computing a value from props or state: do it during render, no effect needed.",
        "Responding to a click or submit: put the logic in the event handler.",
        "Resetting state when a prop changes: give the component a different <code>key</code>.",
    ]),
    ("note", "Infinite loop", "An effect that sets state, with that same state in its dependency array, can loop forever. Also, an object or function created inline changes identity on every render, so listing it as a dependency re-runs the effect each time."),
    ("exercise", "Write a <code>useWindowWidth</code>-style effect: track <code>window.innerWidth</code> in state, update it on the <code>resize</code> event and remove the listener on cleanup."),
    ("solution", "javascript", 'function Width() {\n  const [w, setW] = useState(window.innerWidth);\n  useEffect(() => {\n    const onResize = () => setW(window.innerWidth);\n    window.addEventListener("resize", onResize);\n    return () => window.removeEventListener("resize", onResize);\n  }, []);\n  return <p>{w}px</p>;\n}'),
]

CONTENT["react-hooks-context"] = [
    ("p", "Hooks are ordinary functions, so you can package repeated logic into your own. This lesson covers three tools that make larger apps manageable: custom hooks, refs and context."),
    ("h2", "Custom hooks"),
    ("p", "A custom hook is a function whose name starts with <code>use</code> and which calls other hooks. It shares <em>logic</em>, not state: each component that calls it gets its own copy."),
    ("code", "javascript", 'function useLocalStorage(key, initial) {\n  const [value, setValue] = useState(() => {\n    const saved = localStorage.getItem(key);\n    return saved ? JSON.parse(saved) : initial;\n  });\n  useEffect(() => {\n    localStorage.setItem(key, JSON.stringify(value));\n  }, [key, value]);\n  return [value, setValue];\n}\n\nfunction Settings() {\n  const [theme, setTheme] = useLocalStorage("theme", "light");\n  return <button onClick={() => setTheme(theme === "light" ? "dark" : "light")}>{theme}</button>;\n}'),
    ("p", "Passing a function to <code>useState</code> (lazy initialization) means the expensive read runs only on the first render."),
    ("h2", "useRef"),
    ("p", "A ref holds a value that persists across renders but does <strong>not</strong> cause a re-render when it changes. Two main uses: reaching a DOM element, and storing mutable values like timer ids."),
    ("code", "javascript", 'import { useRef } from "react";\n\nfunction SearchBox() {\n  const inputRef = useRef(null);\n  return (\n    <>\n      <input ref={inputRef} />\n      <button onClick={() => inputRef.current.focus()}>Focus</button>\n    </>\n  );\n}'),
    ("h2", "Context"),
    ("p", "Passing props through many layers just to reach a deeply nested component is called <em>prop drilling</em>. <strong>Context</strong> lets a parent make a value available to its entire subtree. Good candidates: the current user, the theme, the language."),
    ("code", "javascript", 'import { createContext, useContext, useState } from "react";\n\nconst ThemeContext = createContext("light");\n\nfunction ThemeProvider({ children }) {\n  const [theme, setTheme] = useState("light");\n  return (\n    <ThemeContext.Provider value={{ theme, setTheme }}>\n      {children}\n    </ThemeContext.Provider>\n  );\n}\n\nfunction ThemeButton() {\n  const { theme, setTheme } = useContext(ThemeContext);\n  return <button onClick={() => setTheme(theme === "light" ? "dark" : "light")}>Theme: {theme}</button>;\n}\n\n// <ThemeProvider><Page /></ThemeProvider>'),
    ("note", "Use sparingly", "Every consumer re-renders when the context value changes. Keep contexts small and focused, and prefer plain props when data only goes one or two levels down."),
    ("h2", "useMemo and useCallback"),
    ("p", "<code>useMemo</code> caches an expensive computed value; <code>useCallback</code> caches a function so its identity stays stable. Do not add them by default; use them when profiling shows a real problem or when a stable identity is needed for a dependency array."),
    ("exercise", "Write a <code>useToggle(initial)</code> custom hook that returns <code>[value, toggle]</code>, then use it for a show/hide panel."),
    ("solution", "javascript", 'function useToggle(initial = false) {\n  const [value, setValue] = useState(initial);\n  const toggle = () => setValue((v) => !v);\n  return [value, toggle];\n}\n\nfunction Panel() {\n  const [open, toggle] = useToggle();\n  return (\n    <>\n      <button onClick={toggle}>{open ? "Hide" : "Show"}</button>\n      {open && <p>Secret panel</p>}\n    </>\n  );\n}'),
]

CONTENT["react-data-fetching"] = [
    ("p", "Almost every real app loads data from an API. A robust component must handle three situations, not one: <strong>loading</strong>, <strong>error</strong> and <strong>success</strong>. Skipping the first two is why many apps flash blank screens or crash on a network hiccup."),
    ("h2", "A fetch hook with all three states"),
    ("code", "javascript", 'function useFetch(url) {\n  const [state, setState] = useState({ status: "loading", data: null, error: null });\n\n  useEffect(() => {\n    const controller = new AbortController();\n    setState({ status: "loading", data: null, error: null });\n\n    fetch(url, { signal: controller.signal })\n      .then((res) => {\n        if (!res.ok) throw new Error(`HTTP ${res.status}`);\n        return res.json();\n      })\n      .then((data) => setState({ status: "success", data, error: null }))\n      .catch((error) => {\n        if (error.name !== "AbortError")\n          setState({ status: "error", data: null, error });\n      });\n\n    return () => controller.abort();     // cancel when url changes or unmounting\n  }, [url]);\n\n  return state;\n}'),
    ("p", "<code>AbortController</code> cancels the in-flight request when the component unmounts or <code>url</code> changes, preventing an old response from overwriting newer data."),
    ("h2", "Using it"),
    ("code", "javascript", 'function Users() {\n  const { status, data, error } = useFetch("https://jsonplaceholder.typicode.com/users");\n\n  if (status === "loading") return <p>Loading...</p>;\n  if (status === "error") return <p role="alert">Failed: {error.message}</p>;\n\n  return (\n    <ul>\n      {data.map((u) => <li key={u.id}>{u.name}</li>)}\n    </ul>\n  );\n}'),
    ("h2", "Mutations"),
    ("p", "Sending data (POST, PUT, DELETE) usually happens in an event handler, not an effect."),
    ("code", "javascript", 'async function createUser(name) {\n  const res = await fetch("/api/users", {\n    method: "POST",\n    headers: { "Content-Type": "application/json" },\n    body: JSON.stringify({ name }),\n  });\n  if (!res.ok) throw new Error("Could not save");\n  return res.json();\n}'),
    ("h2", "Use a data library when it grows"),
    ("p", "Hand-rolled fetching does not cache, deduplicate requests, retry or refetch in the background. Libraries such as <strong>TanStack Query</strong> or <strong>SWR</strong> provide all of that. The pattern stays the same: a hook returns <code>{ data, isLoading, error }</code>."),
    ("code", "javascript", 'import { useQuery } from "@tanstack/react-query";\n\nfunction Users() {\n  const { data, isLoading, error } = useQuery({\n    queryKey: ["users"],\n    queryFn: () => fetch("/api/users").then((r) => r.json()),\n  });\n  if (isLoading) return <p>Loading...</p>;\n  if (error) return <p>Error</p>;\n  return data.map((u) => <p key={u.id}>{u.name}</p>);\n}'),
    ("h2", "Routing"),
    ("p", "Single-page apps show different screens without full page loads. React Router maps URLs to components."),
    ("code", "bash", "npm install react-router-dom"),
    ("code", "javascript", 'import { BrowserRouter, Routes, Route, Link, useParams } from "react-router-dom";\n\nfunction UserPage() {\n  const { id } = useParams();\n  return <h2>User {id}</h2>;\n}\n\nfunction App() {\n  return (\n    <BrowserRouter>\n      <nav>\n        <Link to="/">Home</Link> | <Link to="/users/42">User 42</Link>\n      </nav>\n      <Routes>\n        <Route path="/" element={<h1>Home</h1>} />\n        <Route path="/users/:id" element={<UserPage />} />\n        <Route path="*" element={<p>Not found</p>} />\n      </Routes>\n    </BrowserRouter>\n  );\n}'),
    ("p", "Use <code>&lt;Link&gt;</code> instead of <code>&lt;a&gt;</code> for internal navigation so the page does not reload."),
    ("note", "Where to go next", "Ready for more? Learn a framework built on React, such as Next.js, for server rendering and file-based routing, and TypeScript for safer props."),
    ("exercise", "Fetch a list of posts from <code>https://jsonplaceholder.typicode.com/posts</code>, show a loading message and an error message, and add a text box that filters posts by title as you type."),
    ("solution", "javascript", 'function Posts() {\n  const { status, data, error } = useFetch("https://jsonplaceholder.typicode.com/posts");\n  const [q, setQ] = useState("");\n  if (status === "loading") return <p>Loading...</p>;\n  if (status === "error") return <p>{error.message}</p>;\n  const shown = data.filter((p) => p.title.toLowerCase().includes(q.toLowerCase()));\n  return (\n    <>\n      <input value={q} onChange={(e) => setQ(e.target.value)} placeholder="Filter" />\n      <ul>{shown.map((p) => <li key={p.id}>{p.title}</li>)}</ul>\n    </>\n  );\n}'),
]
