"""Rich lesson bodies for the Python track."""

CONTENT = {}

CONTENT["python-hello-world"] = [
    ("p", "Python is an <strong>interpreted</strong> language. You write plain text in a <code>.py</code> file, and the interpreter reads it top to bottom, running each statement as it goes. There is no separate compile step, so you get feedback in seconds. That fast loop is one of the main reasons Python is a popular first language and a favorite for scripting, data work and web backends."),
    ("h2", "Check your installation"),
    ("p", "Open a terminal and ask Python for its version. On macOS and Linux the command is usually <code>python3</code>; on Windows it is often <code>python</code> or <code>py</code>. Any version 3.9 or newer works for this course."),
    ("code", "bash", "python3 --version"),
    ("output", "Python 3.12.4"),
    ("h2", "Your first program"),
    ("p", "<code>print()</code> is a built-in <em>function</em>. You call it by writing its name followed by parentheses, and put whatever you want displayed inside them. Text is written between quotes and is called a <em>string</em>. Numbers need no quotes, and Python will do the math before printing."),
    ("code", "python", 'print("Hello, stackcone!")\nprint(2 + 2)\nprint("2 + 2 =", 2 + 2)'),
    ("output", "Hello, stackcone!\n4\n2 + 2 = 4"),
    ("p", "Save this as <code>hello.py</code> and run it from the folder where you saved it:"),
    ("code", "bash", "python3 hello.py"),
    ("h2", "Comments and the interpreter"),
    ("p", "Anything after a <code>#</code> on a line is a <strong>comment</strong>. Python ignores it, so use comments to explain <em>why</em> code does something, not <em>what</em> it does. You can also type <code>python3</code> on its own to open the interactive prompt (the REPL), which is a great place to try one-liners."),
    ("code", "python", '# This line is ignored by Python\nprint("visible")  # comments can follow code too'),
    ("h2", "Common mistakes"),
    ("ul", [
        "<strong>Missing quotes</strong>: <code>print(Hello)</code> fails with <code>NameError</code> because Python thinks <code>Hello</code> is a variable. Write <code>print(\"Hello\")</code>.",
        "<strong>Mismatched parentheses or quotes</strong>: every opening <code>(</code> or <code>\"</code> needs a closing partner, or you get a <code>SyntaxError</code>.",
        "<strong>Wrong capitalization</strong>: Python is case sensitive. <code>Print</code> is not <code>print</code>.",
        "<strong>Running from the wrong folder</strong>: <code>No such file or directory</code> means your terminal is not in the folder that contains the file. Use <code>cd</code> to move there.",
    ]),
    ("note", "Reading errors", "When Python fails it prints a <em>traceback</em>. Read it from the bottom: the last line names the error and the line above shows which line of your file caused it."),
    ("exercise", "Change the program to print your name and the current year on two separate lines, then add a comment above each line explaining it."),
    ("solution", "python", '# Print my name\nprint("Amar")\n# Print the year\nprint(2026)'),
]

CONTENT["python-variables-and-types"] = [
    ("p", "A <strong>variable</strong> is a name that points at a value. You create one with the assignment operator <code>=</code>. Python is <em>dynamically typed</em>: you never declare a type, because the type belongs to the value, not the name. The same name can later point at a value of a different type, although doing that on purpose is usually a sign of confusing code."),
    ("h2", "The core types"),
    ("ul", [
        "<code>int</code>: whole numbers of any size, such as <code>28</code> or <code>-5</code>.",
        "<code>float</code>: decimal numbers such as <code>19.99</code>. They are binary approximations, so <code>0.1 + 0.2</code> is not exactly <code>0.3</code>.",
        "<code>str</code>: text, written in single or double quotes.",
        "<code>bool</code>: <code>True</code> or <code>False</code> (note the capital letters).",
        "<code>None</code>: a special value that means \"nothing here yet\".",
    ]),
    ("code", "python", 'age = 28\nprice = 19.99\nname = "Amar"\nactive = True\nnickname = None\n\nprint(type(age), type(price), type(name), type(active))'),
    ("output", "<class 'int'> <class 'float'> <class 'str'> <class 'bool'>"),
    ("h2", "Naming rules and style"),
    ("p", "Names can contain letters, digits and underscores but cannot start with a digit or be a reserved word like <code>class</code> or <code>if</code>. The community style is <code>snake_case</code> for variables: <code>total_price</code>, not <code>totalPrice</code>. Pick names that say what the value is."),
    ("h2", "Doing math and building strings"),
    ("p", "Arithmetic uses <code>+ - * /</code>. Also useful: <code>//</code> for floor division, <code>%</code> for the remainder and <code>**</code> for powers. To put values inside text, use an <strong>f-string</strong>: prefix the string with <code>f</code> and place expressions in braces."),
    ("code", "python", 'items = 3\nunit_price = 4.5\ntotal = items * unit_price\n\nprint(7 // 2, 7 % 2, 2 ** 10)\nprint(f"{items} items cost ${total:.2f}")'),
    ("output", "3 1 1024\n3 items cost $13.50"),
    ("h2", "Type conversion"),
    ("p", "Input from files and users usually arrives as text. Convert it with <code>int()</code>, <code>float()</code>, <code>str()</code> and <code>bool()</code>. Conversion can fail: <code>int(\"abc\")</code> raises a <code>ValueError</code>, which you will learn to handle in the error-handling lesson."),
    ("code", "python", 'n = int("42")\nprice = float("19.99")\nlabel = str(3.14)\nprint(n + 1, price * 2, label + "!")'),
    ("output", "43 39.98 3.14!"),
    ("note", "Strings are not numbers", "<code>\"2\" + \"2\"</code> is <code>\"22\"</code>, because <code>+</code> joins strings. Mixing types, like <code>\"2\" + 2</code>, raises a <code>TypeError</code>. Convert first."),
    ("exercise", "Create variables for a product title, a price and an in-stock flag. Print one summary line such as <code>Laptop costs $999.00 (in stock: True)</code> using an f-string."),
    ("solution", "python", 'title = "Laptop"\nprice = 999\nin_stock = True\nprint(f"{title} costs ${price:.2f} (in stock: {in_stock})")'),
]

CONTENT["python-control-flow"] = [
    ("p", "Programs get interesting when they can make decisions and repeat work. <strong>Control flow</strong> statements do both. Python marks the body of each one with <em>indentation</em> (four spaces by convention) instead of braces, so consistent indentation is part of the syntax."),
    ("h2", "Conditionals"),
    ("p", "<code>if</code> runs a block when its condition is true. Add <code>elif</code> for extra cases and <code>else</code> for the fallback. Python checks them in order and runs only the first block that matches. Conditions use comparison operators (<code>== != &lt; &gt; &lt;= &gt;=</code>) and the logical words <code>and</code>, <code>or</code>, <code>not</code>."),
    ("code", "python", 'score = 87\nif score >= 90:\n    grade = "A"\nelif score >= 80:\n    grade = "B"\nelse:\n    grade = "C"\nprint(grade)'),
    ("output", "B"),
    ("note", "Truthiness", "Empty things count as false in a condition: <code>0</code>, <code>\"\"</code>, <code>[]</code>, <code>{}</code> and <code>None</code>. That lets you write <code>if items:</code> instead of <code>if len(items) &gt; 0:</code>."),
    ("h2", "for loops"),
    ("p", "A <code>for</code> loop walks through any sequence one item at a time. <code>range(n)</code> produces the numbers <code>0</code> to <code>n-1</code>; <code>range(start, stop, step)</code> gives you control over both ends and the gap. Use <code>enumerate()</code> when you need the position as well as the value."),
    ("code", "python", 'for i in range(3):\n    print("tick", i)\n\nfor idx, color in enumerate(["red", "green"], start=1):\n    print(idx, color)'),
    ("output", "tick 0\ntick 1\ntick 2\n1 red\n2 green"),
    ("h2", "while loops"),
    ("p", "<code>while</code> repeats as long as its condition stays true, which makes it right when you do not know the number of repetitions in advance. Always make sure something inside the loop moves it toward the exit, or you will create an infinite loop. Use <code>break</code> to leave early and <code>continue</code> to skip to the next round."),
    ("code", "python", 'count = 3\nwhile count > 0:\n    print(count)\n    count -= 1\nprint("liftoff")'),
    ("output", "3\n2\n1\nliftoff"),
    ("h2", "Common mistakes"),
    ("ul", [
        "Using <code>=</code> (assign) where you meant <code>==</code> (compare).",
        "Forgetting the colon at the end of <code>if</code>, <code>for</code> or <code>while</code> lines.",
        "Mixing tabs and spaces, which causes <code>IndentationError</code>.",
        "Off-by-one errors: <code>range(5)</code> stops at 4, not 5.",
    ]),
    ("exercise", "Print the even numbers from 2 to 20 using a <code>for</code> loop. Then print \"FizzBuzz\" style: for 1 to 15 print \"Fizz\" for multiples of 3, \"Buzz\" for multiples of 5, and the number otherwise."),
    ("solution", "python", 'for n in range(2, 21, 2):\n    print(n)\n\nfor n in range(1, 16):\n    if n % 3 == 0:\n        print("Fizz")\n    elif n % 5 == 0:\n        print("Buzz")\n    else:\n        print(n)'),
]

CONTENT["python-functions"] = [
    ("p", "A <strong>function</strong> is a named, reusable block of code. Functions let you avoid copy and paste, give a name to an idea, and test small pieces in isolation. You define one with <code>def</code>, list its <em>parameters</em> in parentheses, and use <code>return</code> to hand a result back to the caller."),
    ("h2", "Defining and calling"),
    ("code", "python", 'def area_circle(radius):\n    return 3.14159 * radius ** 2\n\nprint(area_circle(2))\nresult = area_circle(10)'),
    ("output", "12.56636"),
    ("p", "The values you pass in are called <em>arguments</em>. A function with no <code>return</code> statement returns <code>None</code>. Prefer returning a value over printing inside the function, because a returned value can be reused, tested and combined."),
    ("h2", "Default and keyword arguments"),
    ("p", "Give a parameter a default value and callers may omit it. When you call a function you can also name arguments, which makes calls self-documenting and lets you pass them in any order."),
    ("code", "python", 'def greet(name, excited=False):\n    msg = f"Hello, {name}"\n    return msg + "!" if excited else msg\n\nprint(greet("world"))\nprint(greet("world", excited=True))\nprint(greet(excited=True, name="Ada"))'),
    ("output", "Hello, world\nHello, world!\nHello, Ada!"),
    ("h2", "Returning several values"),
    ("p", "Python can return a tuple, and the caller can unpack it into separate names in one line."),
    ("code", "python", 'def min_max(nums):\n    return min(nums), max(nums)\n\nlow, high = min_max([4, 9, 1, 7])\nprint(low, high)'),
    ("output", "1 9"),
    ("h2", "Scope"),
    ("p", "Variables created inside a function are <strong>local</strong>: they exist only while the function runs. Reading a global variable inside a function is fine, but assigning to it creates a new local one instead. Passing data in through parameters and out through <code>return</code> keeps functions predictable."),
    ("note", "Mutable default trap", "Never use a list or dict as a default value, as in <code>def add(x, items=[])</code>. The same list is shared across every call. Use <code>items=None</code> and create the list inside the function."),
    ("exercise", "Write <code>area_rect(w, h)</code> that returns width times height. Then write <code>is_even(n)</code> that returns <code>True</code> or <code>False</code>, and use it in a loop to print the even numbers below 10."),
    ("solution", "python", 'def area_rect(w, h):\n    return w * h\n\ndef is_even(n):\n    return n % 2 == 0\n\nfor n in range(10):\n    if is_even(n):\n        print(n)'),
]

CONTENT["python-lists-tuples"] = [
    ("p", "Lists and tuples are <strong>ordered sequences</strong>: they keep items in the order you put them in and let you fetch any item by its position. The difference is mutability. A list can be changed after creation; a tuple cannot."),
    ("h2", "Lists"),
    ("p", "Create a list with square brackets. Indexes start at 0, and negative indexes count from the end, so <code>nums[-1]</code> is the last item. Slicing with <code>nums[start:stop]</code> returns a new list that includes <code>start</code> and excludes <code>stop</code>."),
    ("code", "python", 'nums = [10, 20, 30]\nnums.append(40)      # add to the end\nnums.insert(0, 5)    # add at a position\nlast = nums.pop()    # remove and return the last item\n\nprint(nums)\nprint(nums[1:3], nums[-1])\nprint(len(nums), 20 in nums)'),
    ("output", "[5, 10, 20, 30]\n[10, 20] 30\n4 True"),
    ("p", "Other methods you will use constantly: <code>remove(x)</code>, <code>sort()</code>, <code>reverse()</code>, <code>index(x)</code> and <code>count(x)</code>. The built-in <code>sorted(nums)</code> returns a new sorted list and leaves the original alone."),
    ("h2", "Looping and comprehensions"),
    ("p", "A <strong>list comprehension</strong> builds a new list from an existing one in a single readable line: <code>[expression for item in items if condition]</code>."),
    ("code", "python", 'nums = [1, 2, 3, 4, 5, 6]\nsquares = [n * n for n in nums]\nevens = [n for n in nums if n % 2 == 0]\nprint(squares)\nprint(evens)'),
    ("output", "[1, 4, 9, 16, 25, 36]\n[2, 4, 6]"),
    ("h2", "Tuples"),
    ("p", "A tuple uses parentheses and cannot be modified. Use one for a small fixed group of related values, such as a coordinate pair or a database row. Because tuples are immutable, they can be used as dictionary keys."),
    ("code", "python", 'point = (3, 4)\nx, y = point        # unpacking\nprint(x, y, point[0])\n# point[0] = 9      # TypeError: tuples are immutable'),
    ("output", "3 4 3"),
    ("note", "Copies share data", "<code>b = a</code> does not copy a list; both names point at the same list. Use <code>b = a.copy()</code> or <code>b = a[:]</code> when you want an independent copy."),
    ("exercise", "Given <code>scores = [88, 92, 75, 95]</code>, print the highest score without using <code>max()</code>. Then build a list of the scores that are 90 or above using a comprehension."),
    ("solution", "python", 'scores = [88, 92, 75, 95]\nbest = scores[0]\nfor s in scores:\n    if s > best:\n        best = s\nprint(best)\n\nhigh = [s for s in scores if s >= 90]\nprint(high)'),
]

CONTENT["python-dictionaries"] = [
    ("p", "A <strong>dictionary</strong> stores data as key-value pairs. Instead of asking \"what is at position 2?\" you ask \"what is the value for the key <code>\"email\"</code>?\". Lookups are very fast, on average constant time no matter how large the dictionary grows. Keys must be immutable (strings, numbers, tuples); values can be anything."),
    ("h2", "Creating and reading"),
    ("code", "python", 'user = {"id": 1, "email": "dev@example.com"}\nuser["role"] = "admin"      # add or update\n\nprint(user["email"])\nprint(user.get("phone", "n/a"))  # safe lookup with a default\nprint("role" in user)'),
    ("output", "dev@example.com\nn/a\nTrue"),
    ("p", "Indexing a missing key with <code>user[\"phone\"]</code> raises <code>KeyError</code>. Use <code>.get(key, default)</code> when the key may not exist. Remove entries with <code>del user[\"role\"]</code> or <code>user.pop(\"role\")</code>."),
    ("h2", "Iterating"),
    ("code", "python", 'for key, val in user.items():\n    print(key, "=", val)\n\nprint(list(user.keys()))\nprint(list(user.values()))'),
    ("output", "id = 1\nemail = dev@example.com\nrole = admin\n['id', 'email', 'role']\n[1, 'dev@example.com', 'admin']"),
    ("h2", "A classic pattern: counting"),
    ("p", "Dictionaries are the natural tool for counting things. <code>counts.get(word, 0) + 1</code> reads the current count, treating a missing word as zero."),
    ("code", "python", 'text = "the cat and the hat"\ncounts = {}\nfor word in text.split():\n    counts[word] = counts.get(word, 0) + 1\nprint(counts)'),
    ("output", "{'the': 2, 'cat': 1, 'and': 1, 'hat': 1}"),
    ("h2", "Sets"),
    ("p", "A <strong>set</strong> is an unordered collection of unique values. Adding a duplicate does nothing, which makes sets ideal for removing repeats and for fast membership checks. They also support math operations: union <code>|</code>, intersection <code>&amp;</code> and difference <code>-</code>."),
    ("code", "python", 'tags = {"python", "api", "python"}\nprint(tags)\nprint({1, 2, 3} & {2, 3, 4})\nprint(len(set([1, 1, 2, 2, 3])))'),
    ("output", "{'python', 'api'}\n{2, 3}\n3"),
    ("note", "Order", "Since Python 3.7 dictionaries remember insertion order. Sets do not guarantee any order, so never rely on it."),
    ("exercise", "Build a word-frequency dictionary from a sentence, then print the word that appears most often."),
    ("solution", "python", 'text = "to be or not to be"\ncounts = {}\nfor w in text.split():\n    counts[w] = counts.get(w, 0) + 1\n\nbest = max(counts, key=counts.get)\nprint(best, counts[best])'),
]

CONTENT["python-oop-classes"] = [
    ("p", "A <strong>class</strong> is a blueprint that bundles data (attributes) with the functions that work on it (methods). An <strong>object</strong>, or instance, is one thing built from that blueprint. Classes help when several related values travel together, such as a bank account with an owner and a balance, and when behavior belongs with that data."),
    ("h2", "Your first class"),
    ("p", "<code>__init__</code> runs automatically when you create an instance and sets up its starting state. The first parameter of every method is <code>self</code>, which refers to the specific object the method is being called on. You do not pass it yourself; Python does."),
    ("code", "python", 'class BankAccount:\n    def __init__(self, owner, balance=0):\n        self.owner = owner\n        self.balance = balance\n\n    def deposit(self, amount):\n        self.balance += amount\n\nacct = BankAccount("Amar", 100)\nacct.deposit(50)\nprint(acct.owner, acct.balance)'),
    ("output", "Amar 150"),
    ("h2", "Each object has its own state"),
    ("p", "Two instances of the same class do not share attribute values. Changing one account leaves the other untouched."),
    ("code", "python", 'a = BankAccount("Ann", 10)\nb = BankAccount("Bob", 500)\na.deposit(5)\nprint(a.balance, b.balance)'),
    ("output", "15 500"),
    ("h2", "Making objects printable"),
    ("p", "Special methods with double underscores customize behavior. <code>__repr__</code> controls how an object is displayed, which makes debugging much easier than the default <code>&lt;BankAccount object at 0x...&gt;</code>."),
    ("code", "python", 'class BankAccount:\n    def __init__(self, owner, balance=0):\n        self.owner, self.balance = owner, balance\n\n    def __repr__(self):\n        return f"BankAccount({self.owner!r}, {self.balance})"\n\nprint(BankAccount("Amar", 100))'),
    ("output", "BankAccount('Amar', 100)"),
    ("h2", "Inheritance in one minute"),
    ("p", "A subclass reuses and extends another class. Put the parent in parentheses and call <code>super()</code> to run its logic."),
    ("code", "python", 'class SavingsAccount(BankAccount):\n    def add_interest(self, rate):\n        self.deposit(self.balance * rate)\n\ns = SavingsAccount("Amar", 1000)\ns.add_interest(0.05)\nprint(s.balance)'),
    ("output", "1050.0"),
    ("note", "When to use a class", "If you only need to group a few values, a dictionary or a <code>dataclass</code> is simpler. Reach for a full class when behavior and data belong together."),
    ("exercise", "Add a <code>withdraw(amount)</code> method that refuses to make the balance negative. Return <code>True</code> when it works and <code>False</code> when it does not."),
    ("solution", "python", 'class BankAccount:\n    def __init__(self, owner, balance=0):\n        self.owner = owner\n        self.balance = balance\n\n    def withdraw(self, amount):\n        if amount > self.balance:\n            return False\n        self.balance -= amount\n        return True\n\nacct = BankAccount("Amar", 100)\nprint(acct.withdraw(150), acct.withdraw(40), acct.balance)'),
]

CONTENT["python-file-handling"] = [
    ("p", "Real programs read configuration, process logs and save results, all of which means working with files. Python's <code>open()</code> gives you a file object, and the safest way to use it is inside a <code>with</code> block. The block guarantees the file is closed when you leave it, even if an error happens."),
    ("h2", "Writing a file"),
    ("p", "The second argument is the <strong>mode</strong>: <code>\"w\"</code> writes and <em>erases any existing content</em>, <code>\"a\"</code> appends, <code>\"r\"</code> reads (the default). Always pass <code>encoding=\"utf-8\"</code> so text behaves the same on every operating system."),
    ("code", "python", 'with open("notes.txt", "w", encoding="utf-8") as f:\n    f.write("first line\\n")\n    f.write("second line\\n")'),
    ("h2", "Reading a file"),
    ("p", "<code>f.read()</code> returns the whole file as one string, <code>f.readlines()</code> returns a list of lines, and looping over the file object reads one line at a time, which keeps memory use low for large files."),
    ("code", "python", 'with open("notes.txt", encoding="utf-8") as f:\n    for line in f:\n        print(line.strip())'),
    ("output", "first line\nsecond line"),
    ("p", "<code>strip()</code> removes the trailing newline character that every line carries."),
    ("h2", "Appending and paths"),
    ("p", "Use mode <code>\"a\"</code> to add to the end of a file without erasing it. For building paths that work on Windows, macOS and Linux, prefer <code>pathlib</code> over string concatenation."),
    ("code", "python", 'from pathlib import Path\n\npath = Path("data") / "log.txt"\npath.parent.mkdir(exist_ok=True)\nwith path.open("a", encoding="utf-8") as f:\n    f.write("started\\n")\nprint(path.exists(), path.read_text(encoding="utf-8"))'),
    ("h2", "Handling missing files"),
    ("p", "Opening a file that does not exist raises <code>FileNotFoundError</code>. Catch that specific exception to give a helpful fallback."),
    ("code", "python", 'try:\n    with open("missing.txt", encoding="utf-8") as f:\n        data = f.read()\nexcept FileNotFoundError:\n    data = ""\n    print("no file, using empty data")'),
    ("output", "no file, using empty data"),
    ("note", "Watch out", "Opening with <code>\"w\"</code> truncates the file immediately, before you write anything. If you meant to add to a file, use <code>\"a\"</code>."),
    ("exercise", "Write a function <code>count_lines(path)</code> that returns how many lines a file contains, or <code>0</code> if the file does not exist."),
    ("solution", "python", 'def count_lines(path):\n    try:\n        with open(path, encoding="utf-8") as f:\n            return sum(1 for _ in f)\n    except FileNotFoundError:\n        return 0'),
]

CONTENT["python-error-handling"] = [
    ("p", "Things go wrong: files are missing, users type letters where numbers belong, networks drop. When Python hits a problem it raises an <strong>exception</strong>. If nothing handles it, the program stops and prints a traceback. <strong>Error handling</strong> lets you respond gracefully instead."),
    ("h2", "try and except"),
    ("p", "Put risky code in a <code>try</code> block and describe how to recover in <code>except</code>. Catch the <em>specific</em> exception you expect. A bare <code>except:</code> hides real bugs, including typos in your own code."),
    ("code", "python", 'raw = "abc"\ntry:\n    n = int(raw)\nexcept ValueError:\n    n = 0\n    print("not a number, using 0")\nprint(n)'),
    ("output", "not a number, using 0\n0"),
    ("h2", "else and finally"),
    ("p", "<code>else</code> runs only when no exception happened, and <code>finally</code> always runs, which makes it the place for cleanup such as closing a connection."),
    ("code", "python", 'try:\n    result = 10 / 2\nexcept ZeroDivisionError:\n    print("cannot divide by zero")\nelse:\n    print("result:", result)\nfinally:\n    print("done")'),
    ("output", "result: 5.0\ndone"),
    ("h2", "Raising your own errors"),
    ("p", "Use <code>raise</code> to signal that the caller gave you bad input. Choose the most fitting built-in type (<code>ValueError</code> for a bad value, <code>TypeError</code> for a bad type) and write a message that says what was wrong."),
    ("code", "python", 'def parse_port(text):\n    try:\n        port = int(text)\n    except ValueError:\n        raise ValueError(f"invalid port: {text}") from None\n    if not 1 <= port <= 65535:\n        raise ValueError("port out of range")\n    return port\n\nprint(parse_port("8080"))\nprint(parse_port("99999"))'),
    ("output", "8080\nValueError: port out of range"),
    ("h2", "Common exceptions"),
    ("ul", [
        "<code>ValueError</code>: right type, wrong value, like <code>int(\"x\")</code>.",
        "<code>TypeError</code>: wrong type, like <code>\"a\" + 1</code>.",
        "<code>KeyError</code> / <code>IndexError</code>: missing dictionary key or list position.",
        "<code>FileNotFoundError</code>: the path does not exist.",
        "<code>ZeroDivisionError</code>: dividing by zero.",
    ]),
    ("note", "Fail loudly", "Only catch an exception when you can actually do something useful about it. Swallowing errors silently makes bugs very hard to find later."),
    ("exercise", "Write <code>safe_divide(a, b)</code> that returns the result, or <code>None</code> when <code>b</code> is zero. Then wrap file reading in try/except so it returns <code>None</code> if the file is missing."),
    ("solution", "python", 'def safe_divide(a, b):\n    try:\n        return a / b\n    except ZeroDivisionError:\n        return None\n\ndef read_or_none(path):\n    try:\n        with open(path, encoding="utf-8") as f:\n            return f.read()\n    except FileNotFoundError:\n        return None'),
]
