"""Rich lesson bodies for the Java track."""

CONTENT = {}

CONTENT["java-hello-world"] = [
    ("p", "Java is a <strong>compiled, statically typed</strong> language. You write source code in <code>.java</code> files, the compiler (<code>javac</code>) turns it into bytecode (<code>.class</code> files), and the Java Virtual Machine (JVM) runs that bytecode. Because the JVM exists on every major platform, the same compiled program runs on Windows, macOS and Linux. That portability, plus speed and a huge ecosystem, is why Java powers so many banks, Android apps and backend services."),
    ("h2", "JDK, JRE and JVM"),
    ("ul", [
        "<strong>JVM</strong>: the engine that runs bytecode.",
        "<strong>JRE</strong>: the JVM plus the standard libraries needed to run programs.",
        "<strong>JDK</strong>: the JRE plus developer tools such as the compiler. Install a JDK (17 or newer) to follow this course.",
    ]),
    ("code", "bash", "java -version\njavac -version"),
    ("h2", "Your first class"),
    ("p", "Every Java program lives inside a class. The program starts at the <code>main</code> method, which must have exactly this signature. The file name must match the public class name, so this class goes in <code>Hello.java</code>."),
    ("code", "java", 'public class Hello {\n    public static void main(String[] args) {\n        System.out.println("Hello, stackcone!");\n    }\n}'),
    ("p", "Reading the signature word by word:"),
    ("ul", [
        "<code>public</code>: callable from anywhere, so the JVM can start it.",
        "<code>static</code>: belongs to the class itself, so no object is needed to call it.",
        "<code>void</code>: returns nothing.",
        "<code>String[] args</code>: command-line arguments, as an array of strings.",
    ]),
    ("h2", "Compile and run"),
    ("code", "bash", "javac Hello.java\njava Hello"),
    ("output", "Hello, stackcone!"),
    ("p", "<code>javac</code> produces <code>Hello.class</code>; <code>java Hello</code> runs it (note: no <code>.class</code> extension). Since Java 11 you can also run a single file directly with <code>java Hello.java</code>."),
    ("h2", "Common mistakes"),
    ("ul", [
        "<strong>Missing semicolon</strong>: every statement ends with <code>;</code>.",
        "<strong>Class and file name mismatch</strong>: <code>class Hello</code> in <code>hello.java</code> fails to compile.",
        "<strong>Case sensitivity</strong>: <code>system.out.println</code> is an error; it is <code>System</code> with a capital S.",
        "<strong>Braces</strong>: every <code>{</code> needs a matching <code>}</code>.",
    ]),
    ("exercise", "Modify the program to print your name on one line and your favorite language on the next, using two <code>println</code> calls."),
    ("solution", "java", 'public class Hello {\n    public static void main(String[] args) {\n        System.out.println("Amar");\n        System.out.println("Java");\n    }\n}'),
]

CONTENT["java-variables-types"] = [
    ("p", "In Java you must <strong>declare the type</strong> of every variable, and the compiler enforces it. That feels strict compared with Python, but it catches a whole class of mistakes before the program ever runs. A variable declaration has the shape <code>type name = value;</code>."),
    ("h2", "Primitive types"),
    ("p", "Primitives hold raw values directly and are very fast. The ones you will use most:"),
    ("ul", [
        "<code>int</code>: 32-bit whole numbers (about ±2.1 billion). <code>long</code> is the 64-bit version.",
        "<code>double</code>: 64-bit decimals. <code>float</code> is the less precise 32-bit version.",
        "<code>boolean</code>: <code>true</code> or <code>false</code>.",
        "<code>char</code>: a single character in single quotes, like <code>'A'</code>.",
    ]),
    ("code", "java", 'int count = 3;\nlong population = 8_000_000_000L;\ndouble price = 9.99;\nboolean active = true;\nchar grade = \'A\';\nString name = "stackcone";\n\nSystem.out.println(name + " has " + count + " items");'),
    ("output", "stackcone has 3 items"),
    ("p", "<code>String</code> is not a primitive but a class, written with a capital letter. Strings are <strong>immutable</strong>: methods like <code>toUpperCase()</code> return a new string instead of changing the original."),
    ("h2", "Type inference with var"),
    ("p", "Since Java 10 you can write <code>var</code> for local variables and let the compiler work out the type from the right-hand side. The variable is still statically typed; you are only saving keystrokes."),
    ("code", "java", 'var total = 42;          // int\nvar label = "Total";      // String\nSystem.out.println(label + ": " + total);'),
    ("h2", "Casting and integer division"),
    ("p", "Converting a wider type to a narrower one requires an explicit <em>cast</em>. Beware that dividing two <code>int</code> values gives an <code>int</code>, discarding the fraction."),
    ("code", "java", 'double d = 9.7;\nint truncated = (int) d;      // 9, not rounded\n\nSystem.out.println(7 / 2);       // 3\nSystem.out.println(7 / 2.0);     // 3.5\nSystem.out.println(truncated);'),
    ("output", "3\n3.5\n9"),
    ("h2", "Comparing strings"),
    ("p", "Use <code>.equals()</code> to compare string contents. The <code>==</code> operator compares whether two references point at the very same object, which is almost never what you want for text."),
    ("code", "java", 'String a = new String("java");\nString b = "java";\nSystem.out.println(a == b);       // false (different objects)\nSystem.out.println(a.equals(b));  // true'),
    ("note", "final", "Add <code>final</code> to a variable that should never change: <code>final int MAX = 100;</code>. The compiler will reject any later assignment."),
    ("exercise", "Declare an <code>int</code> price in cents and a <code>double</code> tax rate. Compute the total as a double and print it formatted like <code>Total: 1080.00</code> using <code>System.out.printf</code>."),
    ("solution", "java", 'int cents = 1000;\ndouble rate = 0.08;\ndouble total = cents + cents * rate;\nSystem.out.printf("Total: %.2f%n", total);'),
]

CONTENT["java-control-flow"] = [
    ("p", "Control flow decides which code runs and how many times. Java's syntax will feel familiar if you know any C-style language: conditions go in parentheses and blocks go in braces. Unlike Python, indentation is only for humans; the braces are what the compiler reads."),
    ("h2", "if / else"),
    ("code", "java", 'int score = 87;\nString grade;\nif (score >= 90) {\n    grade = "A";\n} else if (score >= 80) {\n    grade = "B";\n} else {\n    grade = "C";\n}\nSystem.out.println(grade);'),
    ("output", "B"),
    ("p", "Conditions must be real <code>boolean</code> expressions; Java has no \"truthy\" values, so <code>if (count)</code> will not compile. Combine conditions with <code>&amp;&amp;</code> (and), <code>||</code> (or) and <code>!</code> (not). For a simple choice, the ternary operator is compact: <code>String s = ok ? \"yes\" : \"no\";</code>."),
    ("h2", "switch"),
    ("p", "When one value selects between many branches, <code>switch</code> is clearer than a chain of <code>else if</code>. Modern Java (14+) supports arrow syntax with no fall-through and can produce a value."),
    ("code", "java", 'int day = 3;\nString name = switch (day) {\n    case 1 -> "Mon";\n    case 2 -> "Tue";\n    case 3 -> "Wed";\n    default -> "Other";\n};\nSystem.out.println(name);'),
    ("output", "Wed"),
    ("h2", "Loops"),
    ("p", "A classic <code>for</code> loop has three parts: initialize, test and update. The enhanced <code>for</code> (\"for-each\") loop reads every element of an array or collection without an index. <code>while</code> repeats while a condition holds, and <code>do/while</code> runs the body at least once."),
    ("code", "java", 'for (int i = 0; i < 3; i++) {\n    System.out.println("tick " + i);\n}\n\nint[] nums = {4, 8, 15};\nint sum = 0;\nfor (int n : nums) {\n    sum += n;\n}\nSystem.out.println(sum);\n\nint count = 3;\nwhile (count > 0) {\n    count--;\n}'),
    ("output", "tick 0\ntick 1\ntick 2\n27"),
    ("p", "Use <code>break</code> to exit a loop early and <code>continue</code> to jump to the next iteration."),
    ("h2", "Common mistakes"),
    ("ul", [
        "Using <code>=</code> instead of <code>==</code> in a condition. Java usually catches this for non-booleans, but not for boolean variables.",
        "Off-by-one errors: <code>i &lt;= nums.length</code> reads one past the end and throws <code>ArrayIndexOutOfBoundsException</code>.",
        "A stray semicolon after <code>if (x);</code> makes the block run unconditionally.",
        "Forgetting to change the loop variable in <code>while</code>, causing an infinite loop.",
    ]),
    ("exercise", "Print the sum of all even numbers from 1 to 100 using a <code>for</code> loop and an <code>if</code>. Then rewrite the loop to step by 2 without the <code>if</code>."),
    ("solution", "java", 'int sum = 0;\nfor (int i = 1; i <= 100; i++) {\n    if (i % 2 == 0) sum += i;\n}\nSystem.out.println(sum);   // 2550\n\nint sum2 = 0;\nfor (int i = 2; i <= 100; i += 2) {\n    sum2 += i;\n}\nSystem.out.println(sum2);  // 2550'),
]

CONTENT["java-oop-classes"] = [
    ("p", "Java is object-oriented from the ground up. A <strong>class</strong> describes the shape of something (its fields) and what it can do (its methods). An <strong>object</strong> is a concrete instance created with <code>new</code>. Good classes hide their internal data and expose a small, safe set of operations. That idea is called <strong>encapsulation</strong>."),
    ("h2", "A class with a constructor"),
    ("p", "A constructor has the same name as the class and no return type. It runs when you call <code>new</code> and sets the object up. Marking fields <code>private</code> stops outside code from changing them directly."),
    ("code", "java", 'public class BankAccount {\n    private final String owner;\n    private double balance;\n\n    public BankAccount(String owner, double balance) {\n        this.owner = owner;\n        this.balance = balance;\n    }\n\n    public void deposit(double amount) {\n        if (amount <= 0) throw new IllegalArgumentException("amount must be positive");\n        balance += amount;\n    }\n\n    public double getBalance() { return balance; }\n    public String getOwner()   { return owner; }\n}'),
    ("p", "<code>this</code> refers to the current object, and is needed here to tell the field <code>this.owner</code> apart from the parameter <code>owner</code>."),
    ("h2", "Using the class"),
    ("code", "java", 'BankAccount acct = new BankAccount("Amar", 100);\nacct.deposit(50);\nSystem.out.println(acct.getOwner() + ": " + acct.getBalance());'),
    ("output", "Amar: 150.0"),
    ("h2", "Static versus instance"),
    ("p", "Instance members belong to each object; <code>static</code> members belong to the class and are shared. <code>Math.sqrt(9)</code> is a static method: you call it on the class, not on an object."),
    ("h2", "Inheritance and interfaces"),
    ("p", "A subclass <code>extends</code> one parent class. An <code>interface</code> is a contract of methods that a class promises to provide, and a class may <code>implements</code> many of them. Prefer interfaces when you want different classes to be used interchangeably."),
    ("code", "java", 'interface Shape {\n    double area();\n}\n\nclass Circle implements Shape {\n    private final double r;\n    Circle(double r) { this.r = r; }\n    public double area() { return Math.PI * r * r; }\n}\n\nclass Square implements Shape {\n    private final double s;\n    Square(double s) { this.s = s; }\n    public double area() { return s * s; }\n}\n\nShape[] shapes = { new Circle(1), new Square(2) };\nfor (Shape sh : shapes) {\n    System.out.printf("%.2f%n", sh.area());\n}'),
    ("output", "3.14\n4.00"),
    ("p", "Calling <code>sh.area()</code> runs the right version for each object. That is <strong>polymorphism</strong>: one call, many behaviors."),
    ("note", "Access modifiers", "<code>private</code>: this class only. <code>protected</code>: same package and subclasses. <code>public</code>: everywhere. No modifier: same package. Start with <code>private</code> and open up only as needed."),
    ("exercise", "Add a <code>withdraw(double amount)</code> method to <code>BankAccount</code> that throws <code>IllegalStateException</code> if the balance would go negative."),
    ("solution", "java", 'public void withdraw(double amount) {\n    if (amount > balance) {\n        throw new IllegalStateException("insufficient funds");\n    }\n    balance -= amount;\n}'),
]

CONTENT["java-collections"] = [
    ("p", "Arrays have a fixed size. Real programs need data structures that grow, shrink and search efficiently, and Java's <strong>Collections Framework</strong> provides them in <code>java.util</code>. The three interfaces to know are <code>List</code> (ordered, duplicates allowed), <code>Set</code> (no duplicates) and <code>Map</code> (key-value pairs)."),
    ("h2", "List and ArrayList"),
    ("p", "<code>ArrayList</code> is the default list. The angle brackets are <strong>generics</strong>: they tell the compiler what the list holds, so mistakes are caught at compile time instead of at runtime."),
    ("code", "java", 'import java.util.*;\n\nList<String> names = new ArrayList<>();\nnames.add("Ada");\nnames.add("Linus");\nnames.add("Grace");\n\nSystem.out.println(names.get(1));\nSystem.out.println(names.size());\nnames.remove("Linus");\nSystem.out.println(names);'),
    ("output", "Linus\n3\n[Ada, Grace]"),
    ("h2", "Set and HashSet"),
    ("p", "A <code>HashSet</code> silently ignores duplicates and answers \"is this in here?\" in roughly constant time. Use <code>LinkedHashSet</code> to keep insertion order or <code>TreeSet</code> for sorted order."),
    ("code", "java", 'Set<Integer> seen = new HashSet<>();\nSystem.out.println(seen.add(5));   // true\nSystem.out.println(seen.add(5));   // false, already present\nSystem.out.println(seen.contains(5));'),
    ("output", "true\nfalse\ntrue"),
    ("h2", "Map and HashMap"),
    ("p", "A <code>Map</code> stores values by key. <code>getOrDefault</code> and <code>merge</code> make counting easy without null checks."),
    ("code", "java", 'Map<String, Integer> counts = new HashMap<>();\nfor (String w : "to be or not to be".split(" ")) {\n    counts.merge(w, 1, Integer::sum);\n}\nSystem.out.println(counts.get("to"));\n\nfor (Map.Entry<String, Integer> e : counts.entrySet()) {\n    System.out.println(e.getKey() + "=" + e.getValue());\n}'),
    ("output", "2\n(entries in hash order, for example: not=1, be=2, or=1, to=2)"),
    ("h2", "Choosing the right one"),
    ("ul", [
        "Need order and index access? <code>ArrayList</code>.",
        "Need fast add/remove at both ends? <code>ArrayDeque</code>.",
        "Need uniqueness or fast contains? <code>HashSet</code>.",
        "Need lookup by key? <code>HashMap</code>.",
        "Need keys kept sorted? <code>TreeMap</code> / <code>TreeSet</code>.",
    ]),
    ("h2", "Sorting and streams"),
    ("code", "java", 'List<Integer> nums = new ArrayList<>(List.of(5, 2, 9, 1));\nCollections.sort(nums);\nSystem.out.println(nums);\n\nList<Integer> big = nums.stream().filter(n -> n > 2).toList();\nSystem.out.println(big);'),
    ("output", "[1, 2, 5, 9]\n[5, 9]"),
    ("note", "Program to the interface", "Declare variables as <code>List</code>, <code>Set</code> or <code>Map</code>, not the concrete class. You can then swap <code>ArrayList</code> for <code>LinkedList</code> in one place without touching the rest of the code."),
    ("exercise", "Given a list of words, use a <code>Map&lt;String, Integer&gt;</code> to count occurrences, then print the word with the highest count."),
    ("solution", "java", 'List<String> words = List.of("a", "b", "a", "c", "a", "b");\nMap<String, Integer> counts = new HashMap<>();\nfor (String w : words) counts.merge(w, 1, Integer::sum);\n\nString best = null;\nfor (var e : counts.entrySet()) {\n    if (best == null || e.getValue() > counts.get(best)) best = e.getKey();\n}\nSystem.out.println(best + " " + counts.get(best));'),
]

CONTENT["java-exceptions"] = [
    ("p", "When something goes wrong at runtime, Java throws an <strong>exception</strong> object and unwinds the call stack until some code catches it. If nothing does, the thread ends with a stack trace. Handling exceptions well is the difference between a program that crashes mysteriously and one that fails clearly."),
    ("h2", "Checked and unchecked"),
    ("ul", [
        "<strong>Checked</strong> exceptions (such as <code>IOException</code>) describe problems outside your control. The compiler forces you to catch them or declare them with <code>throws</code>.",
        "<strong>Unchecked</strong> exceptions extend <code>RuntimeException</code> (such as <code>NullPointerException</code> or <code>IllegalArgumentException</code>). They usually signal a bug, and you are not forced to catch them.",
    ]),
    ("h2", "try / catch / finally"),
    ("code", "java", 'try {\n    int n = Integer.parseInt("abc");\n    System.out.println(n);\n} catch (NumberFormatException e) {\n    System.out.println("bad number: " + e.getMessage());\n} finally {\n    System.out.println("always runs");\n}'),
    ("output", 'bad number: For input string: "abc"\nalways runs'),
    ("p", "List catch blocks from most specific to most general; the first match wins. You can also catch several types in one block with <code>catch (IOException | SQLException e)</code>."),
    ("h2", "try-with-resources"),
    ("p", "Anything that must be closed (files, connections) should be opened in the parentheses of a <code>try</code>. Java closes it automatically, even when an exception is thrown, so you never need a manual <code>finally</code> for cleanup."),
    ("code", "java", 'import java.io.*;\nimport java.nio.file.*;\n\ntry (BufferedReader in = Files.newBufferedReader(Path.of("notes.txt"))) {\n    System.out.println(in.readLine());\n} catch (IOException e) {\n    System.out.println("cannot read file: " + e.getMessage());\n}'),
    ("h2", "Throwing your own"),
    ("p", "Validate input early and throw an exception whose message says exactly what was wrong. When you catch one exception and throw another, pass the original as the <em>cause</em> so the trace is not lost."),
    ("code", "java", 'public static int parsePositive(String raw) {\n    try {\n        int n = Integer.parseInt(raw);\n        if (n <= 0) throw new IllegalArgumentException("must be positive: " + n);\n        return n;\n    } catch (NumberFormatException e) {\n        throw new IllegalArgumentException("not a number: " + raw, e);\n    }\n}'),
    ("h2", "Common mistakes"),
    ("ul", [
        "Empty catch blocks (<code>catch (Exception e) {}</code>) hide failures. At least log the error.",
        "Catching <code>Exception</code> or <code>Throwable</code> too broadly, which also swallows bugs.",
        "Using exceptions for normal control flow; they are slow and obscure intent.",
        "Losing the original cause by not passing it to the new exception.",
    ]),
    ("note", "NullPointerException", "The most common runtime error. It happens when you call a method on a <code>null</code> reference. Check for null at boundaries, or return <code>Optional</code> from methods that may have no result."),
    ("exercise", "Write <code>int safeDivide(int a, int b)</code> that returns 0 when <code>b</code> is zero by catching <code>ArithmeticException</code>."),
    ("solution", "java", 'public static int safeDivide(int a, int b) {\n    try {\n        return a / b;\n    } catch (ArithmeticException e) {\n        return 0;\n    }\n}'),
]
