"""JavaScript and SQL tracks."""

def M(slug, track, title, minutes, level, summary, objectives):
    return {"slug": slug, "track": track, "title": title, "minutes": minutes, "level": level,
            "summary": summary, "objectives": objectives}

META = [
    M("js-hello-world", "javascript", "Hello, JavaScript", 10, "Beginner", "Run JavaScript in the browser and in Node.js, and print your first output.", ["Run code in the console and Node", "Use console.log", "Understand where JS runs"]),
    M("js-variables-types", "javascript", "Variables and Types", 13, "Beginner", "let, const, primitive types, template strings and the equality traps.", ["Choose const or let", "Name the primitive types", "Use === not =="]),
    M("js-functions", "javascript", "Functions and Scope", 15, "Beginner", "Declarations, arrow functions, closures and how scope works.", ["Write arrow functions", "Explain closures", "Use default and rest parameters"]),
    M("js-arrays-objects", "javascript", "Arrays and Objects", 17, "Intermediate", "map, filter, reduce, destructuring and spread for everyday data work.", ["Transform arrays without loops", "Destructure objects", "Copy with spread"]),
    M("js-async", "javascript", "Promises and async/await", 16, "Intermediate", "Handle work that finishes later: timers, fetch and error handling.", ["Explain the event loop", "Use async/await", "Run requests in parallel"]),
    M("js-dom", "javascript", "The DOM and Events", 14, "Intermediate", "Select elements, react to clicks and update the page.", ["Query the DOM", "Add event listeners", "Update text and classes"]),
    M("sql-introduction", "sql", "Databases and SQL Basics", 10, "Beginner", "Tables, rows, keys and how relational databases organize data.", ["Define table, row, column", "Explain primary keys", "Run a first query"]),
    M("sql-select-where", "sql", "SELECT and WHERE", 14, "Beginner", "Read columns and filter rows with conditions, patterns and NULL checks.", ["Select specific columns", "Filter with AND/OR/IN/LIKE", "Handle NULL correctly"]),
    M("sql-sorting-aggregates", "sql", "Sorting and Aggregates", 15, "Beginner", "ORDER BY, LIMIT, COUNT, SUM, AVG and GROUP BY with HAVING.", ["Sort and paginate", "Summarize with aggregates", "Group rows"]),
    M("sql-joins", "sql", "Joins", 17, "Intermediate", "Combine tables with INNER, LEFT and self joins.", ["Write an INNER JOIN", "Know when LEFT JOIN is needed", "Avoid duplicate-row surprises"]),
    M("sql-modifying-data", "sql", "INSERT, UPDATE, DELETE", 12, "Intermediate", "Change data safely, including transactions.", ["Insert rows", "Update with WHERE", "Wrap changes in a transaction"]),
    M("sql-schema-design", "sql", "Creating Tables and Design", 15, "Intermediate", "Data types, constraints, foreign keys and normalization.", ["Create tables with constraints", "Model one-to-many relations", "Normalize a design"]),
    M("sql-indexes-performance", "sql", "Indexes and Query Performance", 14, "Advanced", "Why queries are slow, how indexes help and how to read EXPLAIN.", ["Create an index", "Read a query plan", "Avoid common slow patterns"]),
]

CONTENT = {}

CONTENT["js-hello-world"] = [
    ("p", "JavaScript began as a small scripting language for web pages and now runs almost everywhere: every browser, servers through <strong>Node.js</strong>, mobile apps and desktop tools. It is the only language browsers run natively, so anyone who builds for the web meets it sooner or later."),
    ("h2", "Two places to run it"),
    ("ul", [
        "<strong>The browser console</strong>: open developer tools (F12, or Cmd+Option+J on a Mac) and type code straight in. Nothing to install.",
        "<strong>Node.js</strong>: install it from nodejs.org, save code in a file and run it from the terminal.",
    ]),
    ("code", "javascript", 'console.log("Hello, stackcone!");\nconsole.log(2 + 2);\nconsole.log("2 + 2 =", 2 + 2);'),
    ("output", "Hello, stackcone!\n4\n2 + 2 = 4"),
    ("code", "bash", "node hello.js"),
    ("h2", "Statements, semicolons and comments"),
    ("p", "Statements usually end with a semicolon. JavaScript can insert them automatically, but relying on that occasionally causes surprises, so pick a style and stay consistent. Comments use <code>//</code> for one line and <code>/* ... */</code> for blocks."),
    ("code", "javascript", '// a single-line comment\nconst greeting = "hi"; /* inline block comment */\nconsole.log(greeting);'),
    ("h2", "JavaScript is not Java"),
    ("p", "The names are a marketing accident. The languages are unrelated: JavaScript is dynamically typed and runs in an engine (V8 in Chrome and Node), while Java is compiled and statically typed."),
    ("h2", "Common mistakes"),
    ("ul", [
        "Forgetting quotes around text, giving <code>ReferenceError: Hello is not defined</code>.",
        "Typing <code>Console.log</code> with a capital C; names are case sensitive.",
        "Ignoring the console: red errors there almost always tell you the file, line and cause.",
    ]),
    ("exercise", "Print your name, then your favorite number multiplied by 3, on two separate lines."),
    ("solution", "javascript", 'console.log("stackcone");\nconsole.log(7 * 3);'),
]

CONTENT["js-variables-types"] = [
    ("p", "You create variables with <code>const</code> and <code>let</code>. <code>const</code> means the name cannot be reassigned; <code>let</code> allows reassignment. A good habit: <strong>use <code>const</code> by default</strong> and switch to <code>let</code> only when the value must change. Avoid the old <code>var</code>; its scoping rules cause bugs."),
    ("code", "javascript", 'const name = "Ada";\nlet count = 0;\ncount += 1;\n// name = "Bob";   // TypeError: assignment to constant\nconsole.log(name, count);'),
    ("output", "Ada 1"),
    ("h2", "The types"),
    ("ul", [
        "<code>number</code>: all numbers, integers and decimals alike (<code>42</code>, <code>3.14</code>). Also <code>NaN</code> and <code>Infinity</code>.",
        "<code>string</code>, <code>boolean</code>, <code>undefined</code> (declared but no value), <code>null</code> (deliberately empty), <code>bigint</code> and <code>symbol</code>.",
        "<code>object</code>: everything else, including arrays and functions.",
    ]),
    ("code", "javascript", 'console.log(typeof 42, typeof "hi", typeof true);\nconsole.log(typeof undefined, typeof null, typeof [], typeof {});'),
    ("output", "number string boolean\nundefined object object object"),
    ("note", "Known quirk", "<code>typeof null</code> is <code>\"object\"</code>. It is a decades-old bug that cannot be fixed without breaking the web. Use <code>value === null</code> to check for null and <code>Array.isArray(x)</code> for arrays."),
    ("h2", "Template strings"),
    ("p", "Backticks create <strong>template literals</strong>: embed any expression with <code>${...}</code> and write multi-line text without escapes."),
    ("code", "javascript", 'const items = 3, price = 4.5;\nconsole.log(`${items} items cost $${(items * price).toFixed(2)}`);'),
    ("output", "3 items cost $13.50"),
    ("h2", "Equality: always use ==="),
    ("p", "<code>==</code> converts types before comparing, giving odd results. <code>===</code> compares value and type and behaves predictably."),
    ("code", "javascript", 'console.log(0 == "0", 0 === "0");\nconsole.log(null == undefined, null === undefined);\nconsole.log(0.1 + 0.2 === 0.3);'),
    ("output", "true false\ntrue false\nfalse"),
    ("p", "The last line is not a JavaScript quirk but floating-point math: decimals are stored in binary, so <code>0.1 + 0.2</code> is <code>0.30000000000000004</code>. Compare money in whole cents."),
    ("h2", "Truthy and falsy"),
    ("p", "In a condition, these are false: <code>false</code>, <code>0</code>, <code>\"\"</code>, <code>null</code>, <code>undefined</code>, <code>NaN</code>. Everything else, including <code>\"0\"</code> and <code>[]</code>, is true. Use <code>??</code> to fall back only for null/undefined, and <code>?.</code> to read nested values safely."),
    ("code", "javascript", 'const user = { profile: null };\nconsole.log(user.profile?.email ?? "no email");'),
    ("output", "no email"),
    ("exercise", "Convert the string <code>\"42\"</code> to a number, add 8, and print a message using a template string. Then check whether <code>NaN === NaN</code> and explain the result."),
    ("solution", "javascript", 'const n = Number("42") + 8;\nconsole.log(`The answer is ${n}`);\nconsole.log(NaN === NaN);          // false: NaN is never equal to anything\nconsole.log(Number.isNaN(NaN));    // true: the correct check'),
]

CONTENT["js-functions"] = [
    ("p", "Functions are values in JavaScript: you can store them in variables, pass them to other functions and return them. That flexibility powers almost every modern pattern, from array methods to React components."),
    ("h2", "Three ways to write one"),
    ("code", "javascript", 'function add(a, b) {        // declaration\n  return a + b;\n}\nconst mul = function (a, b) { return a * b; };   // expression\nconst sub = (a, b) => a - b;                      // arrow function\n\nconsole.log(add(2, 3), mul(2, 3), sub(2, 3));'),
    ("output", "5 6 -1"),
    ("p", "An arrow function with a single expression returns it implicitly. Arrow functions are the standard for short callbacks."),
    ("h2", "Default, rest and destructured parameters"),
    ("code", "javascript", 'function greet(name = "friend", ...tags) {\n  return `Hi ${name} [${tags.join(", ")}]`;\n}\nconsole.log(greet());\nconsole.log(greet("Ada", "admin", "dev"));\n\nconst area = ({ w, h }) => w * h;\nconsole.log(area({ w: 3, h: 4 }));'),
    ("output", "Hi friend []\nHi Ada [admin, dev]\n12"),
    ("h2", "Scope and closures"),
    ("p", "Variables declared with <code>let</code> or <code>const</code> live inside the nearest <code>{ }</code> block. A <strong>closure</strong> is a function that remembers the variables from where it was created, even after that outer function has returned. It is how you keep private state."),
    ("code", "javascript", 'function makeCounter() {\n  let n = 0;\n  return () => ++n;\n}\nconst a = makeCounter();\nconst b = makeCounter();\na(); a();\nconsole.log(a(), b());'),
    ("output", "3 1"),
    ("p", "Each call to <code>makeCounter</code> creates a separate <code>n</code>, so the two counters do not interfere."),
    ("h2", "Functions as arguments"),
    ("code", "javascript", 'function repeat(times, action) {\n  for (let i = 0; i < times; i++) action(i);\n}\nrepeat(3, (i) => console.log("run", i));'),
    ("output", "run 0\nrun 1\nrun 2"),
    ("note", "Common bug", "A function with no <code>return</code> gives back <code>undefined</code>. Also, a <code>return</code> followed by a newline before the value returns <code>undefined</code>; keep the value on the same line."),
    ("exercise", "Write <code>makeMultiplier(factor)</code> that returns a function multiplying its input by <code>factor</code>. Use it to make <code>double</code> and <code>triple</code>."),
    ("solution", "javascript", 'const makeMultiplier = (factor) => (x) => x * factor;\nconst double = makeMultiplier(2);\nconst triple = makeMultiplier(3);\nconsole.log(double(5), triple(5));   // 10 15'),
]

CONTENT["js-arrays-objects"] = [
    ("p", "Arrays hold ordered lists and objects hold named properties. Almost all real JavaScript is transforming these two shapes. Learning the array methods well means you rarely need a manual <code>for</code> loop."),
    ("h2", "Arrays"),
    ("code", "javascript", 'const nums = [1, 2, 3];\nnums.push(4);         // add to end\nnums.unshift(0);      // add to start\nconsole.log(nums, nums.length, nums.at(-1));\nconsole.log(nums.includes(3), nums.indexOf(3));'),
    ("output", "[ 0, 1, 2, 3, 4 ] 5 4\ntrue 3"),
    ("h2", "map, filter, reduce"),
    ("p", "<code>map</code> transforms every item, <code>filter</code> keeps some, and <code>reduce</code> folds the list into one value. None of them change the original array; they return new ones, so they chain nicely."),
    ("code", "javascript", 'const prices = [10, 25, 40, 5];\nconst withTax = prices.map((p) => p * 1.2);\nconst big = prices.filter((p) => p > 9);\nconst total = prices.reduce((sum, p) => sum + p, 0);\nconsole.log(withTax);\nconsole.log(big, total);'),
    ("output", "[ 12, 30, 48, 6 ]\n[ 10, 25, 40 ] 80"),
    ("p", "Also useful: <code>find</code> (first match), <code>some</code> / <code>every</code> (yes/no checks), <code>sort</code> and <code>flat</code>. Beware that <code>sort()</code> converts to strings by default and mutates the array; pass a comparer for numbers: <code>nums.sort((a, b) => a - b)</code>."),
    ("h2", "Objects"),
    ("code", "javascript", 'const user = { name: "Ada", age: 36, tags: ["dev"] };\nuser.role = "admin";\nconsole.log(user.name, user["age"]);\nconsole.log(Object.keys(user));\nconsole.log(Object.entries(user).length);'),
    ("output", "Ada 36\n[ 'name', 'age', 'tags', 'role' ]\n4"),
    ("h2", "Destructuring and spread"),
    ("p", "Destructuring unpacks values into variables; the spread operator <code>...</code> copies or merges. Together they give you concise, immutable-style updates that React relies on."),
    ("code", "javascript", 'const { name, ...rest } = user;\nconst [first, second] = [10, 20, 30];\nconst updated = { ...user, age: 37 };\nconst merged = [...[1, 2], ...[3]];\nconsole.log(name, first, second, updated.age, merged);'),
    ("output", "Ada 10 20 37 [ 1, 2, 3 ]"),
    ("note", "Shallow copies", "Spread copies only the top level. Nested objects are still shared. Use <code>structuredClone(obj)</code> for a deep copy."),
    ("h2", "Grouping with reduce"),
    ("code", "javascript", 'const words = ["apple", "avocado", "banana"];\nconst byLetter = words.reduce((acc, w) => {\n  (acc[w[0]] ??= []).push(w);\n  return acc;\n}, {});\nconsole.log(byLetter);'),
    ("output", "{ a: [ 'apple', 'avocado' ], b: [ 'banana' ] }"),
    ("exercise", "Given an array of user objects with <code>name</code> and <code>age</code>, produce an array of the names of users aged 18 or over, sorted alphabetically."),
    ("solution", "javascript", 'const users = [{ name: "Zed", age: 20 }, { name: "Amy", age: 15 }, { name: "Bob", age: 30 }];\nconst adults = users\n  .filter((u) => u.age >= 18)\n  .map((u) => u.name)\n  .sort();\nconsole.log(adults);   // [ \'Bob\', \'Zed\' ]'),
]

CONTENT["js-async"] = [
    ("p", "JavaScript runs your code on a <strong>single thread</strong>. To stay responsive while waiting for things like network requests or timers, it hands slow work to the environment and continues. When the result is ready, a callback is queued and runs once the current code has finished. This mechanism is the <em>event loop</em>."),
    ("code", "javascript", 'console.log("1 start");\nsetTimeout(() => console.log("3 timer"), 0);\nconsole.log("2 end");'),
    ("output", "1 start\n2 end\n3 timer"),
    ("p", "Even with a delay of 0, the timer callback runs after the synchronous code finishes."),
    ("h2", "Promises"),
    ("p", "A <strong>promise</strong> stands for a value that will arrive later. It is pending, then either fulfilled with a value or rejected with an error. Chain <code>.then()</code> for success and <code>.catch()</code> for failure."),
    ("code", "javascript", 'const wait = (ms) => new Promise((resolve) => setTimeout(resolve, ms));\n\nwait(100)\n  .then(() => console.log("done waiting"))\n  .catch((err) => console.error(err));'),
    ("h2", "async / await"),
    ("p", "<code>async</code> functions always return a promise, and <code>await</code> pauses the function until a promise settles, so asynchronous code reads top to bottom. Wrap awaits in <code>try/catch</code> to handle errors."),
    ("code", "javascript", 'async function loadUser(id) {\n  try {\n    const res = await fetch(`https://api.example.com/users/${id}`);\n    if (!res.ok) throw new Error(`HTTP ${res.status}`);\n    return await res.json();\n  } catch (err) {\n    console.error("failed:", err.message);\n    return null;\n  }\n}\nloadUser(1).then(console.log);'),
    ("note", "fetch gotcha", "<code>fetch</code> only rejects on network failure. A 404 or 500 still resolves, so always check <code>res.ok</code>."),
    ("h2", "Parallel work"),
    ("p", "Awaiting things one after another makes them run in sequence. When the calls are independent, start them together with <code>Promise.all</code>, which resolves when all are done and rejects if any fails."),
    ("code", "javascript", 'const wait = (ms, v) => new Promise((r) => setTimeout(() => r(v), ms));\n\nasync function main() {\n  console.time("parallel");\n  const [a, b] = await Promise.all([wait(200, "A"), wait(200, "B")]);\n  console.timeEnd("parallel");   // ~200ms, not 400ms\n  console.log(a, b);\n}\nmain();'),
    ("output", "parallel: 201ms\nA B"),
    ("p", "<code>Promise.allSettled</code> waits for every promise and reports each outcome, which is handy when partial failure is acceptable."),
    ("h2", "Common mistakes"),
    ("ul", [
        "Forgetting <code>await</code>, so you log a pending promise instead of its value.",
        "Using <code>await</code> inside <code>forEach</code>; it does not wait. Use a <code>for...of</code> loop or <code>Promise.all</code> with <code>map</code>.",
        "Not handling rejections, which produce \"unhandled promise rejection\" errors.",
    ]),
    ("exercise", "Write <code>retry(fn, times)</code>, an async function that calls <code>fn</code> and, if it throws, tries again up to <code>times</code> attempts before giving up."),
    ("solution", "javascript", 'async function retry(fn, times) {\n  let lastErr;\n  for (let i = 0; i < times; i++) {\n    try {\n      return await fn();\n    } catch (err) {\n      lastErr = err;\n    }\n  }\n  throw lastErr;\n}'),
]

CONTENT["js-dom"] = [
    ("p", "When a browser loads an HTML page it builds the <strong>DOM</strong> (Document Object Model), a tree of objects representing every element. JavaScript can read and change that tree, which is how pages become interactive. Everything starts from the global <code>document</code> object."),
    ("h2", "Selecting elements"),
    ("code", "javascript", 'const title = document.querySelector("h1");        // first match\nconst items = document.querySelectorAll(".item");  // all matches\nconst byId  = document.getElementById("save");'),
    ("p", "<code>querySelector</code> takes any CSS selector, so you already know the syntax. It returns <code>null</code> if nothing matches, so check before using the result."),
    ("h2", "Changing content and style"),
    ("code", "javascript", 'title.textContent = "Welcome back";\ntitle.classList.add("highlight");\ntitle.classList.toggle("hidden");\ntitle.setAttribute("data-state", "ready");\ntitle.style.color = "tomato";'),
    ("p", "Prefer <code>textContent</code> over <code>innerHTML</code> for plain text. Setting <code>innerHTML</code> with user-supplied text opens the door to cross-site scripting (XSS) attacks. Prefer toggling CSS classes over setting inline styles."),
    ("h2", "Events"),
    ("p", "An <strong>event listener</strong> runs a function when something happens: a click, a key press, a form submit. The function receives an <code>event</code> object describing what occurred."),
    ("code", "javascript", 'const button = document.querySelector("#save");\nlet clicks = 0;\nbutton.addEventListener("click", (event) => {\n  clicks += 1;\n  button.textContent = `Saved ${clicks} times`;\n});\n\nconst form = document.querySelector("form");\nform.addEventListener("submit", (e) => {\n  e.preventDefault();               // stop the page reload\n  console.log(new FormData(form).get("email"));\n});'),
    ("h2", "Creating elements"),
    ("code", "javascript", 'const li = document.createElement("li");\nli.textContent = "New task";\ndocument.querySelector("ul").append(li);'),
    ("h2", "Event delegation"),
    ("p", "Instead of attaching a listener to every list item, attach one to the parent and inspect <code>event.target</code>. It works for items added later, and uses less memory."),
    ("code", "javascript", 'document.querySelector("ul").addEventListener("click", (e) => {\n  const li = e.target.closest("li");\n  if (li) li.classList.toggle("done");\n});'),
    ("note", "Timing", "Scripts placed in the <code>&lt;head&gt;</code> run before the elements exist. Add <code>defer</code> to the script tag, or place it at the end of <code>&lt;body&gt;</code>."),
    ("exercise", "Build a counter: a button that increments a number shown on the page each time it is clicked, plus a reset button."),
    ("solution", "javascript", '// HTML: <p id="n">0</p> <button id="inc">+1</button> <button id="reset">Reset</button>\nlet n = 0;\nconst out = document.querySelector("#n");\ndocument.querySelector("#inc").addEventListener("click", () => {\n  out.textContent = ++n;\n});\ndocument.querySelector("#reset").addEventListener("click", () => {\n  n = 0;\n  out.textContent = n;\n});'),
]

# ---------------- SQL ----------------
CONTENT["sql-introduction"] = [
    ("p", "A <strong>relational database</strong> stores data in <em>tables</em>, like spreadsheets with strict rules. Each <em>row</em> is one record and each <em>column</em> is one attribute with a fixed type. <strong>SQL</strong> (Structured Query Language) is the standard language for asking these databases questions and changing their data. It works, with small dialect differences, in PostgreSQL, MySQL, SQLite, SQL Server and Oracle."),
    ("h2", "A sample table"),
    ("p", "Throughout this course we use two tables. <code>customers</code> holds people, and <code>orders</code> holds purchases, each pointing at a customer."),
    ("code", "sql", "-- customers\n-- id | name  | country | age\n--  1 | Ada   | UK      | 36\n--  2 | Linus | FI      | 28\n--  3 | Grace | US      | 45\n\n-- orders\n-- id | customer_id | total | status\n-- 10 |           1 | 120.0 | paid\n-- 11 |           1 |  35.5 | paid\n-- 12 |           3 |  80.0 | refunded"),
    ("h2", "Keys"),
    ("ul", [
        "A <strong>primary key</strong> uniquely identifies each row (<code>customers.id</code>). It can never be duplicated or null.",
        "A <strong>foreign key</strong> is a column that points at another table's primary key (<code>orders.customer_id</code>). This is how tables relate.",
    ]),
    ("h2", "Your first query"),
    ("code", "sql", "SELECT name, country\nFROM customers;"),
    ("output", "name   | country\nAda    | UK\nLinus  | FI\nGrace  | US"),
    ("p", "A query names what you want (<code>SELECT</code>) and where it lives (<code>FROM</code>). SQL is <em>declarative</em>: you describe the result, and the database engine works out the fastest way to produce it. Keywords are case-insensitive, but writing them in capitals and ending statements with a semicolon is the convention."),
    ("h2", "Trying it"),
    ("p", "The easiest way to practice is SQLite, which needs no server: install it, run <code>sqlite3 practice.db</code> and paste the statements. Online playgrounds such as SQLite Fiddle or DB Fiddle work too."),
    ("code", "bash", "sqlite3 practice.db\nsqlite> CREATE TABLE customers (id INTEGER PRIMARY KEY, name TEXT, country TEXT, age INTEGER);\nsqlite> .tables"),
    ("note", "SQL families", "Statements fall into groups: <strong>DQL</strong> (SELECT), <strong>DML</strong> (INSERT, UPDATE, DELETE), <strong>DDL</strong> (CREATE, ALTER, DROP) and <strong>TCL</strong> (COMMIT, ROLLBACK). You will meet all of them."),
    ("exercise", "Write a query that returns only the <code>name</code> and <code>age</code> columns from <code>customers</code>."),
    ("solution", "sql", "SELECT name, age\nFROM customers;"),
]

CONTENT["sql-select-where"] = [
    ("p", "<code>SELECT</code> chooses <em>columns</em>; <code>WHERE</code> chooses <em>rows</em>. Combining them lets you pull exactly the data you need, and nothing else."),
    ("h2", "Choosing columns"),
    ("code", "sql", "SELECT * FROM customers;               -- every column\nSELECT name, age FROM customers;        -- only some\nSELECT name AS customer FROM customers; -- rename with an alias\nSELECT DISTINCT country FROM customers; -- remove duplicates"),
    ("p", "Avoid <code>SELECT *</code> in application code. It fetches more than you need and breaks when columns are added or reordered."),
    ("h2", "Filtering with WHERE"),
    ("code", "sql", "SELECT name FROM customers\nWHERE age >= 30;"),
    ("output", "name\nAda\nGrace"),
    ("p", "Comparison operators: <code>= &lt;&gt; &lt; &gt; &lt;= &gt;=</code> (note that equality is a single <code>=</code>, and not-equal is <code>&lt;&gt;</code> or <code>!=</code>). Combine tests with <code>AND</code>, <code>OR</code> and <code>NOT</code>, and use parentheses to be explicit, since AND binds tighter than OR."),
    ("code", "sql", "SELECT * FROM customers\nWHERE (country = 'UK' OR country = 'US')\n  AND age > 30;"),
    ("h2", "IN, BETWEEN and LIKE"),
    ("code", "sql", "SELECT * FROM customers WHERE country IN ('UK', 'US', 'FI');\nSELECT * FROM orders    WHERE total BETWEEN 50 AND 150;   -- inclusive\nSELECT * FROM customers WHERE name LIKE 'G%';             -- starts with G\nSELECT * FROM customers WHERE name LIKE '_da';            -- one char then 'da'"),
    ("p", "In <code>LIKE</code>, <code>%</code> matches any run of characters and <code>_</code> matches exactly one. Text values use single quotes; double quotes are for identifiers in standard SQL."),
    ("h2", "NULL is not a value"),
    ("p", "<code>NULL</code> means \"unknown or missing\". Any comparison with NULL is unknown, so <code>WHERE phone = NULL</code> matches nothing. Use <code>IS NULL</code> and <code>IS NOT NULL</code>."),
    ("code", "sql", "SELECT * FROM customers WHERE phone IS NULL;\nSELECT name, COALESCE(phone, 'n/a') AS phone FROM customers;"),
    ("note", "Common bug", "<code>WHERE country &lt;&gt; 'UK'</code> silently excludes rows where country is NULL. Add <code>OR country IS NULL</code> if you want them."),
    ("exercise", "From <code>orders</code>, return the id and total of every paid order over 50."),
    ("solution", "sql", "SELECT id, total\nFROM orders\nWHERE status = 'paid' AND total > 50;"),
]

CONTENT["sql-sorting-aggregates"] = [
    ("p", "So far we have listed rows. Real questions are usually about <em>order</em> (who is biggest?) and <em>summaries</em> (how much in total?). This lesson covers both."),
    ("h2", "ORDER BY and LIMIT"),
    ("code", "sql", "SELECT name, age FROM customers\nORDER BY age DESC, name ASC\nLIMIT 2;"),
    ("output", "name  | age\nGrace | 45\nAda   | 36"),
    ("p", "<code>ORDER BY</code> sorts ascending by default; add <code>DESC</code> for descending and list several columns to break ties. <code>LIMIT n</code> keeps the first <code>n</code> rows, and <code>OFFSET</code> skips rows for pagination. Without ORDER BY, row order is <em>not guaranteed</em>."),
    ("h2", "Aggregate functions"),
    ("p", "Aggregates collapse many rows into one value: <code>COUNT</code>, <code>SUM</code>, <code>AVG</code>, <code>MIN</code>, <code>MAX</code>."),
    ("code", "sql", "SELECT COUNT(*)       AS orders,\n       SUM(total)     AS revenue,\n       AVG(total)     AS average,\n       MAX(total)     AS biggest\nFROM orders\nWHERE status = 'paid';"),
    ("output", "orders | revenue | average | biggest\n2      | 155.5   | 77.75   | 120.0"),
    ("p", "<code>COUNT(*)</code> counts rows; <code>COUNT(column)</code> counts rows where the column is not NULL; <code>COUNT(DISTINCT column)</code> counts unique values."),
    ("h2", "GROUP BY"),
    ("p", "<code>GROUP BY</code> splits rows into buckets and runs the aggregates once per bucket."),
    ("code", "sql", "SELECT customer_id, COUNT(*) AS orders, SUM(total) AS spent\nFROM orders\nGROUP BY customer_id\nORDER BY spent DESC;"),
    ("output", "customer_id | orders | spent\n1           | 2      | 155.5\n3           | 1      | 80.0"),
    ("p", "The rule: every column in <code>SELECT</code> must either appear in <code>GROUP BY</code> or be inside an aggregate function."),
    ("h2", "HAVING versus WHERE"),
    ("p", "<code>WHERE</code> filters rows <em>before</em> grouping; <code>HAVING</code> filters the groups <em>after</em> aggregation."),
    ("code", "sql", "SELECT customer_id, SUM(total) AS spent\nFROM orders\nWHERE status = 'paid'          -- rows first\nGROUP BY customer_id\nHAVING SUM(total) > 100;       -- then groups"),
    ("note", "Logical order", "SQL runs clauses in this order: FROM, WHERE, GROUP BY, HAVING, SELECT, ORDER BY, LIMIT. That is why you cannot use a SELECT alias inside WHERE."),
    ("exercise", "Find the number of customers in each country, showing only countries with two or more customers, most first."),
    ("solution", "sql", "SELECT country, COUNT(*) AS customers\nFROM customers\nGROUP BY country\nHAVING COUNT(*) >= 2\nORDER BY customers DESC;"),
]

CONTENT["sql-joins"] = [
    ("p", "Good database design splits data across tables so nothing is duplicated: a customer's name lives once in <code>customers</code>, not on every order. A <strong>join</strong> stitches related rows back together at query time, matching a foreign key to a primary key."),
    ("h2", "INNER JOIN"),
    ("p", "Returns only rows that have a match in both tables."),
    ("code", "sql", "SELECT c.name, o.id AS order_id, o.total\nFROM customers c\nINNER JOIN orders o ON o.customer_id = c.id;"),
    ("output", "name  | order_id | total\nAda   | 10       | 120.0\nAda   | 11       | 35.5\nGrace | 12       | 80.0"),
    ("p", "Linus has no orders, so he does not appear. The short names <code>c</code> and <code>o</code> are <em>table aliases</em>; they keep queries readable and disambiguate columns that share a name, like <code>id</code>."),
    ("h2", "LEFT JOIN"),
    ("p", "Keeps <strong>every row from the left table</strong>, filling the right side with NULL when there is no match. Use it to answer \"who has none?\" questions."),
    ("code", "sql", "SELECT c.name, o.id AS order_id\nFROM customers c\nLEFT JOIN orders o ON o.customer_id = c.id;\n\n-- customers who never ordered\nSELECT c.name\nFROM customers c\nLEFT JOIN orders o ON o.customer_id = c.id\nWHERE o.id IS NULL;"),
    ("output", "name\nLinus"),
    ("h2", "Join types at a glance"),
    ("ul", [
        "<strong>INNER</strong>: only matches.",
        "<strong>LEFT</strong>: all left rows, matches from the right.",
        "<strong>RIGHT</strong>: mirror of LEFT (rarely needed; swap the table order instead).",
        "<strong>FULL OUTER</strong>: all rows from both sides.",
        "<strong>CROSS</strong>: every combination; use with care, it multiplies row counts.",
    ]),
    ("h2", "Joining and aggregating"),
    ("code", "sql", "SELECT c.name, COALESCE(SUM(o.total), 0) AS spent\nFROM customers c\nLEFT JOIN orders o ON o.customer_id = c.id\nGROUP BY c.id, c.name\nORDER BY spent DESC;"),
    ("h2", "Self join"),
    ("p", "A table can join to itself, for example to pair each employee with their manager (both live in <code>employees</code>)."),
    ("code", "sql", "SELECT e.name AS employee, m.name AS manager\nFROM employees e\nLEFT JOIN employees m ON e.manager_id = m.id;"),
    ("note", "Duplicate rows", "Joining a customer to many orders repeats the customer per order. That is correct, but summing a customer-level column after such a join double counts. Aggregate before joining when that matters."),
    ("exercise", "List each order's id, total and the name of the customer who placed it, but only for refunded orders."),
    ("solution", "sql", "SELECT o.id, o.total, c.name\nFROM orders o\nJOIN customers c ON c.id = o.customer_id\nWHERE o.status = 'refunded';"),
]

CONTENT["sql-modifying-data"] = [
    ("p", "Queries read data; three statements change it. Because they change data, the golden rule is: <strong>write the WHERE clause first</strong>, and run it as a SELECT to check what it matches before you UPDATE or DELETE."),
    ("h2", "INSERT"),
    ("code", "sql", "INSERT INTO customers (name, country, age)\nVALUES ('Margaret', 'US', 52);\n\nINSERT INTO customers (name, country, age) VALUES\n  ('Alan', 'UK', 41),\n  ('Barbara', 'US', 47);"),
    ("p", "Always name the columns so the statement survives table changes. Columns you omit receive their default (or NULL, or an auto-generated id)."),
    ("h2", "UPDATE"),
    ("code", "sql", "UPDATE orders\nSET status = 'shipped'\nWHERE id = 10;\n\nUPDATE customers\nSET age = age + 1\nWHERE country = 'UK';"),
    ("note", "The classic disaster", "<code>UPDATE orders SET status = 'x';</code> with no WHERE changes <em>every row</em>. The same goes for DELETE. Test with <code>SELECT ... WHERE</code> first."),
    ("h2", "DELETE"),
    ("code", "sql", "DELETE FROM orders\nWHERE status = 'refunded' AND total < 10;"),
    ("p", "<code>DELETE</code> removes rows; <code>DROP TABLE</code> removes the whole table. Many systems prefer a <em>soft delete</em>: add a <code>deleted_at</code> column and filter on it, so data can be recovered."),
    ("h2", "Transactions"),
    ("p", "A <strong>transaction</strong> groups statements so they succeed or fail together. Moving money must subtract from one account and add to another; if the second step fails, the first must be undone. Databases guarantee this through the ACID properties (atomicity, consistency, isolation, durability)."),
    ("code", "sql", "BEGIN;\n  UPDATE accounts SET balance = balance - 100 WHERE id = 1;\n  UPDATE accounts SET balance = balance + 100 WHERE id = 2;\nCOMMIT;      -- or ROLLBACK; to undo everything since BEGIN"),
    ("h2", "Upsert"),
    ("p", "Sometimes you want \"insert, or update if it already exists\". PostgreSQL and SQLite support it:"),
    ("code", "sql", "INSERT INTO customers (id, name, country, age)\nVALUES (1, 'Ada', 'UK', 37)\nON CONFLICT (id) DO UPDATE SET age = excluded.age;"),
    ("exercise", "Insert two products, raise the price of one by 10 percent, then delete any product priced under 1. Wrap it in a transaction."),
    ("solution", "sql", "BEGIN;\nINSERT INTO products (name, price) VALUES ('Pen', 1.50), ('Gum', 0.50);\nUPDATE products SET price = price * 1.10 WHERE name = 'Pen';\nDELETE FROM products WHERE price < 1;\nCOMMIT;"),
]

CONTENT["sql-schema-design"] = [
    ("p", "Before you can query data you have to shape it. <strong>Schema design</strong> decides which tables exist, what columns they have and how they connect. A good schema prevents whole categories of bugs, because the database itself refuses bad data."),
    ("h2", "CREATE TABLE"),
    ("code", "sql", "CREATE TABLE customers (\n  id      INTEGER PRIMARY KEY,\n  email   TEXT    NOT NULL UNIQUE,\n  name    TEXT    NOT NULL,\n  age     INTEGER CHECK (age >= 0),\n  created TIMESTAMP DEFAULT CURRENT_TIMESTAMP\n);\n\nCREATE TABLE orders (\n  id          INTEGER PRIMARY KEY,\n  customer_id INTEGER NOT NULL REFERENCES customers(id),\n  total       NUMERIC(10, 2) NOT NULL,\n  status      TEXT NOT NULL DEFAULT 'pending'\n);"),
    ("h2", "Constraints"),
    ("ul", [
        "<code>PRIMARY KEY</code>: unique, not null identifier.",
        "<code>NOT NULL</code>: the value is required.",
        "<code>UNIQUE</code>: no two rows may share the value (emails, usernames).",
        "<code>CHECK</code>: a rule every row must satisfy.",
        "<code>DEFAULT</code>: the value used when none is given.",
        "<code>REFERENCES</code> (foreign key): the value must exist in the other table. Deleting a referenced customer now fails, or cascades if you declare <code>ON DELETE CASCADE</code>.",
    ]),
    ("h2", "Choosing types"),
    ("p", "Use <code>INTEGER</code> for counts and ids, <code>NUMERIC(p, s)</code> for money (never floating point, which rounds), <code>TEXT</code> or <code>VARCHAR</code> for strings, <code>BOOLEAN</code>, <code>DATE</code> and <code>TIMESTAMP</code> for time. Store times in UTC."),
    ("h2", "Relationships"),
    ("ul", [
        "<strong>One-to-many</strong>: a customer has many orders. Put the foreign key on the \"many\" side.",
        "<strong>Many-to-many</strong>: students and courses. Add a <em>join table</em> holding both foreign keys.",
        "<strong>One-to-one</strong>: rare; a foreign key that is also unique.",
    ]),
    ("code", "sql", "CREATE TABLE enrollments (\n  student_id INTEGER REFERENCES students(id),\n  course_id  INTEGER REFERENCES courses(id),\n  PRIMARY KEY (student_id, course_id)\n);"),
    ("h2", "Normalization"),
    ("p", "<strong>Normalization</strong> means storing each fact once. If an <code>orders</code> table repeated the customer's name and address on every row, changing an address would mean editing many rows and risking inconsistency. Split it: customer details in <code>customers</code>, and orders point to them by id. Aim for about third normal form: every column depends on the key, the whole key, and nothing but the key. Denormalize deliberately later only if measurements show you need speed."),
    ("h2", "Changing a schema"),
    ("code", "sql", "ALTER TABLE customers ADD COLUMN phone TEXT;\nALTER TABLE customers DROP COLUMN phone;\nDROP TABLE IF EXISTS old_orders;"),
    ("note", "Migrations", "In real projects schema changes are written as versioned migration files (Django, Flyway, Alembic) and applied in order, so every environment stays identical."),
    ("exercise", "Design tables for a blog: authors, posts and tags, where a post has one author and many tags. Write the CREATE TABLE statements."),
    ("solution", "sql", "CREATE TABLE authors (id INTEGER PRIMARY KEY, name TEXT NOT NULL);\nCREATE TABLE posts (\n  id INTEGER PRIMARY KEY,\n  author_id INTEGER NOT NULL REFERENCES authors(id),\n  title TEXT NOT NULL,\n  body TEXT\n);\nCREATE TABLE tags (id INTEGER PRIMARY KEY, name TEXT UNIQUE NOT NULL);\nCREATE TABLE post_tags (\n  post_id INTEGER REFERENCES posts(id),\n  tag_id  INTEGER REFERENCES tags(id),\n  PRIMARY KEY (post_id, tag_id)\n);"),
]

CONTENT["sql-indexes-performance"] = [
    ("p", "A query that takes 2 ms on a hundred rows can take minutes on a hundred million. Without help, the database must read every row to find matches, a <strong>full table scan</strong>. An <strong>index</strong> is a separate, sorted lookup structure (usually a B-tree) that lets it jump straight to the right rows, like the index at the back of a book."),
    ("h2", "Creating an index"),
    ("code", "sql", "CREATE INDEX idx_orders_customer ON orders (customer_id);\nCREATE UNIQUE INDEX idx_customers_email ON customers (email);\nCREATE INDEX idx_orders_cust_status ON orders (customer_id, status);   -- composite"),
    ("p", "Primary keys and UNIQUE constraints are indexed automatically. Foreign key columns usually are not, and they are the most common candidates: joins and lookups on them are constant companions."),
    ("h2", "Reading the plan"),
    ("p", "<code>EXPLAIN</code> shows how the database intends to run a query. Look for a scan of the whole table versus an index search."),
    ("code", "sql", "EXPLAIN QUERY PLAN\nSELECT * FROM orders WHERE customer_id = 1;"),
    ("output", "-- before index: SCAN orders\n-- after index:  SEARCH orders USING INDEX idx_orders_customer (customer_id=?)"),
    ("p", "In PostgreSQL use <code>EXPLAIN ANALYZE</code> to also run the query and report real timings."),
    ("h2", "The trade-off"),
    ("ul", [
        "Indexes make reads faster but every INSERT, UPDATE and DELETE must also maintain them, so writes get slower.",
        "They use disk space. Do not index everything; index columns you filter, join and sort on.",
        "Low-selectivity columns (such as a boolean) rarely benefit.",
    ]),
    ("h2", "Composite index order"),
    ("p", "An index on <code>(customer_id, status)</code> helps queries filtering by <code>customer_id</code>, or by both, but not by <code>status</code> alone. Put the most commonly filtered, most selective column first."),
    ("h2", "Patterns that defeat indexes"),
    ("code", "sql", "-- Slow: function on the column prevents index use\nSELECT * FROM customers WHERE LOWER(email) = 'a@b.com';\n\n-- Slow: leading wildcard\nSELECT * FROM customers WHERE name LIKE '%son';\n\n-- Better: compare the raw column\nSELECT * FROM customers WHERE email = 'a@b.com';"),
    ("h2", "Other habits that keep queries fast"),
    ("ul", [
        "Select only needed columns instead of <code>SELECT *</code>.",
        "Paginate with <code>LIMIT</code>; for deep pages prefer keyset pagination (<code>WHERE id &gt; last_seen</code>) over big OFFSETs.",
        "Avoid the N+1 problem: one query per row from application code. Fetch related rows with a join or an <code>IN</code> list.",
    ]),
    ("note", "Measure, do not guess", "Add an index, re-run EXPLAIN and compare. Query planners are complex, and real data often surprises you."),
    ("exercise", "A query <code>SELECT * FROM orders WHERE customer_id = ? AND status = 'paid' ORDER BY created DESC</code> is slow. Propose an index and explain the column order."),
    ("solution", "sql", "-- Equality columns first, then the sort column, so the database can\n-- read matching rows already in order without a separate sort step.\nCREATE INDEX idx_orders_lookup ON orders (customer_id, status, created DESC);"),
]
