"""Django, FastAPI, Express tracks."""
from content_js_sql import M

META = [
    M("django-introduction", "django", "Introduction and Setup", 12, "Beginner", "What Django gives you, and how to create a project and run the server.", ["Create a Django project", "Explain project vs app", "Run the dev server"]),
    M("django-models", "django", "Models and Migrations", 17, "Beginner", "Describe tables in Python, migrate them and query with the ORM.", ["Define models", "Run migrations", "Query with filter/get/order_by"]),
    M("django-views-urls", "django", "Views, URLs and Templates", 17, "Beginner", "Route a URL to a view and render HTML with the template language.", ["Write function views", "Map URLs", "Use template tags and filters"]),
    M("django-forms-admin", "django", "Forms and the Admin", 16, "Intermediate", "Validate input with ModelForm and manage data with the built-in admin.", ["Build a ModelForm", "Handle POST safely with CSRF", "Register models in the admin"]),
    M("django-rest-api", "django", "Building a JSON API", 15, "Intermediate", "Return JSON from views and expose a REST API with Django REST framework.", ["Return JsonResponse", "Write a serializer", "Use a ModelViewSet"]),
    M("fastapi-introduction", "fastapi", "Introduction and First Endpoint", 11, "Beginner", "Install FastAPI, write an endpoint and explore the automatic docs.", ["Run a FastAPI app", "Define path operations", "Open /docs"]),
    M("fastapi-parameters", "fastapi", "Path, Query and Body Parameters", 15, "Beginner", "Accept data from the URL and request body with type validation.", ["Use path and query parameters", "Model a body with Pydantic", "Return validation errors"]),
    M("fastapi-pydantic-responses", "fastapi", "Models, Responses and Errors", 15, "Intermediate", "Response models, status codes and raising HTTP errors.", ["Declare response_model", "Set status codes", "Raise HTTPException"]),
    M("fastapi-dependencies", "fastapi", "Dependency Injection and Auth", 16, "Intermediate", "Share logic with Depends, and protect routes with tokens.", ["Write a dependency", "Inject a database session", "Protect a route"]),
    M("fastapi-async-database", "fastapi", "Async, Databases and Deployment", 16, "Advanced", "When to use async def, talking to a database and running in production.", ["Choose async vs sync", "Connect SQLAlchemy", "Run with uvicorn/Docker"]),
    M("express-introduction", "express", "Introduction and Hello Server", 11, "Beginner", "Set up Node and Express and serve your first routes.", ["Initialize a Node project", "Create an Express app", "Define routes"]),
    M("express-routing-middleware", "express", "Routing and Middleware", 15, "Beginner", "Route parameters, JSON bodies, and the middleware pipeline.", ["Read params, query and body", "Write middleware", "Use routers"]),
    M("express-rest-api", "express", "Building a REST API", 16, "Intermediate", "CRUD endpoints with validation, status codes and error handling.", ["Design CRUD routes", "Return correct status codes", "Centralize error handling"]),
    M("express-database-auth", "express", "Databases and Authentication", 17, "Intermediate", "Persist data, hash passwords and protect routes with JWT.", ["Connect a database", "Hash passwords", "Verify a JWT in middleware"]),
]

CONTENT = {}

# ---------------- Django ----------------
CONTENT["django-introduction"] = [
    ("p", "<strong>Django</strong> is a high-level Python web framework that follows a \"batteries included\" philosophy. Out of the box you get an ORM (talk to a database with Python objects), URL routing, templates, form handling, authentication, an automatic admin interface and strong security defaults. It powers sites such as Instagram and Pinterest."),
    ("h2", "The MTV pattern"),
    ("ul", [
        "<strong>Model</strong>: your data, defined as Python classes that map to database tables.",
        "<strong>Template</strong>: the HTML, with placeholders for data.",
        "<strong>View</strong>: a function that receives a request, gets data and returns a response.",
    ]),
    ("p", "A URL configuration connects incoming paths to views. This is Django's flavor of MVC."),
    ("h2", "Install and start a project"),
    ("code", "bash", "python3 -m venv .venv\nsource .venv/bin/activate          # Windows: .venv\\Scripts\\activate\npip install django\n\ndjango-admin startproject mysite\ncd mysite\npython manage.py runserver"),
    ("p", "Visit <code>http://127.0.0.1:8000/</code> to see the welcome page. A <strong>virtual environment</strong> keeps this project's packages separate from the rest of your system."),
    ("h2", "Project versus app"),
    ("p", "A <em>project</em> is the whole site (settings and root URLs). An <em>app</em> is one feature, such as <code>blog</code> or <code>accounts</code>. Apps are meant to be reusable and self-contained."),
    ("code", "bash", "python manage.py startapp blog"),
    ("p", "Then register the app by adding <code>\"blog\"</code> to <code>INSTALLED_APPS</code> in <code>mysite/settings.py</code>."),
    ("h2", "What is in the folder"),
    ("ul", [
        "<code>manage.py</code>: command-line helper (run the server, migrations, tests).",
        "<code>mysite/settings.py</code>: configuration, including database and installed apps.",
        "<code>mysite/urls.py</code>: the root URL table.",
        "<code>blog/models.py</code>, <code>views.py</code>, <code>admin.py</code>: the app's code.",
    ]),
    ("note", "Security", "Never commit <code>SECRET_KEY</code> or run with <code>DEBUG = True</code> in production. Read them from environment variables."),
    ("exercise", "Create a project called <code>library</code> with an app called <code>books</code>, register the app, and confirm the dev server starts."),
    ("solution", "bash", "django-admin startproject library\ncd library\npython manage.py startapp books\n# add \"books\" to INSTALLED_APPS in library/settings.py\npython manage.py runserver"),
]

CONTENT["django-models"] = [
    ("p", "A Django <strong>model</strong> is a Python class describing one database table. Each attribute is a column. You never write SQL for the common cases; the ORM (object-relational mapper) does it for you."),
    ("h2", "Defining models"),
    ("code", "python", '# blog/models.py\nfrom django.db import models\n\nclass Author(models.Model):\n    name = models.CharField(max_length=100)\n\n    def __str__(self):\n        return self.name\n\nclass Post(models.Model):\n    author = models.ForeignKey(Author, on_delete=models.CASCADE, related_name="posts")\n    title = models.CharField(max_length=200)\n    body = models.TextField()\n    published = models.BooleanField(default=False)\n    created = models.DateTimeField(auto_now_add=True)\n\n    class Meta:\n        ordering = ["-created"]\n\n    def __str__(self):\n        return self.title'),
    ("p", "Common fields: <code>CharField</code>, <code>TextField</code>, <code>IntegerField</code>, <code>BooleanField</code>, <code>DateTimeField</code>, <code>EmailField</code>, <code>ForeignKey</code> (one-to-many) and <code>ManyToManyField</code>. Django adds an <code>id</code> primary key automatically."),
    ("h2", "Migrations"),
    ("p", "Migrations are versioned scripts that carry model changes into the database. Change a model, generate a migration, then apply it."),
    ("code", "bash", "python manage.py makemigrations\npython manage.py migrate"),
    ("p", "Commit migration files to git so teammates and servers apply the same changes."),
    ("h2", "Querying with the ORM"),
    ("p", "Open the shell with <code>python manage.py shell</code> and try:"),
    ("code", "python", 'from blog.models import Author, Post\n\nada = Author.objects.create(name="Ada")\nPost.objects.create(author=ada, title="Hello", body="First post", published=True)\n\nPost.objects.all()                              # everything\nPost.objects.filter(published=True)             # WHERE published\nPost.objects.filter(title__contains="Hel")      # LIKE\nPost.objects.exclude(author=ada)\nPost.objects.order_by("-created")[:5]           # ORDER BY / LIMIT\nPost.objects.get(id=1)                          # exactly one, or raises\nada.posts.count()                               # via related_name'),
    ("p", "Querysets are <em>lazy</em>: nothing hits the database until you iterate, slice or evaluate them, so you can chain filters freely. Lookups use double underscores: <code>__gt</code>, <code>__in</code>, <code>__icontains</code>, <code>__startswith</code>, and even across relations, <code>author__name=\"Ada\"</code>."),
    ("h2", "Updating and deleting"),
    ("code", "python", 'post = Post.objects.get(id=1)\npost.title = "Updated"\npost.save()\n\nPost.objects.filter(published=False).update(published=True)\npost.delete()'),
    ("h2", "Avoiding the N+1 problem"),
    ("p", "Looping over posts and printing <code>post.author.name</code> runs one extra query per post. Fetch related rows up front:"),
    ("code", "python", 'posts = Post.objects.select_related("author")        # JOIN for foreign keys\nposts = Author.objects.prefetch_related("posts")    # 2 queries for reverse/many-to-many'),
    ("note", "Tip", "Add <code>print(qs.query)</code> or use the Django Debug Toolbar to see the SQL generated behind your code."),
    ("exercise", "Add a <code>Comment</code> model with a foreign key to <code>Post</code>, a <code>text</code> field and a timestamp. Make and apply the migration, then create two comments in the shell."),
    ("solution", "python", 'class Comment(models.Model):\n    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name="comments")\n    text = models.TextField()\n    created = models.DateTimeField(auto_now_add=True)\n\n# shell:\n# post = Post.objects.first()\n# Comment.objects.create(post=post, text="Nice")\n# post.comments.create(text="Thanks")'),
]

CONTENT["django-views-urls"] = [
    ("p", "When a browser asks for a page, Django looks up the URL in your URL configuration, calls the matching <strong>view</strong>, and sends back the response the view returns."),
    ("h2", "A view"),
    ("code", "python", '# blog/views.py\nfrom django.shortcuts import render, get_object_or_404\nfrom .models import Post\n\ndef post_list(request):\n    posts = Post.objects.filter(published=True).select_related("author")\n    return render(request, "blog/post_list.html", {"posts": posts})\n\ndef post_detail(request, pk):\n    post = get_object_or_404(Post, pk=pk, published=True)\n    return render(request, "blog/post_detail.html", {"post": post})'),
    ("p", "<code>render</code> combines a template with a context dictionary. <code>get_object_or_404</code> returns the object or an HTTP 404 page, instead of crashing with an exception."),
    ("h2", "URLs"),
    ("code", "python", '# blog/urls.py\nfrom django.urls import path\nfrom . import views\n\napp_name = "blog"\nurlpatterns = [\n    path("", views.post_list, name="list"),\n    path("<int:pk>/", views.post_detail, name="detail"),\n]\n\n# mysite/urls.py\nfrom django.urls import include, path\nurlpatterns = [\n    path("blog/", include("blog.urls")),\n]'),
    ("p", "<code>&lt;int:pk&gt;</code> captures a number from the URL and passes it to the view as <code>pk</code>. Giving each route a <code>name</code> lets you generate links without hard-coding paths."),
    ("h2", "Templates"),
    ("p", "Create <code>blog/templates/blog/post_list.html</code>. Templates use <code>{{ variable }}</code> to print values and <code>{% tag %}</code> for logic."),
    ("code", "html", '<!-- blog/templates/blog/post_list.html -->\n{% extends "base.html" %}\n{% block content %}\n  <h1>Posts</h1>\n  {% for post in posts %}\n    <article>\n      <h2><a href="{% url \'blog:detail\' post.pk %}">{{ post.title }}</a></h2>\n      <p>by {{ post.author.name }} on {{ post.created|date:"M d, Y" }}</p>\n      <p>{{ post.body|truncatewords:30 }}</p>\n    </article>\n  {% empty %}\n    <p>No posts yet.</p>\n  {% endfor %}\n{% endblock %}'),
    ("ul", [
        "<code>{% extends %}</code> and <code>{% block %}</code>: inherit a shared layout so you write headers and footers once.",
        "<code>|date</code>, <code>|truncatewords</code>: <em>filters</em> that transform values.",
        "Django auto-escapes variables, protecting against XSS. Only use <code>|safe</code> on content you fully trust.",
    ]),
    ("h2", "Class-based views"),
    ("p", "For common patterns, generic views remove boilerplate."),
    ("code", "python", 'from django.views.generic import ListView, DetailView\n\nclass PostList(ListView):\n    model = Post\n    queryset = Post.objects.filter(published=True)\n    template_name = "blog/post_list.html"\n    context_object_name = "posts"\n    paginate_by = 10'),
    ("note", "Common error", "<code>TemplateDoesNotExist</code> usually means the folder is misnamed or the app is missing from <code>INSTALLED_APPS</code>. Templates conventionally live in <code>app/templates/app/</code>."),
    ("exercise", "Add a page at <code>/blog/about/</code> that shows the number of published posts using a view, a URL and a template."),
    ("solution", "python", '# views.py\ndef about(request):\n    return render(request, "blog/about.html", {"count": Post.objects.filter(published=True).count()})\n# urls.py\npath("about/", views.about, name="about"),\n# about.html\n# <p>We have {{ count }} posts.</p>'),
]

CONTENT["django-forms-admin"] = [
    ("p", "Two of Django's biggest time savers: <strong>forms</strong> (validate and clean user input, redisplay errors) and the <strong>admin</strong> (a ready-made interface for managing your data)."),
    ("h2", "ModelForm"),
    ("p", "A <code>ModelForm</code> builds a form from a model, including validation rules."),
    ("code", "python", '# blog/forms.py\nfrom django import forms\nfrom .models import Post\n\nclass PostForm(forms.ModelForm):\n    class Meta:\n        model = Post\n        fields = ["title", "body", "published"]\n\n    def clean_title(self):\n        title = self.cleaned_data["title"].strip()\n        if len(title) < 5:\n            raise forms.ValidationError("Title is too short.")\n        return title'),
    ("h2", "Handling GET and POST"),
    ("p", "The same view shows the empty form on GET and processes it on POST. After a successful POST, <em>redirect</em> so refreshing does not resubmit."),
    ("code", "python", 'from django.shortcuts import redirect, render\nfrom .forms import PostForm\n\ndef post_create(request):\n    if request.method == "POST":\n        form = PostForm(request.POST)\n        if form.is_valid():\n            post = form.save(commit=False)\n            post.author = request.user.author     # fill fields not on the form\n            post.save()\n            return redirect("blog:detail", pk=post.pk)\n    else:\n        form = PostForm()\n    return render(request, "blog/post_form.html", {"form": form})'),
    ("code", "html", '<form method="post">\n  {% csrf_token %}\n  {{ form.as_p }}\n  <button type="submit">Save</button>\n</form>'),
    ("note", "CSRF", "<code>{% csrf_token %}</code> is required in every POST form. It defends against cross-site request forgery; without it Django rejects the submission with a 403."),
    ("h2", "The admin"),
    ("p", "Create a superuser, register your models, and Django generates a full create, edit, search and delete interface."),
    ("code", "bash", "python manage.py createsuperuser\npython manage.py runserver     # then visit /admin/"),
    ("code", "python", '# blog/admin.py\nfrom django.contrib import admin\nfrom .models import Author, Post\n\n@admin.register(Post)\nclass PostAdmin(admin.ModelAdmin):\n    list_display = ("title", "author", "published", "created")\n    list_filter = ("published", "author")\n    search_fields = ("title", "body")\n    list_editable = ("published",)\n\nadmin.site.register(Author)'),
    ("h2", "Authentication"),
    ("p", "Django ships user accounts, sessions and password hashing. Protect a view with the <code>login_required</code> decorator."),
    ("code", "python", 'from django.contrib.auth.decorators import login_required\n\n@login_required\ndef dashboard(request):\n    return render(request, "dashboard.html")'),
    ("exercise", "Add a <code>ContactForm</code> (a plain <code>forms.Form</code>, not tied to a model) with <code>email</code> and <code>message</code> fields, and make the view print the cleaned data on a valid submission."),
    ("solution", "python", 'class ContactForm(forms.Form):\n    email = forms.EmailField()\n    message = forms.CharField(widget=forms.Textarea, min_length=10)\n\ndef contact(request):\n    form = ContactForm(request.POST or None)\n    if request.method == "POST" and form.is_valid():\n        print(form.cleaned_data)\n        return redirect("blog:list")\n    return render(request, "contact.html", {"form": form})'),
]

CONTENT["django-rest-api"] = [
    ("p", "Modern apps often serve JSON to a React front end or a mobile app instead of HTML pages. Django can do that natively, and the <strong>Django REST framework</strong> (DRF) makes it fast to build a full API."),
    ("h2", "A plain JSON view"),
    ("code", "python", 'from django.http import JsonResponse\nfrom .models import Post\n\ndef api_posts(request):\n    data = list(Post.objects.filter(published=True).values("id", "title", "created"))\n    return JsonResponse({"posts": data})'),
    ("h2", "Django REST framework"),
    ("code", "bash", "pip install djangorestframework"),
    ("p", "Add <code>\"rest_framework\"</code> to <code>INSTALLED_APPS</code>. DRF has three main pieces: serializers, viewsets and routers."),
    ("h2", "Serializers"),
    ("p", "A serializer converts model instances to JSON and validates incoming JSON, much like a form."),
    ("code", "python", '# blog/serializers.py\nfrom rest_framework import serializers\nfrom .models import Post\n\nclass PostSerializer(serializers.ModelSerializer):\n    author_name = serializers.CharField(source="author.name", read_only=True)\n\n    class Meta:\n        model = Post\n        fields = ["id", "title", "body", "published", "author", "author_name", "created"]\n        read_only_fields = ["created"]'),
    ("h2", "ViewSets and routers"),
    ("p", "A <code>ModelViewSet</code> provides list, create, retrieve, update and delete in a few lines."),
    ("code", "python", '# blog/api.py\nfrom rest_framework import viewsets, permissions\nfrom .models import Post\nfrom .serializers import PostSerializer\n\nclass PostViewSet(viewsets.ModelViewSet):\n    queryset = Post.objects.select_related("author")\n    serializer_class = PostSerializer\n    permission_classes = [permissions.IsAuthenticatedOrReadOnly]\n\n# mysite/urls.py\nfrom rest_framework.routers import DefaultRouter\nrouter = DefaultRouter()\nrouter.register("posts", PostViewSet)\nurlpatterns += [path("api/", include(router.urls))]'),
    ("p", "That gives you <code>GET /api/posts/</code>, <code>POST /api/posts/</code>, <code>GET /api/posts/1/</code>, <code>PUT</code>, <code>PATCH</code> and <code>DELETE</code>, plus a browsable HTML interface for testing."),
    ("h2", "Trying it"),
    ("code", "bash", 'curl http://127.0.0.1:8000/api/posts/\ncurl -X POST http://127.0.0.1:8000/api/posts/ \\\n  -H "Content-Type: application/json" \\\n  -d \'{"title": "Hello API", "body": "text", "author": 1}\''),
    ("h2", "Pagination, filtering and auth"),
    ("code", "python", '# settings.py\nREST_FRAMEWORK = {\n    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",\n    "PAGE_SIZE": 20,\n    "DEFAULT_AUTHENTICATION_CLASSES": [\n        "rest_framework.authentication.SessionAuthentication",\n        "rest_framework.authentication.TokenAuthentication",\n    ],\n}'),
    ("note", "Consider FastAPI too", "If you only need an API and want automatic docs and type-based validation, the FastAPI course in this section is a lighter alternative. Django shines when you also want the admin, auth and ORM together."),
    ("exercise", "Add a custom action on the viewset: <code>POST /api/posts/1/publish/</code> that sets <code>published=True</code> and returns the updated post."),
    ("solution", "python", 'from rest_framework.decorators import action\nfrom rest_framework.response import Response\n\nclass PostViewSet(viewsets.ModelViewSet):\n    ...\n    @action(detail=True, methods=["post"])\n    def publish(self, request, pk=None):\n        post = self.get_object()\n        post.published = True\n        post.save()\n        return Response(self.get_serializer(post).data)'),
]

# ---------------- FastAPI ----------------
CONTENT["fastapi-introduction"] = [
    ("p", "<strong>FastAPI</strong> is a modern Python framework for building APIs. It is fast, uses standard Python type hints for validation, and generates interactive documentation automatically. It is built on Starlette (web layer) and Pydantic (data validation)."),
    ("h2", "Install and run"),
    ("code", "bash", 'python3 -m venv .venv && source .venv/bin/activate\npip install "fastapi[standard]"'),
    ("code", "python", '# main.py\nfrom fastapi import FastAPI\n\napp = FastAPI(title="Demo API")\n\n@app.get("/")\ndef root():\n    return {"message": "Hello, FastAPI"}\n\n@app.get("/health")\ndef health():\n    return {"status": "ok"}'),
    ("code", "bash", "fastapi dev main.py      # or: uvicorn main:app --reload"),
    ("p", "The <code>--reload</code> behavior restarts the server when you save a file. Visit <code>http://127.0.0.1:8000/</code> to see the JSON."),
    ("h2", "Automatic documentation"),
    ("p", "Two free UIs appear the moment you have endpoints:"),
    ("ul", [
        "<code>/docs</code>: Swagger UI, where you can try each endpoint from the browser.",
        "<code>/redoc</code>: a cleaner reference view.",
        "<code>/openapi.json</code>: the machine-readable OpenAPI schema; front-end tools can generate clients from it.",
    ]),
    ("h2", "Path operations"),
    ("p", "A <strong>path operation</strong> is a function plus a decorator naming the HTTP method and URL path: <code>@app.get</code>, <code>@app.post</code>, <code>@app.put</code>, <code>@app.delete</code>. Whatever the function returns (dicts, lists, Pydantic models) is converted to JSON."),
    ("h2", "Why type hints matter here"),
    ("p", "In the next lessons you will see that the annotations you write, such as <code>item_id: int</code>, are not decoration: FastAPI reads them to convert, validate and document input automatically."),
    ("note", "FastAPI vs Flask vs Django", "Flask is minimal and unopinionated. Django is full-stack with an ORM and admin. FastAPI focuses on APIs, with validation, docs and async support built in."),
    ("exercise", "Add a <code>GET /about</code> endpoint that returns your name and app version, then open <code>/docs</code> and call it from the browser."),
    ("solution", "python", '@app.get("/about")\ndef about():\n    return {"author": "stackcone", "version": "1.0.0"}'),
]

CONTENT["fastapi-parameters"] = [
    ("p", "Real endpoints take input. FastAPI reads it from three places and validates it using your type hints: the URL <strong>path</strong>, the <strong>query string</strong> and the request <strong>body</strong>."),
    ("h2", "Path parameters"),
    ("code", "python", '@app.get("/users/{user_id}")\ndef get_user(user_id: int):\n    return {"user_id": user_id}'),
    ("p", "Requesting <code>/users/42</code> gives you the integer 42. Requesting <code>/users/abc</code> automatically returns an HTTP 422 error explaining that the value is not a valid integer. You wrote no validation code."),
    ("h2", "Query parameters"),
    ("p", "Function parameters that are not in the path become query parameters. Give them defaults to make them optional."),
    ("code", "python", 'from fastapi import Query\n\n@app.get("/search")\ndef search(q: str, limit: int = 10, page: int = Query(1, ge=1)):\n    return {"q": q, "limit": limit, "page": page}\n\n# GET /search?q=python&limit=5'),
    ("p", "<code>Query(1, ge=1)</code> adds a rule: the value must be greater than or equal to 1. Similar options: <code>le</code>, <code>min_length</code>, <code>max_length</code>, <code>pattern</code>."),
    ("h2", "Request body with Pydantic"),
    ("p", "For JSON bodies, describe the shape with a Pydantic model. FastAPI parses the JSON, validates every field and gives you a typed object."),
    ("code", "python", 'from pydantic import BaseModel, Field\n\nclass Item(BaseModel):\n    name: str = Field(min_length=1, max_length=50)\n    price: float = Field(gt=0)\n    tags: list[str] = []\n    in_stock: bool = True\n\n@app.post("/items")\ndef create_item(item: Item):\n    return {"created": item.name, "total_with_tax": round(item.price * 1.2, 2)}'),
    ("code", "bash", 'curl -X POST http://127.0.0.1:8000/items \\\n  -H "Content-Type: application/json" \\\n  -d \'{"name": "Pen", "price": 1.5}\''),
    ("output", '{"created":"Pen","total_with_tax":1.8}'),
    ("h2", "Validation errors"),
    ("p", "Send <code>{\"name\": \"\", \"price\": -1}</code> and FastAPI replies with status 422 and a list showing exactly which fields failed and why. Clients get clear, consistent errors for free."),
    ("h2", "Mixing all three"),
    ("code", "python", '@app.put("/items/{item_id}")\ndef update_item(item_id: int, item: Item, notify: bool = False):\n    return {"id": item_id, "item": item, "notify": notify}'),
    ("p", "FastAPI infers each source: <code>item_id</code> is in the path, <code>item</code> is a body model, and <code>notify</code> is a query parameter."),
    ("note", "Tip", "Use <code>Optional</code> or <code>str | None = None</code> for values that may be missing, so the docs show them as optional."),
    ("exercise", "Create <code>POST /users</code> accepting <code>username</code> (3 to 20 characters), <code>email</code> and <code>age</code> (must be at least 13). Return the username in uppercase."),
    ("solution", "python", 'from pydantic import BaseModel, Field, EmailStr   # pip install email-validator\n\nclass User(BaseModel):\n    username: str = Field(min_length=3, max_length=20)\n    email: EmailStr\n    age: int = Field(ge=13)\n\n@app.post("/users")\ndef create_user(user: User):\n    return {"username": user.username.upper()}'),
]

CONTENT["fastapi-pydantic-responses"] = [
    ("p", "How an API <em>replies</em> matters as much as what it accepts: the right shape, the right status code and helpful errors. FastAPI makes each of these explicit."),
    ("h2", "Response models"),
    ("p", "Declaring a <code>response_model</code> filters the output to exactly the fields you specify. This is how you avoid accidentally leaking secrets, such as a password hash."),
    ("code", "python", 'from pydantic import BaseModel\n\nclass UserIn(BaseModel):\n    username: str\n    password: str\n\nclass UserOut(BaseModel):\n    id: int\n    username: str\n\n@app.post("/users", response_model=UserOut, status_code=201)\ndef create_user(user: UserIn):\n    saved = {"id": 1, "username": user.username, "password": "hashed..."}\n    return saved            # password is removed by UserOut'),
    ("h2", "Status codes"),
    ("ul", [
        "<code>200 OK</code>: success (default).",
        "<code>201 Created</code>: a resource was created (POST).",
        "<code>204 No Content</code>: success with nothing to return (DELETE).",
        "<code>400 / 422</code>: bad input. <code>401 / 403</code>: not authenticated / not allowed. <code>404</code>: not found. <code>409</code>: conflict.",
    ]),
    ("h2", "Raising errors"),
    ("code", "python", 'from fastapi import HTTPException, status\n\nusers = {1: {"id": 1, "username": "ada"}}\n\n@app.get("/users/{user_id}", response_model=UserOut)\ndef get_user(user_id: int):\n    if user_id not in users:\n        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="User not found")\n    return users[user_id]\n\n@app.delete("/users/{user_id}", status_code=204)\ndef delete_user(user_id: int):\n    if users.pop(user_id, None) is None:\n        raise HTTPException(404, "User not found")'),
    ("output", '// GET /users/99\n{"detail":"User not found"}'),
    ("h2", "Custom exception handlers"),
    ("code", "python", 'from fastapi.responses import JSONResponse\n\nclass OutOfStock(Exception):\n    def __init__(self, item): self.item = item\n\n@app.exception_handler(OutOfStock)\ndef out_of_stock_handler(request, exc: OutOfStock):\n    return JSONResponse(status_code=409, content={"error": f"{exc.item} is out of stock"})'),
    ("h2", "Lists and pagination"),
    ("code", "python", 'from typing import List\n\n@app.get("/users", response_model=List[UserOut])\ndef list_users(skip: int = 0, limit: int = 20):\n    return list(users.values())[skip: skip + limit]'),
    ("note", "Consistency", "Pick one error shape for the whole API and stick to it; front-end code becomes much simpler when every error looks the same."),
    ("exercise", "Build a tiny in-memory <code>/todos</code> API: <code>POST</code> (201), <code>GET</code> by id (404 if missing) and <code>DELETE</code> (204)."),
    ("solution", "python", 'todos, next_id = {}, 1\n\nclass TodoIn(BaseModel):\n    title: str\n\n@app.post("/todos", status_code=201)\ndef add(t: TodoIn):\n    global next_id\n    todos[next_id] = {"id": next_id, "title": t.title}\n    next_id += 1\n    return todos[next_id - 1]\n\n@app.get("/todos/{tid}")\ndef get(tid: int):\n    if tid not in todos:\n        raise HTTPException(404, "Not found")\n    return todos[tid]\n\n@app.delete("/todos/{tid}", status_code=204)\ndef remove(tid: int):\n    todos.pop(tid, None)'),
]

CONTENT["fastapi-dependencies"] = [
    ("p", "Many endpoints need the same things: a database session, the current user, pagination settings. <strong>Dependency injection</strong> lets you declare what an endpoint needs, and FastAPI provides it. You write the shared logic once with <code>Depends</code>."),
    ("h2", "A simple dependency"),
    ("code", "python", 'from fastapi import Depends\n\ndef pagination(skip: int = 0, limit: int = 20):\n    return {"skip": skip, "limit": min(limit, 100)}\n\n@app.get("/items")\ndef list_items(page: dict = Depends(pagination)):\n    return page\n\n@app.get("/users")\ndef list_users(page: dict = Depends(pagination)):\n    return page'),
    ("h2", "Dependencies with cleanup"),
    ("p", "A dependency that uses <code>yield</code> runs setup before the endpoint and cleanup after it, perfect for database sessions."),
    ("code", "python", 'from sqlalchemy.orm import Session\nfrom .database import SessionLocal\n\ndef get_db():\n    db = SessionLocal()\n    try:\n        yield db\n    finally:\n        db.close()\n\n@app.get("/posts")\ndef posts(db: Session = Depends(get_db)):\n    return db.query(Post).all()'),
    ("h2", "Authentication with a bearer token"),
    ("p", "FastAPI includes security helpers. The pattern: a dependency reads and verifies the token, and any route that lists it is protected."),
    ("code", "python", 'from fastapi.security import OAuth2PasswordBearer\nimport jwt   # pip install pyjwt\n\noauth2 = OAuth2PasswordBearer(tokenUrl="login")\nSECRET, ALGO = "change-me", "HS256"      # load from environment in real apps\n\ndef current_user(token: str = Depends(oauth2)):\n    try:\n        payload = jwt.decode(token, SECRET, algorithms=[ALGO])\n    except jwt.PyJWTError:\n        raise HTTPException(401, "Invalid token", headers={"WWW-Authenticate": "Bearer"})\n    return payload["sub"]\n\n@app.get("/me")\ndef me(user: str = Depends(current_user)):\n    return {"user": user}'),
    ("p", "Issuing tokens on login uses <code>jwt.encode({\"sub\": username, \"exp\": ...}, SECRET, algorithm=ALGO)</code>. Passwords must be stored hashed, for example with <code>passlib</code>'s bcrypt or <code>argon2</code>, never in plain text."),
    ("h2", "Router-level dependencies"),
    ("code", "python", 'from fastapi import APIRouter\n\nadmin = APIRouter(prefix="/admin", dependencies=[Depends(current_user)])\n\n@admin.get("/stats")\ndef stats():\n    return {"users": 10}\n\napp.include_router(admin)'),
    ("note", "Testing benefit", "Because dependencies are injected, tests can replace them: <code>app.dependency_overrides[get_db] = fake_db</code>."),
    ("exercise", "Write a dependency <code>require_api_key</code> that reads the <code>X-API-Key</code> header and raises 403 unless it equals <code>\"secret\"</code>, and protect one route with it."),
    ("solution", "python", 'from fastapi import Header\n\ndef require_api_key(x_api_key: str = Header(...)):\n    if x_api_key != "secret":\n        raise HTTPException(403, "Bad API key")\n\n@app.get("/private", dependencies=[Depends(require_api_key)])\ndef private():\n    return {"ok": True}'),
]

CONTENT["fastapi-async-database"] = [
    ("p", "You may write endpoints with <code>def</code> or <code>async def</code>. Choosing correctly affects performance, and databases plus deployment are what turn a demo into a service."),
    ("h2", "async or not?"),
    ("ul", [
        "<strong>async def</strong>: use when everything you call inside is <em>awaitable</em> (async database drivers, <code>httpx.AsyncClient</code>). The event loop can serve other requests while you wait.",
        "<strong>def</strong>: use when you call blocking code (a regular database driver, <code>requests</code>, heavy computation). FastAPI runs these in a thread pool so they do not freeze the server.",
    ]),
    ("note", "The trap", "Calling blocking code inside <code>async def</code> stalls the whole event loop and every other request waits. When unsure, use plain <code>def</code>."),
    ("code", "python", 'import httpx\n\n@app.get("/proxy")\nasync def proxy():\n    async with httpx.AsyncClient() as client:\n        r = await client.get("https://api.github.com")\n    return {"status": r.status_code}'),
    ("h2", "A database with SQLAlchemy"),
    ("code", "python", '# database.py\nfrom sqlalchemy import create_engine\nfrom sqlalchemy.orm import sessionmaker, DeclarativeBase\n\nengine = create_engine("sqlite:///./app.db", connect_args={"check_same_thread": False})\nSessionLocal = sessionmaker(bind=engine, autoflush=False)\n\nclass Base(DeclarativeBase):\n    pass\n\n# models.py\nfrom sqlalchemy import String\nfrom sqlalchemy.orm import Mapped, mapped_column\n\nclass Todo(Base):\n    __tablename__ = "todos"\n    id: Mapped[int] = mapped_column(primary_key=True)\n    title: Mapped[str] = mapped_column(String(100))\n    done: Mapped[bool] = mapped_column(default=False)\n\nBase.metadata.create_all(engine)'),
    ("code", "python", '@app.post("/todos", status_code=201)\ndef create(t: TodoIn, db: Session = Depends(get_db)):\n    todo = Todo(title=t.title)\n    db.add(todo)\n    db.commit()\n    db.refresh(todo)\n    return todo\n\n@app.get("/todos/{tid}")\ndef read(tid: int, db: Session = Depends(get_db)):\n    todo = db.get(Todo, tid)\n    if not todo:\n        raise HTTPException(404)\n    return todo'),
    ("p", "For production use PostgreSQL, and manage schema changes with <strong>Alembic</strong> migrations instead of <code>create_all</code>."),
    ("h2", "Background tasks"),
    ("code", "python", 'from fastapi import BackgroundTasks\n\ndef send_email(to: str):\n    print("emailing", to)\n\n@app.post("/signup")\ndef signup(email: str, bg: BackgroundTasks):\n    bg.add_task(send_email, email)      # runs after the response is sent\n    return {"ok": True}'),
    ("h2", "Deploying"),
    ("code", "dockerfile", 'FROM python:3.12-slim\nWORKDIR /app\nCOPY requirements.txt .\nRUN pip install --no-cache-dir -r requirements.txt\nCOPY . .\nCMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]'),
    ("ul", [
        "Read secrets and the database URL from environment variables (<code>pydantic-settings</code> helps).",
        "Run behind a process manager or several workers: <code>uvicorn main:app --workers 4</code>.",
        "Add CORS middleware if a browser front end on another origin calls your API.",
        "Write tests with <code>TestClient</code> from <code>fastapi.testclient</code>.",
    ]),
    ("exercise", "Write a test using <code>TestClient</code> that posts a todo and asserts the response has status 201 and a <code>title</code> field."),
    ("solution", "python", 'from fastapi.testclient import TestClient\nfrom main import app\n\nclient = TestClient(app)\n\ndef test_create_todo():\n    r = client.post("/todos", json={"title": "write tests"})\n    assert r.status_code == 201\n    assert r.json()["title"] == "write tests"'),
]

# ---------------- Express ----------------
CONTENT["express-introduction"] = [
    ("p", "<strong>Express</strong> is the most popular web framework for <strong>Node.js</strong>. It is deliberately minimal: a thin layer on top of Node's HTTP server that adds routing and a middleware system. Many bigger frameworks are built on it, and it is an excellent way to learn how web servers work."),
    ("h2", "Setup"),
    ("p", "Install Node.js (version 18 or newer), then create a project."),
    ("code", "bash", "mkdir my-api && cd my-api\nnpm init -y\nnpm install express"),
    ("p", "In <code>package.json</code> add <code>\"type\": \"module\"</code> to use modern <code>import</code> syntax."),
    ("h2", "Hello server"),
    ("code", "javascript", '// index.js\nimport express from "express";\n\nconst app = express();\nconst PORT = process.env.PORT || 3000;\n\napp.get("/", (req, res) => {\n  res.send("Hello, Express");\n});\n\napp.get("/health", (req, res) => {\n  res.json({ status: "ok", time: new Date().toISOString() });\n});\n\napp.listen(PORT, () => console.log(`Listening on http://localhost:${PORT}`));'),
    ("code", "bash", "node index.js          # or: node --watch index.js to auto-restart"),
    ("p", "Open <code>http://localhost:3000/</code>. Each route takes a path and a <em>handler</em> receiving <code>req</code> (the request) and <code>res</code> (the response). Always finish a request by sending a response, otherwise the client hangs."),
    ("h2", "Common response methods"),
    ("ul", [
        "<code>res.send(text)</code>: send text or HTML.",
        "<code>res.json(obj)</code>: send JSON with the right content type.",
        "<code>res.status(404).json({ ... })</code>: set the status code first.",
        "<code>res.redirect(\"/new\")</code> and <code>res.sendFile(path)</code>.",
    ]),
    ("h2", "HTTP methods"),
    ("p", "<code>app.get</code>, <code>app.post</code>, <code>app.put</code>, <code>app.patch</code> and <code>app.delete</code> correspond to reading, creating, replacing, updating and removing resources."),
    ("note", "Test with curl", "<code>curl -i http://localhost:3000/health</code> shows the status line and headers as well as the body."),
    ("exercise", "Add <code>GET /hello/:name</code> that responds with <code>Hello, &lt;name&gt;!</code>. Look at the <code>req.params</code> object."),
    ("solution", "javascript", 'app.get("/hello/:name", (req, res) => {\n  res.send(`Hello, ${req.params.name}!`);\n});'),
]

CONTENT["express-routing-middleware"] = [
    ("p", "Two ideas sit at the heart of Express: <strong>routing</strong> (which code handles which request) and <strong>middleware</strong> (a pipeline every request passes through)."),
    ("h2", "Reading input"),
    ("code", "javascript", 'app.use(express.json());                 // parse JSON bodies\n\napp.get("/users/:id", (req, res) => {\n  res.json({ id: req.params.id, verbose: req.query.verbose });   // /users/7?verbose=1\n});\n\napp.post("/users", (req, res) => {\n  const { name, email } = req.body;\n  res.status(201).json({ name, email });\n});'),
    ("ul", [
        "<code>req.params</code>: values from the path (<code>:id</code>).",
        "<code>req.query</code>: the query string (<code>?page=2</code>).",
        "<code>req.body</code>: parsed body; requires the <code>express.json()</code> middleware, otherwise it is undefined.",
        "<code>req.headers</code>: request headers.",
    ]),
    ("h2", "Middleware"),
    ("p", "A middleware function receives <code>(req, res, next)</code>. It can inspect or change the request, end the response, or call <code>next()</code> to pass control on. They run in the order you register them."),
    ("code", "javascript", 'function logger(req, res, next) {\n  const start = Date.now();\n  res.on("finish", () => {\n    console.log(`${req.method} ${req.url} ${res.statusCode} ${Date.now() - start}ms`);\n  });\n  next();\n}\n\nfunction requireKey(req, res, next) {\n  if (req.get("x-api-key") !== "secret") {\n    return res.status(401).json({ error: "Unauthorized" });\n  }\n  next();\n}\n\napp.use(logger);                          // for every route\napp.get("/private", requireKey, (req, res) => res.json({ ok: true }));   // for one route'),
    ("note", "Order matters", "Register <code>express.json()</code> and your logger <em>before</em> the routes that need them. Forgetting <code>next()</code> leaves the request hanging."),
    ("h2", "Routers"),
    ("p", "Split a large app into modules with <code>express.Router()</code>."),
    ("code", "javascript", '// routes/users.js\nimport { Router } from "express";\nconst router = Router();\n\nrouter.get("/", (req, res) => res.json([]));\nrouter.get("/:id", (req, res) => res.json({ id: req.params.id }));\n\nexport default router;\n\n// index.js\nimport users from "./routes/users.js";\napp.use("/api/users", users);'),
    ("h2", "Useful built-in and third-party middleware"),
    ("ul", [
        "<code>express.static(\"public\")</code>: serve files from a folder.",
        "<code>cors</code>: allow browsers on other origins to call your API.",
        "<code>helmet</code>: set secure HTTP headers.",
        "<code>morgan</code>: ready-made request logging.",
    ]),
    ("exercise", "Write middleware that adds a <code>req.requestId</code> (a random id) and an <code>X-Request-Id</code> response header, and apply it to all routes."),
    ("solution", "javascript", 'import { randomUUID } from "node:crypto";\n\napp.use((req, res, next) => {\n  req.requestId = randomUUID();\n  res.setHeader("X-Request-Id", req.requestId);\n  next();\n});'),
]

CONTENT["express-rest-api"] = [
    ("p", "A <strong>REST API</strong> models your data as <em>resources</em> at URLs, manipulated with HTTP methods. Designing it consistently makes it predictable for whoever consumes it. Here we build a complete CRUD API for tasks, using an in-memory array to keep the focus on the API design."),
    ("h2", "Route design"),
    ("ul", [
        "<code>GET /tasks</code>: list. <code>GET /tasks/:id</code>: one.",
        "<code>POST /tasks</code>: create (201). <code>PATCH /tasks/:id</code>: partial update. <code>DELETE /tasks/:id</code>: remove (204).",
        "Use plural nouns for resources and let the HTTP method express the action.",
    ]),
    ("code", "javascript", 'import express from "express";\nconst app = express();\napp.use(express.json());\n\nlet tasks = [];\nlet nextId = 1;\n\napp.get("/tasks", (req, res) => {\n  const { done } = req.query;\n  const list = done === undefined ? tasks : tasks.filter((t) => String(t.done) === done);\n  res.json(list);\n});\n\napp.get("/tasks/:id", (req, res) => {\n  const task = tasks.find((t) => t.id === Number(req.params.id));\n  if (!task) return res.status(404).json({ error: "Task not found" });\n  res.json(task);\n});\n\napp.post("/tasks", (req, res) => {\n  const { title } = req.body;\n  if (typeof title !== "string" || !title.trim()) {\n    return res.status(400).json({ error: "title is required" });\n  }\n  const task = { id: nextId++, title: title.trim(), done: false };\n  tasks.push(task);\n  res.status(201).location(`/tasks/${task.id}`).json(task);\n});\n\napp.patch("/tasks/:id", (req, res) => {\n  const task = tasks.find((t) => t.id === Number(req.params.id));\n  if (!task) return res.status(404).json({ error: "Task not found" });\n  Object.assign(task, req.body);\n  res.json(task);\n});\n\napp.delete("/tasks/:id", (req, res) => {\n  tasks = tasks.filter((t) => t.id !== Number(req.params.id));\n  res.status(204).end();\n});'),
    ("h2", "Validation"),
    ("p", "Never trust request bodies. Validate with a schema library such as <strong>zod</strong>, which also gives clear error messages."),
    ("code", "javascript", 'import { z } from "zod";\n\nconst TaskInput = z.object({\n  title: z.string().trim().min(1).max(100),\n  done: z.boolean().optional(),\n});\n\napp.post("/tasks", (req, res) => {\n  const parsed = TaskInput.safeParse(req.body);\n  if (!parsed.success) return res.status(400).json({ errors: parsed.error.issues });\n  // ...create using parsed.data\n});'),
    ("h2", "Centralized error handling"),
    ("p", "An error-handling middleware has <em>four</em> parameters and goes after all routes. Errors passed to <code>next(err)</code> land there, so you handle them in one place."),
    ("code", "javascript", 'app.use((req, res) => res.status(404).json({ error: "Route not found" }));\n\napp.use((err, req, res, next) => {\n  console.error(err);\n  res.status(err.status || 500).json({ error: err.message || "Internal Server Error" });\n});'),
    ("p", "In Express 4, errors thrown inside <code>async</code> handlers are not caught automatically: wrap them with <code>try/catch</code> and call <code>next(err)</code>. Express 5 handles rejected promises for you."),
    ("note", "Status codes", "200 OK, 201 Created, 204 No Content, 400 Bad Request, 401 Unauthorized, 403 Forbidden, 404 Not Found, 409 Conflict, 500 Server Error. Use the most accurate one."),
    ("exercise", "Add pagination to <code>GET /tasks</code> using <code>?page=</code> and <code>?limit=</code> (defaults 1 and 10, maximum limit 50) and include the total count in the response."),
    ("solution", "javascript", 'app.get("/tasks", (req, res) => {\n  const page = Math.max(1, Number(req.query.page) || 1);\n  const limit = Math.min(50, Math.max(1, Number(req.query.limit) || 10));\n  const start = (page - 1) * limit;\n  res.json({ total: tasks.length, page, limit, data: tasks.slice(start, start + limit) });\n});'),
]

CONTENT["express-database-auth"] = [
    ("p", "An in-memory array disappears when the server restarts. Real APIs store data in a database and identify users. This lesson shows the standard building blocks: a database connection, password hashing and token-based authentication."),
    ("h2", "Connecting to a database"),
    ("p", "PostgreSQL with the <code>pg</code> package is a solid default. Always use <strong>parameterized queries</strong>: values are sent separately from the SQL so user input can never change the query's meaning (this prevents SQL injection)."),
    ("code", "bash", "npm install pg"),
    ("code", "javascript", 'import pg from "pg";\nconst pool = new pg.Pool({ connectionString: process.env.DATABASE_URL });\n\napp.get("/tasks/:id", async (req, res, next) => {\n  try {\n    const { rows } = await pool.query("SELECT * FROM tasks WHERE id = $1", [req.params.id]);\n    if (!rows.length) return res.status(404).json({ error: "Not found" });\n    res.json(rows[0]);\n  } catch (err) {\n    next(err);\n  }\n});\n\n// NEVER build SQL by string concatenation:\n// pool.query("SELECT * FROM tasks WHERE id = " + req.params.id)   // injectable!'),
    ("p", "If you prefer an ORM, look at Prisma or Drizzle, which give you typed models and migrations."),
    ("h2", "Hashing passwords"),
    ("p", "Never store passwords in plain text. Store a slow, salted <strong>hash</strong> so a leaked database does not reveal them. <code>bcrypt</code> (or argon2) is designed for exactly this."),
    ("code", "javascript", 'import bcrypt from "bcrypt";\n\napp.post("/register", async (req, res, next) => {\n  try {\n    const { email, password } = req.body;\n    if (!email || !password || password.length < 8)\n      return res.status(400).json({ error: "email and 8+ char password required" });\n    const hash = await bcrypt.hash(password, 12);\n    await pool.query("INSERT INTO users (email, password_hash) VALUES ($1, $2)", [email, hash]);\n    res.status(201).json({ ok: true });\n  } catch (err) { next(err); }\n});'),
    ("h2", "Logging in with a JWT"),
    ("p", "After verifying the password, issue a <strong>JSON Web Token</strong>: a signed string containing the user id. The client sends it back in the <code>Authorization</code> header on later requests, and the server verifies the signature without a database lookup."),
    ("code", "javascript", 'import jwt from "jsonwebtoken";\n\napp.post("/login", async (req, res, next) => {\n  try {\n    const { email, password } = req.body;\n    const { rows } = await pool.query("SELECT * FROM users WHERE email = $1", [email]);\n    const user = rows[0];\n    const ok = user && (await bcrypt.compare(password, user.password_hash));\n    if (!ok) return res.status(401).json({ error: "Invalid credentials" });\n    const token = jwt.sign({ sub: user.id }, process.env.JWT_SECRET, { expiresIn: "1h" });\n    res.json({ token });\n  } catch (err) { next(err); }\n});'),
    ("h2", "Protecting routes"),
    ("code", "javascript", 'function auth(req, res, next) {\n  const header = req.get("authorization") || "";\n  const token = header.startsWith("Bearer ") ? header.slice(7) : null;\n  if (!token) return res.status(401).json({ error: "Missing token" });\n  try {\n    req.userId = jwt.verify(token, process.env.JWT_SECRET).sub;\n    next();\n  } catch {\n    res.status(401).json({ error: "Invalid or expired token" });\n  }\n}\n\napp.get("/me", auth, async (req, res) => {\n  const { rows } = await pool.query("SELECT id, email FROM users WHERE id = $1", [req.userId]);\n  res.json(rows[0]);\n});'),
    ("note", "Security checklist", "Keep secrets in environment variables, always use HTTPS, add <code>helmet</code> and rate limiting (<code>express-rate-limit</code>) on login, return the same message for wrong email and wrong password, and never log passwords or tokens."),
    ("exercise", "Write an <code>authorizeOwner</code> middleware that loads a task and returns 403 unless <code>task.user_id</code> equals <code>req.userId</code>."),
    ("solution", "javascript", 'async function authorizeOwner(req, res, next) {\n  const { rows } = await pool.query("SELECT user_id FROM tasks WHERE id = $1", [req.params.id]);\n  if (!rows.length) return res.status(404).json({ error: "Not found" });\n  if (rows[0].user_id !== req.userId) return res.status(403).json({ error: "Forbidden" });\n  next();\n}'),
]
