"""Docker, Next.js, LangChain, Spring Boot tracks."""
from content_js_sql import M

META = [
    M("docker-introduction", "docker", "Containers and Docker Basics", 14, "Beginner", "What containers are, images vs containers and the core commands.", ["Explain image vs container", "Run and stop containers", "Map ports and mount volumes"]),
    M("docker-dockerfile", "docker", "Writing a Dockerfile", 16, "Intermediate", "Build your own image, use layer caching and keep images small.", ["Write a Dockerfile", "Use .dockerignore", "Use multi-stage builds"]),
    M("docker-compose", "docker", "Docker Compose", 15, "Intermediate", "Run an app with a database and other services from one file.", ["Write docker-compose.yml", "Connect services by name", "Persist data with volumes"]),
    M("nextjs-introduction", "nextjs", "Introduction and Project Setup", 12, "Beginner", "Create a Next.js app and understand the app directory.", ["Create a Next.js project", "Explain file-based routing", "Add layouts"]),
    M("nextjs-routing-layouts", "nextjs", "Routing, Layouts and Navigation", 15, "Beginner", "Dynamic routes, nested layouts, Link and loading states.", ["Create dynamic routes", "Nest layouts", "Use loading and not-found files"]),
    M("nextjs-server-components", "nextjs", "Server and Client Components", 17, "Intermediate", "Fetch data on the server and add interactivity only where needed.", ["Know the server/client split", "Fetch data in async components", "Use 'use client' correctly"]),
    M("nextjs-api-forms", "nextjs", "Route Handlers and Server Actions", 16, "Intermediate", "Build API endpoints and handle forms without writing fetch code.", ["Write a route handler", "Use a server action", "Revalidate cached data"]),
    M("nextjs-deploy-seo", "nextjs", "SEO, Images and Deployment", 14, "Intermediate", "Metadata, next/image, environment variables and deploying.", ["Set metadata", "Optimize images", "Deploy to Vercel or Docker"]),
    M("langchain-introduction", "langchain", "LLM Apps and LangChain Basics", 14, "Beginner", "How LLM apps work, and calling a chat model through LangChain.", ["Explain messages and tokens", "Call a chat model", "Stream output"]),
    M("langchain-prompts-chains", "langchain", "Prompts, Parsers and Chains", 16, "Beginner", "Compose prompts, models and parsers with the pipe operator.", ["Write prompt templates", "Get structured output", "Build a chain with LCEL"]),
    M("langchain-rag", "langchain", "Retrieval-Augmented Generation", 20, "Intermediate", "Load documents, split, embed, store in a vector database and answer with sources.", ["Build a RAG pipeline", "Choose chunk sizes", "Cite sources"]),
    M("langchain-agents-tools", "langchain", "Tools and Agents", 17, "Intermediate", "Give models functions to call and let them decide when.", ["Define a tool", "Bind tools to a model", "Run an agent loop safely"]),
    M("langchain-evaluation-production", "langchain", "Evaluation and Production", 16, "Advanced", "Test LLM apps, trace them, control cost and guard against failures.", ["Evaluate answers", "Trace with LangSmith", "Reduce cost and latency"]),
    M("spring-introduction", "spring", "Spring Boot Setup and First App", 13, "Beginner", "Generate a project and run a first REST endpoint.", ["Create a project with Initializr", "Explain auto-configuration", "Return JSON"]),
    M("spring-rest-controllers", "spring", "REST Controllers and Validation", 17, "Beginner", "Handle GET/POST/PUT/DELETE with DTOs, validation and error handling.", ["Write a REST controller", "Validate input", "Handle exceptions globally"]),
    M("spring-dependency-injection", "spring", "Dependency Injection and Layers", 14, "Intermediate", "Beans, services, repositories and constructor injection.", ["Explain inversion of control", "Use @Service and constructor injection", "Structure controller/service/repository"]),
    M("spring-data-jpa", "spring", "Spring Data JPA", 18, "Intermediate", "Entities, repositories, relationships and derived queries.", ["Map an entity", "Use JpaRepository", "Define relationships"]),
    M("spring-testing-config", "spring", "Configuration, Profiles and Testing", 15, "Advanced", "application.yml, profiles, and unit and integration tests.", ["Externalize configuration", "Use profiles", "Write MockMvc tests"]),
]

CONTENT = {}

# ---------------- Docker ----------------
CONTENT["docker-introduction"] = [
    ("p", "\"It works on my machine\" is one of software's oldest problems. <strong>Docker</strong> solves it by packaging an application together with everything it needs (runtime, libraries, system tools, configuration) into a standard unit called a <strong>container</strong>. That container runs the same way on your laptop, a teammate's machine and a production server."),
    ("h2", "Images and containers"),
    ("ul", [
        "An <strong>image</strong> is a read-only template: the packaged filesystem and default command. Think of it as a recipe or a class.",
        "A <strong>container</strong> is a running instance of an image, an isolated process. Think of it as a dish or an object. You can start many containers from one image.",
        "A <strong>registry</strong> (Docker Hub, GitHub Container Registry) stores and shares images.",
    ]),
    ("p", "Containers differ from virtual machines: they share the host's kernel rather than booting a full operating system, so they start in about a second and use far less memory."),
    ("h2", "Your first container"),
    ("code", "bash", "docker --version\ndocker run hello-world"),
    ("p", "Docker looked for the image locally, pulled it from Docker Hub because it was missing, created a container and ran it. Now something more useful, a web server:"),
    ("code", "bash", "docker run -d --name web -p 8080:80 nginx"),
    ("ul", [
        "<code>-d</code>: run in the background (detached).",
        "<code>--name web</code>: give the container a friendly name.",
        "<code>-p 8080:80</code>: map port 8080 on your machine to port 80 in the container. Visit <code>http://localhost:8080</code>.",
    ]),
    ("h2", "Essential commands"),
    ("code", "bash", "docker ps                 # running containers (add -a for all)\ndocker logs -f web        # follow logs\ndocker exec -it web sh    # open a shell inside\ndocker stop web           # stop\ndocker start web          # start again\ndocker rm web             # delete the container\ndocker images             # local images\ndocker rmi nginx          # delete an image\ndocker system prune       # clean unused data"),
    ("h2", "Environment variables and volumes"),
    ("p", "A container's filesystem is <strong>temporary</strong>: delete the container and its data is gone. To keep data, mount a <em>volume</em> or a folder from your machine. Pass configuration through environment variables."),
    ("code", "bash", 'docker run -d --name db \\\n  -e POSTGRES_PASSWORD=secret \\\n  -v pgdata:/var/lib/postgresql/data \\\n  -p 5432:5432 postgres:16\n\n# mount the current folder into a container (handy in development)\ndocker run --rm -it -v "$PWD":/app -w /app python:3.12 python script.py'),
    ("note", "Tags", "<code>postgres:16</code> pins a version. Without a tag you get <code>latest</code>, which changes over time and can break your builds. Always pin versions for anything that matters."),
    ("exercise", "Run a Redis container in the background on port 6379, connect to it with <code>docker exec</code> and <code>redis-cli</code>, set a key, then stop and remove the container."),
    ("solution", "bash", 'docker run -d --name cache -p 6379:6379 redis:7\ndocker exec -it cache redis-cli\n# 127.0.0.1:6379> SET greeting hello\n# 127.0.0.1:6379> GET greeting\ndocker stop cache && docker rm cache'),
]

CONTENT["docker-dockerfile"] = [
    ("p", "A <strong>Dockerfile</strong> is a text file of instructions for building your own image. Each instruction adds a <em>layer</em>. Docker caches layers, so ordering the file well makes rebuilds very fast."),
    ("h2", "A Python example"),
    ("code", "dockerfile", 'FROM python:3.12-slim\n\nWORKDIR /app\n\n# copy dependency list first so this layer is cached\nCOPY requirements.txt .\nRUN pip install --no-cache-dir -r requirements.txt\n\n# then the source code (changes often)\nCOPY . .\n\nEXPOSE 8000\nCMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]'),
    ("code", "bash", "docker build -t my-api:1.0 .\ndocker run -d -p 8000:8000 my-api:1.0"),
    ("h2", "Instructions"),
    ("ul", [
        "<code>FROM</code>: the base image to start from.",
        "<code>WORKDIR</code>: set the working directory (creates it if needed).",
        "<code>COPY</code>: copy files from your project into the image.",
        "<code>RUN</code>: execute a command at <em>build</em> time, such as installing packages.",
        "<code>ENV</code>: set an environment variable.",
        "<code>EXPOSE</code>: document the port the app listens on (does not publish it).",
        "<code>CMD</code> / <code>ENTRYPOINT</code>: the command that runs when the <em>container starts</em>.",
    ]),
    ("h2", "Why order matters"),
    ("p", "When you change a file, Docker rebuilds from the first changed layer onward. Copying <code>requirements.txt</code> and installing dependencies <em>before</em> copying the rest of your code means everyday code edits reuse the cached dependency layer, cutting build time from minutes to seconds."),
    ("h2", ".dockerignore"),
    ("p", "Keep junk and secrets out of the build context:"),
    ("code", "text", ".git\n.venv\n__pycache__\nnode_modules\n.env\n*.log"),
    ("h2", "Multi-stage builds"),
    ("p", "Build tools such as compilers are needed to <em>build</em> the app but not to <em>run</em> it. A multi-stage build compiles in one stage and copies only the result into a small final image."),
    ("code", "dockerfile", '# Stage 1: build\nFROM node:20 AS build\nWORKDIR /app\nCOPY package*.json ./\nRUN npm ci\nCOPY . .\nRUN npm run build\n\n# Stage 2: serve\nFROM nginx:alpine\nCOPY --from=build /app/dist /usr/share/nginx/html\nEXPOSE 80'),
    ("h2", "Good habits"),
    ("ul", [
        "Use small base images (<code>-slim</code>, <code>alpine</code>) and pin versions.",
        "Run as a non-root user: <code>RUN useradd -m app</code> then <code>USER app</code>.",
        "Never bake secrets into the image; pass them at runtime.",
        "One main process per container.",
    ]),
    ("note", "Shell form vs exec form", "Prefer <code>CMD [\"python\", \"app.py\"]</code> (exec form). It receives stop signals correctly, so <code>docker stop</code> shuts the app down cleanly."),
    ("exercise", "Write a Dockerfile for a Node.js app that installs dependencies with <code>npm ci</code>, copies the code and starts <code>node server.js</code> on port 3000, using a cache-friendly order."),
    ("solution", "dockerfile", 'FROM node:20-alpine\nWORKDIR /app\nCOPY package*.json ./\nRUN npm ci --omit=dev\nCOPY . .\nEXPOSE 3000\nUSER node\nCMD ["node", "server.js"]'),
]

CONTENT["docker-compose"] = [
    ("p", "Real applications are several services: a web app, a database, a cache. Starting each with a long <code>docker run</code> command is tedious and error-prone. <strong>Docker Compose</strong> describes the whole stack in one YAML file and starts everything with a single command."),
    ("h2", "A complete example"),
    ("code", "yaml", 'services:\n  api:\n    build: .\n    ports:\n      - "8000:8000"\n    environment:\n      DATABASE_URL: postgresql://app:secret@db:5432/appdb\n      REDIS_URL: redis://cache:6379\n    depends_on:\n      db:\n        condition: service_healthy\n      cache:\n        condition: service_started\n\n  db:\n    image: postgres:16\n    environment:\n      POSTGRES_USER: app\n      POSTGRES_PASSWORD: secret\n      POSTGRES_DB: appdb\n    volumes:\n      - pgdata:/var/lib/postgresql/data\n    healthcheck:\n      test: ["CMD-SHELL", "pg_isready -U app -d appdb"]\n      interval: 5s\n      retries: 5\n\n  cache:\n    image: redis:7\n\nvolumes:\n  pgdata:'),
    ("h2", "Running it"),
    ("code", "bash", "docker compose up -d          # build if needed and start everything\ndocker compose ps\ndocker compose logs -f api\ndocker compose exec db psql -U app appdb\ndocker compose down             # stop and remove containers\ndocker compose down -v          # ...and delete volumes (data!)"),
    ("h2", "Networking by service name"),
    ("p", "Compose puts all services on a private network where each is reachable by its <strong>service name</strong>. That is why the URL above uses <code>db</code> and <code>cache</code> as hostnames rather than <code>localhost</code>. Inside a container, <code>localhost</code> means the container itself."),
    ("h2", "Volumes and data"),
    ("p", "A named volume (<code>pgdata</code>) keeps the database files across restarts and rebuilds. Without it, your data disappears whenever the container is recreated."),
    ("h2", "Development conveniences"),
    ("code", "yaml", "  api:\n    build: .\n    volumes:\n      - ./:/app                 # live-reload: edit code on your machine\n    command: uvicorn main:app --reload --host 0.0.0.0\n    env_file:\n      - .env                    # keep settings out of the YAML"),
    ("h2", "Health checks and start order"),
    ("p", "<code>depends_on</code> alone only waits until the container <em>starts</em>, not until the database is ready to accept connections. Combining it with a <code>healthcheck</code>, as above, makes the app wait for a truly ready database."),
    ("note", "Compose is not Kubernetes", "Compose is perfect for development and small single-server deployments. For large multi-server production systems teams typically move to an orchestrator such as Kubernetes."),
    ("exercise", "Write a compose file with a <code>web</code> service using the <code>nginx</code> image on port 8080, and a <code>redis</code> service. Bring it up and check both are running."),
    ("solution", "yaml", 'services:\n  web:\n    image: nginx:alpine\n    ports:\n      - "8080:80"\n  redis:\n    image: redis:7\n# docker compose up -d && docker compose ps'),
]

# ---------------- Next.js ----------------
CONTENT["nextjs-introduction"] = [
    ("p", "<strong>Next.js</strong> is a full-stack framework built on React. React alone only handles the UI in the browser; Next.js adds the rest of what real sites need: routing, server-side rendering, data fetching, API endpoints, image optimization and easy deployment. It is widely used for marketing sites, dashboards and SaaS products."),
    ("h2", "Why not just React?"),
    ("ul", [
        "<strong>Routing</strong> comes from your folder structure, with no router library to configure.",
        "<strong>Server rendering</strong> sends ready-made HTML, which loads faster and is easier for search engines to read.",
        "<strong>Backend code</strong> lives in the same project: fetch from a database directly in a component, or write API endpoints.",
    ]),
    ("h2", "Create a project"),
    ("code", "bash", "npx create-next-app@latest my-site\ncd my-site\nnpm run dev"),
    ("p", "Accept the defaults (TypeScript, ESLint, the App Router). Visit <code>http://localhost:3000</code>."),
    ("h2", "The app directory"),
    ("code", "text", "app/\n  layout.tsx        # shared wrapper for every page (html, body, nav)\n  page.tsx          # the home page at /\n  about/\n    page.tsx        # /about\n  blog/\n    page.tsx        # /blog\n    [slug]/\n      page.tsx      # /blog/anything\npublic/             # static files served at the root\nnext.config.ts"),
    ("p", "A folder becomes a URL segment, and a <code>page.tsx</code> inside makes it reachable. That is <strong>file-based routing</strong>."),
    ("code", "javascript", '// app/page.tsx\nexport default function Home() {\n  return (\n    <main>\n      <h1>Welcome to my site</h1>\n      <p>Built with Next.js</p>\n    </main>\n  );\n}\n\n// app/about/page.tsx\nexport default function About() {\n  return <h1>About</h1>;\n}'),
    ("h2", "The root layout"),
    ("code", "javascript", '// app/layout.tsx\nimport Link from "next/link";\nimport "./globals.css";\n\nexport const metadata = { title: "My Site", description: "A Next.js site" };\n\nexport default function RootLayout({ children }: { children: React.ReactNode }) {\n  return (\n    <html lang="en">\n      <body>\n        <nav>\n          <Link href="/">Home</Link> <Link href="/about">About</Link>\n        </nav>\n        {children}\n      </body>\n    </html>\n  );\n}'),
    ("p", "The layout wraps every page and is preserved when you navigate, so it does not re-render. Use <code>&lt;Link&gt;</code> for internal links: it prefetches pages and navigates without a full reload."),
    ("note", "Prerequisites", "You should know React (components, props, state). Take the React course first if not."),
    ("exercise", "Add a <code>/contact</code> page with a heading and your email address, and add a link to it in the navigation."),
    ("solution", "javascript", '// app/contact/page.tsx\nexport default function Contact() {\n  return (\n    <main>\n      <h1>Contact</h1>\n      <p>hello@example.com</p>\n    </main>\n  );\n}\n// in layout.tsx nav: <Link href="/contact">Contact</Link>'),
]

CONTENT["nextjs-routing-layouts"] = [
    ("p", "The App Router gives you a small set of special file names. Learn them and you can build almost any navigation structure."),
    ("h2", "Dynamic routes"),
    ("p", "Wrap a folder name in square brackets to capture that part of the URL as a parameter."),
    ("code", "javascript", '// app/blog/[slug]/page.tsx  ->  /blog/hello-world\nexport default async function Post({ params }: { params: Promise<{ slug: string }> }) {\n  const { slug } = await params;\n  return <h1>Post: {slug}</h1>;\n}'),
    ("p", "<code>[...slug]</code> catches any number of segments; <code>[[...slug]]</code> also matches the bare path. In recent Next.js versions <code>params</code> is a promise, so <code>await</code> it."),
    ("h2", "Nested layouts"),
    ("p", "A <code>layout.tsx</code> in any folder wraps all pages beneath it, and layouts nest. A dashboard can have its own sidebar without affecting the marketing pages."),
    ("code", "javascript", '// app/dashboard/layout.tsx\nexport default function DashboardLayout({ children }: { children: React.ReactNode }) {\n  return (\n    <div style={{ display: "flex" }}>\n      <aside>Sidebar</aside>\n      <section>{children}</section>\n    </div>\n  );\n}'),
    ("h2", "Route groups"),
    ("p", "Folders in parentheses organize code without adding to the URL: <code>app/(marketing)/about/page.tsx</code> is still <code>/about</code>. They also let different groups use different layouts."),
    ("h2", "Special files"),
    ("ul", [
        "<code>loading.tsx</code>: shown instantly while a page's data loads (uses React Suspense).",
        "<code>error.tsx</code>: shown when something inside throws. It must be a client component.",
        "<code>not-found.tsx</code>: shown for a missing page; call <code>notFound()</code> to trigger it.",
        "<code>route.ts</code>: an API endpoint instead of a page.",
    ]),
    ("code", "javascript", '// app/blog/[slug]/loading.tsx\nexport default function Loading() {\n  return <p>Loading post...</p>;\n}\n\n// app/blog/[slug]/page.tsx\nimport { notFound } from "next/navigation";\n\nexport default async function Post({ params }: { params: Promise<{ slug: string }> }) {\n  const { slug } = await params;\n  const post = await getPost(slug);      // your data function\n  if (!post) notFound();\n  return <article><h1>{post.title}</h1></article>;\n}'),
    ("h2", "Navigation"),
    ("code", "javascript", '"use client";\nimport Link from "next/link";\nimport { usePathname, useRouter } from "next/navigation";\n\nexport function NavLink({ href, children }: { href: string; children: React.ReactNode }) {\n  const active = usePathname() === href;\n  return <Link href={href} className={active ? "active" : ""}>{children}</Link>;\n}\n\nexport function BackButton() {\n  const router = useRouter();\n  return <button onClick={() => router.back()}>Back</button>;\n}'),
    ("note", "Tip", "A folder without a <code>page.tsx</code> is not a route. You can keep components or helpers next to the pages that use them without exposing them as URLs."),
    ("exercise", "Create <code>/products</code> (a list) and <code>/products/[id]</code> (a detail page that shows the id), plus a <code>loading.tsx</code> for the detail page."),
    ("solution", "javascript", '// app/products/page.tsx\nimport Link from "next/link";\nexport default function Products() {\n  return <ul>{[1, 2, 3].map((id) => <li key={id}><Link href={`/products/${id}`}>Product {id}</Link></li>)}</ul>;\n}\n// app/products/[id]/page.tsx\nexport default async function Product({ params }: { params: Promise<{ id: string }> }) {\n  const { id } = await params;\n  return <h1>Product {id}</h1>;\n}'),
]

CONTENT["nextjs-server-components"] = [
    ("p", "In the App Router, components are <strong>Server Components</strong> by default. They run only on the server, ship no JavaScript to the browser, and can talk directly to databases and secret keys. When you need interactivity, you opt in to a <strong>Client Component</strong> with a directive."),
    ("h2", "Fetching data on the server"),
    ("p", "A server component can be <code>async</code>, so you fetch data right in the component with <code>await</code>. No <code>useEffect</code>, no loading state boilerplate, no API round trip from the browser."),
    ("code", "javascript", '// app/users/page.tsx  (a server component)\ninterface User { id: number; name: string; }\n\nexport default async function Users() {\n  const res = await fetch("https://jsonplaceholder.typicode.com/users");\n  const users: User[] = await res.json();\n\n  return (\n    <ul>\n      {users.map((u) => <li key={u.id}>{u.name}</li>)}\n    </ul>\n  );\n}'),
    ("p", "You can also query a database directly: <code>const posts = await db.post.findMany()</code>. That code and any secrets never reach the browser."),
    ("h2", "Client components"),
    ("p", "Add <code>\"use client\"</code> at the top of a file when you need state, effects, event handlers or browser APIs."),
    ("code", "javascript", '// app/components/LikeButton.tsx\n"use client";\nimport { useState } from "react";\n\nexport default function LikeButton() {\n  const [likes, setLikes] = useState(0);\n  return <button onClick={() => setLikes(likes + 1)}>Like ({likes})</button>;\n}'),
    ("h2", "Composing them"),
    ("p", "Server components can import and render client components, and pass data down as props. The rule of thumb: <strong>keep components on the server, and push the <code>\"use client\"</code> boundary down to the smallest interactive leaf</strong>. That keeps bundles small."),
    ("code", "javascript", 'import LikeButton from "../components/LikeButton";\n\nexport default async function Post({ params }: { params: Promise<{ id: string }> }) {\n  const { id } = await params;\n  const post = await getPost(id);           // runs on the server\n  return (\n    <article>\n      <h1>{post.title}</h1>\n      <p>{post.body}</p>\n      <LikeButton />                        {/* interactive island */}\n    </article>\n  );\n}'),
    ("h2", "Caching and freshness"),
    ("p", "Next.js can cache fetched data and rendered pages. You control how fresh they are:"),
    ("code", "javascript", '// always fresh\nawait fetch(url, { cache: "no-store" });\n\n// refresh at most every 60 seconds\nawait fetch(url, { next: { revalidate: 60 } });\n\n// page-level setting\nexport const revalidate = 3600;'),
    ("p", "Pages that use no request-specific data can be generated at build time (<em>static</em>); pages using cookies, headers or <code>no-store</code> render per request (<em>dynamic</em>). Caching defaults have changed between versions, so check the docs for the version you use."),
    ("note", "Error you will meet", "Using <code>useState</code> or <code>onClick</code> in a server component fails with a message telling you to add <code>\"use client\"</code>. That is the signal to extract that interactive part into its own client component."),
    ("exercise", "Create a page that fetches five posts from <code>jsonplaceholder.typicode.com/posts?_limit=5</code> on the server and renders them, with a separate client component that toggles showing each post body."),
    ("solution", "javascript", '// components/Expandable.tsx\n"use client";\nimport { useState } from "react";\nexport default function Expandable({ title, body }: { title: string; body: string }) {\n  const [open, setOpen] = useState(false);\n  return (\n    <div>\n      <h3 onClick={() => setOpen(!open)} style={{ cursor: "pointer" }}>{title}</h3>\n      {open && <p>{body}</p>}\n    </div>\n  );\n}\n// app/posts/page.tsx (server)\nexport default async function Posts() {\n  const posts = await (await fetch("https://jsonplaceholder.typicode.com/posts?_limit=5")).json();\n  return <>{posts.map((p: any) => <Expandable key={p.id} title={p.title} body={p.body} />)}</>;\n}'),
]

CONTENT["nextjs-api-forms"] = [
    ("p", "Next.js can be your backend too. Two tools cover most needs: <strong>route handlers</strong> for classic HTTP endpoints, and <strong>server actions</strong> for form submissions and mutations from your own UI."),
    ("h2", "Route handlers"),
    ("p", "A <code>route.ts</code> file exports functions named after HTTP methods."),
    ("code", "javascript", '// app/api/tasks/route.ts\nimport { NextResponse } from "next/server";\n\nconst tasks = [{ id: 1, title: "Learn Next.js" }];\n\nexport async function GET() {\n  return NextResponse.json(tasks);\n}\n\nexport async function POST(request: Request) {\n  const body = await request.json();\n  if (!body.title) {\n    return NextResponse.json({ error: "title required" }, { status: 400 });\n  }\n  const task = { id: tasks.length + 1, title: String(body.title) };\n  tasks.push(task);\n  return NextResponse.json(task, { status: 201 });\n}'),
    ("p", "Dynamic segments work here too: <code>app/api/tasks/[id]/route.ts</code>. Use route handlers when other clients (a mobile app, a webhook) need an HTTP API."),
    ("h2", "Server actions"),
    ("p", "A server action is an async function marked <code>\"use server\"</code> that runs on the server but can be called straight from a form. No manual <code>fetch</code>, no API route, and forms work even before JavaScript loads."),
    ("code", "javascript", '// app/tasks/actions.ts\n"use server";\nimport { revalidatePath } from "next/cache";\n\nexport async function addTask(formData: FormData) {\n  const title = String(formData.get("title") ?? "").trim();\n  if (!title) return;\n  await db.task.create({ data: { title } });   // your database call\n  revalidatePath("/tasks");                     // refresh the list\n}\n\n// app/tasks/page.tsx\nimport { addTask } from "./actions";\n\nexport default async function Tasks() {\n  const tasks = await db.task.findMany();\n  return (\n    <>\n      <form action={addTask}>\n        <input name="title" placeholder="New task" required />\n        <button type="submit">Add</button>\n      </form>\n      <ul>{tasks.map((t) => <li key={t.id}>{t.title}</li>)}</ul>\n    </>\n  );\n}'),
    ("h2", "Pending and error states"),
    ("code", "javascript", '"use client";\nimport { useFormStatus } from "react-dom";\n\nexport function SubmitButton() {\n  const { pending } = useFormStatus();\n  return <button disabled={pending}>{pending ? "Saving..." : "Add"}</button>;\n}'),
    ("note", "Security", "Server actions are public HTTP endpoints under the hood. Always validate input (for example with zod) and check that the current user is allowed to perform the action. Never trust that only your form calls it."),
    ("h2", "Middleware"),
    ("p", "A <code>middleware.ts</code> file at the project root runs before requests complete, which is ideal for redirects and auth checks."),
    ("code", "javascript", 'import { NextResponse } from "next/server";\nimport type { NextRequest } from "next/server";\n\nexport function middleware(req: NextRequest) {\n  const loggedIn = req.cookies.has("session");\n  if (!loggedIn && req.nextUrl.pathname.startsWith("/dashboard")) {\n    return NextResponse.redirect(new URL("/login", req.url));\n  }\n}\n\nexport const config = { matcher: ["/dashboard/:path*"] };'),
    ("exercise", "Add <code>GET /api/health</code> returning <code>{ status: \"ok\" }</code>, then a contact form using a server action that logs the submitted email on the server."),
    ("solution", "javascript", '// app/api/health/route.ts\nimport { NextResponse } from "next/server";\nexport async function GET() { return NextResponse.json({ status: "ok" }); }\n\n// app/contact/actions.ts\n"use server";\nexport async function submit(formData: FormData) {\n  console.log("email:", formData.get("email"));\n}'),
]

CONTENT["nextjs-deploy-seo"] = [
    ("p", "A good site is discoverable, fast and live on the internet. Next.js includes tools for all three."),
    ("h2", "Metadata for SEO"),
    ("p", "Export a <code>metadata</code> object (or an async <code>generateMetadata</code> for dynamic pages). Next.js renders the right <code>&lt;title&gt;</code> and meta tags into the HTML that search engines read."),
    ("code", "javascript", '// static\nexport const metadata = {\n  title: "Pricing | Acme",\n  description: "Simple pricing for teams of every size.",\n  openGraph: { title: "Pricing | Acme", images: ["/og.png"] },\n};\n\n// dynamic\nexport async function generateMetadata({ params }: { params: Promise<{ slug: string }> }) {\n  const { slug } = await params;\n  const post = await getPost(slug);\n  return { title: post.title, description: post.excerpt };\n}'),
    ("p", "Also add <code>app/sitemap.ts</code> and <code>app/robots.ts</code> to generate <code>sitemap.xml</code> and <code>robots.txt</code>."),
    ("h2", "Images"),
    ("p", "<code>next/image</code> resizes and compresses images, serves modern formats, lazy-loads them and reserves space to avoid layout shift. Always give it dimensions (or <code>fill</code>)."),
    ("code", "javascript", 'import Image from "next/image";\n\n<Image src="/hero.jpg" alt="Team at work" width={1200} height={600} priority />'),
    ("p", "Use <code>priority</code> for the main above-the-fold image only. For remote images, allow the host in <code>next.config.ts</code> under <code>images.remotePatterns</code>."),
    ("h2", "Fonts"),
    ("code", "javascript", 'import { Inter } from "next/font/google";\nconst inter = Inter({ subsets: ["latin"] });\n\n// <body className={inter.className}>'),
    ("p", "Fonts are downloaded at build time and self-hosted, avoiding extra requests and layout jumps."),
    ("h2", "Environment variables"),
    ("code", "bash", "# .env.local (never commit)\nDATABASE_URL=postgres://...\nNEXT_PUBLIC_SITE_URL=https://example.com"),
    ("p", "Variables are server-only by default. Only names starting with <code>NEXT_PUBLIC_</code> are exposed to the browser, so never put secrets in them."),
    ("h2", "Build and deploy"),
    ("code", "bash", "npm run build      # compile and show which routes are static or dynamic\nnpm start          # run the production server"),
    ("ul", [
        "<strong>Vercel</strong>: push to GitHub, import the repo, done. The easiest option.",
        "<strong>Docker</strong>: set <code>output: \"standalone\"</code> in the config and copy the standalone build into a small image.",
        "<strong>Static export</strong>: <code>output: \"export\"</code> produces plain files for any static host, if you use no server features.",
    ]),
    ("note", "Measure", "Run Lighthouse in Chrome DevTools and check Core Web Vitals (LCP, CLS, INP). They influence both user experience and search ranking."),
    ("exercise", "Add unique metadata to a blog post page using <code>generateMetadata</code>, and switch a plain <code>&lt;img&gt;</code> to <code>next/image</code>."),
    ("solution", "javascript", 'export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }) {\n  const { slug } = await params;\n  return { title: `Post: ${slug}`, description: `Read ${slug} on our blog.` };\n}\n// <Image src="/cover.jpg" alt="Cover" width={800} height={400} />'),
]

# ---------------- LangChain ----------------
CONTENT["langchain-introduction"] = [
    ("p", "A <strong>large language model</strong> (LLM) predicts text. Given a conversation, it produces a helpful continuation. On its own that is a chat box; wrapped in code that gives it data, tools and memory, it becomes an application. <strong>LangChain</strong> is a Python (and JavaScript) library that standardizes those building blocks so you can swap models and compose steps easily."),
    ("h2", "Core vocabulary"),
    ("ul", [
        "<strong>Messages</strong>: a conversation is a list of messages with roles: <code>system</code> (instructions), <code>human</code> (the user) and <code>ai</code> (the model).",
        "<strong>Tokens</strong>: models read and write chunks of text called tokens (roughly three quarters of a word). Pricing and limits are measured in tokens.",
        "<strong>Context window</strong>: the maximum tokens the model can consider at once (prompt plus answer).",
        "<strong>Temperature</strong>: randomness. 0 gives focused, repeatable answers; higher values are more creative.",
    ]),
    ("h2", "Setup"),
    ("code", "bash", 'python3 -m venv .venv && source .venv/bin/activate\npip install langchain langchain-openai\nexport OPENAI_API_KEY="sk-..."        # never hard-code or commit keys'),
    ("h2", "Call a chat model"),
    ("code", "python", 'from langchain_openai import ChatOpenAI\nfrom langchain_core.messages import SystemMessage, HumanMessage\n\nllm = ChatOpenAI(model="gpt-4o-mini", temperature=0)\n\nreply = llm.invoke([\n    SystemMessage(content="You are a concise assistant."),\n    HumanMessage(content="Explain a database index in one sentence."),\n])\nprint(reply.content)'),
    ("output", "A database index is a data structure that lets the database find rows quickly without scanning the whole table."),
    ("p", "LangChain provides a common interface: <code>invoke</code> for one call, <code>stream</code> for token-by-token output and <code>batch</code> for many inputs. To use another provider, change only the import and class, for example <code>ChatAnthropic</code> from <code>langchain_anthropic</code>."),
    ("h2", "Streaming"),
    ("code", "python", 'for chunk in llm.stream("Write a haiku about Python"):\n    print(chunk.content, end="", flush=True)'),
    ("p", "Streaming makes chat apps feel fast: users start reading immediately instead of waiting for the full answer."),
    ("h2", "Costs and safety basics"),
    ("ul", [
        "Log token usage (<code>reply.usage_metadata</code>) from day one.",
        "Set a maximum output length and timeouts.",
        "Treat model output as untrusted text: never run it as code or SQL without validation.",
    ]),
    ("note", "Non-determinism", "Even at temperature 0, outputs can vary slightly. Design your app and tests to tolerate wording differences."),
    ("exercise", "Ask the model to translate a sentence into Spanish with a system message that says to reply only with the translation, then print the token usage."),
    ("solution", "python", 'reply = llm.invoke([\n    SystemMessage(content="Translate to Spanish. Reply only with the translation."),\n    HumanMessage(content="Where is the train station?"),\n])\nprint(reply.content)\nprint(reply.usage_metadata)'),
]

CONTENT["langchain-prompts-chains"] = [
    ("p", "Hard-coding prompts as strings becomes messy fast. LangChain gives you reusable <strong>prompt templates</strong>, <strong>output parsers</strong> and a way to connect them into <strong>chains</strong> with the pipe operator, called LCEL (LangChain Expression Language)."),
    ("h2", "Prompt templates"),
    ("code", "python", 'from langchain_core.prompts import ChatPromptTemplate\n\nprompt = ChatPromptTemplate.from_messages([\n    ("system", "You are a helpful {role}. Answer in at most {words} words."),\n    ("human", "{question}"),\n])\n\nmessages = prompt.invoke({"role": "teacher", "words": 30, "question": "What is recursion?"})'),
    ("h2", "A first chain"),
    ("p", "The pipe <code>|</code> feeds the output of one step into the next: prompt, then model, then parser."),
    ("code", "python", 'from langchain_core.output_parsers import StrOutputParser\n\nchain = prompt | llm | StrOutputParser()\n\nprint(chain.invoke({"role": "teacher", "words": 30, "question": "What is recursion?"}))'),
    ("p", "<code>StrOutputParser</code> turns the model\'s message object into a plain string. Every chain built this way automatically supports <code>invoke</code>, <code>stream</code>, <code>batch</code> and async versions."),
    ("h2", "Structured output"),
    ("p", "Free text is hard for programs to use. Ask the model for data that matches a schema, and LangChain returns a validated object."),
    ("code", "python", 'from pydantic import BaseModel, Field\n\nclass Review(BaseModel):\n    sentiment: str = Field(description="positive, negative or neutral")\n    score: int = Field(ge=1, le=5)\n    summary: str\n\nstructured = llm.with_structured_output(Review)\nresult = structured.invoke("The battery is great but the screen scratches easily.")\nprint(result.sentiment, result.score)\nprint(result.model_dump())'),
    ("output", "neutral 3\n{'sentiment': 'neutral', 'score': 3, 'summary': 'Great battery but a screen that scratches easily.'}"),
    ("h2", "Composing bigger chains"),
    ("code", "python", 'from langchain_core.runnables import RunnablePassthrough, RunnableParallel\n\nsummarize = ChatPromptTemplate.from_template("Summarize in one line: {text}") | llm | StrOutputParser()\ntranslate = ChatPromptTemplate.from_template("Translate to French: {text}") | llm | StrOutputParser()\n\nboth = RunnableParallel(summary=summarize, french=translate)\nprint(both.invoke({"text": "LangChain helps build LLM applications."}))'),
    ("p", "<code>RunnableParallel</code> runs branches at the same time. Other useful runnables: <code>RunnableLambda</code> to wrap your own function, and <code>RunnablePassthrough</code> to carry inputs alongside results."),
    ("h2", "Prompt-writing tips"),
    ("ul", [
        "Be specific about role, task, format and length.",
        "Give one or two examples (few-shot) when the format matters.",
        "Put untrusted user text in its own clearly labeled section to reduce prompt-injection risk.",
        "Version and test your prompts like code.",
    ]),
    ("note", "Debugging", "Set <code>set_debug(True)</code> from <code>langchain.globals</code> to print every step's inputs and outputs, or use tracing (covered in a later lesson)."),
    ("exercise", "Build a chain that takes a job description and returns a structured object with <code>title</code>, <code>skills</code> (list of strings) and <code>seniority</code>."),
    ("solution", "python", 'class Job(BaseModel):\n    title: str\n    skills: list[str]\n    seniority: str\n\nchain = ChatPromptTemplate.from_template("Extract job info:\\n{jd}") | llm.with_structured_output(Job)\nprint(chain.invoke({"jd": "Senior Python engineer with SQL and Docker experience."}))'),
]

CONTENT["langchain-rag"] = [
    ("p", "A model only knows what it was trained on, and it can confidently make things up. <strong>Retrieval-Augmented Generation (RAG)</strong> fixes both problems: before answering, your app <em>looks up</em> relevant passages from your own documents and gives them to the model as context. Answers become grounded in your data, and you can show sources."),
    ("h2", "The pipeline"),
    ("ul", [
        "<strong>Load</strong> documents (PDFs, web pages, markdown).",
        "<strong>Split</strong> them into chunks small enough to be focused.",
        "<strong>Embed</strong> each chunk: convert text into a vector (list of numbers) so that similar meanings are close together.",
        "<strong>Store</strong> the vectors in a vector database.",
        "At question time: <strong>embed the question</strong>, <strong>retrieve</strong> the nearest chunks, and <strong>generate</strong> an answer from them.",
    ]),
    ("h2", "Indexing"),
    ("code", "bash", "pip install langchain-community langchain-text-splitters langchain-chroma langchain-openai pypdf"),
    ("code", "python", 'from langchain_community.document_loaders import PyPDFLoader\nfrom langchain_text_splitters import RecursiveCharacterTextSplitter\nfrom langchain_openai import OpenAIEmbeddings\nfrom langchain_chroma import Chroma\n\ndocs = PyPDFLoader("handbook.pdf").load()\n\nsplitter = RecursiveCharacterTextSplitter(chunk_size=800, chunk_overlap=120)\nchunks = splitter.split_documents(docs)\n\nvectorstore = Chroma.from_documents(\n    chunks,\n    OpenAIEmbeddings(model="text-embedding-3-small"),\n    persist_directory="./chroma",\n)'),
    ("p", "<code>chunk_overlap</code> repeats a little text between neighboring chunks so a sentence cut at a boundary is not lost. Chunk size is a key tuning knob: too large and results get noisy, too small and they lose context. Start around 500 to 1000 characters and measure."),
    ("h2", "Retrieval and answering"),
    ("code", "python", 'from langchain_core.prompts import ChatPromptTemplate\nfrom langchain_core.output_parsers import StrOutputParser\nfrom langchain_core.runnables import RunnablePassthrough\n\nretriever = vectorstore.as_retriever(search_kwargs={"k": 4})\n\nprompt = ChatPromptTemplate.from_template(\n    "Answer using ONLY the context. If the answer is not in the context, say you don\'t know.\\n\\n"\n    "Context:\\n{context}\\n\\nQuestion: {question}"\n)\n\ndef format_docs(docs):\n    return "\\n\\n".join(f"[{d.metadata.get(\'page\')}] {d.page_content}" for d in docs)\n\nrag = (\n    {"context": retriever | format_docs, "question": RunnablePassthrough()}\n    | prompt | llm | StrOutputParser()\n)\n\nprint(rag.invoke("How many vacation days do new employees get?"))'),
    ("h2", "Returning sources"),
    ("code", "python", 'docs = retriever.invoke("vacation days")\nfor d in docs:\n    print(d.metadata["source"], "page", d.metadata.get("page"))'),
    ("p", "Showing where each answer came from builds trust and lets users verify it."),
    ("h2", "Why RAG systems fail"),
    ("ul", [
        "<strong>Bad retrieval</strong>: the right chunk is not in the top k. Improve chunking, add metadata filters, try hybrid (keyword + vector) search or a reranker.",
        "<strong>Bad generation</strong>: the model ignores context or invents. Tighten the prompt and require citations.",
        "<strong>Stale data</strong>: re-index when documents change.",
        "<strong>Missing evaluation</strong>: without a test set of questions you cannot tell if a change helped.",
    ]),
    ("note", "Security", "Documents can contain instructions aimed at the model (prompt injection). Treat retrieved text as data, restrict what tools the model may call, and enforce document-level permissions at retrieval time."),
    ("exercise", "Index a folder of markdown files, ask three questions about them, and print the source file names for each answer. Try chunk sizes 300 and 1000 and compare answers."),
    ("solution", "python", 'from langchain_community.document_loaders import DirectoryLoader, TextLoader\n\ndocs = DirectoryLoader("notes/", glob="**/*.md", loader_cls=TextLoader).load()\nchunks = RecursiveCharacterTextSplitter(chunk_size=300, chunk_overlap=50).split_documents(docs)\nvs = Chroma.from_documents(chunks, OpenAIEmbeddings(model="text-embedding-3-small"))\nfor q in ["What is our refund policy?", "Who owns onboarding?"]:\n    hits = vs.as_retriever(search_kwargs={"k": 3}).invoke(q)\n    print(q, [h.metadata["source"] for h in hits])'),
]

CONTENT["langchain-agents-tools"] = [
    ("p", "A chain follows steps <em>you</em> decided in advance. An <strong>agent</strong> lets the model decide which steps to take, calling <strong>tools</strong> (ordinary functions) when it needs facts or actions. Tools are how a model gets fresh data, does exact math and changes the world."),
    ("h2", "Defining a tool"),
    ("p", "Decorate a function with <code>@tool</code>. The name, type hints and <em>docstring</em> become the description the model reads, so write them clearly."),
    ("code", "python", 'from langchain_core.tools import tool\n\n@tool\ndef get_weather(city: str) -> str:\n    """Get the current weather for a city."""\n    data = {"Paris": "18C, cloudy", "Delhi": "34C, sunny"}\n    return data.get(city, "unknown city")\n\n@tool\ndef multiply(a: float, b: float) -> float:\n    """Multiply two numbers exactly."""\n    return a * b'),
    ("h2", "Tool calling by hand"),
    ("code", "python", 'llm_with_tools = llm.bind_tools([get_weather, multiply])\nresponse = llm_with_tools.invoke("What is the weather in Paris?")\nprint(response.tool_calls)'),
    ("output", "[{'name': 'get_weather', 'args': {'city': 'Paris'}, 'id': 'call_1'}]"),
    ("p", "The model does not run the function. It <em>requests</em> a call with arguments; your code executes it and sends the result back so the model can write the final answer. An <strong>agent loop</strong> automates that exchange."),
    ("h2", "A ready-made agent"),
    ("code", "python", 'from langgraph.prebuilt import create_react_agent\n\nagent = create_react_agent(llm, [get_weather, multiply])\n\nresult = agent.invoke({"messages": [("user", "What is the weather in Delhi, and what is 12.5 times 8?")]})\nprint(result["messages"][-1].content)'),
    ("p", "The agent calls both tools (possibly in parallel), reads their results and composes the answer. Use <code>agent.stream(...)</code> to watch each step."),
    ("h2", "Writing good tools"),
    ("ul", [
        "One clear purpose per tool, with a precise description of when to use it.",
        "Simple, typed arguments; return short, useful strings or JSON.",
        "Return errors as readable messages so the model can recover and retry.",
        "Keep the tool list small. Too many similar tools confuse the model.",
    ]),
    ("h2", "Safety for agents"),
    ("ul", [
        "<strong>Least privilege</strong>: give read-only tools where possible.",
        "<strong>Confirm dangerous actions</strong> (sending email, deleting, spending money) with a human before executing.",
        "<strong>Limit loops</strong>: cap the number of steps and total cost.",
        "<strong>Validate arguments</strong> exactly as you would any user input.",
        "<strong>Prompt injection</strong>: text from web pages or emails may try to instruct the agent. Never let untrusted content authorize actions.",
    ]),
    ("note", "Do you need an agent?", "If the steps are known in advance, a plain chain is cheaper, faster and more predictable. Reach for agents when the number and order of steps genuinely depends on the input."),
    ("exercise", "Write a <code>word_count(text: str)</code> tool and a <code>current_time()</code> tool, give them to an agent, and ask it how many words are in a sentence you supply."),
    ("solution", "python", 'from datetime import datetime\n\n@tool\ndef word_count(text: str) -> int:\n    """Count the words in a piece of text."""\n    return len(text.split())\n\n@tool\ndef current_time() -> str:\n    """Return the current UTC time in ISO format."""\n    return datetime.utcnow().isoformat()\n\nagent = create_react_agent(llm, [word_count, current_time])\nprint(agent.invoke({"messages": [("user", "How many words are in: the quick brown fox?")]})["messages"][-1].content)'),
]

CONTENT["langchain-evaluation-production"] = [
    ("p", "A demo that worked once is not a product. LLM apps are non-deterministic, depend on outside services and can fail in odd ways, so shipping one needs the same rigor as any system, plus a few new habits: evaluation, tracing, cost control and guardrails."),
    ("h2", "Build an evaluation set"),
    ("p", "Collect 30 to 100 realistic questions with the expected answer or key facts. Run your app against them after every change and compare. Without this, every prompt tweak is a guess."),
    ("code", "python", 'dataset = [\n    {"q": "How many vacation days do new hires get?", "must_include": ["15"]},\n    {"q": "Who approves expense reports?", "must_include": ["manager"]},\n]\n\ndef run_eval(chain):\n    passed = 0\n    for row in dataset:\n        answer = chain.invoke(row["q"]).lower()\n        ok = all(term in answer for term in row["must_include"])\n        passed += ok\n        print("PASS" if ok else "FAIL", row["q"])\n    print(f"{passed}/{len(dataset)} passed")'),
    ("h2", "LLM-as-judge"),
    ("p", "For open-ended answers, another model can grade against a rubric (correctness, groundedness in context, tone). Use a strong model for judging, clear criteria and spot-check its grades by hand."),
    ("code", "python", 'class Grade(BaseModel):\n    correct: bool\n    reason: str\n\njudge = ChatPromptTemplate.from_template(\n    "Question: {q}\\nReference: {ref}\\nAnswer: {ans}\\nIs the answer consistent with the reference?"\n) | llm.with_structured_output(Grade)'),
    ("h2", "Tracing"),
    ("p", "A trace records every step of a run: prompts, retrieved chunks, tool calls, latency, tokens and cost. LangSmith (or open-source alternatives such as Langfuse) capture them so you can see <em>why</em> an answer was wrong."),
    ("code", "bash", 'export LANGSMITH_TRACING=true\nexport LANGSMITH_API_KEY="..."'),
    ("h2", "Cost and latency"),
    ("ul", [
        "Use a smaller, cheaper model for easy steps (classification, extraction) and a stronger one only where needed.",
        "Trim context: retrieve fewer, better chunks instead of stuffing the window.",
        "Cache repeated requests, and use provider prompt caching for long shared prefixes.",
        "Stream responses and run independent steps in parallel.",
        "Set budgets and alerts on tokens per user and per day.",
    ]),
    ("h2", "Reliability"),
    ("code", "python", 'llm = ChatOpenAI(model="gpt-4o-mini", timeout=30, max_retries=3)\nfallback = ChatOpenAI(model="gpt-4o")\nsafe_llm = llm.with_fallbacks([fallback])'),
    ("h2", "Guardrails"),
    ("ul", [
        "Validate structured output with schemas and reject or retry bad results.",
        "Filter or refuse unsafe input and output; log refusals.",
        "Remove sensitive data (PII) before sending it to third-party models when policies require it.",
        "Keep a human in the loop for high-stakes decisions.",
    ]),
    ("note", "Ship gradually", "Release to a small group first, log real questions, add the failures to your evaluation set and repeat. Real usage teaches you more than any prompt brainstorm."),
    ("exercise", "Extend <code>run_eval</code> to record latency and token usage per question and print the average, then compare two prompts on the same dataset."),
    ("solution", "python", 'import time\n\ndef run_eval(chain):\n    times = []\n    for row in dataset:\n        t = time.perf_counter()\n        chain.invoke(row["q"])\n        times.append(time.perf_counter() - t)\n    print(f"avg latency: {sum(times) / len(times):.2f}s")\n# Run once per prompt variant and compare pass rate and latency.'),
]

# ---------------- Spring Boot ----------------
CONTENT["spring-introduction"] = [
    ("p", "<strong>Spring Boot</strong> is the most widely used way to build Java backends. The Spring Framework provides dependency injection and a huge ecosystem; Spring Boot adds <em>auto-configuration</em> and sensible defaults so you can get a production-ready service running in minutes instead of days of XML and setup."),
    ("h2", "Generate a project"),
    ("p", "Go to start.spring.io, choose Maven or Gradle, Java 17 or newer, and add these dependencies: <strong>Spring Web</strong>, <strong>Validation</strong>, <strong>Spring Data JPA</strong> and <strong>H2 Database</strong>. Download, unzip and open it in your IDE."),
    ("code", "bash", "cd demo\n./mvnw spring-boot:run        # Windows: mvnw.cmd spring-boot:run"),
    ("h2", "The entry point"),
    ("code", "java", 'package com.example.demo;\n\nimport org.springframework.boot.SpringApplication;\nimport org.springframework.boot.autoconfigure.SpringBootApplication;\n\n@SpringBootApplication\npublic class DemoApplication {\n    public static void main(String[] args) {\n        SpringApplication.run(DemoApplication.class, args);\n    }\n}'),
    ("p", "<code>@SpringBootApplication</code> combines three things: configuration, component scanning (find your classes in this package and below) and auto-configuration. Because Spring Web is on the classpath, Boot automatically starts an embedded Tomcat server on port 8080. No separate server installation is needed."),
    ("h2", "Your first endpoint"),
    ("code", "java", 'import org.springframework.web.bind.annotation.GetMapping;\nimport org.springframework.web.bind.annotation.RequestParam;\nimport org.springframework.web.bind.annotation.RestController;\n\n@RestController\npublic class HelloController {\n\n    @GetMapping("/hello")\n    public String hello(@RequestParam(defaultValue = "world") String name) {\n        return "Hello, " + name + "!";\n    }\n\n    @GetMapping("/health")\n    public java.util.Map<String, String> health() {\n        return java.util.Map.of("status", "ok");\n    }\n}'),
    ("code", "bash", "curl 'http://localhost:8080/hello?name=Ada'\ncurl http://localhost:8080/health"),
    ("output", 'Hello, Ada!\n{"status":"ok"}'),
    ("p", "Returning a <code>Map</code> or an object is converted to JSON automatically by Jackson."),
    ("h2", "Project layout"),
    ("ul", [
        "<code>src/main/java</code>: your code.",
        "<code>src/main/resources/application.properties</code> (or <code>.yml</code>): configuration such as the port.",
        "<code>src/test/java</code>: tests.",
        "<code>pom.xml</code> / <code>build.gradle</code>: dependencies and build.",
    ]),
    ("note", "Actuator", "Add the <code>spring-boot-starter-actuator</code> dependency to get <code>/actuator/health</code> and metrics endpoints for free, which is what monitoring tools and load balancers use."),
    ("exercise", "Add <code>GET /time</code> that returns the current server time as a string, and change the port to 9090 in <code>application.properties</code>."),
    ("solution", "java", '@GetMapping("/time")\npublic String time() {\n    return java.time.Instant.now().toString();\n}\n// application.properties:  server.port=9090'),
]

CONTENT["spring-rest-controllers"] = [
    ("p", "A REST controller maps HTTP requests to Java methods. Good APIs use <strong>DTOs</strong> (data transfer objects) as their public contract, validate input, and return meaningful status codes and errors."),
    ("h2", "A CRUD controller"),
    ("code", "java", 'import jakarta.validation.Valid;\nimport org.springframework.http.HttpStatus;\nimport org.springframework.http.ResponseEntity;\nimport org.springframework.web.bind.annotation.*;\nimport java.net.URI;\nimport java.util.List;\n\n@RestController\n@RequestMapping("/api/tasks")\npublic class TaskController {\n\n    private final TaskService service;\n\n    public TaskController(TaskService service) {\n        this.service = service;\n    }\n\n    @GetMapping\n    public List<TaskResponse> list() {\n        return service.findAll();\n    }\n\n    @GetMapping("/{id}")\n    public TaskResponse get(@PathVariable Long id) {\n        return service.findById(id);\n    }\n\n    @PostMapping\n    public ResponseEntity<TaskResponse> create(@Valid @RequestBody CreateTaskRequest req) {\n        TaskResponse created = service.create(req);\n        return ResponseEntity.created(URI.create("/api/tasks/" + created.id())).body(created);\n    }\n\n    @PutMapping("/{id}")\n    public TaskResponse update(@PathVariable Long id, @Valid @RequestBody CreateTaskRequest req) {\n        return service.update(id, req);\n    }\n\n    @DeleteMapping("/{id}")\n    @ResponseStatus(HttpStatus.NO_CONTENT)\n    public void delete(@PathVariable Long id) {\n        service.delete(id);\n    }\n}'),
    ("h2", "DTOs and validation"),
    ("p", "Java <code>record</code>s make compact, immutable DTOs. Validation annotations from Jakarta Validation declare the rules."),
    ("code", "java", 'import jakarta.validation.constraints.*;\n\npublic record CreateTaskRequest(\n    @NotBlank(message = "title is required")\n    @Size(max = 100) String title,\n    boolean done\n) {}\n\npublic record TaskResponse(Long id, String title, boolean done) {}'),
    ("p", "<code>@Valid</code> on the request body makes Spring check the rules before your method runs. On failure it rejects the request with HTTP 400. Common annotations: <code>@NotNull</code>, <code>@NotBlank</code>, <code>@Email</code>, <code>@Min</code>, <code>@Max</code>, <code>@Pattern</code>."),
    ("h2", "Global error handling"),
    ("p", "Handle exceptions in one place with <code>@RestControllerAdvice</code>, so every error has the same JSON shape."),
    ("code", "java", 'import org.springframework.http.HttpStatus;\nimport org.springframework.web.bind.MethodArgumentNotValidException;\nimport org.springframework.web.bind.annotation.*;\nimport java.util.Map;\nimport java.util.stream.Collectors;\n\nclass TaskNotFoundException extends RuntimeException {\n    TaskNotFoundException(Long id) { super("Task " + id + " not found"); }\n}\n\n@RestControllerAdvice\nclass ApiExceptionHandler {\n\n    @ExceptionHandler(TaskNotFoundException.class)\n    @ResponseStatus(HttpStatus.NOT_FOUND)\n    Map<String, String> notFound(TaskNotFoundException e) {\n        return Map.of("error", e.getMessage());\n    }\n\n    @ExceptionHandler(MethodArgumentNotValidException.class)\n    @ResponseStatus(HttpStatus.BAD_REQUEST)\n    Map<String, String> invalid(MethodArgumentNotValidException e) {\n        return e.getBindingResult().getFieldErrors().stream()\n            .collect(Collectors.toMap(f -> f.getField(), f -> f.getDefaultMessage(), (a, b) -> a));\n    }\n}'),
    ("output", '// POST with an empty title\n{"title":"title is required"}'),
    ("note", "Do not expose entities", "Returning database entities directly couples your API to your schema and can leak fields. Map to response DTOs, as above."),
    ("exercise", "Add a <code>priority</code> field to <code>CreateTaskRequest</code> that must be between 1 and 5, and confirm a request with priority 9 returns HTTP 400."),
    ("solution", "java", 'public record CreateTaskRequest(\n    @NotBlank String title,\n    boolean done,\n    @Min(1) @Max(5) int priority\n) {}'),
]

CONTENT["spring-dependency-injection"] = [
    ("p", "The heart of Spring is <strong>inversion of control</strong>. Instead of a class creating the objects it depends on (<code>new EmailSender()</code>), it <em>declares</em> what it needs and Spring supplies it. This makes code easier to test (swap in a fake) and to change (replace an implementation without touching users of it)."),
    ("h2", "Beans"),
    ("p", "A <strong>bean</strong> is an object created and managed by Spring's container. Mark a class with a stereotype annotation and component scanning registers it."),
    ("ul", [
        "<code>@Component</code>: a generic bean.",
        "<code>@Service</code>: business logic.",
        "<code>@Repository</code>: data access.",
        "<code>@RestController</code>: web layer.",
        "<code>@Configuration</code> with <code>@Bean</code> methods: create beans manually, for example for third-party classes.",
    ]),
    ("h2", "Constructor injection"),
    ("code", "java", 'public interface NotificationSender {\n    void send(String to, String message);\n}\n\n@Service\nclass EmailSender implements NotificationSender {\n    public void send(String to, String message) {\n        System.out.println("Email to " + to + ": " + message);\n    }\n}\n\n@Service\npublic class OrderService {\n\n    private final NotificationSender sender;      // depends on an interface\n\n    public OrderService(NotificationSender sender) {   // Spring passes it in\n        this.sender = sender;\n    }\n\n    public void placeOrder(String email) {\n        // ...save order...\n        sender.send(email, "Order received");\n    }\n}'),
    ("p", "Prefer <strong>constructor injection</strong>: dependencies are explicit, can be <code>final</code>, and the class cannot exist in a half-built state. With a single constructor, <code>@Autowired</code> is unnecessary."),
    ("h2", "Testing gets easy"),
    ("code", "java", 'class OrderServiceTest {\n    @Test\n    void sendsConfirmation() {\n        var sent = new java.util.ArrayList<String>();\n        NotificationSender fake = (to, msg) -> sent.add(to + ":" + msg);\n\n        new OrderService(fake).placeOrder("a@b.com");\n\n        assertEquals(1, sent.size());\n    }\n}'),
    ("h2", "The classic layers"),
    ("ul", [
        "<strong>Controller</strong>: HTTP in and out; no business logic.",
        "<strong>Service</strong>: the rules of your application; transactions live here.",
        "<strong>Repository</strong>: talks to the database.",
    ]),
    ("p", "Dependencies point downward only: controllers call services, services call repositories. Keeping that direction makes each layer replaceable and testable."),
    ("h2", "Multiple implementations"),
    ("p", "If two beans implement the same interface, Spring cannot decide. Mark one <code>@Primary</code>, or select by name with <code>@Qualifier(\"smsSender\")</code>."),
    ("h2", "Bean scopes"),
    ("p", "Beans are <strong>singletons</strong> by default: one shared instance. So never keep per-request or per-user state in fields of a service."),
    ("note", "Circular dependencies", "If A needs B and B needs A, Spring fails at startup. It usually means the design needs a third class or an event."),
    ("exercise", "Create a <code>PriceCalculator</code> interface with a <code>StandardCalculator</code> and a <code>DiscountCalculator</code>, mark one <code>@Primary</code>, and inject it into an <code>InvoiceService</code>."),
    ("solution", "java", 'interface PriceCalculator { double total(double subtotal); }\n\n@Service @Primary\nclass DiscountCalculator implements PriceCalculator {\n    public double total(double s) { return s * 0.9; }\n}\n@Service\nclass StandardCalculator implements PriceCalculator {\n    public double total(double s) { return s; }\n}\n\n@Service\nclass InvoiceService {\n    private final PriceCalculator calc;\n    InvoiceService(PriceCalculator calc) { this.calc = calc; }\n    double invoice(double subtotal) { return calc.total(subtotal); }\n}'),
]

CONTENT["spring-data-jpa"] = [
    ("p", "<strong>JPA</strong> (Jakarta Persistence) maps Java classes to database tables, and <strong>Spring Data JPA</strong> generates the repository implementations for you. You describe the data and the queries you want, and it writes the SQL."),
    ("h2", "An entity"),
    ("code", "java", 'import jakarta.persistence.*;\nimport java.time.Instant;\n\n@Entity\n@Table(name = "tasks")\npublic class Task {\n\n    @Id\n    @GeneratedValue(strategy = GenerationType.IDENTITY)\n    private Long id;\n\n    @Column(nullable = false, length = 100)\n    private String title;\n\n    private boolean done;\n\n    private Instant createdAt = Instant.now();\n\n    protected Task() {}                     // required by JPA\n\n    public Task(String title) { this.title = title; }\n\n    // getters and setters ...\n}'),
    ("h2", "A repository"),
    ("code", "java", 'import org.springframework.data.jpa.repository.JpaRepository;\nimport org.springframework.data.jpa.repository.Query;\nimport java.util.List;\n\npublic interface TaskRepository extends JpaRepository<Task, Long> {\n\n    List<Task> findByDoneFalseOrderByCreatedAtDesc();       // derived query\n\n    List<Task> findByTitleContainingIgnoreCase(String text);\n\n    long countByDone(boolean done);\n\n    @Query("select t from Task t where t.title like %:q% and t.done = false")\n    List<Task> searchOpen(String q);                        // custom JPQL\n}'),
    ("p", "There is no implementation class. Spring creates it at startup, and you get <code>save</code>, <code>findById</code>, <code>findAll</code>, <code>deleteById</code>, <code>count</code> and paging for free. Method names like <code>findByDoneFalseOrderByCreatedAtDesc</code> are parsed into queries."),
    ("h2", "Using it in a service"),
    ("code", "java", '@Service\npublic class TaskService {\n    private final TaskRepository repo;\n    public TaskService(TaskRepository repo) { this.repo = repo; }\n\n    @Transactional\n    public Task create(String title) {\n        return repo.save(new Task(title));\n    }\n\n    public Page<Task> page(int page, int size) {\n        return repo.findAll(PageRequest.of(page, size, Sort.by("createdAt").descending()));\n    }\n\n    public Task get(Long id) {\n        return repo.findById(id).orElseThrow(() -> new TaskNotFoundException(id));\n    }\n}'),
    ("h2", "Relationships"),
    ("code", "java", '@Entity\nclass Project {\n    @Id @GeneratedValue private Long id;\n    private String name;\n\n    @OneToMany(mappedBy = "project", cascade = CascadeType.ALL, orphanRemoval = true)\n    private List<Task> tasks = new ArrayList<>();\n}\n\n@Entity\nclass Task {\n    @Id @GeneratedValue private Long id;\n\n    @ManyToOne(fetch = FetchType.LAZY, optional = false)\n    @JoinColumn(name = "project_id")\n    private Project project;\n}'),
    ("ul", [
        "The side with the foreign key (<code>@ManyToOne</code>) is the <em>owning</em> side; <code>mappedBy</code> marks the inverse.",
        "Use <code>FetchType.LAZY</code> so related data loads only when accessed.",
        "Watch for the <strong>N+1 problem</strong>: loading a list then touching a lazy relation per item. Fix with <code>@EntityGraph</code> or a <code>join fetch</code> query.",
    ]),
    ("h2", "Configuration"),
    ("code", "yaml", "spring:\n  datasource:\n    url: jdbc:postgresql://localhost:5432/appdb\n    username: app\n    password: ${DB_PASSWORD}\n  jpa:\n    hibernate:\n      ddl-auto: validate      # never 'update' or 'create' in production\n    show-sql: true"),
    ("note", "Migrations", "For real projects manage the schema with Flyway or Liquibase migration scripts, and let Hibernate only <code>validate</code> it."),
    ("exercise", "Add a repository method that returns tasks created after a given <code>Instant</code>, and a service method that returns the count of completed tasks."),
    ("solution", "java", 'List<Task> findByCreatedAtAfter(Instant since);\nlong countByDone(boolean done);\n\n// service\npublic long completedCount() { return repo.countByDone(true); }'),
]

CONTENT["spring-testing-config"] = [
    ("p", "The last pieces of a production-ready service: configuration that changes per environment, and automated tests that let you change code with confidence."),
    ("h2", "Externalized configuration"),
    ("code", "yaml", "# application.yml\nserver:\n  port: 8080\napp:\n  greeting: Hello\n  max-tasks: 100"),
    ("code", "java", 'import org.springframework.boot.context.properties.ConfigurationProperties;\n\n@ConfigurationProperties(prefix = "app")\npublic record AppProperties(String greeting, int maxTasks) {}\n\n// enable with @ConfigurationPropertiesScan on the application class\n// inject: public HelloController(AppProperties props) { ... }'),
    ("p", "Spring reads properties from many places, later ones overriding earlier ones: the file, environment variables (<code>APP_MAXTASKS=50</code>), command-line arguments. This is how the same jar runs in every environment. Keep secrets in environment variables, never in git."),
    ("h2", "Profiles"),
    ("p", "Profiles switch configuration and even beans per environment."),
    ("code", "yaml", "# application-dev.yml\nspring:\n  datasource:\n    url: jdbc:h2:mem:devdb\n\n# application-prod.yml\nspring:\n  datasource:\n    url: jdbc:postgresql://db:5432/app"),
    ("code", "bash", "java -jar app.jar --spring.profiles.active=prod\n# or: SPRING_PROFILES_ACTIVE=prod"),
    ("h2", "Unit tests"),
    ("p", "Test services in isolation with plain JUnit and Mockito. They start instantly because no Spring container is needed."),
    ("code", "java", 'import static org.mockito.Mockito.*;\nimport static org.junit.jupiter.api.Assertions.*;\n\n@ExtendWith(MockitoExtension.class)\nclass TaskServiceTest {\n\n    @Mock TaskRepository repo;\n    @InjectMocks TaskService service;\n\n    @Test\n    void getThrowsWhenMissing() {\n        when(repo.findById(1L)).thenReturn(java.util.Optional.empty());\n        assertThrows(TaskNotFoundException.class, () -> service.get(1L));\n    }\n}'),
    ("h2", "Web layer tests with MockMvc"),
    ("code", "java", 'import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*;\nimport static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;\n\n@WebMvcTest(TaskController.class)\nclass TaskControllerTest {\n\n    @Autowired MockMvc mvc;\n    @MockBean TaskService service;\n\n    @Test\n    void rejectsBlankTitle() throws Exception {\n        mvc.perform(post("/api/tasks")\n                .contentType("application/json")\n                .content("{\\"title\\": \\"\\"}"))\n           .andExpect(status().isBadRequest());\n    }\n\n    @Test\n    void returnsTask() throws Exception {\n        when(service.findById(1L)).thenReturn(new TaskResponse(1L, "Write tests", false));\n        mvc.perform(get("/api/tasks/1"))\n           .andExpect(status().isOk())\n           .andExpect(jsonPath("$.title").value("Write tests"));\n    }\n}'),
    ("p", "<code>@WebMvcTest</code> loads only the web layer, so it stays fast. Use <code>@SpringBootTest</code> for full integration tests, ideally with Testcontainers to run a real PostgreSQL in Docker."),
    ("h2", "Packaging and running"),
    ("code", "bash", "./mvnw clean package\njava -jar target/demo-0.0.1-SNAPSHOT.jar"),
    ("p", "Boot builds a single executable jar containing the embedded server. It runs anywhere Java runs, and easily fits into a Docker image."),
    ("note", "What next", "Spring Security for authentication and authorization, Spring Cache, messaging with Kafka or RabbitMQ, and Micrometer with Actuator for observability."),
    ("exercise", "Write a MockMvc test asserting that <code>GET /api/tasks/999</code> returns 404 when the service throws <code>TaskNotFoundException</code>."),
    ("solution", "java", '@Test\nvoid missingTaskIs404() throws Exception {\n    when(service.findById(999L)).thenThrow(new TaskNotFoundException(999L));\n    mvc.perform(get("/api/tasks/999"))\n       .andExpect(status().isNotFound());\n}'),
]
