"""Pandas, System Design, Flask."""
from content_js_sql import M

META = [
    M("pandas-introduction", "pandas", "DataFrames and Series", 14, "Beginner", "Load data, inspect it and select rows and columns.", ["Create and load DataFrames", "Inspect with head/info/describe", "Select with loc and iloc"]),
    M("pandas-cleaning", "pandas", "Cleaning Data", 16, "Beginner", "Missing values, duplicates, types and text cleanup.", ["Handle NaN", "Fix dtypes", "Remove duplicates"]),
    M("pandas-groupby-merge", "pandas", "Grouping, Merging and Pivots", 17, "Intermediate", "Aggregate with groupby, join tables and reshape data.", ["Use groupby with agg", "Merge DataFrames", "Build a pivot table"]),
    M("pandas-time-plots", "pandas", "Dates, Plots and Exporting", 15, "Intermediate", "Work with time series, make quick charts and save results.", ["Parse dates", "Resample by period", "Plot and export"]),
    M("sysdesign-fundamentals", "sysdesign", "System Design Fundamentals", 15, "Intermediate", "Requirements, latency, throughput and a framework for design questions.", ["Estimate load", "Define requirements", "Follow a design framework"]),
    M("sysdesign-scaling-caching", "sysdesign", "Scaling and Caching", 17, "Intermediate", "Load balancers, horizontal scaling, caches and CDNs.", ["Scale horizontally", "Use caching patterns", "Explain cache invalidation"]),
    M("sysdesign-databases", "sysdesign", "Choosing and Scaling Databases", 17, "Intermediate", "SQL vs NoSQL, replication, sharding and consistency.", ["Pick a database", "Explain replication and sharding", "Describe CAP and consistency"]),
    M("sysdesign-queues-apis", "sysdesign", "Queues, APIs and Reliability", 16, "Advanced", "Async processing, idempotency, rate limiting and failure handling.", ["Use a message queue", "Design idempotent APIs", "Add retries and rate limits"]),
    M("sysdesign-case-study", "sysdesign", "Case Study: URL Shortener", 18, "Advanced", "Design a URL shortening service end to end.", ["Apply the framework", "Choose keys and storage", "Discuss trade-offs"]),
    M("flask-introduction", "flask", "Introduction and Routes", 12, "Beginner", "Create a Flask app, define routes and return JSON.", ["Run a Flask app", "Define routes with variables", "Return JSON"]),
    M("flask-templates-forms", "flask", "Templates and Forms", 15, "Beginner", "Render HTML with Jinja2 and process form submissions.", ["Render templates", "Use template inheritance", "Handle POST forms"]),
    M("flask-database", "flask", "Databases with SQLAlchemy", 16, "Intermediate", "Models, queries and migrations with Flask-SQLAlchemy.", ["Define models", "Query and commit", "Understand migrations"]),
    M("flask-blueprints-deploy", "flask", "Blueprints, Testing and Deployment", 16, "Intermediate", "Structure larger apps, test them and run with gunicorn.", ["Use blueprints and the app factory", "Write pytest tests", "Deploy with gunicorn"]),
]

CONTENT = {}

# ---------------- Pandas ----------------
CONTENT["pandas-introduction"] = [
    ("p", "<strong>pandas</strong> is Python's standard library for working with tables of data: spreadsheets, CSV files, database results. Its two core types are the <strong>Series</strong> (one column of labeled values) and the <strong>DataFrame</strong> (a table of Series sharing the same row index). If you can picture a spreadsheet, you can picture a DataFrame."),
    ("code", "bash", "pip install pandas"),
    ("h2", "Creating a DataFrame"),
    ("code", "python", 'import pandas as pd\n\ndf = pd.DataFrame({\n    "name": ["Ada", "Linus", "Grace", "Alan"],\n    "country": ["UK", "FI", "US", "UK"],\n    "age": [36, 28, 45, 41],\n    "salary": [120, 95, 150, 110],\n})\nprint(df)'),
    ("output", "    name country  age  salary\n0    Ada      UK   36     120\n1  Linus      FI   28      95\n2  Grace      US   45     150\n3   Alan      UK   41     110"),
    ("h2", "Loading real data"),
    ("code", "python", 'df = pd.read_csv("employees.csv")\ndf = pd.read_excel("report.xlsx")       # needs openpyxl\ndf = pd.read_json("data.json")\n# from a database: pd.read_sql("SELECT * FROM users", connection)'),
    ("h2", "First look"),
    ("code", "python", 'df.head()          # first 5 rows\ndf.shape           # (rows, columns)\ndf.info()          # column names, types, non-null counts\ndf.describe()      # count, mean, std, min, quartiles, max for numbers\ndf["country"].value_counts()   # frequency of each value'),
    ("p", "Always do this before anything else. Surprises such as unexpected types, empty columns or odd ranges show up immediately."),
    ("h2", "Selecting columns and rows"),
    ("code", "python", 'df["name"]                      # one column -> Series\ndf[["name", "salary"]]            # several -> DataFrame\ndf.loc[0]                         # a row by label\ndf.loc[0:1, "name":"age"]         # label slices are inclusive\ndf.iloc[0:2, 0:2]                 # by integer position, end exclusive'),
    ("h2", "Filtering with boolean masks"),
    ("code", "python", 'uk = df[df["country"] == "UK"]\nrich_uk = df[(df["country"] == "UK") & (df["salary"] > 115)]   # & | ~, with parentheses!\nnames = df[df["age"] > 30]["name"]\ndf.query("age > 30 and country == \'UK\'")'),
    ("note", "Common error", "Use <code>&amp;</code> and <code>|</code>, not <code>and</code> and <code>or</code>, and wrap each comparison in parentheses. Otherwise pandas raises \"truth value of a Series is ambiguous\"."),
    ("h2", "New columns, vectorized"),
    ("p", "Operate on whole columns at once instead of looping; it is far faster and shorter."),
    ("code", "python", 'df["salary_k"] = df["salary"] * 1000\ndf["senior"] = df["age"] >= 40\ndf["name_upper"] = df["name"].str.upper()\ndf = df.sort_values("salary", ascending=False)'),
    ("exercise", "Create a DataFrame of five products with price and quantity, add a <code>total</code> column, and show only rows where the total is above 100, sorted by total descending."),
    ("solution", "python", 'items = pd.DataFrame({"product": list("ABCDE"), "price": [10, 25, 5, 40, 8], "qty": [3, 5, 20, 2, 10]})\nitems["total"] = items["price"] * items["qty"]\nprint(items[items["total"] > 100].sort_values("total", ascending=False))'),
]

CONTENT["pandas-cleaning"] = [
    ("p", "Real data is messy: blanks, duplicates, wrong types, inconsistent spelling. Analysts commonly spend most of their time cleaning, and pandas has tools for each problem. The golden rule: <strong>inspect first, change deliberately, and keep the raw file untouched</strong>."),
    ("code", "python", 'import pandas as pd\nimport numpy as np\n\ndf = pd.DataFrame({\n    "name": ["  Ada ", "linus", "Grace", "Grace", None],\n    "age": ["36", "28", "abc", "45", "30"],\n    "salary": [120.0, np.nan, 150.0, 150.0, np.nan],\n    "joined": ["2021-03-01", "2022-07-15", "not a date", "2019-11-30", "2020-01-01"],\n})'),
    ("h2", "Missing values"),
    ("code", "python", 'df.isna().sum()                        # count missing per column\ndf.dropna(subset=["name"])             # drop rows missing a name\ndf["salary"].fillna(df["salary"].median())   # fill with the median\ndf["salary"].fillna(0)\ndf.ffill()                             # carry the previous value forward'),
    ("p", "Decide what missing <em>means</em> before you fill. A blank salary is unknown; filling it with 0 would badly distort averages. Sometimes keeping NaN, and letting statistics skip it, is right."),
    ("h2", "Fixing types"),
    ("code", "python", 'df["age"] = pd.to_numeric(df["age"], errors="coerce")   # bad values become NaN\ndf["joined"] = pd.to_datetime(df["joined"], errors="coerce")\ndf["country"] = df.get("country", "UK").astype("category")   # saves memory\ndf.dtypes'),
    ("p", "<code>errors=\"coerce\"</code> turns unparseable values into NaN/NaT so you can find and inspect them rather than crashing."),
    ("h2", "Duplicates"),
    ("code", "python", 'df.duplicated().sum()\ndf.duplicated(subset=["name"], keep="first")\ndf = df.drop_duplicates(subset=["name"], keep="first")'),
    ("h2", "Cleaning text"),
    ("code", "python", 'df["name"] = (\n    df["name"]\n    .str.strip()          # remove surrounding spaces\n    .str.title()          # Consistent capitalization\n)\ndf["email"] = df["email"].str.lower().str.replace(r"\\s+", "", regex=True)\ndf[df["name"].str.contains("ada", case=False, na=False)]'),
    ("h2", "Renaming, replacing, outliers"),
    ("code", "python", 'df = df.rename(columns={"joined": "join_date"})\ndf["country"] = df["country"].replace({"United Kingdom": "UK", "U.K.": "UK"})\n\n# flag outliers with the IQR rule\nq1, q3 = df["salary"].quantile([0.25, 0.75])\niqr = q3 - q1\noutliers = df[(df["salary"] < q1 - 1.5 * iqr) | (df["salary"] > q3 + 1.5 * iqr)]'),
    ("h2", "Method chaining"),
    ("p", "Chaining steps reads like a recipe and avoids scattered temporary variables."),
    ("code", "python", 'clean = (\n    df\n    .assign(name=lambda d: d["name"].str.strip().str.title())\n    .dropna(subset=["name"])\n    .drop_duplicates(subset=["name"])\n    .assign(age=lambda d: pd.to_numeric(d["age"], errors="coerce"))\n)'),
    ("note", "SettingWithCopyWarning", "This warning means you may be modifying a temporary copy. Use <code>df.loc[mask, \"col\"] = value</code> to assign, or call <code>.copy()</code> after slicing."),
    ("exercise", "Given a column of prices as strings like <code>\"$1,200\"</code>, <code>\"850\"</code> and <code>\"n/a\"</code>, convert it to numbers (NaN for bad values) and fill NaN with the median."),
    ("solution", "python", 's = pd.Series(["$1,200", "850", "n/a"])\nnum = pd.to_numeric(s.str.replace(r"[$,]", "", regex=True), errors="coerce")\nprint(num.fillna(num.median()))'),
]

CONTENT["pandas-groupby-merge"] = [
    ("p", "Analysis is mostly about summarizing (\"average salary per country\") and combining tables (\"attach each order's customer name\"). <code>groupby</code>, <code>merge</code> and pivot tables cover both, and they mirror the SQL you may already know."),
    ("code", "python", 'import pandas as pd\n\nemployees = pd.DataFrame({\n    "name": ["Ada", "Linus", "Grace", "Alan", "Tim"],\n    "dept_id": [1, 2, 1, 3, 2],\n    "country": ["UK", "FI", "US", "UK", "UK"],\n    "salary": [120, 95, 150, 110, 105],\n})\ndepts = pd.DataFrame({"dept_id": [1, 2, 4], "dept": ["Research", "Kernel", "Sales"]})'),
    ("h2", "groupby: split, apply, combine"),
    ("code", "python", 'employees.groupby("country")["salary"].mean()\n\nemployees.groupby("country").agg(\n    people=("name", "count"),\n    avg_salary=("salary", "mean"),\n    top_salary=("salary", "max"),\n).reset_index()'),
    ("output", "  country  people  avg_salary  top_salary\n0      FI       1        95.0          95\n1      UK       3       111.7         120\n2      US       1       150.0         150"),
    ("p", "Named aggregation (<code>new_name=(column, function)</code>) yields clean column names. Group by several columns with a list: <code>groupby([\"country\", \"dept_id\"])</code>."),
    ("h2", "Transform and rank within groups"),
    ("code", "python", 'employees["pct_of_country_avg"] = (\n    employees["salary"] / employees.groupby("country")["salary"].transform("mean")\n)\nemployees["rank_in_country"] = employees.groupby("country")["salary"].rank(ascending=False)'),
    ("p", "<code>transform</code> returns a result the same length as the original, so it slots back in as a new column."),
    ("h2", "merge: joining tables"),
    ("code", "python", 'pd.merge(employees, depts, on="dept_id", how="inner")   # only matching\npd.merge(employees, depts, on="dept_id", how="left")    # keep all employees\npd.merge(employees, depts, on="dept_id", how="outer")   # keep everything\n\n# different key names\npd.merge(employees, depts, left_on="dept_id", right_on="id")'),
    ("p", "The <code>how</code> values match SQL joins: inner, left, right and outer. Tim (dept 2) matches Kernel; Alan (dept 3) has no department, so a left merge gives NaN for his <code>dept</code>. Add <code>validate=\"many_to_one\"</code> to catch accidental duplicate keys that would multiply rows."),
    ("h2", "Stacking tables"),
    ("code", "python", 'pd.concat([jan, feb, mar], ignore_index=True)     # same columns, stacked rows\npd.concat([a, b], axis=1)                       # side by side'),
    ("h2", "Pivot tables"),
    ("code", "python", 'pd.pivot_table(\n    employees, index="country", columns="dept_id",\n    values="salary", aggfunc="mean", fill_value=0,\n)'),
    ("p", "A pivot table reshapes long data into a grid, exactly like a spreadsheet pivot. <code>melt</code> does the reverse, turning wide columns back into rows."),
    ("note", "Check your row counts", "After every merge, compare <code>len()</code> before and after. Unexpected growth means duplicate keys; unexpected shrinkage means an inner join dropped rows."),
    ("exercise", "Using the tables above, find the department name with the highest average salary, ignoring employees without a department."),
    ("solution", "python", 'merged = employees.merge(depts, on="dept_id", how="inner")\nprint(merged.groupby("dept")["salary"].mean().idxmax())   # Research'),
]

CONTENT["pandas-time-plots"] = [
    ("p", "Business data is full of dates: sales per day, signups per week, server load per minute. pandas has first-class time support, and quick plotting turns numbers into pictures you can share."),
    ("h2", "Dates as a datetime index"),
    ("code", "python", 'import pandas as pd\nimport numpy as np\n\nrng = pd.date_range("2026-01-01", periods=90, freq="D")\nsales = pd.DataFrame({"revenue": np.random.default_rng(1).integers(100, 500, size=90)}, index=rng)\n\nsales.index.dayofweek        # 0=Monday ... 6=Sunday\nsales.index.month\nsales.loc["2026-02"]         # partial-string selection: all of February\nsales.loc["2026-01-15":"2026-01-20"]'),
    ("h2", "Resampling"),
    ("p", "<code>resample</code> is <code>groupby</code> for time: regroup daily data into weeks or months."),
    ("code", "python", 'weekly = sales["revenue"].resample("W").sum()\nmonthly = sales["revenue"].resample("MS").agg(["sum", "mean"])\nprint(monthly)'),
    ("h2", "Rolling windows and change"),
    ("code", "python", 'sales["7d_avg"] = sales["revenue"].rolling(7).mean()      # smooth out noise\nsales["pct_change"] = sales["revenue"].pct_change()\nsales["cumulative"] = sales["revenue"].cumsum()\nsales["lag_1"] = sales["revenue"].shift(1)                # yesterday\'s value'),
    ("h2", "Parsing dates from files"),
    ("code", "python", 'df = pd.read_csv("orders.csv", parse_dates=["created"])\ndf["created"] = pd.to_datetime(df["created"], format="%d/%m/%Y")   # be explicit for ambiguous formats\ndf["weekday"] = df["created"].dt.day_name()\ndf["days_since"] = (pd.Timestamp.today() - df["created"]).dt.days'),
    ("p", "Store timestamps in UTC and convert for display with <code>tz_localize</code> and <code>tz_convert</code> when time zones matter."),
    ("h2", "Quick plots"),
    ("code", "bash", "pip install matplotlib"),
    ("code", "python", 'import matplotlib.pyplot as plt\n\nax = sales[["revenue", "7d_avg"]].plot(figsize=(9, 4), title="Daily revenue")\nax.set_ylabel("USD")\nplt.tight_layout()\nplt.savefig("revenue.png", dpi=150)\n\nsales["revenue"].plot.hist(bins=15)                    # distribution\nemployees.groupby("country")["salary"].mean().plot.bar()   # category comparison'),
    ("ul", [
        "Line charts for trends over time; bar charts for comparing categories; histograms for distributions; scatter plots for relationships.",
        "Always label axes and add a title. Start bar charts at zero.",
    ]),
    ("h2", "Exporting"),
    ("code", "python", 'monthly.to_csv("monthly.csv")\nmonthly.to_excel("monthly.xlsx")\ndf.to_parquet("orders.parquet")     # compact and fast for big data\ndf.to_sql("orders", engine, if_exists="replace", index=False)'),
    ("note", "Big files", "For data that does not fit in memory, read in chunks (<code>chunksize=</code>), keep only the columns you need (<code>usecols=</code>), or move to Polars or DuckDB."),
    ("exercise", "Create 60 days of random data, compute a 7-day rolling mean and the best week, and save a line chart to a PNG file."),
    ("solution", "python", 'idx = pd.date_range("2026-01-01", periods=60)\ns = pd.Series(np.random.default_rng(0).normal(100, 15, 60), index=idx)\nprint(s.resample("W").sum().idxmax())\nax = pd.DataFrame({"value": s, "7d": s.rolling(7).mean()}).plot(title="Demo")\nax.figure.savefig("demo.png")'),
]

# ---------------- System design ----------------
CONTENT["sysdesign-fundamentals"] = [
    ("p", "<strong>System design</strong> is deciding how the pieces of a software system (servers, databases, caches, queues) fit together so it works correctly for many users, stays fast and survives failures. There is rarely one right answer; the skill is choosing sensible trade-offs and explaining why."),
    ("h2", "Key vocabulary"),
    ("ul", [
        "<strong>Latency</strong>: how long one request takes (milliseconds).",
        "<strong>Throughput</strong>: how many requests you handle per second (QPS).",
        "<strong>Availability</strong>: the fraction of time the system works. \"Three nines\" (99.9%) allows about 8.8 hours of downtime a year; \"four nines\" about 53 minutes.",
        "<strong>Scalability</strong>: ability to handle growth by adding resources.",
        "<strong>Reliability</strong>: keeps working correctly despite faults.",
    ]),
    ("h2", "A framework for any design"),
    ("ul", [
        "<strong>1. Clarify requirements.</strong> Functional (what it does) and non-functional (scale, latency, availability, consistency). Ask questions; do not assume.",
        "<strong>2. Estimate scale.</strong> Users, requests per second, data size. Back-of-the-envelope is fine.",
        "<strong>3. Sketch the API and data model.</strong> Main endpoints and tables.",
        "<strong>4. Draw a high-level design.</strong> Clients, load balancer, app servers, database, cache.",
        "<strong>5. Deep-dive on the hard parts.</strong> The bottleneck, the trickiest requirement.",
        "<strong>6. Discuss trade-offs and failure modes.</strong> What breaks? What would you change with 100x traffic?",
    ]),
    ("h2", "Back-of-the-envelope estimates"),
    ("p", "Handy numbers: a day has about 86,400 seconds (call it 100,000). One million requests per day is about 12 per second. A read from memory takes around 100 nanoseconds, an SSD read around 100 microseconds, and a cross-continent network round trip around 150 milliseconds."),
    ("code", "python", '# Example: a photo app with 10M daily users\nusers = 10_000_000\nuploads_per_user = 2\navg_photo_mb = 3\n\nuploads_per_day = users * uploads_per_user            # 20M\nuploads_per_sec = uploads_per_day / 86_400            # ~230/s average\npeak_per_sec = uploads_per_sec * 3                    # ~700/s at peak\nstorage_per_day_tb = uploads_per_day * avg_photo_mb / 1_000_000   # 60 TB/day\nprint(round(uploads_per_sec), round(peak_per_sec), storage_per_day_tb)'),
    ("output", "231 694 60.0"),
    ("p", "Sixty terabytes a day tells you immediately that the design needs object storage (like S3) and a CDN, not a database column holding image bytes."),
    ("h2", "Read-heavy vs write-heavy"),
    ("p", "Most consumer systems read far more than they write (often 100 to 1 or more). That points to caching and read replicas. Write-heavy systems (logging, metrics) suggest queues, batching and append-friendly storage."),
    ("note", "Avoid over-engineering", "Start with the simplest thing that meets the requirements: one server and one database can carry more than beginners expect. Add complexity only when a number justifies it."),
    ("exercise", "A service gets 50 million requests a day. Estimate average and peak QPS (assume peak is 5 times the average) and say whether one server handling 1,000 QPS would suffice."),
    ("solution", "python", 'daily = 50_000_000\navg = daily / 86_400        # ~579 QPS\npeak = avg * 5              # ~2,894 QPS\nprint(round(avg), round(peak))\n# One 1,000 QPS server is not enough at peak: need at least 3-4 plus redundancy.'),
]

CONTENT["sysdesign-scaling-caching"] = [
    ("p", "When one server is no longer enough you have two options: make it bigger (<strong>vertical scaling</strong>) or add more of them (<strong>horizontal scaling</strong>). Vertical is simple but has a ceiling and a single point of failure. Horizontal scales much further and tolerates failures, but requires your design to spread work across machines."),
    ("h2", "Stateless services and load balancers"),
    ("p", "To scale out, application servers should be <strong>stateless</strong>: no user data kept only in a server's memory. Sessions and files live in shared stores (a database, Redis, object storage), so any server can handle any request. A <strong>load balancer</strong> sits in front and distributes traffic."),
    ("ul", [
        "<strong>Algorithms</strong>: round robin, least connections, hash by client.",
        "<strong>Health checks</strong> remove failed servers automatically.",
        "Layer 4 balances by connection; layer 7 (HTTP) can route by path or header.",
        "Run at least two balancers, or use a managed one, to avoid a new single point of failure.",
    ]),
    ("h2", "Caching"),
    ("p", "A <strong>cache</strong> stores results of expensive work close to where they are needed. It is the single most effective performance tool: memory is roughly a thousand times faster than a database query. Caches exist at every layer:"),
    ("ul", [
        "<strong>Browser cache</strong> and <strong>CDN</strong>: static files and even API responses served from a location near the user.",
        "<strong>Application cache</strong> (Redis, Memcached): computed results, sessions, hot database rows.",
        "<strong>Database cache</strong>: query plans and pages.",
    ]),
    ("h2", "Cache-aside pattern"),
    ("p", "The most common approach: the app checks the cache first, falls back to the database on a miss, then stores the result."),
    ("code", "python", 'import json, redis\nr = redis.Redis()\n\ndef get_user(user_id):\n    key = f"user:{user_id}"\n    cached = r.get(key)\n    if cached:                              # hit\n        return json.loads(cached)\n    user = db.query_user(user_id)           # miss: go to the database\n    r.setex(key, 300, json.dumps(user))     # store with a 5-minute TTL\n    return user\n\ndef update_user(user_id, data):\n    db.update_user(user_id, data)\n    r.delete(f"user:{user_id}")             # invalidate so the next read refreshes'),
    ("h2", "Other write strategies"),
    ("ul", [
        "<strong>Write-through</strong>: write to cache and database together. Reads are always fresh; writes are slower.",
        "<strong>Write-back</strong>: write to cache and flush to the database later. Fast, but data can be lost if the cache fails.",
    ]),
    ("h2", "Invalidation and eviction"),
    ("p", "\"There are only two hard things in computer science: cache invalidation and naming things.\" Stale data is the price of caching. Manage it with a <strong>TTL</strong> (expire after a time), explicit invalidation on writes, and versioned keys. When memory fills, an <strong>eviction policy</strong> such as LRU (least recently used) decides what to drop."),
    ("h2", "Cache stampede"),
    ("p", "When a popular key expires, thousands of requests can hit the database at once. Mitigate with locks so only one request recomputes, random jitter added to TTLs, and refreshing entries before they expire."),
    ("note", "CDN", "For global users, put static assets and cacheable pages on a CDN. It removes load from your servers and cuts latency because content is served from a nearby edge location."),
    ("exercise", "A product page is read 1,000 times per second but its price changes once a day. Describe a caching design including the TTL and how you would handle a price change."),
    ("solution", "text", "Cache the product JSON in Redis with cache-aside and a TTL of ~10 minutes,\nplus a CDN for images. When the price changes, the update code deletes the\nkey (explicit invalidation) so users see the new price immediately; the\nTTL is only a safety net. Add jitter to TTLs to avoid a stampede."),
]

CONTENT["sysdesign-databases"] = [
    ("p", "The database is usually the hardest part of a system to scale, because it holds state that must stay correct. Choosing the right kind, and knowing how to spread it across machines, is core to system design."),
    ("h2", "SQL versus NoSQL"),
    ("ul", [
        "<strong>Relational (SQL)</strong>: PostgreSQL, MySQL. Structured tables, joins, strong guarantees (ACID transactions). The default for most applications, and far more scalable than many people assume.",
        "<strong>Document</strong> (MongoDB): flexible JSON documents. Good when records vary in shape or are read as a whole.",
        "<strong>Key-value</strong> (Redis, DynamoDB): extremely fast lookups by key; limited querying.",
        "<strong>Wide-column</strong> (Cassandra): massive write throughput across many nodes.",
        "<strong>Graph</strong> (Neo4j): relationship-heavy queries such as social networks.",
        "<strong>Search</strong> (Elasticsearch, OpenSearch): full-text search and analytics.",
    ]),
    ("p", "A sound default: start with PostgreSQL, and add specialized stores only for needs it cannot meet."),
    ("h2", "Replication"),
    ("p", "<strong>Replication</strong> keeps copies of data on several machines. Typically one <em>primary</em> accepts writes and streams changes to <em>replicas</em>, which serve reads. It gives you higher read capacity and failover if the primary dies."),
    ("ul", [
        "Replicas can lag slightly behind (<em>replication lag</em>), so a user might not immediately see their own write. Route reads that need freshness to the primary.",
        "Synchronous replication is safer but slower; asynchronous is faster but can lose the last writes on failure.",
    ]),
    ("h2", "Sharding"),
    ("p", "When one primary cannot handle the data size or write volume, <strong>shard</strong> (partition) the data: each shard holds a subset of rows on its own servers. The <em>shard key</em> decides where a row lives."),
    ("code", "python", 'def shard_for(user_id: int, shards: int = 8) -> int:\n    return user_id % shards          # simple hash sharding\n\nprint(shard_for(1234))            # user 1234 lives on shard 2'),
    ("ul", [
        "Choose a key with even distribution; a bad key creates a <em>hot shard</em>.",
        "Cross-shard joins and transactions become hard or impossible, so shard only when you must.",
        "Adding shards moves data. <strong>Consistent hashing</strong> minimizes how much moves.",
    ]),
    ("h2", "Consistency and the CAP theorem"),
    ("p", "In a distributed system, a network <em>partition</em> (nodes cannot talk) will eventually happen. CAP says that during one you must choose between <strong>Consistency</strong> (every read sees the latest write) and <strong>Availability</strong> (every request gets a response). Banking usually picks consistency; a social feed can accept <strong>eventual consistency</strong>, where replicas converge after a short time."),
    ("h2", "Indexing and denormalization"),
    ("p", "Indexes make queries fast (see the SQL indexes lesson). At large scale you may <em>denormalize</em>: store precomputed or duplicated data (like a counter or a joined view) to avoid expensive queries, accepting extra write work and the need to keep copies in sync."),
    ("note", "Rule of thumb", "Vertical scale first, then add read replicas and caching, then partition by feature, and shard last."),
    ("exercise", "You are designing a chat app storing billions of messages, mostly read by conversation. Suggest a database type and a shard key, and justify them."),
    ("solution", "text", "Use a wide-column or partitioned store (Cassandra/DynamoDB) or sharded\nPostgreSQL. Shard key = conversation_id, so all messages of a\nconversation sit together and reads hit one shard. Sort messages by\ntimestamp within the partition. Watch for very active conversations\n(hot partitions) and cap partition size by time-bucketing."),
]

CONTENT["sysdesign-queues-apis"] = [
    ("p", "Not everything should happen while the user waits. Sending an email, resizing a video or updating a search index can be done <em>later</em>. <strong>Message queues</strong> decouple the part of the system that requests work from the part that does it, which improves speed, resilience and scalability."),
    ("h2", "Queues"),
    ("p", "A producer puts a message on a queue; one or more <strong>consumers</strong> take messages off and process them. Examples: RabbitMQ, Amazon SQS, Kafka, Redis streams."),
    ("ul", [
        "<strong>Smooths spikes</strong>: a burst of 10,000 signups is absorbed by the queue and processed at a steady pace.",
        "<strong>Isolates failure</strong>: if the email service is down, messages wait instead of failing user requests.",
        "<strong>Scales independently</strong>: add more consumers when the queue grows.",
    ]),
    ("code", "python", '# producer (in the web request)\nqueue.publish("send_welcome_email", {"user_id": 42})\nreturn {"status": "created"}          # respond immediately\n\n# consumer (background worker)\ndef handle(message):\n    user = db.get_user(message["user_id"])\n    email.send(user.email, "Welcome!")'),
    ("p", "<strong>Publish/subscribe</strong> (pub/sub) delivers one event to many subscribers, such as \"order placed\" going to billing, shipping and analytics. Kafka is a popular <em>log</em> that lets consumers replay history."),
    ("h2", "Delivery guarantees and idempotency"),
    ("p", "Most queues guarantee <strong>at-least-once</strong> delivery: a message may be delivered twice (for example after a crash before acknowledgment). So consumers must be <strong>idempotent</strong>: processing the same message twice has the same effect as once."),
    ("code", "python", 'def charge(message):\n    key = message["idempotency_key"]\n    if db.exists("processed", key):       # already handled\n        return\n    with db.transaction():\n        payments.charge(message["user_id"], message["amount"])\n        db.insert("processed", key)'),
    ("p", "The same idea protects APIs. A client sends an <code>Idempotency-Key</code> header on a payment request; if the network drops and the client retries, the server recognizes the key and does not charge twice."),
    ("h2", "Retries, backoff and dead-letter queues"),
    ("ul", [
        "Retry transient failures with <strong>exponential backoff</strong> plus random jitter (wait 1s, 2s, 4s...) to avoid hammering a struggling service.",
        "After a limited number of attempts, move the message to a <strong>dead-letter queue</strong> for inspection instead of retrying forever.",
        "Use <strong>timeouts</strong> everywhere; a call without one can hang a whole system.",
        "A <strong>circuit breaker</strong> stops calling a failing dependency for a while, so failures do not cascade.",
    ]),
    ("h2", "Rate limiting"),
    ("p", "Protect your service from abuse and overload by limiting requests per client. A <strong>token bucket</strong> allows bursts while enforcing an average rate."),
    ("code", "python", 'import time\n\nclass TokenBucket:\n    def __init__(self, rate, capacity):\n        self.rate, self.capacity = rate, capacity\n        self.tokens, self.last = capacity, time.monotonic()\n\n    def allow(self):\n        now = time.monotonic()\n        self.tokens = min(self.capacity, self.tokens + (now - self.last) * self.rate)\n        self.last = now\n        if self.tokens >= 1:\n            self.tokens -= 1\n            return True\n        return False          # respond with HTTP 429 Too Many Requests\n\nbucket = TokenBucket(rate=5, capacity=10)   # 5 req/s, bursts up to 10'),
    ("h2", "API design basics"),
    ("ul", [
        "Version your API (<code>/v1/</code>) so you can change it without breaking clients.",
        "Paginate lists, ideally with cursors instead of large offsets.",
        "Return consistent errors and correct status codes.",
    ]),
    ("note", "Design for failure", "Assume every network call can be slow, fail or duplicate. Reliable systems are built from components that expect that."),
    ("exercise", "Design how a video-upload feature should process a file (transcode to several resolutions) without making the user wait, and say how you would prevent duplicate work if a worker crashes."),
    ("solution", "text", "1. Client uploads to object storage via a pre-signed URL.\n2. API stores a 'video' row (status=processing) and publishes a message with video_id.\n3. Worker consumes, transcodes, writes outputs, sets status=ready.\n4. Idempotency: workers check status/outputs before starting; the message is\n   acknowledged only after success, so a crash makes it be redelivered and\n   the idempotent check skips finished work. Failures after N retries go to a DLQ."),
]

CONTENT["sysdesign-case-study"] = [
    ("p", "Let us apply everything by designing a <strong>URL shortener</strong> (like bit.ly): users submit a long URL and get a short one; visiting the short link redirects to the original. It is small enough to finish in one lesson yet touches every core idea."),
    ("h2", "1. Requirements"),
    ("ul", [
        "<strong>Functional</strong>: create a short URL, redirect, optional custom alias and expiry, basic click counts.",
        "<strong>Non-functional</strong>: very low redirect latency, high availability, links should not be guessable in order, and reads far outnumber writes.",
    ]),
    ("h2", "2. Estimates"),
    ("code", "python", 'new_urls_per_day = 100_000_000 / 30          # assume 100M new URLs per month\nwrites_per_sec = new_urls_per_day / 86_400     # ~40/s\nread_write_ratio = 100\nreads_per_sec = writes_per_sec * read_write_ratio   # ~4,000/s\n\nrecords_5_years = 100_000_000 * 12 * 5          # 6 billion\nbytes_per_record = 500\nstorage_tb = records_5_years * bytes_per_record / 1e12\nprint(round(writes_per_sec), round(reads_per_sec), round(storage_tb, 1))'),
    ("output", "39 3858 3.0"),
    ("p", "Roughly 40 writes per second and 4,000 reads per second is modest; 3 TB over five years fits comfortably in a database. The design is read-heavy, so caching is the big lever."),
    ("h2", "3. API and data model"),
    ("code", "text", "POST /api/v1/urls       { long_url, custom_alias?, expires_at? } -> { short_url }\nGET  /{code}             -> 301/302 redirect to the long URL\n\ntable urls(\n  code        VARCHAR(10) PRIMARY KEY,\n  long_url    TEXT NOT NULL,\n  created_at  TIMESTAMP,\n  expires_at  TIMESTAMP NULL,\n  user_id     BIGINT NULL\n)"),
    ("h2", "4. Generating the short code"),
    ("p", "Seven characters of base62 (a-z, A-Z, 0-9) give 62 to the power 7, about 3.5 trillion codes, far more than the 6 billion needed. Options:"),
    ("ul", [
        "<strong>Hash the URL</strong> (MD5 or SHA-256) and take the first 7 characters. Simple, but collisions must be detected and handled.",
        "<strong>Counter + base62</strong>: an auto-incrementing id encoded in base62. No collisions, but sequential codes are guessable, and one counter is a bottleneck. Fix by allocating id <em>ranges</em> to each app server, and by adding a shuffle or salt so codes look random.",
        "<strong>Random code</strong> with a uniqueness check on insert, retrying on the rare collision.",
    ]),
    ("code", "python", 'ALPHABET = "0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ"\n\ndef base62(n: int) -> str:\n    if n == 0:\n        return ALPHABET[0]\n    out = []\n    while n:\n        n, r = divmod(n, 62)\n        out.append(ALPHABET[r])\n    return "".join(reversed(out))\n\nprint(base62(125), base62(3_500_000_000))'),
    ("output", "21 3lbTzk"),
    ("h2", "5. High-level design"),
    ("ul", [
        "Clients hit a <strong>load balancer</strong>, which spreads requests over stateless <strong>app servers</strong>.",
        "Redirect path: check <strong>Redis</strong> for <code>code</code>; on a miss read the database and fill the cache (cache-aside, long TTL, LRU eviction). The hottest links stay in memory, so most reads never touch the database.",
        "Write path: validate the URL, allocate a code, insert into the database.",
        "Database: PostgreSQL with a primary and read replicas; shard by <code>code</code> hash only if it outgrows one cluster. A key-value store such as DynamoDB also fits well, since access is always by key.",
        "Analytics: publish a click event to a <strong>queue</strong>; workers aggregate counts asynchronously so redirects stay fast.",
    ]),
    ("h2", "6. Trade-offs and edge cases"),
    ("ul", [
        "<strong>301 vs 302</strong>: 301 (permanent) lets browsers cache the redirect, reducing load but hiding later clicks from analytics. 302 keeps every click visible.",
        "<strong>Abuse</strong>: rate limit creation, block malicious domains, and scan for phishing.",
        "<strong>Expiry</strong>: a background job deletes expired rows; check <code>expires_at</code> on read too.",
        "<strong>Custom aliases</strong> need a uniqueness check and reserved words (<code>api</code>, <code>admin</code>).",
        "<strong>Availability</strong>: multiple regions with replicated data and DNS failover if global uptime matters.",
    ]),
    ("note", "How to present it", "Talk through the six steps in order, state assumptions aloud, sketch as you go and invite the interviewer to steer toward the part they care about. Clear structure matters more than a perfect answer."),
    ("exercise", "Extend the design with per-link click analytics (clicks per day, top countries) without slowing down redirects. Which components do you add, and where does each piece of data live?"),
    ("solution", "text", "On each redirect the server publishes a small event {code, ts, country, referrer}\nto Kafka/SQS (fire-and-forget, after responding). A consumer batches events and\nwrites aggregates into an analytics store (ClickHouse/BigQuery, or Postgres\ntables partitioned by day). A dashboard API reads only the aggregates. The\nredirect path never waits on analytics writes; if the queue is down, events\nare buffered or dropped without breaking redirects."),
]

# ---------------- Flask ----------------
CONTENT["flask-introduction"] = [
    ("p", "<strong>Flask</strong> is a small, flexible Python web framework. It gives you routing and request handling and leaves the rest (database, forms, authentication) to libraries you choose. That makes it an excellent way to understand how web apps work, and it is easy to start with and easy to grow."),
    ("h2", "Setup and hello world"),
    ("code", "bash", "python3 -m venv .venv && source .venv/bin/activate\npip install flask"),
    ("code", "python", '# app.py\nfrom flask import Flask, jsonify, request\n\napp = Flask(__name__)\n\n@app.route("/")\ndef home():\n    return "Hello, Flask!"\n\n@app.route("/health")\ndef health():\n    return jsonify(status="ok")\n\nif __name__ == "__main__":\n    app.run(debug=True)'),
    ("code", "bash", "flask --app app run --debug        # or: python app.py"),
    ("p", "Visit <code>http://127.0.0.1:5000/</code>. Debug mode reloads on save and shows an interactive error page; <strong>never enable it in production</strong>."),
    ("h2", "Routes with variables"),
    ("code", "python", '@app.route("/users/<int:user_id>")\ndef get_user(user_id):\n    return jsonify(id=user_id)\n\n@app.route("/hello/<name>")\ndef hello(name):\n    return f"Hello, {name}!"'),
    ("p", "Converters such as <code>int</code>, <code>float</code>, <code>string</code> and <code>uuid</code> validate and convert the URL part. A non-matching URL gives a 404 automatically."),
    ("h2", "HTTP methods and the request object"),
    ("code", "python", '@app.route("/search")\ndef search():\n    q = request.args.get("q", "")           # query string ?q=...\n    page = request.args.get("page", 1, type=int)\n    return jsonify(query=q, page=page)\n\n@app.route("/items", methods=["POST"])\ndef create_item():\n    data = request.get_json(silent=True) or {}\n    if not data.get("name"):\n        return jsonify(error="name is required"), 400\n    return jsonify(id=1, name=data["name"]), 201'),
    ("p", "A view can return a string, a dict (converted to JSON), or a tuple of <code>(body, status)</code>. Use <code>abort(404)</code> to stop with an error."),
    ("h2", "Error handlers"),
    ("code", "python", '@app.errorhandler(404)\ndef not_found(e):\n    return jsonify(error="Not found"), 404'),
    ("note", "Flask or FastAPI?", "Flask is great for server-rendered sites and small services. For new JSON APIs with automatic validation and docs, FastAPI (covered in this section) is often a better fit."),
    ("exercise", "Add <code>GET /add?a=2&amp;b=3</code> returning the sum as JSON, responding with 400 if either value is missing or not a number."),
    ("solution", "python", '@app.route("/add")\ndef add():\n    a = request.args.get("a", type=float)\n    b = request.args.get("b", type=float)\n    if a is None or b is None:\n        return jsonify(error="a and b must be numbers"), 400\n    return jsonify(sum=a + b)'),
]

CONTENT["flask-templates-forms"] = [
    ("p", "Flask renders HTML using <strong>Jinja2</strong> templates. A template is an HTML file with placeholders and small bits of logic, filled with data from your view."),
    ("h2", "Rendering a template"),
    ("code", "python", 'from flask import render_template\n\n@app.route("/")\ndef index():\n    posts = [{"title": "Hello", "body": "First post"}, {"title": "Flask", "body": "Is small"}]\n    return render_template("index.html", posts=posts, user="Ada")'),
    ("code", "html", '<!-- templates/index.html -->\n{% extends "base.html" %}\n{% block content %}\n  <h1>Welcome, {{ user }}</h1>\n  {% for post in posts %}\n    <article>\n      <h2>{{ post.title }}</h2>\n      <p>{{ post.body|truncate(80) }}</p>\n    </article>\n  {% else %}\n    <p>No posts yet.</p>\n  {% endfor %}\n{% endblock %}'),
    ("ul", [
        "<code>{{ ... }}</code> prints a value, and Jinja <strong>auto-escapes</strong> it to prevent XSS.",
        "<code>{% ... %}</code> is a statement (<code>if</code>, <code>for</code>, <code>extends</code>, <code>block</code>).",
        "<code>|filter</code> transforms values: <code>upper</code>, <code>length</code>, <code>default</code>, <code>truncate</code>.",
    ]),
    ("h2", "Template inheritance"),
    ("code", "html", '<!-- templates/base.html -->\n<!DOCTYPE html>\n<html lang="en">\n<head>\n  <title>{% block title %}My App{% endblock %}</title>\n  <link rel="stylesheet" href="{{ url_for(\'static\', filename=\'style.css\') }}">\n</head>\n<body>\n  <nav><a href="{{ url_for(\'index\') }}">Home</a></nav>\n  {% block content %}{% endblock %}\n</body>\n</html>'),
    ("p", "<code>url_for</code> builds URLs from view function names, so links do not break when you rename a route. Static files go in a <code>static/</code> folder."),
    ("h2", "Handling forms"),
    ("code", "python", 'from flask import request, redirect, url_for, flash\n\napp.secret_key = "change-me"     # load from an environment variable in real apps\n\n@app.route("/contact", methods=["GET", "POST"])\ndef contact():\n    if request.method == "POST":\n        email = request.form.get("email", "").strip()\n        message = request.form.get("message", "").strip()\n        if not email or not message:\n            flash("Both fields are required.")\n        else:\n            save_message(email, message)\n            flash("Thanks, we got your message!")\n            return redirect(url_for("contact"))      # Post/Redirect/Get\n    return render_template("contact.html")'),
    ("code", "html", '<form method="post">\n  {% for m in get_flashed_messages() %}<p class="notice">{{ m }}</p>{% endfor %}\n  <label>Email <input name="email" type="email" required></label>\n  <label>Message <textarea name="message" required></textarea></label>\n  <button>Send</button>\n</form>'),
    ("p", "Redirecting after a successful POST stops the browser from resubmitting the form when the user refreshes. For CSRF protection and validation, add <strong>Flask-WTF</strong>."),
    ("note", "Security", "Never build HTML by concatenating user input into strings. Let Jinja escape it, and only use <code>|safe</code> on content you have sanitized."),
    ("exercise", "Create a <code>/greet</code> page with a form that asks for a name and shows \"Hello, &lt;name&gt;!\" after submission, using a base template."),
    ("solution", "python", '@app.route("/greet", methods=["GET", "POST"])\ndef greet():\n    name = request.form.get("name") if request.method == "POST" else None\n    return render_template("greet.html", name=name)\n# greet.html: {% if name %}<h1>Hello, {{ name }}!</h1>{% endif %}\n#             <form method="post"><input name="name"><button>Go</button></form>'),
]

CONTENT["flask-database"] = [
    ("p", "Most apps need a database. The usual choice with Flask is <strong>Flask-SQLAlchemy</strong>, which wraps SQLAlchemy, Python's leading ORM, so you work with classes instead of raw SQL."),
    ("code", "bash", "pip install flask flask-sqlalchemy flask-migrate"),
    ("h2", "Setup and models"),
    ("code", "python", 'from flask import Flask\nfrom flask_sqlalchemy import SQLAlchemy\nfrom datetime import datetime, timezone\n\napp = Flask(__name__)\napp.config["SQLALCHEMY_DATABASE_URI"] = "sqlite:///app.db"\ndb = SQLAlchemy(app)\n\nclass User(db.Model):\n    id = db.Column(db.Integer, primary_key=True)\n    email = db.Column(db.String(120), unique=True, nullable=False)\n    name = db.Column(db.String(80), nullable=False)\n    posts = db.relationship("Post", backref="author", lazy=True)\n\nclass Post(db.Model):\n    id = db.Column(db.Integer, primary_key=True)\n    title = db.Column(db.String(200), nullable=False)\n    body = db.Column(db.Text)\n    created = db.Column(db.DateTime, default=lambda: datetime.now(timezone.utc))\n    user_id = db.Column(db.Integer, db.ForeignKey("user.id"), nullable=False)\n\nwith app.app_context():\n    db.create_all()'),
    ("h2", "Create, read, update, delete"),
    ("code", "python", 'with app.app_context():\n    ada = User(email="ada@example.com", name="Ada")\n    db.session.add(ada)\n    db.session.commit()\n\n    db.session.add(Post(title="Hello", body="First", user_id=ada.id))\n    db.session.commit()\n\n    User.query.all()\n    User.query.filter_by(email="ada@example.com").first()\n    db.session.get(User, 1)\n    Post.query.filter(Post.title.contains("Hel")).order_by(Post.created.desc()).limit(10).all()\n\n    ada.name = "Ada Lovelace"       # update by changing attributes\n    db.session.commit()\n\n    db.session.delete(ada)\n    db.session.commit()'),
    ("p", "Changes are staged in the <em>session</em> and only written when you call <code>commit()</code>. If something fails, call <code>db.session.rollback()</code>."),
    ("h2", "Using it in routes"),
    ("code", "python", '@app.route("/posts")\ndef posts():\n    posts = Post.query.order_by(Post.created.desc()).all()\n    return jsonify([{"id": p.id, "title": p.title, "author": p.author.name} for p in posts])\n\n@app.route("/posts/<int:post_id>")\ndef post_detail(post_id):\n    post = db.get_or_404(Post, post_id)\n    return jsonify(id=post.id, title=post.title)'),
    ("h2", "Migrations"),
    ("p", "When models change, <code>create_all</code> will not alter existing tables. <strong>Flask-Migrate</strong> (Alembic) records schema changes as versioned scripts."),
    ("code", "bash", "flask db init\nflask db migrate -m \"add posts\"\nflask db upgrade"),
    ("note", "N+1 queries", "Looping over posts and reading <code>p.author</code> triggers one query per post. Load related rows in one go with <code>Post.query.options(joinedload(Post.author))</code>."),
    ("exercise", "Add a <code>Comment</code> model belonging to a <code>Post</code>, then a route that returns a post with its comments as JSON."),
    ("solution", "python", 'class Comment(db.Model):\n    id = db.Column(db.Integer, primary_key=True)\n    text = db.Column(db.Text, nullable=False)\n    post_id = db.Column(db.Integer, db.ForeignKey("post.id"), nullable=False)\n    post = db.relationship("Post", backref="comments")\n\n@app.route("/posts/<int:pid>/full")\ndef full(pid):\n    p = db.get_or_404(Post, pid)\n    return jsonify(title=p.title, comments=[c.text for c in p.comments])'),
]

CONTENT["flask-blueprints-deploy"] = [
    ("p", "A single <code>app.py</code> is fine for learning but becomes unmanageable as an app grows. Flask has patterns for organizing code, plus a standard path to testing and production."),
    ("h2", "Blueprints"),
    ("p", "A <strong>blueprint</strong> groups related routes, templates and static files into a module."),
    ("code", "python", '# myapp/blog/routes.py\nfrom flask import Blueprint, jsonify\n\nbp = Blueprint("blog", __name__, url_prefix="/blog")\n\n@bp.route("/")\ndef index():\n    return jsonify(posts=[])\n\n@bp.route("/<int:post_id>")\ndef show(post_id):\n    return jsonify(id=post_id)'),
    ("h2", "The application factory"),
    ("p", "Create the app inside a function, so you can build differently configured instances, for example one for tests and one for production."),
    ("code", "python", '# myapp/__init__.py\nfrom flask import Flask\nfrom .extensions import db\n\ndef create_app(config=None):\n    app = Flask(__name__)\n    app.config.from_mapping(\n        SECRET_KEY="dev",\n        SQLALCHEMY_DATABASE_URI="sqlite:///app.db",\n    )\n    if config:\n        app.config.update(config)\n    app.config.from_prefixed_env()        # FLASK_SECRET_KEY etc. override\n\n    db.init_app(app)\n\n    from .blog.routes import bp as blog_bp\n    app.register_blueprint(blog_bp)\n    return app'),
    ("code", "text", "myapp/\n  __init__.py        # create_app\n  extensions.py      # db = SQLAlchemy()\n  models.py\n  blog/\n    __init__.py\n    routes.py\n    templates/\ntests/\n  test_blog.py\nwsgi.py"),
    ("h2", "Testing with pytest"),
    ("code", "python", '# tests/test_blog.py\nimport pytest\nfrom myapp import create_app\nfrom myapp.extensions import db\n\n@pytest.fixture\ndef client():\n    app = create_app({"TESTING": True, "SQLALCHEMY_DATABASE_URI": "sqlite:///:memory:"})\n    with app.app_context():\n        db.create_all()\n        yield app.test_client()\n\ndef test_index_returns_json(client):\n    res = client.get("/blog/")\n    assert res.status_code == 200\n    assert res.get_json() == {"posts": []}\n\ndef test_unknown_route_404(client):\n    assert client.get("/nope").status_code == 404'),
    ("code", "bash", "pip install pytest\npytest -q"),
    ("h2", "Running in production"),
    ("p", "The built-in dev server is not for production. Use a WSGI server such as <strong>gunicorn</strong>, usually behind Nginx or a platform's load balancer."),
    ("code", "python", '# wsgi.py\nfrom myapp import create_app\napp = create_app()'),
    ("code", "bash", "pip install gunicorn\ngunicorn -w 4 -b 0.0.0.0:8000 wsgi:app"),
    ("code", "dockerfile", 'FROM python:3.12-slim\nWORKDIR /app\nCOPY requirements.txt .\nRUN pip install --no-cache-dir -r requirements.txt\nCOPY . .\nCMD ["gunicorn", "-w", "4", "-b", "0.0.0.0:8000", "wsgi:app"]'),
    ("h2", "Production checklist"),
    ("ul", [
        "<code>DEBUG</code> off; a strong <code>SECRET_KEY</code> read from an environment variable.",
        "A real database (PostgreSQL) with migrations applied.",
        "HTTPS, secure cookies (<code>SESSION_COOKIE_SECURE</code>) and CSRF protection on forms.",
        "Structured logging and error monitoring (for example Sentry).",
    ]),
    ("note", "Next steps", "Add Flask-Login for user sessions, Flask-WTF for forms, and Flask-Smorest or Flask-RESTX if you want OpenAPI docs for a JSON API."),
    ("exercise", "Split a small app into an app factory plus an <code>api</code> blueprint at <code>/api</code> with a <code>/ping</code> route, and write a pytest test that checks it returns 200."),
    ("solution", "python", '# api.py\nbp = Blueprint("api", __name__, url_prefix="/api")\n@bp.route("/ping")\ndef ping():\n    return {"pong": True}\n\n# factory: app.register_blueprint(bp)\n# test\ndef test_ping(client):\n    assert client.get("/api/ping").status_code == 200'),
]
