"""Rich lesson bodies for the Data Structures track."""

CONTENT = {}

CONTENT["ds-introduction"] = [
    ("p", "A <strong>data structure</strong> is a way of organizing data in memory so that the operations you care about are fast enough. An <strong>algorithm</strong> is the sequence of steps that uses the structure to solve a problem. The two go together: the right structure often makes the algorithm trivial, and the wrong one turns a feature that should be instant into a timeout."),
    ("h2", "Why it matters"),
    ("p", "Imagine finding a contact among one million. In an unsorted list you may have to look at every entry, about a million steps. In a hash table you jump straight to it, about one step. The data is identical; only the structure changed."),
    ("h2", "The toolbox"),
    ("ul", [
        "<strong>Array / list</strong>: ordered items with fast access by position.",
        "<strong>Linked list</strong>: items chained by pointers, with fast insert and remove at a known spot.",
        "<strong>Stack</strong>: last in, first out (undo history, function calls).",
        "<strong>Queue</strong>: first in, first out (task scheduling, breadth-first search).",
        "<strong>Hash table</strong>: key to value lookup in about constant time.",
        "<strong>Tree</strong>: hierarchical data with fast ordered search (file systems, databases).",
        "<strong>Graph</strong>: things connected to other things (maps, social networks, dependencies).",
    ]),
    ("h2", "Abstract data types"),
    ("p", "An <em>abstract data type</em> (ADT) says <strong>what</strong> operations exist, not how they are built. A stack promises <code>push</code> and <code>pop</code>; you could build it on an array or a linked list. Thinking in ADTs lets you pick the behavior you need first and the implementation second."),
    ("h2", "You already use them"),
    ("code", "python", 'stack = []\nstack.append("a")        # list used as a stack\nstack.append("b")\nprint(stack.pop())\n\nlookup = {"id": 7}       # dict is a hash table\nprint(lookup["id"])'),
    ("output", "b\n7"),
    ("h2", "How to choose"),
    ("p", "Ask four questions: What operations will I do most often? Does order matter? Are duplicates allowed? How large can the data get? The rest of this course gives you the vocabulary (and the Big O lesson gives you the measuring stick) to answer them."),
    ("exercise", "For a chat app's \"recent messages\" feature, would you prioritize fast append or fast lookup by ID? Name a structure for each need and explain whether one structure could serve both."),
    ("solution", "python", '# Fast append + ordered display -> list/deque (append at the end)\n# Fast lookup by message id   -> dict {id: message}\n# Use both: a list of ids for order and a dict for lookup,\n# or Python 3.7+ dict itself, which remembers insertion order.\nmessages = {}\nmessages[101] = "hi"\nmessages[102] = "hello"\nprint(list(messages.values())[-1])'),
]

CONTENT["ds-arrays"] = [
    ("p", "An <strong>array</strong> stores elements one after another in a single block of memory. Because every element takes the same amount of space, the computer can calculate the address of element <code>i</code> directly: start address plus <code>i</code> times the element size. That is why reading <code>arr[i]</code> takes the same tiny amount of time whether the array has ten items or ten million."),
    ("h2", "What is fast and what is slow"),
    ("ul", [
        "<strong>Read or write by index</strong>: O(1).",
        "<strong>Append at the end</strong>: O(1) on average.",
        "<strong>Insert or delete in the middle or front</strong>: O(n), because everything after it must shift.",
        "<strong>Search for a value</strong> in an unsorted array: O(n), since you may check every element.",
    ]),
    ("code", "python", 'nums = [10, 20, 30, 40]\nprint(nums[2])        # O(1) access\nnums.append(50)       # O(1) amortized\nnums.insert(1, 15)    # O(n) shifts 20, 30, 40, 50\nprint(nums)'),
    ("output", "30\n[10, 15, 20, 30, 40, 50]"),
    ("h2", "Fixed versus dynamic arrays"),
    ("p", "In C or Java a plain array has a fixed length. Python lists, Java's <code>ArrayList</code> and JavaScript arrays are <em>dynamic arrays</em>: when they run out of room they allocate a bigger block (usually double), copy everything over and continue. Each resize is O(n), but they are rare, so appends average out to O(1)."),
    ("h2", "Why arrays are fast in practice"),
    ("p", "Contiguous memory is friendly to the CPU cache. When you read one element, its neighbors come along for free, so scanning an array is often faster than scanning a linked list even when the Big O is the same."),
    ("h2", "A classic technique: two pointers"),
    ("p", "Many array problems can be solved with two indexes that move toward each other, avoiding nested loops. Reversing an array in place is the simplest example."),
    ("code", "python", 'def reverse(a):\n    left, right = 0, len(a) - 1\n    while left < right:\n        a[left], a[right] = a[right], a[left]\n        left += 1\n        right -= 1\n\nvals = [1, 2, 3, 4, 5]\nreverse(vals)\nprint(vals)'),
    ("output", "[5, 4, 3, 2, 1]"),
    ("p", "This runs in O(n) time and O(1) extra space, because it swaps in place instead of building a second array."),
    ("note", "Common bug", "Off-by-one errors and reading past the end (<code>IndexError</code>). Remember valid indexes run from <code>0</code> to <code>len(a) - 1</code>."),
    ("exercise", "Reverse an array in place without using <code>reverse()</code> or slicing. Then write a function that returns the second largest value in one pass."),
    ("solution", "python", 'def second_largest(a):\n    first = second = float("-inf")\n    for x in a:\n        if x > first:\n            first, second = x, first\n        elif first > x > second:\n            second = x\n    return second\n\nprint(second_largest([4, 9, 1, 7, 9]))  # 7'),
]

CONTENT["ds-linked-lists"] = [
    ("p", "A <strong>linked list</strong> is a chain of <em>nodes</em>. Each node holds a value and a reference (pointer) to the next node. The nodes can live anywhere in memory; the pointers are what tie them together. You keep track of the first node, called the <em>head</em>, and follow <code>next</code> pointers until you reach <code>None</code>."),
    ("h2", "Building one"),
    ("code", "python", 'class Node:\n    def __init__(self, val, nxt=None):\n        self.val = val\n        self.next = nxt\n\nhead = Node(1, Node(2, Node(3)))\n\ncur = head\nwhile cur:\n    print(cur.val)\n    cur = cur.next'),
    ("output", "1\n2\n3"),
    ("h2", "Insert and delete"),
    ("p", "The big advantage: adding or removing at a known position is O(1), because you only rewire a pointer, and nothing shifts. Inserting at the head is the simplest case."),
    ("code", "python", 'def push_front(head, val):\n    return Node(val, head)     # new head points at old head\n\ndef delete_value(head, target):\n    if head and head.val == target:\n        return head.next\n    cur = head\n    while cur and cur.next:\n        if cur.next.val == target:\n            cur.next = cur.next.next   # skip the node\n            break\n        cur = cur.next\n    return head\n\nhead = push_front(head, 0)\nhead = delete_value(head, 2)'),
    ("p", "Finding the node to delete still takes O(n), because you must walk the list to reach it."),
    ("h2", "Singly versus doubly linked"),
    ("p", "A <strong>singly linked</strong> list has only <code>next</code> pointers, so you can move in one direction. A <strong>doubly linked</strong> list also has <code>prev</code>, which allows walking backward and removing a node when you already hold a reference to it, at the cost of more memory."),
    ("h2", "Arrays vs linked lists"),
    ("ul", [
        "Access by index: array O(1), linked list O(n).",
        "Insert/delete at the front: array O(n), linked list O(1).",
        "Memory: linked lists spend extra space on pointers and cache poorly.",
        "In practice arrays win most of the time; linked lists shine as building blocks (queues, LRU caches, adjacency lists).",
    ]),
    ("h2", "Classic technique: fast and slow pointers"),
    ("code", "python", 'def middle(head):\n    slow = fast = head\n    while fast and fast.next:\n        slow = slow.next\n        fast = fast.next.next\n    return slow.val\n\nprint(middle(Node(1, Node(2, Node(3, Node(4, Node(5)))))))'),
    ("output", "3"),
    ("p", "The fast pointer moves twice as quickly, so when it reaches the end the slow pointer is at the middle. The same idea detects cycles."),
    ("note", "Common bug", "Losing the rest of the list by overwriting <code>next</code> before saving it. When reversing or splicing, store the next node in a temporary variable first."),
    ("exercise", "Implement <code>count_nodes(head)</code> that returns the length of a singly linked list, then <code>reverse(head)</code> that reverses it in place."),
    ("solution", "python", 'def count_nodes(head):\n    n = 0\n    while head:\n        n += 1\n        head = head.next\n    return n\n\ndef reverse(head):\n    prev = None\n    while head:\n        nxt = head.next\n        head.next = prev\n        prev, head = head, nxt\n    return prev'),
]

CONTENT["ds-stacks-queues"] = [
    ("p", "Stacks and queues are simple structures that restrict <em>where</em> you can add and remove items. That restriction is their strength: it matches many real problems exactly and keeps every operation O(1)."),
    ("h2", "Stack: last in, first out"),
    ("p", "Think of a stack of plates. You add to the top and take from the top. The two core operations are <code>push</code> and <code>pop</code>, plus <code>peek</code> to look without removing. In Python a plain list works: <code>append</code> is push and <code>pop()</code> is pop."),
    ("code", "python", 'stack = []\nstack.append("a")\nstack.append("b")\nstack.append("c")\nprint(stack.pop())    # c\nprint(stack[-1])      # b (peek)\nprint(stack)'),
    ("output", "c\nb\n['a', 'b']"),
    ("p", "Where stacks show up: the undo button, browser back history, evaluating expressions, and the call stack that tracks running functions (which is why runaway recursion causes a \"stack overflow\")."),
    ("h2", "Queue: first in, first out"),
    ("p", "A queue is a line at a shop. You join at the back (<code>enqueue</code>) and are served from the front (<code>dequeue</code>). Do not use <code>list.pop(0)</code> for this: it is O(n). Use <code>collections.deque</code>, which is O(1) at both ends."),
    ("code", "python", 'from collections import deque\n\nqueue = deque()\nqueue.append("first")\nqueue.append("second")\nqueue.append("third")\nprint(queue.popleft())   # first\nprint(list(queue))'),
    ("output", "first\n['second', 'third']"),
    ("p", "Queues run job schedulers, print spoolers, message brokers and breadth-first search."),
    ("h2", "Worked example: balanced brackets"),
    ("p", "A stack is the natural tool for checking that every opening bracket has a matching closer in the right order. Push openers; on a closer, the top of the stack must be its partner."),
    ("code", "python", 'def balanced(s):\n    pairs = {")": "(", "]": "[", "}": "{"}\n    stack = []\n    for ch in s:\n        if ch in "([{":\n            stack.append(ch)\n        elif ch in pairs:\n            if not stack or stack.pop() != pairs[ch]:\n                return False\n    return not stack\n\nprint(balanced("{[()]}"))\nprint(balanced("([)]"))'),
    ("output", "True\nFalse"),
    ("h2", "Related structures"),
    ("ul", [
        "<strong>Deque</strong>: add and remove at both ends.",
        "<strong>Priority queue</strong>: serves the smallest (or largest) item first, usually built on a heap (<code>heapq</code> in Python).",
    ]),
    ("note", "Common bug", "Popping from an empty stack or queue raises an error. Check <code>if stack:</code> first, or handle the exception."),
    ("exercise", "Use a stack to reverse a string. Then use a queue to simulate three customers being served in arrival order."),
    ("solution", "python", 'from collections import deque\n\ns = "stackcone"\nstack = list(s)\nout = "".join(stack.pop() for _ in range(len(stack)))\nprint(out)\n\nline = deque(["Ann", "Bob", "Cy"])\nwhile line:\n    print("serving", line.popleft())'),
]

CONTENT["ds-trees"] = [
    ("p", "A <strong>tree</strong> is a hierarchy: one <em>root</em> node at the top, and every node may have <em>children</em> below it. Nodes with no children are <em>leaves</em>. Folders on your disk, the HTML DOM and organization charts are all trees. A <strong>binary tree</strong> limits each node to at most two children, called left and right."),
    ("h2", "Vocabulary"),
    ("ul", [
        "<strong>Depth</strong> of a node: number of edges from the root.",
        "<strong>Height</strong> of the tree: the longest path from the root down to a leaf.",
        "<strong>Subtree</strong>: any node together with all of its descendants. Trees are recursive by nature.",
    ]),
    ("code", "python", 'class TreeNode:\n    def __init__(self, val, left=None, right=None):\n        self.val = val\n        self.left = left\n        self.right = right\n\n#        4\n#       / \\\n#      2   6\n#     / \\\n#    1   3\nroot = TreeNode(4, TreeNode(2, TreeNode(1), TreeNode(3)), TreeNode(6))'),
    ("h2", "Depth-first traversal"),
    ("p", "Recursion fits trees perfectly: handle the node, then hand the left and right subtrees to the same function. The three orders differ only in when the node is visited. <strong>In-order</strong> is left, node, right."),
    ("code", "python", 'def inorder(node):\n    if not node:\n        return\n    inorder(node.left)\n    print(node.val)\n    inorder(node.right)\n\ninorder(root)'),
    ("output", "1\n2\n3\n4\n6"),
    ("p", "<strong>Pre-order</strong> (node, left, right) is useful for copying a tree. <strong>Post-order</strong> (left, right, node) is useful for deleting one, since children are processed before their parent."),
    ("h2", "Breadth-first (level order)"),
    ("p", "Visit nodes level by level using a queue."),
    ("code", "python", 'from collections import deque\n\ndef level_order(root):\n    result, q = [], deque([root])\n    while q:\n        node = q.popleft()\n        result.append(node.val)\n        if node.left:  q.append(node.left)\n        if node.right: q.append(node.right)\n    return result\n\nprint(level_order(root))'),
    ("output", "[4, 2, 6, 1, 3]"),
    ("h2", "Binary search trees"),
    ("p", "A <strong>binary search tree</strong> (BST) keeps every left descendant smaller and every right descendant larger than the node. Searching is like binary search: at each node, go left or right, discarding half the remaining tree. That is O(log n) when the tree is balanced, but degrades to O(n) if it becomes a long chain. In-order traversal of a BST visits values in sorted order, as you saw above."),
    ("code", "python", 'def contains(node, target):\n    while node:\n        if target == node.val:\n            return True\n        node = node.left if target < node.val else node.right\n    return False\n\nprint(contains(root, 3), contains(root, 5))'),
    ("output", "True False"),
    ("note", "Heights matter", "Self-balancing trees (AVL, red-black) keep the height near log n automatically. Databases and language libraries use them, so you rarely write one yourself."),
    ("exercise", "Write <code>height(node)</code> that returns the height of a binary tree, counting an empty tree as 0."),
    ("solution", "python", 'def height(node):\n    if not node:\n        return 0\n    return 1 + max(height(node.left), height(node.right))\n\nprint(height(root))   # 3'),
]

CONTENT["ds-hash-tables"] = [
    ("p", "A <strong>hash table</strong> stores key-value pairs and finds a value from its key in about constant time, no matter how many items it holds. It is the structure behind Python's <code>dict</code> and <code>set</code>, Java's <code>HashMap</code> and JavaScript's <code>Map</code> and objects. If you learn one structure deeply, make it this one."),
    ("h2", "How it works"),
    ("p", "The table is really an array of <em>buckets</em>. To store a key, a <strong>hash function</strong> turns it into a number, and that number modulo the array size picks the bucket. To look the key up later, you run the same hash and go straight to that bucket instead of searching."),
    ("code", "python", 'def bucket_index(key, size):\n    return hash(key) % size\n\nprint(bucket_index("user:42", 8))   # always the same for the same key'),
    ("h2", "Collisions"),
    ("p", "Two different keys can land in the same bucket. That is called a <strong>collision</strong>, and every hash table needs a plan for it:"),
    ("ul", [
        "<strong>Chaining</strong>: each bucket holds a small list of entries that share it.",
        "<strong>Open addressing</strong>: if a bucket is taken, probe the next free one.",
    ]),
    ("p", "When the table gets too full it <em>resizes</em>, allocating more buckets and re-hashing every key. This keeps chains short so lookups stay fast."),
    ("h2", "Complexity"),
    ("ul", [
        "Insert, lookup and delete: <strong>O(1) average</strong>.",
        "Worst case O(n) if nearly every key collides, which good hash functions make very unlikely.",
        "Keys must be hashable, meaning immutable: strings, numbers and tuples work; lists do not.",
    ]),
    ("h2", "Everyday uses"),
    ("code", "python", 'cache = {}\ncache["user:42"] = {"name": "stackcone"}\nprint(cache.get("user:42"))\n\n# Membership testing: set is much faster than list for large data\nseen = set()\nfor n in [3, 1, 3, 2]:\n    if n in seen:\n        print("duplicate:", n)\n    seen.add(n)'),
    ("output", "{'name': 'stackcone'}\nduplicate: 3"),
    ("h2", "Worked example: two-sum"),
    ("p", "Find two numbers in a list that add to a target. Checking every pair is O(n squared). With a hash table you remember what you have seen and check for the complement in O(1), giving O(n) overall."),
    ("code", "python", 'def two_sum(nums, target):\n    seen = {}\n    for i, n in enumerate(nums):\n        need = target - n\n        if need in seen:\n            return seen[need], i\n        seen[n] = i\n\nprint(two_sum([2, 7, 11, 15], 9))'),
    ("output", "(0, 1)"),
    ("note", "Trade-off", "Hash tables trade memory and ordering for speed. If you need keys sorted or range queries, use a tree-based map instead."),
    ("exercise", "Return the first duplicate character in a string using a set, or <code>None</code> if all characters are unique."),
    ("solution", "python", 'def first_duplicate(s):\n    seen = set()\n    for ch in s:\n        if ch in seen:\n            return ch\n        seen.add(ch)\n    return None\n\nprint(first_duplicate("stackcone"))   # c'),
]

CONTENT["ds-graphs"] = [
    ("p", "A <strong>graph</strong> is a set of <em>vertices</em> (nodes) joined by <em>edges</em>. It models anything made of connections: roads between cities, friends in a social network, links between web pages, packages that depend on other packages. A tree is just a graph with no cycles and one root."),
    ("h2", "Kinds of graphs"),
    ("ul", [
        "<strong>Undirected</strong>: an edge works both ways (friendship). <strong>Directed</strong>: an edge has a direction (follows, links to).",
        "<strong>Weighted</strong>: edges carry a cost such as distance or time.",
        "<strong>Cyclic</strong> or <strong>acyclic</strong>: whether you can follow edges and return to where you started. A directed acyclic graph (DAG) models task dependencies.",
    ]),
    ("h2", "Representing a graph"),
    ("p", "The most common representation is an <strong>adjacency list</strong>: a dictionary mapping each vertex to a list of its neighbors. It uses space proportional to vertices plus edges and is fast to iterate, which suits most real graphs."),
    ("code", "python", 'graph = {\n    "A": ["B", "C"],\n    "B": ["D"],\n    "C": ["D"],\n    "D": [],\n}\nprint(graph["A"])'),
    ("output", "['B', 'C']"),
    ("p", "An <em>adjacency matrix</em> (a 2D grid of yes/no) answers \"is there an edge between X and Y?\" in O(1) but uses V squared memory, so it fits only dense graphs."),
    ("h2", "Breadth-first search (BFS)"),
    ("p", "BFS explores all neighbors before going deeper, using a queue. In an unweighted graph it finds the path with the fewest edges. Track visited nodes so you never loop forever on a cycle."),
    ("code", "python", 'from collections import deque\n\ndef bfs(start):\n    seen = {start}\n    q = deque([start])\n    order = []\n    while q:\n        node = q.popleft()\n        order.append(node)\n        for nxt in graph[node]:\n            if nxt not in seen:\n                seen.add(nxt)\n                q.append(nxt)\n    return order\n\nprint(bfs("A"))'),
    ("output", "['A', 'B', 'C', 'D']"),
    ("h2", "Depth-first search (DFS)"),
    ("p", "DFS follows one path as far as it goes before backing up, using recursion or a stack. It is the basis for cycle detection, topological sorting and finding connected components."),
    ("code", "python", 'def dfs(node, seen=None):\n    seen = seen if seen is not None else set()\n    seen.add(node)\n    for nxt in graph[node]:\n        if nxt not in seen:\n            dfs(nxt, seen)\n    return seen\n\nprint(sorted(dfs("A")))'),
    ("output", "['A', 'B', 'C', 'D']"),
    ("p", "Both BFS and DFS run in O(V + E): every vertex and edge is examined at most once."),
    ("h2", "Where to go next"),
    ("ul", [
        "<strong>Dijkstra</strong>: shortest paths with weighted edges.",
        "<strong>Topological sort</strong>: order tasks so dependencies come first.",
        "<strong>Union-Find</strong>: quickly answer whether two nodes are connected.",
    ]),
    ("note", "Always mark visited", "Forgetting the <code>seen</code> set is the most common graph bug. On any graph with a cycle it causes an infinite loop."),
    ("exercise", "Extend <code>bfs</code> to take a target and return the shortest path as a list of nodes, or <code>None</code> if unreachable."),
    ("solution", "python", 'from collections import deque\n\ndef shortest_path(start, target):\n    q = deque([[start]])\n    seen = {start}\n    while q:\n        path = q.popleft()\n        node = path[-1]\n        if node == target:\n            return path\n        for nxt in graph[node]:\n            if nxt not in seen:\n                seen.add(nxt)\n                q.append(path + [nxt])\n    return None\n\nprint(shortest_path("A", "D"))   # [\'A\', \'B\', \'D\']'),
]

CONTENT["ds-big-o"] = [
    ("p", "How do you compare two solutions to the same problem? Timing them on your laptop depends on the hardware and the input. <strong>Big O notation</strong> instead describes how the number of steps <em>grows</em> as the input size <code>n</code> grows. It lets you predict whether code that works on 100 items will survive 100 million."),
    ("h2", "The common classes"),
    ("ul", [
        "<strong>O(1) constant</strong>: same work regardless of size. Array index, dict lookup.",
        "<strong>O(log n) logarithmic</strong>: each step halves the problem. Binary search.",
        "<strong>O(n) linear</strong>: touch every item once. Scanning a list.",
        "<strong>O(n log n)</strong>: efficient sorting (merge sort, Python's <code>sorted</code>).",
        "<strong>O(n squared) quadratic</strong>: a loop inside a loop over the same data. Comparing all pairs.",
        "<strong>O(2 to the n) exponential</strong>: doubles with every added item. Naive recursion over subsets.",
    ]),
    ("h2", "Reading code"),
    ("code", "python", 'def first(items):          # O(1)\n    return items[0]\n\ndef total(items):          # O(n)\n    s = 0\n    for x in items:\n        s += x\n    return s\n\ndef has_pair(items):       # O(n^2)\n    for i in items:\n        for j in items:\n            if i != j and i + j == 10:\n                return True\n    return False'),
    ("h2", "Rules for simplifying"),
    ("ul", [
        "<strong>Drop constants</strong>: 3n and n are both O(n). Big O describes shape, not exact counts.",
        "<strong>Keep the dominant term</strong>: n squared + n is O(n squared).",
        "<strong>Sequential steps add</strong>: an O(n) loop followed by an O(n) loop is O(n).",
        "<strong>Nested steps multiply</strong>: an O(n) loop containing an O(n) loop is O(n squared).",
    ]),
    ("h2", "Binary search: the power of halving"),
    ("p", "On a sorted list, check the middle; the answer is in one half, so discard the other. A billion items need only about 30 comparisons."),
    ("code", "python", 'def binary_search(a, target):\n    lo, hi = 0, len(a) - 1\n    while lo <= hi:\n        mid = (lo + hi) // 2\n        if a[mid] == target:\n            return mid\n        if a[mid] < target:\n            lo = mid + 1\n        else:\n            hi = mid - 1\n    return -1\n\nprint(binary_search([1, 3, 5, 7, 9, 11], 7))'),
    ("output", "3"),
    ("h2", "Space complexity"),
    ("p", "Big O also measures <em>memory</em>. Building a new list of n items costs O(n) extra space; swapping values in place costs O(1). Trading space for time, such as adding a hash table to avoid a nested loop, is one of the most common optimizations."),
    ("h2", "Best, average, worst"),
    ("p", "Big O usually quotes the worst case. Quicksort is O(n log n) on average but O(n squared) in the worst case; hash lookups are O(1) on average and O(n) worst case. State which one you mean."),
    ("note", "Practical advice", "Big O matters most as n gets large. For tiny inputs, a simple O(n squared) solution is fine and often faster. Measure before optimizing."),
    ("exercise", "What is the time complexity of finding whether a list contains duplicates by comparing every pair? Rewrite it using a set to reach O(n)."),
    ("solution", "python", '# Pairwise comparison: O(n^2) time, O(1) space\n# With a set: O(n) time, O(n) space\ndef has_duplicates(items):\n    seen = set()\n    for x in items:\n        if x in seen:\n            return True\n        seen.add(x)\n    return False'),
]
