"""HTML & CSS, TypeScript, Git & Command Line tracks."""
from content_js_sql import M

META = [
    M("html-introduction", "htmlcss", "HTML Fundamentals", 14, "Beginner", "Elements, attributes, headings, links, images and a valid page skeleton.", ["Write a valid HTML5 page", "Use links and images with alt text", "Choose semantic elements"]),
    M("html-forms-semantics", "htmlcss", "Forms and Semantic HTML", 15, "Beginner", "Inputs, labels, validation and landmarks that make pages accessible.", ["Build an accessible form", "Use built-in validation", "Structure with header/nav/main/footer"]),
    M("css-basics", "htmlcss", "CSS Basics", 16, "Beginner", "Selectors, the cascade, the box model, colors and typography.", ["Write selectors", "Explain specificity", "Use the box model"]),
    M("css-flexbox", "htmlcss", "Flexbox Layout", 15, "Intermediate", "Align and distribute items in one dimension.", ["Use flex containers", "Align and space items", "Build a nav bar and cards row"]),
    M("css-grid-responsive", "htmlcss", "Grid and Responsive Design", 17, "Intermediate", "Two-dimensional layouts, media queries and mobile-first CSS.", ["Build a grid layout", "Write media queries", "Use clamp and custom properties"]),
    M("ts-introduction", "typescript", "Why TypeScript", 12, "Beginner", "Set up TypeScript and meet basic type annotations and inference.", ["Install and run tsc", "Annotate variables and functions", "Read a type error"]),
    M("ts-types-interfaces", "typescript", "Types, Interfaces and Unions", 16, "Beginner", "Model data with interfaces, unions, literals and narrowing.", ["Define interfaces and type aliases", "Use union types and narrowing", "Prefer literals over strings"]),
    M("ts-generics-utility", "typescript", "Generics and Utility Types", 17, "Intermediate", "Write reusable typed functions and transform types with Partial, Pick and more.", ["Write a generic function", "Use utility types", "Constrain generics"]),
    M("ts-real-world", "typescript", "TypeScript in Real Projects", 15, "Intermediate", "tsconfig, strict mode, typing APIs and React props.", ["Configure strict mode", "Type API responses safely", "Type React components"]),
    M("git-command-line", "git", "Command Line Essentials", 14, "Beginner", "Navigate files, read output, pipe commands and use the shell productively.", ["Navigate with cd and ls", "Create, copy and delete safely", "Use pipes and grep"]),
    M("git-introduction", "git", "Git Basics", 15, "Beginner", "Repositories, commits, staging and reading history.", ["Init a repo and commit", "Understand the staging area", "Read git log and diff"]),
    M("git-branching-merging", "git", "Branching and Merging", 16, "Intermediate", "Work in parallel, merge, resolve conflicts and rebase.", ["Create and switch branches", "Resolve a merge conflict", "Choose merge vs rebase"]),
    M("git-remote-github", "git", "Remotes, GitHub and Pull Requests", 15, "Intermediate", "Push, pull, fork and review code with pull requests.", ["Push and pull", "Open a pull request", "Keep a fork up to date"]),
    M("git-undo-workflows", "git", "Undoing Things and Team Workflows", 15, "Advanced", "Restore, reset, revert, stash and the reflog safety net.", ["Undo safely", "Use stash", "Recover with reflog"]),
]

CONTENT = {}

CONTENT["html-introduction"] = [
    ("p", "<strong>HTML</strong> (HyperText Markup Language) describes the <em>structure and meaning</em> of a web page: what is a heading, a paragraph, a link, an image. It does not control appearance (that is CSS) or behavior (that is JavaScript). Every web page you have ever seen starts as HTML."),
    ("h2", "Elements and attributes"),
    ("p", "An <strong>element</strong> is a pair of tags around content: <code>&lt;p&gt;Hello&lt;/p&gt;</code>. The opening tag can carry <strong>attributes</strong>, name/value pairs that configure it. A few elements are <em>void</em> and have no closing tag, such as <code>&lt;img&gt;</code> and <code>&lt;br&gt;</code>."),
    ("code", "html", '<a href="https://stackcone.com" target="_blank" rel="noopener">Visit stackcone</a>\n<img src="logo.png" alt="stackcone logo" width="120">'),
    ("h2", "A page skeleton"),
    ("code", "html", '<!DOCTYPE html>\n<html lang="en">\n<head>\n  <meta charset="UTF-8">\n  <meta name="viewport" content="width=device-width, initial-scale=1">\n  <title>My First Page</title>\n</head>\n<body>\n  <h1>Hello, web</h1>\n  <p>This is a paragraph with <strong>bold</strong> and <em>italic</em> text.</p>\n</body>\n</html>'),
    ("ul", [
        "<code>&lt;!DOCTYPE html&gt;</code> tells the browser to use modern standards.",
        "<code>lang</code> helps screen readers and translation tools.",
        "<code>&lt;head&gt;</code> holds information about the page (title, character set, styles). <code>&lt;body&gt;</code> holds what people see.",
        "The <code>viewport</code> meta tag is essential for pages to display properly on phones.",
    ]),
    ("h2", "Text, lists and links"),
    ("code", "html", '<h1>Main title</h1>       <!-- one per page -->\n<h2>Section</h2>\n<p>Some text.</p>\n\n<ul>\n  <li>Unordered item</li>\n  <li>Another</li>\n</ul>\n<ol>\n  <li>First</li>\n  <li>Second</li>\n</ol>\n\n<a href="/about/">Relative link</a>\n<a href="#contact">Jump to a section</a>'),
    ("p", "Use headings in order (h1, then h2, then h3) to outline the page. Do not choose a heading level because of its size; that is CSS's job."),
    ("h2", "Images and alt text"),
    ("p", "Every <code>&lt;img&gt;</code> needs an <code>alt</code> attribute describing it. Screen readers read it aloud, and it shows if the image fails to load. Use an empty <code>alt=\"\"</code> for purely decorative images. Setting <code>width</code> and <code>height</code> prevents layout jumps while the image loads, and <code>loading=\"lazy\"</code> defers off-screen images."),
    ("h2", "Tables"),
    ("code", "html", '<table>\n  <thead><tr><th>Language</th><th>Year</th></tr></thead>\n  <tbody>\n    <tr><td>Python</td><td>1991</td></tr>\n    <tr><td>Java</td><td>1995</td></tr>\n  </tbody>\n</table>'),
    ("p", "Tables are for tabular data only, never for page layout."),
    ("note", "Validate", "Paste your page into validator.w3.org to catch unclosed tags and other mistakes. Browsers forgive errors silently, which hides bugs."),
    ("exercise", "Create a page about yourself with a title, a photo (with alt text), a list of three skills and a link to a site you like."),
    ("solution", "html", '<!DOCTYPE html>\n<html lang="en">\n<head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>About stackcone</title></head>\n<body>\n  <h1>About stackcone</h1>\n  <img src="me.jpg" alt="Portrait of stackcone" width="160">\n  <h2>Skills</h2>\n  <ul><li>Python</li><li>SQL</li><li>React</li></ul>\n  <p>Favorite site: <a href="https://developer.mozilla.org">MDN</a></p>\n</body>\n</html>'),
]

CONTENT["html-forms-semantics"] = [
    ("p", "Forms collect input, and <strong>semantic</strong> elements tell browsers, search engines and assistive technology what each part of a page <em>is</em>. Getting both right makes your site usable by everyone."),
    ("h2", "Semantic layout"),
    ("code", "html", '<body>\n  <header>\n    <nav><a href="/">Home</a> <a href="/blog/">Blog</a></nav>\n  </header>\n  <main>\n    <article>\n      <h1>Post title</h1>\n      <p>Content...</p>\n    </article>\n    <aside>Related links</aside>\n  </main>\n  <footer>&copy; 2026</footer>\n</body>'),
    ("p", "Prefer these over a sea of <code>&lt;div&gt;</code> elements. Screen-reader users can jump straight to <code>main</code> or <code>nav</code>, and search engines understand the page better. Use <code>&lt;div&gt;</code> and <code>&lt;span&gt;</code> only when nothing more meaningful fits."),
    ("h2", "A form"),
    ("code", "html", '<form action="/signup" method="post">\n  <label for="email">Email</label>\n  <input id="email" name="email" type="email" required autocomplete="email">\n\n  <label for="pw">Password</label>\n  <input id="pw" name="password" type="password" minlength="8" required>\n\n  <label for="plan">Plan</label>\n  <select id="plan" name="plan">\n    <option value="free">Free</option>\n    <option value="pro">Pro</option>\n  </select>\n\n  <fieldset>\n    <legend>Contact by</legend>\n    <label><input type="radio" name="contact" value="email" checked> Email</label>\n    <label><input type="radio" name="contact" value="phone"> Phone</label>\n  </fieldset>\n\n  <label><input type="checkbox" name="terms" required> I agree to the terms</label>\n  <textarea name="notes" rows="3" placeholder="Anything else?"></textarea>\n\n  <button type="submit">Create account</button>\n</form>'),
    ("h2", "Labels matter"),
    ("p", "Every input needs a <code>&lt;label&gt;</code> linked by <code>for</code>/<code>id</code> (or by wrapping the input). Clicking the label focuses the field, and screen readers announce it. Placeholder text is not a substitute, since it disappears as soon as you type."),
    ("h2", "Input types and built-in validation"),
    ("ul", [
        "<code>type</code>: <code>email</code>, <code>url</code>, <code>tel</code>, <code>number</code>, <code>date</code>, <code>password</code>, <code>search</code>, <code>file</code>. Mobile keyboards adapt to the type.",
        "Validation attributes: <code>required</code>, <code>min</code>, <code>max</code>, <code>minlength</code>, <code>maxlength</code>, <code>pattern</code>.",
        "The <code>name</code> attribute is the key sent to the server; an input without one is not submitted.",
    ]),
    ("note", "Server-side too", "Browser validation is a convenience, easily bypassed. Always validate again on the server."),
    ("h2", "Buttons"),
    ("p", "Inside a form a <code>&lt;button&gt;</code> submits by default. Use <code>type=\"button\"</code> for buttons that should not submit. Use a <code>&lt;button&gt;</code> for actions and an <code>&lt;a&gt;</code> for navigation."),
    ("h2", "Accessibility quick wins"),
    ("ul", [
        "Everything usable with a keyboard: tab through your page.",
        "Sufficient color contrast (aim for 4.5:1 for body text).",
        "Meaningful link text: \"Read the pricing guide\", not \"click here\".",
    ]),
    ("exercise", "Build a contact form with name, email, a topic dropdown, a message box and a submit button. Every field needs a label and the email and message must be required."),
    ("solution", "html", '<form action="/contact" method="post">\n  <label for="n">Name</label><input id="n" name="name" required>\n  <label for="e">Email</label><input id="e" name="email" type="email" required>\n  <label for="t">Topic</label>\n  <select id="t" name="topic"><option>Sales</option><option>Support</option></select>\n  <label for="m">Message</label><textarea id="m" name="message" required></textarea>\n  <button type="submit">Send</button>\n</form>'),
]

CONTENT["css-basics"] = [
    ("p", "<strong>CSS</strong> (Cascading Style Sheets) controls how HTML looks: colors, fonts, spacing and layout. A rule has a <em>selector</em> (what to style) and <em>declarations</em> (how to style it)."),
    ("code", "css", "h1 {\n  color: #0a0a0a;\n  font-size: 2rem;\n}"),
    ("p", "Link a stylesheet from the head of your page: <code>&lt;link rel=\"stylesheet\" href=\"styles.css\"&gt;</code>."),
    ("h2", "Selectors"),
    ("code", "css", "p { }                    /* every paragraph */\n.card { }                 /* elements with class=\"card\" */\n#hero { }                 /* the element with id=\"hero\" */\nnav a { }                 /* links inside nav */\nul > li { }               /* direct children only */\na:hover { }               /* when hovered */\ninput:focus-visible { }   /* keyboard focus */\nbutton[disabled] { }      /* attribute selector */"),
    ("p", "Prefer <strong>classes</strong> for styling. IDs are too specific, and element selectors are too broad."),
    ("h2", "The cascade and specificity"),
    ("p", "When rules conflict, CSS picks a winner: the more <em>specific</em> selector wins (ID beats class beats element), and if specificity is equal, the rule that comes <em>later</em> wins. Some properties are also <em>inherited</em> by children, such as <code>color</code> and <code>font-family</code>. Avoid <code>!important</code>; it makes styles hard to override and debug."),
    ("h2", "The box model"),
    ("p", "Every element is a box made of <strong>content</strong>, <strong>padding</strong> (space inside), <strong>border</strong> and <strong>margin</strong> (space outside). By default, <code>width</code> covers only the content, so adding padding makes the box larger. Almost every stylesheet begins by fixing that:"),
    ("code", "css", "*, *::before, *::after {\n  box-sizing: border-box;   /* width includes padding and border */\n}\n\n.card {\n  width: 300px;\n  padding: 1rem;\n  border: 1px solid #ddd;\n  border-radius: 8px;\n  margin: 0 auto 1.5rem;\n}"),
    ("h2", "Units and colors"),
    ("ul", [
        "<code>px</code>: fixed pixels. <code>rem</code>: relative to the root font size (great for accessible sizing). <code>em</code>: relative to the current font size.",
        "<code>%</code>, <code>vw</code>, <code>vh</code>: relative to the parent or the viewport.",
        "Colors: names (<code>tomato</code>), hex (<code>#ff6347</code>), <code>rgb()</code>, <code>hsl()</code>.",
    ]),
    ("h2", "Typography"),
    ("code", "css", "body {\n  font-family: system-ui, -apple-system, \"Segoe UI\", sans-serif;\n  font-size: 1rem;\n  line-height: 1.6;\n  color: #222;\n}\nh1 { font-weight: 700; letter-spacing: -0.02em; }"),
    ("h2", "Custom properties"),
    ("p", "CSS variables keep values consistent and make theming easy."),
    ("code", "css", ":root {\n  --brand: #2563eb;\n  --radius: 8px;\n}\n.button {\n  background: var(--brand);\n  border-radius: var(--radius);\n  color: white;\n  padding: 0.6rem 1.2rem;\n}\n.button:hover { filter: brightness(1.1); }"),
    ("note", "DevTools", "Right-click an element and choose Inspect. You can see which rules apply, which are overridden, and edit values live. It is the fastest way to learn CSS."),
    ("exercise", "Style a card: a white background, 1rem padding, a subtle border, rounded corners and a hover effect that lifts it with a shadow."),
    ("solution", "css", ".card {\n  background: #fff;\n  padding: 1rem;\n  border: 1px solid #e5e5e5;\n  border-radius: 10px;\n  transition: box-shadow 0.2s, transform 0.2s;\n}\n.card:hover {\n  box-shadow: 0 8px 20px rgba(0, 0, 0, 0.08);\n  transform: translateY(-2px);\n}"),
]

CONTENT["css-flexbox"] = [
    ("p", "<strong>Flexbox</strong> lays items out along one axis (a row or a column) and makes alignment, spacing and distributing free space easy. It replaced hacks with floats and is the right tool for nav bars, toolbars, card rows and centering."),
    ("h2", "The basics"),
    ("p", "Set <code>display: flex</code> on the <em>container</em>. Its direct children become <em>flex items</em>."),
    ("code", "css", ".row {\n  display: flex;\n  gap: 1rem;                 /* space between items */\n}"),
    ("code", "html", '<div class="row">\n  <div>One</div><div>Two</div><div>Three</div>\n</div>'),
    ("h2", "Two axes"),
    ("ul", [
        "<strong>Main axis</strong>: the direction items flow, set by <code>flex-direction</code> (<code>row</code> by default, or <code>column</code>). Controlled by <code>justify-content</code>.",
        "<strong>Cross axis</strong>: perpendicular to it. Controlled by <code>align-items</code>.",
    ]),
    ("code", "css", ".bar {\n  display: flex;\n  justify-content: space-between;  /* start | center | end | space-between | space-around | space-evenly */\n  align-items: center;             /* stretch | start | center | end | baseline */\n}"),
    ("h2", "Perfect centering"),
    ("code", "css", ".center {\n  display: flex;\n  justify-content: center;\n  align-items: center;\n  min-height: 100vh;\n}"),
    ("h2", "How items grow and shrink"),
    ("p", "Three properties on <em>items</em> control sizing: <code>flex-grow</code> (share of spare space), <code>flex-shrink</code> (willingness to get smaller) and <code>flex-basis</code> (starting size). The shorthand <code>flex: 1</code> means \"grow to fill equally\"."),
    ("code", "css", ".sidebar { flex: 0 0 240px; }   /* fixed width, never grows or shrinks */\n.content { flex: 1; }            /* takes all remaining space */"),
    ("h2", "Wrapping"),
    ("code", "css", ".cards {\n  display: flex;\n  flex-wrap: wrap;\n  gap: 1rem;\n}\n.cards > .card {\n  flex: 1 1 260px;      /* at least 260px, share leftover space */\n}"),
    ("p", "Items wrap onto new lines when they would drop below their basis, giving a responsive card row without media queries."),
    ("h2", "A typical nav bar"),
    ("code", "css", ".nav {\n  display: flex;\n  align-items: center;\n  gap: 1.5rem;\n}\n.nav .logo { margin-right: auto; }   /* pushes everything after it to the right */"),
    ("note", "Common mistake", "Applying flex properties to the wrong element. <code>justify-content</code> and <code>align-items</code> go on the container; <code>flex</code> and <code>align-self</code> go on the children."),
    ("exercise", "Build a header with a logo on the left and three links on the right, vertically centered. Then make a footer with three columns of equal width."),
    ("solution", "css", "header { display: flex; align-items: center; gap: 1rem; padding: 1rem; }\nheader .logo { margin-right: auto; }\nfooter { display: flex; gap: 2rem; }\nfooter > * { flex: 1; }"),
]

CONTENT["css-grid-responsive"] = [
    ("p", "<strong>CSS Grid</strong> lays out content in rows <em>and</em> columns at the same time. Use Flexbox for one-dimensional alignment and Grid for whole-page or gallery layouts. Combined with media queries, it lets one page adapt to any screen."),
    ("h2", "A basic grid"),
    ("code", "css", ".grid {\n  display: grid;\n  grid-template-columns: repeat(3, 1fr);   /* three equal columns */\n  gap: 1rem;\n}"),
    ("p", "The <code>fr</code> unit means a fraction of the free space. <code>1fr 2fr</code> creates a column twice as wide as the first."),
    ("h2", "Auto-responsive grid, no media query"),
    ("code", "css", ".gallery {\n  display: grid;\n  grid-template-columns: repeat(auto-fill, minmax(220px, 1fr));\n  gap: 1rem;\n}"),
    ("p", "This fits as many columns of at least 220px as the container allows, and grows them evenly. Resize the window and columns appear or disappear by themselves."),
    ("h2", "Page layout with areas"),
    ("code", "css", ".page {\n  display: grid;\n  grid-template-columns: 220px 1fr;\n  grid-template-rows: auto 1fr auto;\n  grid-template-areas:\n    \"header header\"\n    \"sidebar main\"\n    \"footer footer\";\n  min-height: 100vh;\n}\nheader  { grid-area: header; }\naside   { grid-area: sidebar; }\nmain    { grid-area: main; }\nfooter  { grid-area: footer; }"),
    ("h2", "Mobile-first responsive design"),
    ("p", "Write styles for the smallest screen first, then use <code>min-width</code> media queries to enhance for larger ones. The result is simpler CSS, and phones download less."),
    ("code", "css", ".page { display: block; }             /* phone: everything stacked */\n\n@media (min-width: 768px) {\n  .page {\n    display: grid;\n    grid-template-columns: 220px 1fr;   /* tablet and up */\n  }\n}"),
    ("h2", "Fluid sizing with clamp"),
    ("code", "css", "h1 { font-size: clamp(1.75rem, 4vw, 3rem); }   /* min, preferred, max */\n.container { width: min(100% - 2rem, 1100px); margin-inline: auto; }"),
    ("h2", "Responsive images"),
    ("code", "css", "img { max-width: 100%; height: auto; display: block; }"),
    ("h2", "Dark mode"),
    ("code", "css", ":root { --bg: #fff; --text: #111; }\n@media (prefers-color-scheme: dark) {\n  :root { --bg: #0b0b0b; --text: #eaeaea; }\n}\nbody { background: var(--bg); color: var(--text); }"),
    ("note", "Test it", "Use your browser's device toolbar to try phone widths. Do not design only for your own screen."),
    ("exercise", "Make a three-column card gallery that collapses to two columns under 900px and one column under 600px, using media queries with <code>max-width</code>."),
    ("solution", "css", ".gallery { display: grid; grid-template-columns: repeat(3, 1fr); gap: 1rem; }\n@media (max-width: 900px) { .gallery { grid-template-columns: repeat(2, 1fr); } }\n@media (max-width: 600px) { .gallery { grid-template-columns: 1fr; } }"),
]

# ---------------- TypeScript ----------------
CONTENT["ts-introduction"] = [
    ("p", "<strong>TypeScript</strong> is JavaScript with a type system. You add annotations that describe the shape of your data, and the compiler checks them <em>before</em> the code runs, catching typos, missing fields and wrong arguments while you type. It compiles to plain JavaScript that runs anywhere."),
    ("h2", "Setup"),
    ("code", "bash", "mkdir ts-demo && cd ts-demo\nnpm init -y\nnpm install --save-dev typescript tsx\nnpx tsc --init          # creates tsconfig.json"),
    ("code", "typescript", '// hello.ts\nconst name: string = "stackcone";\nconsole.log(`Hello, ${name}`);'),
    ("code", "bash", "npx tsx hello.ts        # run directly\nnpx tsc                 # or compile to JavaScript"),
    ("h2", "Annotations"),
    ("code", "typescript", 'let count: number = 3;\nlet title: string = "TS";\nlet done: boolean = false;\nlet tags: string[] = ["a", "b"];\nlet pair: [string, number] = ["age", 36];      // tuple\n\nfunction add(a: number, b: number): number {\n  return a + b;\n}'),
    ("h2", "Type inference"),
    ("p", "You do not need to annotate everything. TypeScript infers types from values, so <code>let n = 5</code> is already a <code>number</code>. Annotate function parameters and public return types; let inference handle local variables."),
    ("h2", "Reading an error"),
    ("code", "typescript", 'add(1, "2");'),
    ("output", 'error TS2345: Argument of type \'string\' is not assignable to parameter of type \'number\'.'),
    ("p", "The compiler points to the exact place and explains the mismatch. In plain JavaScript this would have silently produced <code>\"12\"</code> at runtime."),
    ("h2", "any, unknown and never"),
    ("ul", [
        "<code>any</code> turns off type checking for a value. Avoid it; it hides bugs.",
        "<code>unknown</code> is the safe alternative: you must check the type before using the value.",
        "<code>never</code> marks code that cannot happen, such as a function that always throws.",
    ]),
    ("code", "typescript", 'function parse(input: unknown): number {\n  if (typeof input === "number") return input;\n  if (typeof input === "string") return Number(input);\n  throw new Error("cannot parse");\n}'),
    ("note", "Types vanish", "Types exist only at compile time. They are erased in the output, so they cannot check data arriving from an API at runtime; you will handle that in a later lesson."),
    ("exercise", "Write a function <code>average(nums: number[]): number</code> and confirm the compiler rejects <code>average(\"1,2,3\")</code>."),
    ("solution", "typescript", 'function average(nums: number[]): number {\n  return nums.reduce((a, b) => a + b, 0) / nums.length;\n}\naverage([1, 2, 3]);        // OK: 2\n// average("1,2,3");        // Error: string is not assignable to number[]'),
]

CONTENT["ts-types-interfaces"] = [
    ("p", "Real data has structure. TypeScript lets you name that structure and reuse it, so every function that touches a <code>User</code> agrees on what a user looks like."),
    ("h2", "Interfaces and type aliases"),
    ("code", "typescript", 'interface User {\n  id: number;\n  name: string;\n  email?: string;          // optional\n  readonly createdAt: Date; // cannot be reassigned\n}\n\nconst ada: User = { id: 1, name: "Ada", createdAt: new Date() };\n\nfunction greet(user: User): string {\n  return `Hi ${user.name}`;\n}\n\ntype Point = { x: number; y: number };'),
    ("p", "<code>interface</code> and <code>type</code> overlap heavily. A good rule: use <code>interface</code> for object shapes you may extend, and <code>type</code> for unions and everything else. Pick one convention per project."),
    ("code", "typescript", 'interface Admin extends User {\n  permissions: string[];\n}'),
    ("h2", "Union types"),
    ("p", "A union says a value can be one of several types. Combined with <strong>literal types</strong>, it models a fixed set of options far better than plain strings."),
    ("code", "typescript", 'type Id = number | string;\ntype Status = "idle" | "loading" | "error" | "success";\n\nfunction setStatus(s: Status) { /* ... */ }\nsetStatus("loading");      // OK\n// setStatus("loding");    // Error: typo caught at compile time'),
    ("h2", "Narrowing"),
    ("p", "Inside a branch that checks the type, TypeScript narrows the union automatically."),
    ("code", "typescript", 'function format(id: number | string): string {\n  if (typeof id === "number") {\n    return id.toFixed(0);        // here id is number\n  }\n  return id.toUpperCase();       // here id is string\n}'),
    ("h2", "Discriminated unions"),
    ("p", "Give each variant a shared literal field, and TypeScript can tell them apart. This is perfect for API results and UI state."),
    ("code", "typescript", 'type Result =\n  | { status: "success"; data: string[] }\n  | { status: "error"; message: string };\n\nfunction show(r: Result) {\n  switch (r.status) {\n    case "success": return r.data.join(", ");\n    case "error":   return `Failed: ${r.message}`;\n  }\n}'),
    ("p", "If you later add a third variant and forget to handle it, the compiler flags the incomplete switch. That safety net is a major reason teams adopt TypeScript."),
    ("h2", "Enums versus literal unions"),
    ("p", "Most modern code prefers string literal unions (as above) or <code>as const</code> objects to <code>enum</code>, since they produce no extra runtime code."),
    ("code", "typescript", 'const ROLES = ["admin", "editor", "viewer"] as const;\ntype Role = (typeof ROLES)[number];    // "admin" | "editor" | "viewer"'),
    ("exercise", "Model a <code>Shape</code> as a discriminated union of circle (radius) and rectangle (width, height), and write <code>area(shape)</code> using a switch."),
    ("solution", "typescript", 'type Shape =\n  | { kind: "circle"; radius: number }\n  | { kind: "rect"; width: number; height: number };\n\nfunction area(s: Shape): number {\n  switch (s.kind) {\n    case "circle": return Math.PI * s.radius ** 2;\n    case "rect":   return s.width * s.height;\n  }\n}'),
]

CONTENT["ts-generics-utility"] = [
    ("p", "Sometimes the same logic works for many types: returning the first item of any array, wrapping any value in a response. <strong>Generics</strong> let you write that code once while keeping full type safety, rather than falling back to <code>any</code>."),
    ("h2", "A generic function"),
    ("code", "typescript", 'function first<T>(items: T[]): T | undefined {\n  return items[0];\n}\n\nconst n = first([1, 2, 3]);        // number | undefined\nconst s = first(["a", "b"]);       // string | undefined'),
    ("p", "<code>T</code> is a type parameter, a placeholder filled in from the arguments. The compiler remembers that numbers went in, so numbers come out."),
    ("h2", "Generic types and interfaces"),
    ("code", "typescript", 'interface ApiResponse<T> {\n  data: T;\n  error: string | null;\n}\n\ninterface Product { id: number; title: string; }\n\nconst res: ApiResponse<Product[]> = {\n  data: [{ id: 1, title: "Pen" }],\n  error: null,\n};'),
    ("h2", "Constraints"),
    ("p", "Use <code>extends</code> to require that a type parameter has certain properties."),
    ("code", "typescript", 'function longest<T extends { length: number }>(a: T, b: T): T {\n  return a.length >= b.length ? a : b;\n}\n\nlongest("apple", "fig");        // works for strings\nlongest([1, 2], [1, 2, 3]);     // and arrays\n// longest(1, 2);               // Error: number has no length'),
    ("code", "typescript", 'function getProp<T, K extends keyof T>(obj: T, key: K): T[K] {\n  return obj[key];\n}\ngetProp({ id: 1, name: "Ada" }, "name");   // string\n// getProp({ id: 1 }, "email");            // Error: not a key'),
    ("h2", "Utility types"),
    ("p", "TypeScript ships helpers that build new types from existing ones."),
    ("code", "typescript", 'interface User { id: number; name: string; email: string; }\n\ntype Draft     = Partial<User>;                 // every field optional\ntype Required_ = Required<User>;                // every field required\ntype Preview   = Pick<User, "id" | "name">;     // only these keys\ntype NoEmail   = Omit<User, "email">;           // all but this key\ntype Roles     = Record<string, "admin" | "user">;   // map of string keys\ntype Frozen    = Readonly<User>;\n\nfunction updateUser(id: number, changes: Partial<User>) { /* ... */ }'),
    ("h2", "Deriving types from values"),
    ("code", "typescript", 'const config = { host: "localhost", port: 5432 };\ntype Config = typeof config;          // { host: string; port: number }\n\nasync function load() { return { id: 1, name: "Ada" }; }\ntype Loaded = Awaited<ReturnType<typeof load>>;   // { id: number; name: string }'),
    ("note", "Keep it readable", "Generics are powerful but can become cryptic. If a type takes minutes to understand, consider simplifying it, or splitting it into named pieces."),
    ("exercise", "Write a generic <code>groupBy&lt;T&gt;(items: T[], key: keyof T)</code> returning a record from key value to arrays of items."),
    ("solution", "typescript", 'function groupBy<T>(items: T[], key: keyof T): Record<string, T[]> {\n  const out: Record<string, T[]> = {};\n  for (const item of items) {\n    const k = String(item[key]);\n    (out[k] ??= []).push(item);\n  }\n  return out;\n}\n\ngroupBy([{ t: "a", n: 1 }, { t: "a", n: 2 }, { t: "b", n: 3 }], "t");'),
]

CONTENT["ts-real-world"] = [
    ("p", "Moving from exercises to a real project involves configuration, typing data that comes from outside your code, and typing your framework. This lesson covers the practical parts."),
    ("h2", "tsconfig and strict mode"),
    ("code", "json", '{\n  "compilerOptions": {\n    "target": "ES2022",\n    "module": "ESNext",\n    "moduleResolution": "Bundler",\n    "strict": true,\n    "noUncheckedIndexedAccess": true,\n    "esModuleInterop": true,\n    "skipLibCheck": true,\n    "outDir": "dist"\n  },\n  "include": ["src"]\n}'),
    ("p", "<code>\"strict\": true</code> turns on the checks that make TypeScript worth using: no implicit <code>any</code>, and strict null checks (a value that may be <code>null</code> must be handled). Start every new project with it enabled."),
    ("h2", "Null safety"),
    ("code", "typescript", 'function firstWord(s: string | null): string {\n  if (s === null) return "";\n  return s.split(" ")[0];\n}\n\nconst el = document.querySelector("#name");    // Element | null\nel?.classList.add("active");                     // optional chaining'),
    ("p", "Avoid the non-null assertion <code>el!</code> unless you are truly certain; it just silences the compiler."),
    ("h2", "Typing data from an API"),
    ("p", "<code>response.json()</code> returns <code>any</code>, and types are erased at runtime, so an annotation alone does not prove the data matches. Validate at the boundary with a schema library like <strong>zod</strong> and derive the type from it."),
    ("code", "typescript", 'import { z } from "zod";\n\nconst UserSchema = z.object({\n  id: z.number(),\n  name: z.string(),\n  email: z.string().email(),\n});\ntype User = z.infer<typeof UserSchema>;\n\nasync function getUser(id: number): Promise<User> {\n  const res = await fetch(`/api/users/${id}`);\n  if (!res.ok) throw new Error(`HTTP ${res.status}`);\n  return UserSchema.parse(await res.json());     // throws if the shape is wrong\n}'),
    ("h2", "Typing React"),
    ("code", "typescript", 'import { useState } from "react";\n\ninterface ButtonProps {\n  label: string;\n  variant?: "primary" | "danger";\n  onClick: () => void;\n}\n\nfunction Button({ label, variant = "primary", onClick }: ButtonProps) {\n  return <button className={variant} onClick={onClick}>{label}</button>;\n}\n\nfunction Counter() {\n  const [items, setItems] = useState<string[]>([]);   // give state an explicit type\n  const [user, setUser] = useState<User | null>(null);\n  return <Button label="Add" onClick={() => setItems([...items, "x"])} />;\n}'),
    ("h2", "Migrating gradually"),
    ("ul", [
        "Enable <code>allowJs</code> and rename files from <code>.js</code> to <code>.ts</code> one at a time.",
        "Start with the shared models and utility functions, then the leaves.",
        "Use <code>// @ts-expect-error</code> with a comment for known issues instead of <code>any</code> everywhere.",
        "Run <code>tsc --noEmit</code> in CI so type errors fail the build.",
    ]),
    ("note", "Declaration files", "Libraries without built-in types have community ones: <code>npm install --save-dev @types/node</code> gives you types for Node.js."),
    ("exercise", "Write a zod schema for a <code>Todo</code> (<code>id</code>, <code>title</code>, <code>done</code>), derive its type and write a typed <code>fetchTodos()</code> returning <code>Todo[]</code>."),
    ("solution", "typescript", 'const TodoSchema = z.object({ id: z.number(), title: z.string(), done: z.boolean() });\ntype Todo = z.infer<typeof TodoSchema>;\n\nasync function fetchTodos(): Promise<Todo[]> {\n  const res = await fetch("/api/todos");\n  return z.array(TodoSchema).parse(await res.json());\n}'),
]

# ---------------- Git & CLI ----------------
CONTENT["git-command-line"] = [
    ("p", "The <strong>command line</strong> (terminal, shell) lets you control your computer by typing commands. Developers use it constantly because it is fast, scriptable and the same on servers as on laptops. Git, Docker, npm and most tools are driven from it. The examples use bash/zsh (macOS, Linux, WSL, Git Bash)."),
    ("h2", "Where am I? Moving around"),
    ("code", "bash", "pwd                 # print working directory\nls                  # list files\nls -la              # long format, including hidden files\ncd projects         # go into a folder\ncd ..               # go up one level\ncd ~                # go home\ncd -                # go back to the previous folder"),
    ("p", "Paths can be <em>absolute</em> (start with <code>/</code>, like <code>/Users/stackcone/code</code>) or <em>relative</em> to where you are. Press <strong>Tab</strong> to autocomplete names and the <strong>up arrow</strong> to recall previous commands."),
    ("h2", "Creating, copying, moving, deleting"),
    ("code", "bash", "mkdir notes                 # new folder\nmkdir -p a/b/c              # nested folders\ntouch todo.txt              # empty file\ncp todo.txt backup.txt      # copy\nmv backup.txt notes/        # move (also renames)\nrm todo.txt                 # delete a file\nrm -r notes                 # delete a folder and contents"),
    ("note", "No trash can", "<code>rm</code> is permanent. Double-check paths, and never run <code>rm -rf</code> on something you have not looked at. Try <code>ls</code> with the same path first."),
    ("h2", "Looking inside files"),
    ("code", "bash", "cat file.txt            # print whole file\nless file.txt           # scroll through (q to quit)\nhead -n 5 file.txt      # first 5 lines\ntail -n 20 app.log      # last 20 lines\ntail -f app.log         # follow a growing log\nwc -l file.txt          # count lines"),
    ("h2", "Searching"),
    ("code", "bash", 'grep "error" app.log            # lines containing "error"\ngrep -rn "TODO" src/            # search recursively, show line numbers\ngrep -i "warning" app.log       # ignore case\nfind . -name "*.py"             # find files by name'),
    ("h2", "Pipes and redirection"),
    ("p", "The pipe <code>|</code> sends one command's output into another's input, letting you build powerful one-liners from small tools. <code>&gt;</code> writes output to a file, and <code>&gt;&gt;</code> appends."),
    ("code", "bash", 'cat access.log | grep " 500 " | wc -l         # how many 500 errors?\nls -l | sort -k5 -n | tail -3                # three biggest files\necho "hello" > out.txt\necho "world" >> out.txt'),
    ("h2", "Environment and permissions"),
    ("code", "bash", 'echo $HOME\nexport API_URL="https://example.com"      # set a variable for this session\nchmod +x script.sh                        # make a file executable\n./script.sh                               # run it\nwhich python3                             # where is this command?'),
    ("h2", "Getting help"),
    ("code", "bash", "man ls           # the manual page\nls --help        # quick usage\nhistory | grep git"),
    ("exercise", "In a scratch folder, create a directory <code>demo</code>, write three lines into <code>demo/list.txt</code> with <code>echo</code> and <code>&gt;&gt;</code>, then use <code>grep</code> to print only the lines containing a chosen word."),
    ("solution", "bash", 'mkdir demo\necho "apple pie" >> demo/list.txt\necho "banana split" >> demo/list.txt\necho "apple tart" >> demo/list.txt\ngrep "apple" demo/list.txt'),
]

CONTENT["git-introduction"] = [
    ("p", "<strong>Git</strong> is a version control system: it records the history of your project so you can see what changed, when and why, go back to any earlier state, and work with others without overwriting each other. Almost every software team uses it."),
    ("h2", "Setup"),
    ("code", "bash", 'git --version\ngit config --global user.name "Your Name"\ngit config --global user.email "you@example.com"\ngit config --global init.defaultBranch main'),
    ("h2", "The three areas"),
    ("ul", [
        "<strong>Working directory</strong>: your files as they are right now.",
        "<strong>Staging area (index)</strong>: the changes you have chosen to include in the next commit.",
        "<strong>Repository</strong>: the permanent history of commits.",
    ]),
    ("p", "The staging area is what lets you craft a clean commit from a messy day of edits: stage only the related changes together."),
    ("h2", "Your first repository"),
    ("code", "bash", 'mkdir my-project && cd my-project\ngit init\necho "# My Project" > README.md\n\ngit status                    # what is going on?\ngit add README.md             # stage it\ngit commit -m "Add README"    # record it'),
    ("output", "[main (root-commit) a1b2c3d] Add README\n 1 file changed, 1 insertion(+)\n create mode 100644 README.md"),
    ("h2", "The everyday loop"),
    ("code", "bash", "# edit files...\ngit status               # see changed files\ngit diff                 # see what changed (unstaged)\ngit add -p               # stage chosen hunks interactively\ngit add .                # or stage everything\ngit diff --staged        # review what will be committed\ngit commit -m \"Fix login redirect\""),
    ("h2", "Reading history"),
    ("code", "bash", "git log                        # full history\ngit log --oneline --graph -10   # compact view\ngit show a1b2c3d                # one commit's changes\ngit blame README.md             # who last changed each line"),
    ("h2", "Good commits"),
    ("ul", [
        "One logical change per commit. It should be easy to describe in one line.",
        "Write in the imperative: \"Add search filter\", not \"added\" or \"stuff\".",
        "Keep the first line under about 50 characters; add detail after a blank line if needed.",
    ]),
    ("h2", ".gitignore"),
    ("p", "List files Git should never track: dependencies, build output, secrets."),
    ("code", "bash", "node_modules/\n.venv/\n__pycache__/\n.env\n.DS_Store\ndist/"),
    ("note", "Never commit secrets", "API keys and passwords committed once stay in history even after you delete them. Keep them in <code>.env</code> (ignored) and rotate any key that leaks."),
    ("exercise", "Create a repo, make three commits (add a file, edit it, add another), then use <code>git log --oneline</code> and <code>git show</code> to view the second commit."),
    ("solution", "bash", 'git init demo && cd demo\necho "one" > a.txt && git add a.txt && git commit -m "Add a.txt"\necho "two" >> a.txt && git commit -am "Edit a.txt"\necho "b" > b.txt && git add b.txt && git commit -m "Add b.txt"\ngit log --oneline\ngit show HEAD~1'),
]

CONTENT["git-branching-merging"] = [
    ("p", "A <strong>branch</strong> is an independent line of development. Branches let you build a feature or fix a bug without disturbing the stable code, then combine the work when it is ready. In Git, branches are extremely cheap: just a movable pointer to a commit."),
    ("h2", "Working with branches"),
    ("code", "bash", "git branch                     # list branches\ngit switch -c feature/login    # create AND switch to a new branch\n# ...edit, commit...\ngit switch main                # go back\ngit branch -d feature/login    # delete a merged branch"),
    ("p", "<code>HEAD</code> is Git's name for \"where you are now\". Committing moves the current branch forward."),
    ("h2", "Merging"),
    ("code", "bash", "git switch main\ngit merge feature/login"),
    ("ul", [
        "<strong>Fast-forward</strong>: if main has not moved, Git just slides its pointer forward.",
        "<strong>Merge commit</strong>: if both branches have new commits, Git creates a commit with two parents that joins them.",
    ]),
    ("h2", "Merge conflicts"),
    ("p", "A conflict occurs when both branches changed the same lines. Git stops and marks the file:"),
    ("code", "text", "<<<<<<< HEAD\nconst title = \"Welcome\";\n=======\nconst title = \"Hello there\";\n>>>>>>> feature/login"),
    ("p", "To resolve: open the file, choose or combine the correct code, delete the three marker lines, then finish."),
    ("code", "bash", "git add src/app.js\ngit commit            # completes the merge\n# changed your mind?  git merge --abort"),
    ("note", "Not scary", "Conflicts are normal in team work. Small, frequent merges and pulling often keep them small."),
    ("h2", "Rebase"),
    ("p", "<code>git rebase main</code> replays your branch's commits on top of the latest main, producing a straight, linear history instead of a merge commit."),
    ("code", "bash", "git switch feature/login\ngit rebase main          # re-apply my commits on top of main\ngit switch main\ngit merge feature/login  # now a clean fast-forward"),
    ("note", "Golden rule of rebasing", "Never rebase commits that others have already pulled. Rebase rewrites history, which causes chaos for anyone who has the old version. Rebase your own local work freely."),
    ("h2", "Naming and habits"),
    ("ul", [
        "Prefix names by intent: <code>feature/</code>, <code>fix/</code>, <code>chore/</code>.",
        "Keep branches short-lived: days, not months.",
        "Keep <code>main</code> always working.",
    ]),
    ("exercise", "Create a branch, change the same line of a file on both the branch and main, merge, then resolve the conflict by keeping both changes."),
    ("solution", "bash", 'echo "hi" > f.txt && git add f.txt && git commit -m "init"\ngit switch -c feature\necho "from feature" > f.txt && git commit -am "feature edit"\ngit switch main\necho "from main" > f.txt && git commit -am "main edit"\ngit merge feature       # CONFLICT\n# edit f.txt to contain both lines, remove markers\ngit add f.txt && git commit'),
]

CONTENT["git-remote-github"] = [
    ("p", "So far everything lived on your machine. A <strong>remote</strong> is a copy of the repository hosted elsewhere, usually on GitHub, GitLab or Bitbucket. It is how you back up work, share it and collaborate."),
    ("h2", "Connecting a remote"),
    ("code", "bash", "git clone https://github.com/user/repo.git        # copy an existing repo\n\n# or connect an existing local repo\ngit remote add origin git@github.com:user/repo.git\ngit remote -v\ngit push -u origin main       # first push; -u remembers the link"),
    ("p", "<code>origin</code> is just the conventional name of your main remote. Use SSH keys (or a credential helper) so you are not typing passwords."),
    ("h2", "Push, fetch and pull"),
    ("code", "bash", "git push                 # upload my commits\ngit fetch                # download others' commits without touching my files\ngit pull                 # fetch + merge (or rebase) into my branch\ngit pull --rebase        # keep history linear"),
    ("p", "If a push is rejected with \"non-fast-forward\", someone else pushed first. Pull, resolve anything needed, and push again."),
    ("h2", "The pull request workflow"),
    ("ul", [
        "1. Update <code>main</code> (<code>git pull</code>) and branch off it.",
        "2. Commit your work, then <code>git push -u origin feature/x</code>.",
        "3. On GitHub, open a <strong>pull request</strong> (PR) from your branch into <code>main</code>.",
        "4. Teammates review, comment and request changes; automated checks (CI) run.",
        "5. Push more commits to the same branch to update the PR. When approved, merge it.",
        "6. Delete the branch and pull the updated <code>main</code>.",
    ]),
    ("p", "A good PR is small, has a clear title and description (what and why), and links the issue it solves. Reviewers can then respond in minutes instead of hours."),
    ("h2", "Forks"),
    ("p", "For open source projects you cannot push to, <strong>fork</strong> the repo (your own copy on GitHub), clone your fork, and open PRs from it. Keep it updated by adding the original as a second remote:"),
    ("code", "bash", "git remote add upstream https://github.com/original/repo.git\ngit fetch upstream\ngit switch main\ngit merge upstream/main\ngit push origin main"),
    ("h2", "GitHub CLI"),
    ("code", "bash", 'gh auth login\ngh pr create --fill              # open a PR from the current branch\ngh pr checkout 123              # try someone else\'s PR locally\ngh pr merge --squash'),
    ("note", "Protect main", "Turn on branch protection: require PRs, reviews and passing checks before merging. It prevents accidents."),
    ("exercise", "Create a repo on GitHub, clone it, create a branch, push a change and open a pull request from it."),
    ("solution", "bash", 'git clone git@github.com:you/practice.git && cd practice\ngit switch -c docs/add-notes\necho "notes" > NOTES.md && git add NOTES.md && git commit -m "Add notes"\ngit push -u origin docs/add-notes\ngh pr create --fill'),
]

CONTENT["git-undo-workflows"] = [
    ("p", "Everyone makes mistakes: a commit in the wrong branch, a bad edit, a message typo. Git gives you many ways to undo, but they behave differently. Knowing which is safe on <em>shared</em> history versus <em>local</em> history keeps you out of trouble."),
    ("h2", "Discard uncommitted changes"),
    ("code", "bash", "git restore file.txt              # throw away edits to a file (cannot be undone!)\ngit restore --staged file.txt     # unstage, keep the edits\ngit clean -n                      # preview untracked files that would be removed"),
    ("h2", "Fix the last commit"),
    ("code", "bash", 'git commit --amend -m "Better message"   # change message\ngit add forgotten.txt\ngit commit --amend --no-edit               # add a file to the last commit'),
    ("p", "<code>--amend</code> rewrites the last commit, so only do it before you push."),
    ("h2", "revert: the safe undo for shared history"),
    ("p", "<code>git revert</code> creates a <em>new</em> commit that reverses an earlier one. History is preserved, so it is safe to push."),
    ("code", "bash", "git revert a1b2c3d"),
    ("h2", "reset: move the branch pointer"),
    ("code", "bash", "git reset --soft HEAD~1    # undo the commit, keep changes staged\ngit reset HEAD~1           # undo the commit, keep changes unstaged (--mixed)\ngit reset --hard HEAD~1    # undo the commit AND delete the changes"),
    ("note", "Danger", "<code>--hard</code> discards work. Never reset commits that are already pushed and shared; use <code>revert</code> instead."),
    ("h2", "stash: set work aside"),
    ("p", "Need to switch branches but your changes are not ready to commit?"),
    ("code", "bash", 'git stash push -m "wip login form"\ngit switch other-branch\n# ...do something...\ngit switch -\ngit stash list\ngit stash pop            # bring the changes back'),
    ("h2", "reflog: your safety net"),
    ("p", "Git records every place <code>HEAD</code> has been, for about 90 days, even for commits no branch points to. If you think you lost work after a bad reset or a deleted branch, look here."),
    ("code", "bash", "git reflog\n# a1b2c3d HEAD@{0}: reset: moving to HEAD~3\n# 9f8e7d6 HEAD@{1}: commit: Add checkout page\ngit reset --hard 9f8e7d6      # jump back to before the mistake"),
    ("h2", "Other useful tools"),
    ("ul", [
        "<code>git cherry-pick &lt;sha&gt;</code>: copy one commit onto the current branch.",
        "<code>git bisect</code>: binary search through history to find the commit that introduced a bug.",
        "<code>git tag v1.0.0</code>: mark a release.",
    ]),
    ("h2", "Team workflow summary"),
    ("ul", [
        "<strong>GitHub Flow</strong>: short-lived branches and PRs into <code>main</code>, deploy from main. Simple and popular.",
        "<strong>Trunk-based</strong>: very small changes merged to main daily, behind feature flags.",
        "<strong>Git Flow</strong>: long-lived develop and release branches. Heavier; suited to versioned releases.",
    ]),
    ("exercise", "Make two commits, then use <code>git reset --hard HEAD~1</code> to lose the second. Recover it using <code>git reflog</code>."),
    ("solution", "bash", 'echo 1 > f && git add f && git commit -m "one"\necho 2 >> f && git commit -am "two"\ngit reset --hard HEAD~1\ngit reflog                    # find the SHA of "two"\ngit reset --hard <sha-of-two>'),
]
