"""Algorithms track."""
from content_js_sql import M

META = [
    M("algo-searching", "algorithms", "Searching", 13, "Beginner", "Linear search, binary search and how to search an answer space.", ["Write binary search without off-by-one bugs", "Know when data must be sorted", "Use the bisect module"]),
    M("algo-sorting", "algorithms", "Sorting", 18, "Intermediate", "Bubble, merge and quick sort, plus stability and what Python really uses.", ["Compare O(n^2) and O(n log n) sorts", "Implement merge sort", "Sort with keys"]),
    M("algo-recursion", "algorithms", "Recursion", 15, "Intermediate", "Base cases, recursive cases, the call stack and when to avoid recursion.", ["Identify base and recursive cases", "Trace the call stack", "Convert recursion to iteration"]),
    M("algo-greedy", "algorithms", "Greedy Algorithms", 14, "Intermediate", "Make the locally best choice at each step, and know when that is enough.", ["Explain the greedy choice property", "Solve interval scheduling", "Spot when greedy fails"]),
    M("algo-backtracking", "algorithms", "Backtracking", 16, "Advanced", "Explore choices, undo them, and generate permutations and subsets.", ["Use choose-explore-unchoose", "Generate subsets and permutations", "Prune the search"]),
    M("algo-dynamic-programming", "algorithms", "Dynamic Programming", 20, "Advanced", "Overlapping subproblems, memoization, tabulation, knapsack and edit distance.", ["Recognize DP problems", "Write memoized and tabulated solutions", "Reduce space"]),
]

CONTENT = {}

CONTENT["algo-searching"] = [
    ("p", "Searching means finding an item, or its position, inside a collection. How you do it depends on one question: <strong>is the data sorted?</strong> Sorted data lets you throw away half the possibilities at every step."),
    ("h2", "Linear search"),
    ("p", "Check items one by one. It works on any data and takes O(n) time, so it is perfectly fine for small lists or one-off lookups."),
    ("code", "python", 'def linear_search(items, target):\n    for i, x in enumerate(items):\n        if x == target:\n            return i\n    return -1\n\nprint(linear_search([7, 3, 9, 1], 9))'),
    ("output", "2"),
    ("h2", "Binary search"),
    ("p", "On a <strong>sorted</strong> list, compare the target with the middle element. If it is smaller, the answer must be in the left half; if larger, the right half. Each comparison halves the search space, giving <strong>O(log n)</strong>: a billion items need about 30 checks."),
    ("code", "python", 'def binary_search(a, target):\n    lo, hi = 0, len(a) - 1\n    while lo <= hi:\n        mid = (lo + hi) // 2\n        if a[mid] == target:\n            return mid\n        if a[mid] < target:\n            lo = mid + 1\n        else:\n            hi = mid - 1\n    return -1\n\nnums = [1, 3, 5, 7, 9, 11, 13]\nprint(binary_search(nums, 9), binary_search(nums, 4))'),
    ("output", "4 -1"),
    ("p", "The details that cause bugs: the loop condition is <code>lo &lt;= hi</code> (the range is inclusive on both ends), and the updates are <code>mid + 1</code> and <code>mid - 1</code> so the range always shrinks. Getting either wrong produces an infinite loop or a missed element."),
    ("h2", "Finding a boundary"),
    ("p", "A very common variant: find the first position where a condition becomes true, or the insertion point for a value. Python ships this as <code>bisect</code>."),
    ("code", "python", 'from bisect import bisect_left, bisect_right\n\na = [1, 2, 2, 2, 5, 8]\nprint(bisect_left(a, 2))    # 1  first index of 2\nprint(bisect_right(a, 2))   # 4  index after the last 2\nprint(bisect_right(a, 2) - bisect_left(a, 2))   # count of 2s'),
    ("output", "1\n4\n3"),
    ("h2", "Searching the answer"),
    ("p", "Binary search is not just for lists. Whenever the answer lies in a range and a yes/no test is <em>monotonic</em> (false, false, false, true, true, true), you can binary search on the answer. Example: the smallest speed that lets you finish a task in time."),
    ("code", "python", 'import math\n\ndef min_speed(piles, hours):\n    """Smallest k so that ceil(pile/k) summed over piles <= hours."""\n    lo, hi = 1, max(piles)\n    while lo < hi:\n        mid = (lo + hi) // 2\n        if sum(math.ceil(p / mid) for p in piles) <= hours:\n            hi = mid            # mid works, try smaller\n        else:\n            lo = mid + 1        # too slow\n    return lo\n\nprint(min_speed([3, 6, 7, 11], 8))'),
    ("output", "4"),
    ("note", "Prerequisite", "Binary search on unsorted data gives wrong answers silently. If you must search repeatedly, sorting once (O(n log n)) or using a hash set (O(1) lookup) is often better."),
    ("exercise", "Write <code>first_true(a)</code> that receives a list of booleans like <code>[False, False, True, True]</code> (all False first, then all True) and returns the index of the first True, or -1."),
    ("solution", "python", 'def first_true(a):\n    lo, hi, ans = 0, len(a) - 1, -1\n    while lo <= hi:\n        mid = (lo + hi) // 2\n        if a[mid]:\n            ans = mid\n            hi = mid - 1\n        else:\n            lo = mid + 1\n    return ans\n\nprint(first_true([False, False, True, True]))   # 2'),
]

CONTENT["algo-sorting"] = [
    ("p", "Sorting puts items in order, and a great deal of computing depends on it: fast searching, deduplication, merging, and ranking. Understanding a few classic algorithms teaches ideas (divide and conquer, invariants) that reach far beyond sorting itself."),
    ("h2", "Simple sorts: O(n squared)"),
    ("p", "<strong>Bubble sort</strong> repeatedly swaps adjacent items that are out of order, so large values \"bubble\" to the end. <strong>Insertion sort</strong> grows a sorted prefix by inserting each new item into place, like sorting playing cards in your hand. Both are easy to write, and insertion sort is genuinely fast on tiny or nearly sorted inputs."),
    ("code", "python", 'def insertion_sort(a):\n    for i in range(1, len(a)):\n        key = a[i]\n        j = i - 1\n        while j >= 0 and a[j] > key:\n            a[j + 1] = a[j]\n            j -= 1\n        a[j + 1] = key\n    return a\n\nprint(insertion_sort([5, 2, 4, 6, 1, 3]))'),
    ("output", "[1, 2, 3, 4, 5, 6]"),
    ("h2", "Merge sort: O(n log n)"),
    ("p", "Merge sort is <em>divide and conquer</em>: split the list in half, sort each half recursively, then <strong>merge</strong> the two sorted halves by repeatedly taking the smaller front item. The list is halved log n times, and each level of merging does O(n) work, giving O(n log n) always, at the cost of O(n) extra memory."),
    ("code", "python", 'def merge_sort(a):\n    if len(a) <= 1:\n        return a\n    mid = len(a) // 2\n    left, right = merge_sort(a[:mid]), merge_sort(a[mid:])\n    out, i, j = [], 0, 0\n    while i < len(left) and j < len(right):\n        if left[i] <= right[j]:\n            out.append(left[i]); i += 1\n        else:\n            out.append(right[j]); j += 1\n    return out + left[i:] + right[j:]\n\nprint(merge_sort([38, 27, 43, 3, 9, 82, 10]))'),
    ("output", "[3, 9, 10, 27, 38, 43, 82]"),
    ("h2", "Quick sort"),
    ("p", "Pick a <em>pivot</em>, partition the items into smaller and larger, and recursively sort each side. Average time is O(n log n) and it sorts in place, which is why it is so popular. The worst case is O(n squared), for example when the pivot is always the smallest item; picking a random pivot makes that vanishingly unlikely."),
    ("code", "python", 'import random\n\ndef quick_sort(a):\n    if len(a) <= 1:\n        return a\n    pivot = random.choice(a)\n    less    = [x for x in a if x < pivot]\n    equal   = [x for x in a if x == pivot]\n    greater = [x for x in a if x > pivot]\n    return quick_sort(less) + equal + quick_sort(greater)\n\nprint(quick_sort([3, 6, 1, 8, 2, 9, 2]))'),
    ("output", "[1, 2, 2, 3, 6, 8, 9]"),
    ("h2", "What you should actually use"),
    ("p", "In real code, call the built-in. Python's <code>sorted()</code> and <code>list.sort()</code> use Timsort, a hybrid of merge and insertion sort that is O(n log n) worst case and very fast on partially ordered data. Use <code>key=</code> to sort by a computed value and <code>reverse=True</code> for descending."),
    ("code", "python", 'people = [("Ann", 31), ("Bob", 25), ("Cy", 31)]\nprint(sorted(people, key=lambda p: p[1]))\nprint(sorted(people, key=lambda p: (-p[1], p[0])))   # age desc, then name'),
    ("output", "[('Bob', 25), ('Ann', 31), ('Cy', 31)]\n[('Ann', 31), ('Cy', 31), ('Bob', 25)]"),
    ("h2", "Stability"),
    ("p", "A sort is <strong>stable</strong> if equal items keep their original relative order. In the first output above, Ann stays before Cy. Stability lets you sort by one field, then another, and keep the first ordering as a tiebreaker."),
    ("h2", "The lower bound"),
    ("p", "Any sort that works by comparing items needs at least about n log n comparisons in the worst case. Non-comparison sorts such as counting sort get O(n) only when values are small integers in a known range."),
    ("note", "Rule of thumb", "Memorize: bubble/insertion O(n squared), merge/heap O(n log n) always, quick O(n log n) average. Then use the standard library."),
    ("exercise", "Sort a list of words by length, and alphabetically within the same length, using <code>sorted</code> and a tuple key."),
    ("solution", "python", 'words = ["pear", "fig", "apple", "kiwi", "date"]\nprint(sorted(words, key=lambda w: (len(w), w)))\n# [\'fig\', \'date\', \'kiwi\', \'pear\', \'apple\']'),
]

CONTENT["algo-recursion"] = [
    ("p", "A <strong>recursive</strong> function solves a problem by calling itself on a smaller version of the same problem. It feels odd at first, but many problems (trees, nested folders, divide-and-conquer) are naturally recursive, and the code ends up shorter than a loop."),
    ("h2", "Two required parts"),
    ("ul", [
        "<strong>Base case</strong>: the smallest problem, answered directly. Without it, the function never stops.",
        "<strong>Recursive case</strong>: reduce the problem and call yourself, trusting that the call returns the right answer for the smaller input.",
    ]),
    ("code", "python", 'def factorial(n):\n    if n <= 1:               # base case\n        return 1\n    return n * factorial(n - 1)   # recursive case\n\nprint(factorial(5))'),
    ("output", "120"),
    ("h2", "The call stack"),
    ("p", "Each call waits for the one it started. <code>factorial(3)</code> becomes <code>3 * factorial(2)</code>, which becomes <code>3 * (2 * factorial(1))</code>; when the base case returns 1, the stack unwinds multiplying as it goes. Each waiting call uses memory, so Python limits depth (about 1000) and raises <code>RecursionError</code> if you exceed it."),
    ("h2", "More examples"),
    ("code", "python", 'def sum_list(a):\n    return 0 if not a else a[0] + sum_list(a[1:])\n\ndef reverse(s):\n    return s if len(s) <= 1 else reverse(s[1:]) + s[0]\n\ndef power(x, n):                    # fast exponent, O(log n)\n    if n == 0:\n        return 1\n    half = power(x, n // 2)\n    return half * half * (x if n % 2 else 1)\n\nprint(sum_list([1, 2, 3]), reverse("abc"), power(2, 10))'),
    ("output", "6 cba 1024"),
    ("h2", "Recursion on nested data"),
    ("p", "Recursion shines when data has no fixed depth, like a nested list or a directory tree."),
    ("code", "python", 'def flatten(x):\n    out = []\n    for item in x:\n        if isinstance(item, list):\n            out.extend(flatten(item))\n        else:\n            out.append(item)\n    return out\n\nprint(flatten([1, [2, [3, 4]], 5]))'),
    ("output", "[1, 2, 3, 4, 5]"),
    ("h2", "The Fibonacci trap"),
    ("p", "Naive <code>fib(n) = fib(n-1) + fib(n-2)</code> recomputes the same values over and over and takes exponential time. Caching results fixes it, which leads straight into dynamic programming."),
    ("code", "python", 'from functools import lru_cache\n\n@lru_cache(maxsize=None)\ndef fib(n):\n    return n if n < 2 else fib(n - 1) + fib(n - 2)\n\nprint(fib(50))'),
    ("output", "12586269025"),
    ("h2", "Recursion vs iteration"),
    ("p", "Anything recursive can be written with a loop and an explicit stack. Prefer a loop when depth could be large or the loop is just as clear; prefer recursion when it mirrors the structure of the problem."),
    ("note", "Debugging tip", "Write the base case first, then check that every recursive call moves strictly closer to it. Print the arguments at the top of the function to watch the stack build."),
    ("exercise", "Write a recursive <code>is_palindrome(s)</code> that returns True if a string reads the same backward."),
    ("solution", "python", 'def is_palindrome(s):\n    if len(s) <= 1:\n        return True\n    return s[0] == s[-1] and is_palindrome(s[1:-1])\n\nprint(is_palindrome("level"), is_palindrome("stack"))'),
]

CONTENT["algo-greedy"] = [
    ("p", "A <strong>greedy algorithm</strong> builds a solution one step at a time, always taking the choice that looks best right now, and never reconsidering. When it works, greedy is wonderfully simple and fast. The catch is that it works only for problems with the <em>greedy choice property</em>: a locally best choice can always be extended to a globally best solution."),
    ("h2", "Example: making change"),
    ("p", "With standard coins, always take the largest coin that fits."),
    ("code", "python", 'def make_change(amount, coins=(25, 10, 5, 1)):\n    result = []\n    for c in coins:\n        while amount >= c:\n            amount -= c\n            result.append(c)\n    return result\n\nprint(make_change(63))'),
    ("output", "[25, 25, 10, 1, 1, 1]"),
    ("note", "When greedy fails", "With coins (4, 3, 1) and amount 6, greedy picks 4+1+1 (three coins), but 3+3 needs only two. That case needs dynamic programming. Always look for a counterexample before trusting a greedy idea."),
    ("h2", "Interval scheduling"),
    ("p", "Given meetings with start and end times, attend as many as possible. The winning rule: <strong>always pick the meeting that ends earliest</strong> among those that do not overlap, because that leaves the most room for the rest."),
    ("code", "python", 'def max_meetings(meetings):\n    chosen, last_end = [], float("-inf")\n    for start, end in sorted(meetings, key=lambda m: m[1]):\n        if start >= last_end:\n            chosen.append((start, end))\n            last_end = end\n    return chosen\n\nprint(max_meetings([(1, 4), (3, 5), (0, 6), (5, 7), (8, 9), (5, 9)]))'),
    ("output", "[(1, 4), (5, 7), (8, 9)]"),
    ("h2", "Jump game"),
    ("p", "Each number says how far you may jump. Can you reach the end? Track the farthest index reachable so far."),
    ("code", "python", 'def can_reach_end(nums):\n    farthest = 0\n    for i, jump in enumerate(nums):\n        if i > farthest:\n            return False\n        farthest = max(farthest, i + jump)\n    return True\n\nprint(can_reach_end([2, 3, 1, 1, 4]), can_reach_end([3, 2, 1, 0, 4]))'),
    ("output", "True False"),
    ("h2", "How to justify a greedy choice"),
    ("ul", [
        "<strong>Exchange argument</strong>: show that any optimal solution can be transformed to use your greedy choice without getting worse.",
        "<strong>Stays ahead</strong>: show that after each step greedy is at least as good as any other strategy.",
    ]),
    ("p", "Famous greedy algorithms you will meet later include Dijkstra's shortest paths, Kruskal's and Prim's minimum spanning trees and Huffman coding."),
    ("exercise", "Given <code>prices</code> for consecutive days, compute the maximum profit if you may buy and sell as many times as you like (but hold one share at a time). Hint: add every positive day-to-day rise."),
    ("solution", "python", 'def max_profit(prices):\n    return sum(max(0, b - a) for a, b in zip(prices, prices[1:]))\n\nprint(max_profit([7, 1, 5, 3, 6, 4]))   # 7'),
]

CONTENT["algo-backtracking"] = [
    ("p", "<strong>Backtracking</strong> is systematic trial and error. You build a solution one choice at a time; if a partial solution cannot possibly work, you <em>undo</em> the last choice and try another. It is the tool for problems that ask for <em>all</em> arrangements: subsets, permutations, puzzles like Sudoku and N-Queens."),
    ("h2", "The pattern: choose, explore, unchoose"),
    ("p", "Every backtracking solution has the same skeleton: if the current path is a complete answer, record it; otherwise, for each available option, add it to the path, recurse, then remove it again."),
    ("h2", "Subsets"),
    ("code", "python", 'def subsets(nums):\n    result, path = [], []\n\n    def go(start):\n        result.append(path[:])            # every path is a valid subset\n        for i in range(start, len(nums)):\n            path.append(nums[i])         # choose\n            go(i + 1)                    # explore\n            path.pop()                   # unchoose\n\n    go(0)\n    return result\n\nprint(subsets([1, 2, 3]))'),
    ("output", "[[], [1], [1, 2], [1, 2, 3], [1, 3], [2], [2, 3], [3]]"),
    ("p", "Note <code>path[:]</code>: append a <em>copy</em>, because <code>path</code> keeps changing afterward. Forgetting the copy is the most common bug."),
    ("h2", "Permutations"),
    ("code", "python", 'def permutations(nums):\n    result, path, used = [], [], [False] * len(nums)\n\n    def go():\n        if len(path) == len(nums):\n            result.append(path[:])\n            return\n        for i in range(len(nums)):\n            if used[i]:\n                continue\n            used[i] = True; path.append(nums[i])\n            go()\n            path.pop(); used[i] = False\n\n    go()\n    return result\n\nprint(permutations([1, 2, 3]))'),
    ("output", "[[1, 2, 3], [1, 3, 2], [2, 1, 3], [2, 3, 1], [3, 1, 2], [3, 2, 1]]"),
    ("h2", "Pruning"),
    ("p", "Pruning means abandoning a branch as soon as you know it is doomed. It is what separates a usable backtracking solution from brute force. Example: combinations that add up to a target. If the running sum already exceeds the target, stop."),
    ("code", "python", 'def combination_sum(candidates, target):\n    candidates.sort()\n    result, path = [], []\n\n    def go(start, remaining):\n        if remaining == 0:\n            result.append(path[:]); return\n        for i in range(start, len(candidates)):\n            if candidates[i] > remaining:\n                break                    # prune: sorted, so the rest are too big\n            path.append(candidates[i])\n            go(i, remaining - candidates[i])   # same number may repeat\n            path.pop()\n\n    go(0, target)\n    return result\n\nprint(combination_sum([2, 3, 6, 7], 7))'),
    ("output", "[[2, 2, 3], [7]]"),
    ("h2", "Cost"),
    ("p", "Backtracking is exponential in the worst case: 2 to the n subsets, n factorial permutations. That is acceptable for n up to roughly 10 to 20, which is exactly the range these puzzle problems use. If you find repeated subproblems, switch to dynamic programming."),
    ("exercise", "Generate all valid combinations of n pairs of parentheses. For n=3 there are 5, such as <code>((()))</code> and <code>()()()</code>. Prune: only add <code>(</code> while opens &lt; n, and <code>)</code> while closes &lt; opens."),
    ("solution", "python", 'def gen_parens(n):\n    out = []\n    def go(cur, opens, closes):\n        if len(cur) == 2 * n:\n            out.append(cur); return\n        if opens < n:\n            go(cur + "(", opens + 1, closes)\n        if closes < opens:\n            go(cur + ")", opens, closes + 1)\n    go("", 0, 0)\n    return out\n\nprint(gen_parens(3))'),
]

CONTENT["algo-dynamic-programming"] = [
    ("p", "<strong>Dynamic programming</strong> (DP) solves problems by breaking them into <em>overlapping subproblems</em>, solving each only once and reusing the stored answer. It turns many exponential recursions into polynomial ones. Two properties signal DP: <em>optimal substructure</em> (the best answer is built from best answers to smaller pieces) and <em>overlapping subproblems</em> (the same small problem comes up repeatedly)."),
    ("h2", "A recipe"),
    ("ul", [
        "Define the <strong>state</strong>: what do the parameters of a subproblem mean?",
        "Write the <strong>recurrence</strong>: how does a state depend on smaller states?",
        "Identify the <strong>base cases</strong>.",
        "Choose <strong>memoization</strong> (top-down recursion plus a cache) or <strong>tabulation</strong> (bottom-up loops filling a table).",
    ]),
    ("h2", "Climbing stairs"),
    ("p", "You can climb 1 or 2 steps at a time. How many ways to reach step n? Ways(n) = ways(n-1) + ways(n-2), since your last move was either 1 or 2 steps."),
    ("code", "python", 'from functools import lru_cache\n\n@lru_cache(None)\ndef ways(n):                 # top-down\n    return 1 if n <= 1 else ways(n - 1) + ways(n - 2)\n\ndef ways_table(n):           # bottom-up, O(1) space\n    a, b = 1, 1\n    for _ in range(n - 1):\n        a, b = b, a + b\n    return b\n\nprint(ways(10), ways_table(10))'),
    ("output", "89 89"),
    ("h2", "Coin change (fewest coins)"),
    ("p", "State: <code>dp[x]</code> is the fewest coins to make amount x. Recurrence: <code>dp[x] = 1 + min(dp[x - c])</code> over coins c. This solves the case where greedy failed."),
    ("code", "python", 'def coin_change(coins, amount):\n    INF = float("inf")\n    dp = [0] + [INF] * amount\n    for x in range(1, amount + 1):\n        for c in coins:\n            if c <= x:\n                dp[x] = min(dp[x], dp[x - c] + 1)\n    return dp[amount] if dp[amount] != INF else -1\n\nprint(coin_change([4, 3, 1], 6), coin_change([2], 3))'),
    ("output", "2 -1"),
    ("h2", "0/1 Knapsack"),
    ("p", "Choose items, each with a weight and value, to maximize value within a capacity. State: <code>dp[w]</code> is the best value with capacity w. Iterate capacity downward so each item is used at most once."),
    ("code", "python", 'def knapsack(items, capacity):\n    dp = [0] * (capacity + 1)\n    for weight, value in items:\n        for w in range(capacity, weight - 1, -1):\n            dp[w] = max(dp[w], dp[w - weight] + value)\n    return dp[capacity]\n\nprint(knapsack([(1, 1), (3, 4), (4, 5), (5, 7)], 7))'),
    ("output", "9"),
    ("h2", "Longest common subsequence and edit distance"),
    ("p", "Two-string problems use a 2D table. <code>dp[i][j]</code> describes the first i characters of one string and the first j of the other. Edit distance (the minimum insert, delete and replace operations to turn one word into another) powers spell checkers."),
    ("code", "python", 'def edit_distance(a, b):\n    m, n = len(a), len(b)\n    dp = [[0] * (n + 1) for _ in range(m + 1)]\n    for i in range(m + 1): dp[i][0] = i\n    for j in range(n + 1): dp[0][j] = j\n    for i in range(1, m + 1):\n        for j in range(1, n + 1):\n            if a[i - 1] == b[j - 1]:\n                dp[i][j] = dp[i - 1][j - 1]\n            else:\n                dp[i][j] = 1 + min(dp[i - 1][j], dp[i][j - 1], dp[i - 1][j - 1])\n    return dp[m][n]\n\nprint(edit_distance("kitten", "sitting"))'),
    ("output", "3"),
    ("h2", "Tips"),
    ("ul", [
        "Start with plain recursion, then add a cache: the fastest path to a correct DP.",
        "Draw the table by hand for a tiny input to find the recurrence.",
        "Look at which earlier cells a cell needs; often you can keep just one or two rows to save memory.",
        "Time is roughly (number of states) times (work per state).",
    ]),
    ("exercise", "Find the length of the longest increasing subsequence of <code>[10, 9, 2, 5, 3, 7, 101, 18]</code> using <code>dp[i]</code> = best length ending at index i."),
    ("solution", "python", 'def lis(nums):\n    dp = [1] * len(nums)\n    for i in range(len(nums)):\n        for j in range(i):\n            if nums[j] < nums[i]:\n                dp[i] = max(dp[i], dp[j] + 1)\n    return max(dp)\n\nprint(lis([10, 9, 2, 5, 3, 7, 101, 18]))   # 4'),
]
