"""Expanded Python and Java lesson content for stackcone Learn."""

PYTHON_LESSONS = [
    {"slug": "python-hello-world", "track": "python", "title": "Hello, Python", "minutes": 12, "level": "Beginner",
     "summary": "Install Python, run your first script, use the REPL, and understand how the interpreter works.",
     "objectives": ["Install or verify Python 3", "Run scripts from the terminal", "Use the interactive REPL", "Write comments"],
     "sections": [
         ("p", "Python is an interpreted language — you write text, the interpreter runs it line by line. No separate compile step is required before you see output."),
         ("h2", "Check your install"),
         ("code", "bash", "python3 --version\nwhich python3"),
         ("p", "You want Python 3.10+. On macOS/Linux use <code>python3</code>; on Windows the launcher is often <code>py</code>."),
         ("h2", "Your first program"),
         ("code", "python", '# hello.py — comments start with #\nprint("Hello, stackcone!")\nprint(2 + 2)\nprint("Python", "runs", "line by line")'),
         ("p", "Save as <code>hello.py</code> and run:"),
         ("code", "bash", "python3 hello.py"),
         ("h2", "The REPL"),
         ("p", "Type <code>python3</code> with no file to open an interactive shell. Great for trying one-liners. Exit with <code>exit()</code> or Ctrl-D."),
         ("code", "python", '>>> print(10 * 3)\n30\n>>> "hi".upper()\n\'HI\''),
         ("exercise", "Write a script that prints your name, the city you live in, and the result of <code>7 * 6</code> on three separate lines."),
     ]},
    {"slug": "python-variables-and-types", "track": "python", "title": "Variables and Types", "minutes": 16, "level": "Beginner",
     "summary": "Names, assignment, dynamic typing, and the core built-ins: int, float, str, bool, and None.",
     "objectives": ["Assign and reassign variables", "Use type() and isinstance()", "Convert between types", "Know what None means"],
     "sections": [
         ("p", "A variable is a name bound to a value. Python figures out the type at runtime — you do not declare <code>int x</code> like in Java."),
         ("h2", "Core types"),
         ("code", "python", 'age = 28\nprice = 19.99\nname = "stackcone"\nactive = True\nmissing = None\n\nprint(type(age), type(price), type(name))\nprint(type(active), type(missing))\nprint(isinstance(age, int))'),
         ("h2", "Reassignment and names"),
         ("code", "python", 'x = 10\nx = "now a string"  # legal — name points at a new object\nprint(x)'),
         ("h2", "Type conversion"),
         ("code", "python", 'n = int("42")\ns = str(3.14)\nflag = bool(1)       # True; bool(0) is False\nprint(n + 1, s, flag)\nprint(float("3.5") + 0.5)'),
         ("p", "Conversion fails loudly on bad input — <code>int(\"hi\")</code> raises <code>ValueError</code>. We cover handling that in Error Handling."),
         ("exercise", "Create variables for a product title (str), price (float), quantity (int), and in-stock flag (bool). Print a one-line summary using an f-string."),
     ]},
    {"slug": "python-strings", "track": "python", "title": "Strings and Formatting", "minutes": 18, "level": "Beginner",
     "summary": "Indexing, slicing, common string methods, and f-strings for readable output.",
     "objectives": ["Index and slice strings", "Use strip/split/join/replace", "Format with f-strings", "Know strings are immutable"],
     "sections": [
         ("p", "Strings are sequences of Unicode characters. They are immutable — methods return new strings rather than changing the original."),
         ("h2", "Indexing and slicing"),
         ("code", "python", 'msg = "stackcone"\nprint(msg[0], msg[-1])\nprint(msg[0:5])    # stack\nprint(msg[5:])     # cone\nprint(msg[::-1])   # reverse'),
         ("h2", "Useful methods"),
         ("code", "python", 'raw = "  Hello, World  "\nprint(raw.strip())\nprint(raw.lower())\nparts = "a,b,c".split(",")\nprint(parts)\nprint("-".join(parts))\nprint("hello".replace("l", "L"))'),
         ("h2", "f-strings"),
         ("code", "python", 'user = "stackcone"\nscore = 95\nprint(f"{user} scored {score}/100")\nprint(f"price={9.5:.2f}")'),
         ("exercise", "Given <code>email = \"  Dev@Example.COM \"</code>, normalize it to lowercase with no leading/trailing spaces, then print the domain part after <code>@</code>."),
     ]},
    {"slug": "python-operators", "track": "python", "title": "Operators and Expressions", "minutes": 14, "level": "Beginner",
     "summary": "Arithmetic, comparison, logical operators, and how Python evaluates truthy values.",
     "objectives": ["Use +, -, *, /, //, %, **", "Compare with ==, !=, <, >", "Combine with and/or/not", "Understand truthiness"],
     "sections": [
         ("h2", "Arithmetic"),
         ("code", "python", 'print(7 / 2)    # 3.5 true division\nprint(7 // 2)   # 3 floor division\nprint(7 % 2)    # 1 remainder\nprint(2 ** 10)  # 1024'),
         ("h2", "Comparison and logic"),
         ("code", "python", 'age = 20\nprint(age >= 18 and age < 65)\nprint(not False)\nprint("py" in "python")'),
         ("h2", "Truthy and falsy"),
         ("p", "In conditions, empty containers, <code>0</code>, <code>\"\"</code>, and <code>None</code> are falsy. Everything else is truthy."),
         ("code", "python", 'items = []\nif not items:\n    print("empty list")\nname = "Ada"\nif name:\n    print(f"hi {name}")'),
         ("exercise", "Write expressions that check whether a number is even, whether a string is non-empty, and whether a value is between 1 and 100 inclusive."),
     ]},
    {"slug": "python-control-flow", "track": "python", "title": "Control Flow", "minutes": 18, "level": "Beginner",
     "summary": "Branch with if/elif/else, write clear conditions, and avoid nested spaghetti.",
     "objectives": ["Write if/elif/else chains", "Nest carefully", "Use early returns in functions", "Prefer flat over deep nesting"],
     "sections": [
         ("p", "Control flow decides which code runs. Start with conditionals; loops come next."),
         ("h2", "Conditionals"),
         ("code", "python", 'score = 87\nif score >= 90:\n    grade = "A"\nelif score >= 80:\n    grade = "B"\nelif score >= 70:\n    grade = "C"\nelse:\n    grade = "F"\nprint(grade)'),
         ("h2", "Ternary expression"),
         ("code", "python", 'n = 4\nlabel = "even" if n % 2 == 0 else "odd"\nprint(label)'),
         ("h2", "Guard clauses"),
         ("code", "python", 'def discount(price, member):\n    if price < 0:\n        return 0\n    if not member:\n        return price\n    return price * 0.9\n\nprint(discount(100, True))\nprint(discount(100, False))'),
         ("exercise", "Write a function <code>traffic_light(color)</code> that returns what a driver should do for red, yellow, and green — and a default for unknown colors."),
     ]},
    {"slug": "python-loops", "track": "python", "title": "Loops", "minutes": 20, "level": "Beginner",
     "summary": "for, while, range, enumerate, break/continue, and looping over collections.",
     "objectives": ["Iterate with for and range()", "Use while with a clear exit", "Apply break and continue", "Use enumerate for indexes"],
     "sections": [
         ("h2", "for and range"),
         ("code", "python", 'for i in range(3):\n    print("tick", i)\n\nfor i in range(2, 10, 2):\n    print(i)  # 2, 4, 6, 8'),
         ("h2", "while"),
         ("code", "python", 'count = 3\nwhile count > 0:\n    print(count)\n    count -= 1\nprint("liftoff")'),
         ("h2", "break, continue, enumerate"),
         ("code", "python", 'nums = [3, 7, 0, 9, 2]\nfor i, n in enumerate(nums):\n    if n == 0:\n        continue\n    if n > 8:\n        print(f"stop at index {i}")\n        break\n    print(i, n)'),
         ("h2", "Looping collections"),
         ("code", "python", 'for ch in "py":\n    print(ch)\nfor key in {"a": 1, "b": 2}:\n    print(key)'),
         ("exercise", "Print even numbers from 2 to 20. Then rewrite using a while loop. Finally, sum numbers 1–100 with a for loop."),
     ]},
    {"slug": "python-functions", "track": "python", "title": "Functions", "minutes": 20, "level": "Beginner",
     "summary": "Define reusable blocks with parameters, return values, defaults, *args, and docstrings.",
     "objectives": ["Define functions with def", "Return values", "Use default and keyword args", "Accept *args"],
     "sections": [
         ("p", "Functions package logic behind a name. Prefer small functions that do one thing."),
         ("h2", "Parameters and return"),
         ("code", "python", 'def greet(name, excited=False):\n    """Return a greeting; add ! when excited."""\n    msg = f"Hello, {name}"\n    return msg + "!" if excited else msg\n\nprint(greet("world"))\nprint(greet("world", excited=True))\nprint(greet(excited=True, name="Ada"))'),
         ("h2", "*args"),
         ("code", "python", 'def total(*nums):\n    s = 0\n    for n in nums:\n        s += n\n    return s\n\nprint(total(1, 2, 3, 4))'),
         ("h2", "Scope"),
         ("code", "python", 'rate = 0.1\n\ndef tax(amount):\n    return amount * rate\n\nprint(tax(200))'),
         ("exercise", "Write <code>area_rect(w, h)</code> and <code>area_circle(r)</code> (use 3.14159). Then write <code>average(*nums)</code> that returns the mean or 0 for no inputs."),
     ]},
    {"slug": "python-modules", "track": "python", "title": "Modules and Imports", "minutes": 15, "level": "Beginner",
     "summary": "Import the standard library, create your own modules, and understand packages.",
     "objectives": ["Import stdlib modules", "Use from ... import", "Create a local .py module", "Know __name__ == '__main__'"],
     "sections": [
         ("p", "A module is a <code>.py</code> file. Python’s standard library covers math, dates, JSON, paths, and more."),
         ("h2", "Importing"),
         ("code", "python", 'import math\nfrom datetime import date\n\nprint(math.sqrt(16))\nprint(date.today())'),
         ("h2", "Your own module"),
         ("p", "Put helpers in <code>utils.py</code>, then <code>from utils import helper</code> from another file in the same folder."),
         ("code", "python", '# utils.py\ndef clamp(n, lo, hi):\n    return max(lo, min(hi, n))\n\nif __name__ == "__main__":\n    print(clamp(15, 0, 10))  # only runs when executed directly'),
         ("h2", "Aliases"),
         ("code", "python", 'import json as js\nprint(js.dumps({"ok": True}))'),
         ("exercise", "Create a tiny <code>stats.py</code> with <code>mean(nums)</code>. Import it from another script and print the mean of <code>[2, 4, 6, 8]</code>."),
     ]},
    {"slug": "python-lists-tuples", "track": "python", "title": "Lists and Tuples", "minutes": 20, "level": "Beginner",
     "summary": "Ordered sequences — mutable lists vs immutable tuples, slicing, and common list methods.",
     "objectives": ["Create and slice lists", "Use append/pop/extend/sort", "Unpack tuples", "Know when tuples beat lists"],
     "sections": [
         ("p", "Lists grow and shrink. Tuples are fixed and often used for records like <code>(x, y)</code> or function returns."),
         ("h2", "Lists"),
         ("code", "python", 'nums = [10, 20, 30]\nnums.append(40)\nnums.insert(1, 15)\nprint(nums)\nprint(nums[1:3])\nlast = nums.pop()\nprint(last, nums)\nnums.extend([50, 60])\nprint(nums)'),
         ("h2", "Sorting and membership"),
         ("code", "python", 'scores = [88, 92, 75, 95]\nprint(sorted(scores))      # new list\nscores.sort(reverse=True)  # in place\nprint(scores)\nprint(92 in scores)'),
         ("h2", "Tuples"),
         ("code", "python", 'point = (3, 4)\nx, y = point\nprint(x, y)\nrgb = 255, 128, 0  # tuple packing\nprint(rgb)'),
         ("exercise", "Given <code>scores = [88, 92, 75, 95]</code>, print the highest without <code>max()</code>, then return a tuple of (min, max) using a small function."),
     ]},
    {"slug": "python-dictionaries", "track": "python", "title": "Dictionaries and Sets", "minutes": 20, "level": "Beginner",
     "summary": "Key-value maps, safe lookups, iteration, and sets for uniqueness and membership tests.",
     "objectives": ["Read and write dict keys", "Use get/setdefault/items", "Build frequency maps", "Use sets for uniqueness"],
     "sections": [
         ("h2", "Dictionaries"),
         ("code", "python", 'user = {"id": 1, "email": "dev@example.com"}\nuser["role"] = "admin"\nprint(user.get("phone", "n/a"))\n\nfor key, val in user.items():\n    print(key, val)'),
         ("h2", "Counting with a dict"),
         ("code", "python", 'words = "to be or not to be".split()\nfreq = {}\nfor w in words:\n    freq[w] = freq.get(w, 0) + 1\nprint(freq)'),
         ("h2", "Sets"),
         ("code", "python", 'tags = {"python", "api", "python"}\nprint(tags)\nprint("api" in tags)\nprint({"a", "b"} | {"b", "c"})  # union\nprint({"a", "b"} & {"b", "c"})  # intersection'),
         ("exercise", "Build a word-frequency dict from a sentence. Then use a set to list unique words sorted alphabetically."),
     ]},
    {"slug": "python-comprehensions", "track": "python", "title": "Comprehensions", "minutes": 16, "level": "Intermediate",
     "summary": "Build lists, sets, and dicts in one expression — readable filters and transforms.",
     "objectives": ["Write list comprehensions", "Add if filters", "Build dict comprehensions", "Know when a for-loop is clearer"],
     "sections": [
         ("p", "Comprehensions are Python’s concise way to map/filter. Prefer them when the logic stays short."),
         ("h2", "List comprehensions"),
         ("code", "python", 'nums = [1, 2, 3, 4, 5, 6]\nsquares = [n * n for n in nums]\nevens = [n for n in nums if n % 2 == 0]\nprint(squares)\nprint(evens)'),
         ("h2", "Dict and set"),
         ("code", "python", 'names = ["Ada", "Linus", "Guido"]\nlengths = {name: len(name) for name in names}\nunique_lens = {len(name) for name in names}\nprint(lengths)\nprint(unique_lens)'),
         ("h2", "Nested (use sparingly)"),
         ("code", "python", 'matrix = [[1, 2], [3, 4]]\nflat = [n for row in matrix for n in row]\nprint(flat)'),
         ("exercise", "From <code>prices = [9.5, 12.0, 4.25, 20]</code>, build a list of prices over 10 with 10% tax applied, rounded to 2 decimals."),
     ]},
    {"slug": "python-oop-classes", "track": "python", "title": "Classes and Objects", "minutes": 22, "level": "Intermediate",
     "summary": "Model data with classes, __init__, instance methods, and representation helpers.",
     "objectives": ["Define a class with __init__", "Add instance methods", "Understand self", "Implement __repr__ / __str__"],
     "sections": [
         ("p", "Classes bundle state and behavior. An object is one concrete instance of a class."),
         ("h2", "A simple class"),
         ("code", "python", 'class BankAccount:\n    def __init__(self, owner, balance=0):\n        self.owner = owner\n        self.balance = balance\n\n    def deposit(self, amount):\n        if amount <= 0:\n            raise ValueError("amount must be positive")\n        self.balance += amount\n\n    def __repr__(self):\n        return f"BankAccount({self.owner!r}, {self.balance})"\n\nacct = BankAccount("stackcone", 100)\nacct.deposit(50)\nprint(acct)\nprint(acct.balance)'),
         ("h2", "Instance vs class data"),
         ("code", "python", 'class Counter:\n    total = 0  # shared among instances\n\n    def __init__(self):\n        Counter.total += 1\n\nCounter()\nCounter()\nprint(Counter.total)'),
         ("exercise", "Add a <code>withdraw</code> method that refuses overdrafts. Add <code>transfer(other, amount)</code> that moves money to another account."),
     ]},
    {"slug": "python-inheritance", "track": "python", "title": "Inheritance", "minutes": 18, "level": "Intermediate",
     "summary": "Extend classes with inheritance, override methods, and call super().",
     "objectives": ["Subclass with inheritance", "Override methods", "Use super()", "Prefer composition when inheritance is forced"],
     "sections": [
         ("p", "Inheritance models an “is-a” relationship. Use it when a subclass truly specializes a base type."),
         ("h2", "Subclassing"),
         ("code", "python", 'class Animal:\n    def __init__(self, name):\n        self.name = name\n\n    def speak(self):\n        return "..."\n\nclass Dog(Animal):\n    def speak(self):\n        return f"{self.name} says woof"\n\nclass Cat(Animal):\n    def speak(self):\n        return f"{self.name} says meow"\n\nfor a in (Dog("Rex"), Cat("Mimi")):\n    print(a.speak())'),
         ("h2", "super()"),
         ("code", "python", 'class LoggedDict(dict):\n    def __setitem__(self, key, value):\n        print(f"set {key}={value}")\n        super().__setitem__(key, value)\n\nd = LoggedDict()\nd["x"] = 1'),
         ("exercise", "Create <code>Vehicle</code> with <code>drive()</code>, then <code>Car</code> and <code>Bike</code> subclasses that customize the message. Print both."),
     ]},
    {"slug": "python-file-handling", "track": "python", "title": "File Handling", "minutes": 18, "level": "Intermediate",
     "summary": "Read and write text files safely with context managers and pathlib.",
     "objectives": ["Use with open()", "Read and write text", "Append to files", "Use pathlib.Path"],
     "sections": [
         ("p", "Always open files with a <code>with</code> block so they close even if an error occurs."),
         ("h2", "Write and read"),
         ("code", "python", 'with open("notes.txt", "w", encoding="utf-8") as f:\n    f.write("first line\\n")\n    f.write("second line\\n")\n\nwith open("notes.txt", encoding="utf-8") as f:\n    print(f.read())'),
         ("h2", "Line by line"),
         ("code", "python", 'with open("notes.txt", encoding="utf-8") as f:\n    for line in f:\n        print(line.strip())'),
         ("h2", "pathlib"),
         ("code", "python", 'from pathlib import Path\n\np = Path("notes.txt")\nprint(p.exists(), p.suffix)\ntext = p.read_text(encoding="utf-8")\nprint(len(text.splitlines()), "lines")'),
         ("exercise", "Write a function <code>count_lines(path)</code> that returns the number of lines, or 0 if the file is missing."),
     ]},
    {"slug": "python-error-handling", "track": "python", "title": "Error Handling", "minutes": 18, "level": "Intermediate",
     "summary": "try/except/else/finally, catching specific exceptions, and raising your own.",
     "objectives": ["Catch specific exceptions", "Use else and finally", "Raise ValueError with context", "Avoid bare except"],
     "sections": [
         ("p", "Errors are normal. Catch what you can handle; let unexpected bugs surface."),
         ("h2", "try / except / else / finally"),
         ("code", "python", 'def parse_port(text):\n    try:\n        port = int(text)\n    except ValueError:\n        raise ValueError(f"invalid port: {text}") from None\n    else:\n        if not 1 <= port <= 65535:\n            raise ValueError("port out of range")\n        return port\n    finally:\n        pass  # cleanup hooks go here\n\nprint(parse_port("8080"))'),
         ("h2", "Multiple excepts"),
         ("code", "python", 'def safe_div(a, b):\n    try:\n        return a / b\n    except ZeroDivisionError:\n        return None\n    except TypeError:\n        return None\n\nprint(safe_div(10, 2), safe_div(10, 0))'),
         ("exercise", "Write <code>read_int(path)</code> that reads a file’s first line as an int. Return <code>None</code> if the file is missing or the content is not an integer."),
     ]},
    {"slug": "python-json", "track": "python", "title": "Working with JSON", "minutes": 16, "level": "Intermediate",
     "summary": "Serialize Python data to JSON and parse JSON from APIs and config files.",
     "objectives": ["Use json.dumps / loads", "Read and write .json files", "Handle nested structures", "Know JSON type limits"],
     "sections": [
         ("p", "JSON is the lingua franca of APIs. Python’s <code>json</code> module maps dict/list/str/number/bool/None."),
         ("h2", "dumps and loads"),
         ("code", "python", 'import json\n\npayload = {"user": "stackcone", "roles": ["admin", "editor"], "active": True}\ntext = json.dumps(payload, indent=2)\nprint(text)\nprint(json.loads(text)["roles"])'),
         ("h2", "Files"),
         ("code", "python", 'import json\nfrom pathlib import Path\n\ndata = {"theme": "dark", "font": 14}\nPath("settings.json").write_text(json.dumps(data, indent=2), encoding="utf-8")\nloaded = json.loads(Path("settings.json").read_text(encoding="utf-8"))\nprint(loaded["theme"])'),
         ("exercise", "Save a list of three todo dicts (<code>title</code>, <code>done</code>) to <code>todos.json</code>, then load and print only incomplete titles."),
     ]},
    {"slug": "python-pip-venv", "track": "python", "title": "pip and Virtual Environments", "minutes": 15, "level": "Intermediate",
     "summary": "Isolate project dependencies with venv and install packages with pip.",
     "objectives": ["Create a virtual environment", "Activate and deactivate it", "Install packages with pip", "Freeze requirements"],
     "sections": [
         ("p", "Never install project libraries into the system Python when you can avoid it. Use a virtual environment per project."),
         ("h2", "Create and activate"),
         ("code", "bash", "python3 -m venv .venv\n# macOS/Linux:\nsource .venv/bin/activate\n# Windows:\n# .venv\\Scripts\\activate"),
         ("h2", "Install and freeze"),
         ("code", "bash", "pip install requests\npip freeze > requirements.txt\npip install -r requirements.txt"),
         ("p", "Deactivate with <code>deactivate</code>. Commit <code>requirements.txt</code>, not <code>.venv/</code>."),
         ("exercise", "Create a venv in a scratch folder, install <code>requests</code>, and write a one-liner that prints <code>requests.__version__</code>."),
     ]},
    {"slug": "python-mini-project", "track": "python", "title": "Mini Project: CLI Notes", "minutes": 25, "level": "Intermediate",
     "summary": "Build a small command-line notes app that stores JSON on disk — tying together files, dicts, and functions.",
     "objectives": ["Design a simple CLI flow", "Persist data as JSON", "Handle missing files", "Structure code with functions"],
     "sections": [
         ("p", "Put the pieces together: read user commands, store notes in a list of dicts, and save to disk after each change."),
         ("h2", "Starter skeleton"),
         ("code", "python", 'import json\nfrom pathlib import Path\n\nSTORE = Path("notes.json")\n\ndef load():\n    if not STORE.exists():\n        return []\n    return json.loads(STORE.read_text(encoding="utf-8"))\n\ndef save(notes):\n    STORE.write_text(json.dumps(notes, indent=2), encoding="utf-8")\n\ndef add_note(text):\n    notes = load()\n    notes.append({"text": text, "done": False})\n    save(notes)\n\ndef list_notes():\n    for i, n in enumerate(load(), 1):\n        mark = "x" if n["done"] else " "\n        print(f"{i}. [{mark}] {n[\'text\']}")\n\nadd_note("Ship Learn course")\nadd_note("Write tests")\nlist_notes()'),
         ("h2", "Next steps"),
         ("p", "Add commands to mark done by index, delete a note, and quit. Wrap input in a <code>while True</code> menu."),
         ("exercise", "Extend the app with <code>done &lt;n&gt;</code> and <code>delete &lt;n&gt;</code> commands. Reject out-of-range indexes cleanly."),
     ]},
]

JAVA_LESSONS = [
    {"slug": "java-hello-world", "track": "java", "title": "Hello, Java", "minutes": 14, "level": "Beginner",
     "summary": "JDK setup, your first class, the main method, and the compile–run cycle.",
     "objectives": ["Verify the JDK", "Write public class + main", "Compile with javac", "Run with java"],
     "sections": [
         ("p", "Java is compiled to bytecode that runs on the JVM. You write <code>.java</code>, compile to <code>.class</code>, then run."),
         ("h2", "Check your JDK"),
         ("code", "bash", "java -version\njavac -version"),
         ("h2", "Your first class"),
         ("code", "java", 'public class Hello {\n    public static void main(String[] args) {\n        System.out.println("Hello, stackcone!");\n        System.out.println(2 + 2);\n    }\n}'),
         ("p", "File name must match the public class: <code>Hello.java</code>."),
         ("code", "bash", "javac Hello.java\njava Hello"),
         ("h2", "What just happened"),
         ("p", "<code>javac</code> produces <code>Hello.class</code>. <code>java Hello</code> loads that class and calls <code>main</code>."),
         ("exercise", "Print your name and a favorite language on two lines. Then add a third line that prints <code>args.length</code> when you pass CLI arguments."),
     ]},
    {"slug": "java-variables-types", "track": "java", "title": "Variables and Types", "minutes": 18, "level": "Beginner",
     "summary": "Primitives, reference types, final, and declaring typed variables.",
     "objectives": ["Declare primitive variables", "Use String", "Apply final", "Know widening vs casting"],
     "sections": [
         ("p", "Java is statically typed — every variable has a type known at compile time."),
         ("h2", "Primitives"),
         ("code", "java", 'int count = 3;\nlong big = 9_000_000_000L;\ndouble price = 9.99;\nboolean ok = true;\nchar grade = \'A\';\n\nSystem.out.println(count + " " + price);'),
         ("h2", "String and final"),
         ("code", "java", 'String title = "Widget";\nfinal int MAX = 100;\n// MAX = 101; // compile error\nSystem.out.println(title + " max=" + MAX);'),
         ("h2", "Casting"),
         ("code", "java", 'double d = 3.7;\nint truncated = (int) d; // 3\nSystem.out.println(truncated);'),
         ("exercise", "Declare SKU (String), quantity (int), unit price (double). Print the line total as quantity × price."),
     ]},
    {"slug": "java-strings-arrays", "track": "java", "title": "Strings and Arrays", "minutes": 18, "level": "Beginner",
     "summary": "String methods, immutability, and fixed-length arrays.",
     "objectives": ["Use common String methods", "Create and index arrays", "Loop arrays with for and for-each", "Know array length"],
     "sections": [
         ("h2", "Strings"),
         ("code", "java", 'String email = "  Dev@Example.COM  ";\nString normalized = email.trim().toLowerCase();\nSystem.out.println(normalized);\nSystem.out.println(normalized.contains("@"));\nSystem.out.println(normalized.substring(0, 3));'),
         ("h2", "Arrays"),
         ("code", "java", 'int[] scores = {88, 92, 75};\nSystem.out.println(scores[0]);\nSystem.out.println(scores.length);\nscores[2] = 80;\n\nfor (int i = 0; i < scores.length; i++) {\n    System.out.println(i + " -> " + scores[i]);\n}\nfor (int s : scores) {\n    System.out.println(s);\n}'),
         ("p", "Arrays have a fixed length after creation. For resizable lists, use <code>ArrayList</code> (Collections lesson)."),
         ("exercise", "Create a <code>String[]</code> of three cities. Print them joined by commas without a trailing comma."),
     ]},
    {"slug": "java-operators", "track": "java", "title": "Operators", "minutes": 14, "level": "Beginner",
     "summary": "Arithmetic, comparison, logical operators, and short-circuit evaluation.",
     "objectives": ["Use arithmetic operators", "Compare values", "Combine with && || !", "Understand short-circuiting"],
     "sections": [
         ("h2", "Arithmetic and compound assignment"),
         ("code", "java", 'int n = 7;\nSystem.out.println(n / 2);   // 3 integer division\nSystem.out.println(n % 2);\nn += 3;\nSystem.out.println(n);'),
         ("h2", "Logic"),
         ("code", "java", 'int age = 20;\nboolean member = true;\nSystem.out.println(age >= 18 && member);\nSystem.out.println(!(age < 13));'),
         ("h2", "Short-circuit"),
         ("code", "java", 'String name = null;\n// Safe: second part skipped when name is null\nif (name != null && name.length() > 0) {\n    System.out.println(name);\n} else {\n    System.out.println("empty");\n}'),
         ("exercise", "Write a condition that is true only when <code>score</code> is between 0 and 100 inclusive and <code>submitted</code> is true."),
     ]},
    {"slug": "java-control-flow", "track": "java", "title": "Control Flow", "minutes": 18, "level": "Beginner",
     "summary": "if/else, switch, for, while, and enhanced for-each loops.",
     "objectives": ["Write if/else chains", "Use switch expressions/statements", "Loop with for and while", "Iterate arrays with for-each"],
     "sections": [
         ("h2", "if / else"),
         ("code", "java", 'int score = 87;\nString grade;\nif (score >= 90) {\n    grade = "A";\n} else if (score >= 80) {\n    grade = "B";\n} else {\n    grade = "C";\n}\nSystem.out.println(grade);'),
         ("h2", "switch"),
         ("code", "java", 'String day = "Mon";\nswitch (day) {\n    case "Mon":\n    case "Tue":\n        System.out.println("weekday");\n        break;\n    case "Sat":\n    case "Sun":\n        System.out.println("weekend");\n        break;\n    default:\n        System.out.println("unknown");\n}'),
         ("h2", "Loops"),
         ("code", "java", 'for (int i = 0; i < 3; i++) {\n    System.out.println("tick " + i);\n}\nint c = 3;\nwhile (c > 0) {\n    System.out.println(c);\n    c--;\n}'),
         ("exercise", "Print numbers 1–10, skipping 5. Then rewrite with a while loop."),
     ]},
    {"slug": "java-methods", "track": "java", "title": "Methods", "minutes": 18, "level": "Beginner",
     "summary": "Declare methods, return values, overload by signature, and pass arguments.",
     "objectives": ["Declare static and instance methods", "Return values", "Overload methods", "Understand pass-by-value"],
     "sections": [
         ("h2", "Static helpers"),
         ("code", "java", 'public class MathUtil {\n    public static int areaRect(int w, int h) {\n        return w * h;\n    }\n\n    public static double areaRect(double w, double h) { // overload\n        return w * h;\n    }\n\n    public static void main(String[] args) {\n        System.out.println(areaRect(3, 4));\n        System.out.println(areaRect(3.5, 2.0));\n    }\n}'),
         ("h2", "Pass-by-value"),
         ("p", "Java passes a copy of the value (for primitives) or a copy of the reference (for objects). Reassigning a parameter does not change the caller’s variable; mutating a mutable object does."),
         ("code", "java", 'static void bump(int n) {\n    n++;\n}\n\npublic static void main(String[] args) {\n    int x = 1;\n    bump(x);\n    System.out.println(x); // still 1\n}'),
         ("exercise", "Write overloaded <code>max</code> methods for two ints and three ints. Call both from <code>main</code>."),
     ]},
    {"slug": "java-oop-classes", "track": "java", "title": "Classes and Objects", "minutes": 22, "level": "Intermediate",
     "summary": "Fields, constructors, encapsulation with private, and getters/setters.",
     "objectives": ["Define fields and constructors", "Encapsulate with private", "Add getters/setters", "Override toString"],
     "sections": [
         ("code", "java", 'public class User {\n    private final String email;\n    private int loginCount;\n\n    public User(String email) {\n        this.email = email;\n        this.loginCount = 0;\n    }\n\n    public void recordLogin() {\n        loginCount++;\n    }\n\n    public String getEmail() {\n        return email;\n    }\n\n    public int getLoginCount() {\n        return loginCount;\n    }\n\n    @Override\n    public String toString() {\n        return "User(" + email + ", logins=" + loginCount + ")";\n    }\n\n    public static void main(String[] args) {\n        User u = new User("a@b.com");\n        u.recordLogin();\n        System.out.println(u);\n    }\n}'),
         ("p", "<code>final</code> fields must be assigned in the constructor and cannot be reassigned."),
         ("exercise", "Add <code>resetLogins()</code> and a constructor that also accepts an initial login count (validate ≥ 0)."),
     ]},
    {"slug": "java-inheritance", "track": "java", "title": "Inheritance", "minutes": 20, "level": "Intermediate",
     "summary": "Extend classes with extends, override methods, and use protected members.",
     "objectives": ["Create a subclass", "Override methods with @Override", "Call super()", "Know single inheritance for classes"],
     "sections": [
         ("code", "java", 'class Animal {\n    protected String name;\n\n    Animal(String name) {\n        this.name = name;\n    }\n\n    String speak() {\n        return "...";\n    }\n}\n\nclass Dog extends Animal {\n    Dog(String name) {\n        super(name);\n    }\n\n    @Override\n    String speak() {\n        return name + " says woof";\n    }\n}\n\npublic class Demo {\n    public static void main(String[] args) {\n        Animal a = new Dog("Rex");\n        System.out.println(a.speak());\n    }\n}'),
         ("p", "A class can extend only one parent. For multiple capabilities, use interfaces."),
         ("exercise", "Add a <code>Cat</code> subclass. Put both in an <code>Animal[]</code> and print each <code>speak()</code>."),
     ]},
    {"slug": "java-interfaces", "track": "java", "title": "Interfaces", "minutes": 18, "level": "Intermediate",
     "summary": "Define contracts with interfaces, implement multiple interfaces, and use default methods.",
     "objectives": ["Declare an interface", "Implement one or more interfaces", "Use default methods", "Program to the interface"],
     "sections": [
         ("code", "java", 'interface Payable {\n    double pay();\n\n    default String label() {\n        return "payment";\n    }\n}\n\nclass Salary implements Payable {\n    private final double monthly;\n\n    Salary(double monthly) {\n        this.monthly = monthly;\n    }\n\n    public double pay() {\n        return monthly;\n    }\n}\n\nclass Invoice implements Payable {\n    private final double amount;\n\n    Invoice(double amount) {\n        this.amount = amount;\n    }\n\n    public double pay() {\n        return amount;\n    }\n}\n\npublic class Demo {\n    public static void main(String[] args) {\n        Payable[] items = { new Salary(5000), new Invoice(120.5) };\n        for (Payable p : items) {\n            System.out.println(p.label() + "=" + p.pay());\n        }\n    }\n}'),
         ("exercise", "Create a <code>Notify</code> interface with <code>send(String msg)</code>. Implement <code>EmailNotify</code> and <code>SmsNotify</code> that print different prefixes."),
     ]},
    {"slug": "java-collections", "track": "java", "title": "Collections Framework", "minutes": 22, "level": "Intermediate",
     "summary": "ArrayList, HashMap, HashSet, and choosing the right collection.",
     "objectives": ["Use ArrayList", "Store key-value in HashMap", "Use HashSet for uniqueness", "Iterate with for-each"],
     "sections": [
         ("h2", "List"),
         ("code", "java", 'import java.util.*;\n\nList<String> tags = new ArrayList<>();\ntags.add("java");\ntags.add("api");\ntags.add("java");\nSystem.out.println(tags.size());\nSystem.out.println(tags.get(0));\nfor (String t : tags) {\n    System.out.println(t);\n}'),
         ("h2", "Map and Set"),
         ("code", "java", 'import java.util.*;\n\nMap<String, Integer> stock = new HashMap<>();\nstock.put("widget", 42);\nstock.put("gadget", 7);\nSystem.out.println(stock.getOrDefault("nope", 0));\n\nSet<String> unique = new HashSet<>(tags);\nSystem.out.println(unique);'),
         ("h2", "When to pick what"),
         ("p", "List — ordered, duplicates OK. Set — unique membership. Map — keyed lookup. Prefer interfaces (<code>List</code>, <code>Map</code>) in variable types."),
         ("exercise", "Count word frequency in a sentence using a <code>HashMap&lt;String, Integer&gt;</code> and print the map."),
     ]},
    {"slug": "java-generics", "track": "java", "title": "Generics Basics", "minutes": 16, "level": "Intermediate",
     "summary": "Type parameters on classes and methods so collections stay type-safe.",
     "objectives": ["Declare a generic class", "Use type parameters on methods", "Avoid raw types", "Read List<T> signatures"],
     "sections": [
         ("p", "Generics catch type errors at compile time — no more accidental <code>List</code> of mixed objects."),
         ("code", "java", 'public class Box<T> {\n    private T value;\n\n    public void set(T value) {\n        this.value = value;\n    }\n\n    public T get() {\n        return value;\n    }\n\n    public static void main(String[] args) {\n        Box<String> b = new Box<>();\n        b.set("hi");\n        System.out.println(b.get());\n    }\n}'),
         ("h2", "Generic method"),
         ("code", "java", 'static <T> T first(T[] items) {\n    return items.length == 0 ? null : items[0];\n}'),
         ("exercise", "Write a generic <code>Pair&lt;A, B&gt;</code> with fields <code>left</code> and <code>right</code> and a <code>toString</code>."),
     ]},
    {"slug": "java-exceptions", "track": "java", "title": "Exception Handling", "minutes": 18, "level": "Intermediate",
     "summary": "try/catch/finally, checked vs unchecked exceptions, and throwing useful errors.",
     "objectives": ["Catch specific exceptions", "Use finally / try-with-resources mindset", "Throw IllegalArgumentException", "Know checked vs unchecked"],
     "sections": [
         ("code", "java", 'public static int parsePositive(String raw) {\n    try {\n        int n = Integer.parseInt(raw);\n        if (n <= 0) {\n            throw new IllegalArgumentException("must be positive");\n        }\n        return n;\n    } catch (NumberFormatException e) {\n        throw new IllegalArgumentException("not a number: " + raw, e);\n    }\n}\n\npublic static void main(String[] args) {\n    System.out.println(parsePositive("42"));\n}'),
         ("h2", "Checked vs unchecked"),
         ("p", "Unchecked (<code>RuntimeException</code>) need not be declared. Checked exceptions must be caught or declared with <code>throws</code>."),
         ("code", "java", 'static int divide(int a, int b) {\n    try {\n        return a / b;\n    } catch (ArithmeticException e) {\n        return 0;\n    } finally {\n        // always runs\n    }\n}'),
         ("exercise", "Write <code>parsePort(String)</code> that returns an int 1–65535 or throws <code>IllegalArgumentException</code> with a clear message."),
     ]},
    {"slug": "java-packages", "track": "java", "title": "Packages and Access", "minutes": 15, "level": "Intermediate",
     "summary": "Organize code into packages and control visibility with public, protected, and private.",
     "objectives": ["Declare a package", "Import types", "Use access modifiers", "Follow reverse-DNS naming"],
     "sections": [
         ("p", "Packages prevent name clashes and signal ownership. Convention: <code>com.company.project</code>."),
         ("code", "java", '// file: com/stackcone/util/Ids.java\npackage com.stackcone.util;\n\npublic final class Ids {\n    private Ids() {}\n\n    public static String user(int id) {\n        return "user:" + id;\n    }\n}'),
         ("code", "java", 'import com.stackcone.util.Ids;\n\npublic class App {\n    public static void main(String[] args) {\n        System.out.println(Ids.user(42));\n    }\n}'),
         ("h2", "Access levels"),
         ("p", "<code>private</code> — class only. package-private (default) — same package. <code>protected</code> — package + subclasses. <code>public</code> — everywhere."),
         ("exercise", "Sketch a package layout for a blog app with <code>model</code>, <code>service</code>, and <code>api</code> packages and list what should be public."),
     ]},
    {"slug": "java-io-basics", "track": "java", "title": "I/O Basics", "minutes": 16, "level": "Intermediate",
     "summary": "Read and write text files with modern java.nio.file APIs.",
     "objectives": ["Use Path and Files", "Read all lines", "Write strings to disk", "Handle IOException"],
     "sections": [
         ("code", "java", 'import java.io.IOException;\nimport java.nio.file.*;\nimport java.util.List;\n\npublic class IoDemo {\n    public static void main(String[] args) throws IOException {\n        Path path = Paths.get("notes.txt");\n        Files.writeString(path, "first line\\nsecond line\\n");\n        List<String> lines = Files.readAllLines(path);\n        for (String line : lines) {\n            System.out.println(line);\n        }\n    }\n}'),
         ("p", "Production code often wraps I/O in try/catch or propagates <code>IOException</code> to a higher layer."),
         ("exercise", "Write a method that appends a timestamped line to <code>log.txt</code>, creating the file if needed."),
     ]},
    {"slug": "java-streams", "track": "java", "title": "Streams Intro", "minutes": 18, "level": "Intermediate",
     "summary": "Filter, map, and reduce collections with the Stream API.",
     "objectives": ["Create a stream from a List", "Use filter/map/collect", "Run a simple reduction", "Know streams are not reusable"],
     "sections": [
         ("code", "java", 'import java.util.*;\nimport java.util.stream.Collectors;\n\npublic class StreamDemo {\n    public static void main(String[] args) {\n        List<Integer> nums = List.of(1, 2, 3, 4, 5, 6);\n        List<Integer> evensSquared = nums.stream()\n            .filter(n -> n % 2 == 0)\n            .map(n -> n * n)\n            .collect(Collectors.toList());\n        System.out.println(evensSquared);\n\n        int sum = nums.stream().mapToInt(Integer::intValue).sum();\n        System.out.println(sum);\n    }\n}'),
         ("p", "Streams shine for declarative data pipelines. For simple loops, a classic for-each is still fine."),
         ("exercise", "From a list of words, collect uppercase words longer than 3 characters into a new list."),
     ]},
    {"slug": "java-mini-project", "track": "java", "title": "Mini Project: Student Registry", "minutes": 25, "level": "Intermediate",
     "summary": "Build an in-memory student registry using classes, ArrayList, and a simple menu.",
     "objectives": ["Model a Student class", "Store students in a List", "Search by id", "Print a formatted roster"],
     "sections": [
         ("p", "Combine OOP and collections into a tiny app you can extend later with file persistence."),
         ("h2", "Starter"),
         ("code", "java", 'import java.util.*;\n\nclass Student {\n    final String id;\n    final String name;\n    final double gpa;\n\n    Student(String id, String name, double gpa) {\n        this.id = id;\n        this.name = name;\n        this.gpa = gpa;\n    }\n\n    public String toString() {\n        return id + " | " + name + " | " + gpa;\n    }\n}\n\npublic class Registry {\n    private final List<Student> students = new ArrayList<>();\n\n    void add(Student s) { students.add(s); }\n\n    Student find(String id) {\n        for (Student s : students) {\n            if (s.id.equals(id)) return s;\n        }\n        return null;\n    }\n\n    void printAll() {\n        for (Student s : students) System.out.println(s);\n    }\n\n    public static void main(String[] args) {\n        Registry r = new Registry();\n        r.add(new Student("s1", "Ada", 3.9));\n        r.add(new Student("s2", "Linus", 3.5));\n        r.printAll();\n        System.out.println(r.find("s1"));\n    }\n}'),
         ("exercise", "Add <code>remove(String id)</code> and <code>averageGpa()</code>. Reject duplicate IDs on add with an exception."),
     ]},
]
